### ISSUE TITLE
Can't seem to connect when using HTTPS

### ISSUE THREAD

**Issue by jamieOH** [vanhauser-thc/thc-hydra#102]
I have successfully used Hydra for my router, but now when I try with https:// websites I am getting the "child with pid XXXX terminating, can not connect" error. Not sure what I am doing wrong. Am I missing something?

Here is what I am doing:

`hydra -l (user) -P (passlist) -V -t 1 www.XXXXX.co.uk https-get "/index.phtml?d=XXXXXX"`

I've tried -s 443 and -S but I can see 443 is used anyway when using https methods. When I do http-get instead I get false positives. When I do -s 443 with http-get I get no positives (I'm testing with details I know are correct). I am also unsure whether to use HEAD or GET - I am dealing with a browser authentication pop-up window. Thanks, sorry for the noob question.

**Comment by vanhauser-thc** [comment]
if you get "can not connect" then the SSL connection might fail. Try the -O (capital o) option to enable support for old/outdated SSL options.

If this fails, add -d to the command line (debug mode) and check out what might be going wrong. If you can not find the issue, post the full output here

**Comment by jamieOH** [comment]
Hi, when trying to use -O I get "Invalid option" - am I on an outdated version or do I need to use it in conjunction with something else?

**Comment by vanhauser-thc** [comment]
can you please output the output of "./configure --debug" ?

**Comment by jamieOH** [comment]
Did a fresh install and no longer get that error so can't help you out there sorry. Is there a way to use a redirection to a certain URL as a success/failure by the way?

**Comment by vanhauser-thc** [comment]
yes you can
