### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by Diadlo** [vanhauser-thc/thc-hydra#108]
What about union all files like "hydra-\<protocol_name\>*.c" in different directory? Wouldn't it make the project a bit cleaner?
Also, I'd like to take care of it, and I appreciate any guidance

**Comment by vanhauser-thc** [comment]
hmmm I know what you mean, but I kinda prefer it like that. thanks for the offer though.

**Comment by Diadlo** [comment]
Ok
