### ISSUE TITLE
[enhancement] Hydra http-form module to handle hidden fields

### ISSUE THREAD

**Issue by ghost** [vanhauser-thc/thc-hydra#11]
I'm working on some enhancements on the http-form module. Currently, the module issues HTTP GET or POST requests directly to the server appending only the parameters required for the user and password. This only works with simple forms, and supposes a clear disadvantage on more complex forms that have extra fields. A common scenario I myself have found many times out there is that of login forms issuing random tokens in hidden form fields in order to avoid CSRF or session fixation attacks (commonly known as "CSRF tokens"). In such scenarios, Hydra will usually falsely report all passwords as valid, since the backend checks for the validity of the CSRF token (which Hydra didn't send) and prints an output different to the expected one because the provided token is invalid. To overcome this, one could just switch to alternatives, such as Brutus, or nmap's "http-form-brute" script. However, I myself have found Hydra to perform much better than the above ones with as many heads as CPU cores. Why wouldn't Hydra be able to handle hidden fields? The idea of Hydra being able to handle complex forms came to my mind, and I'm working on some improvements, that I list as follow:
        1. Hydra first sends a request to retrieve the cookies. Use that same response to retrieve the HTML code too.
        2. Let the user specify the target form via simple CSS selectors, such as #myform, or [name=myform].
        3. Same as now, the user would specify the names of the fields in the target form that are expected to contain the user and password.
        4. Read the values of the hidden fields in the target form and issue them too, automatically.
        5. Other extra fields that are not hidden would be ignored, but I don't care much about it since most (if not any) login forms have only two mandatory fields (user & pass) while the others being optional (such as "Remember me"). Apart from the hidden ones.

I'll be working on these features in the following weeks. I'd love to hear your feedback.

**Comment by Themercee** [comment]
Hi @ghost , I was wondering if you implement the CSRF token finder? If yes how to use it?
Thanks :)
