### ISSUE TITLE
Syntax thc hydra. Help!

### ISSUE THREAD

**Issue by tcsang** [vanhauser-thc/thc-hydra#112]
Hi all,
Could you help me about thc hydra?
Ex: 
Url: id.thatvukiem.com/login.html
Method: post
Parameter: 
- inServerId: 1
- inUserName: myUser
- inPassword: myPassword
- Login: login page 
File wordlist: password500.txt

My current syntax: 
hydra -l myUser -P password500.txt id.thatvukiem.com http-post-form "/login.html::parent%5BinUserName%5D=^USER^&parent%5BinPassword%5D=^PASS^&parent%5B:&_adminLogin=YES&SAVE=Login&dangnhap=%C4%90%C4%83ng+nh%E1%BA%ADp&inServerId=1"

It take a long time for my test. And don't find my user and password. 

Thanks all,

**Comment by vanhauser-thc** [comment]
sorry, this is not a help forum. this is for bugs only.

but your line looks wrong. like double :: is wrong, the parent%5B etc. seems incomplete. etc.
