### ISSUE TITLE
Hydra could not create an SSL session

### ISSUE THREAD

**Issue by jpprovost1988** [vanhauser-thc/thc-hydra#114]
I'm trying to test hydra on a web based form using https-post-form and the following command : 

hydra -v -V -l user -p pass website.com https-post-form -s 443 -m "/Login.aspx:user=^USER^&pass=^PASS^:Error"

And I get the following error message : 

[VERBOSE] Could not create an SSL session: error:00000000:lib(0):func(0):reason(0)

Any ideas?

Here's the ouput of ./configure --debug

./configure --debug

Starting hydra auto configuration ...
Detected 64 Bit Linux OS

Checking for zlib (libz.so, zlib.h) ...
                                        ... found
Checking for openssl (libssl, libcrypto, ssl.h, sha.h) ...
DEBUG: SSL_LIB= include /etc/ld.so.conf.d/fakeroot-x86_64-linux-gnu.conf /etc/ld.so.conf.d/i386-linux-gnu_GL.conf /etc/ld.so.conf.d/i686-linux-gnu.conf /etc/ld.so.conf.d/libc.conf /etc/ld.so.conf.d/x86_64-linux-gnu.conf /etc/ld.so.conf.d/x86_64-linux-gnu_EGL.conf /etc/ld.so.conf.d/x86_64-linux-gnu_GL.conf /lib/i386-linux-gnu /lib/i686-linux-gnu /lib/x86_64-linux-gnu /usr/lib/i386-linux-gnu /usr/lib/i386-linux-gnu/mesa /usr/lib/i686-linux-gnu /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/libfakeroot /usr/lib/x86_64-linux-gnu/mesa /usr/lib/x86_64-linux-gnu/mesa-egl /usr/local/lib /lib64 /usr/lib64 /usr/local/lib64 /opt/local/lib64 /lib /usr/lib /usr/local/lib /opt/local/lib
DEBUG: SSL_INC=/usr/include /usr/local/include /opt/include /opt/local/include
DEBUG: SSL_PATH=/lib/i386-linux-gnu/libssl
DEBUG: CRYPTO_PATH=/lib/i386-linux-gnu/libcrypto
DEBUG: SSL_INC=/usr/include/openssl/ssl.h
                                                       ... found
Checking for idn (libidn.so) ...
DEBUG: IDN_PATH=/usr/lib/x86_64-linux-gnu/libidn
DEBUG: IDN_IPATH=/usr/include/stringprep.h
DEBUG: PR29_IPATH=/usr/include/pr29.h
                             ... found
Checking for curses (libcurses.so / term.h) ...
DEBUG: CURSES_PATH=/libcurses
DEBUG: CURSES_IPATH=/term.h
                                            ... NOT found, color output disabled
Checking for pcre (libpcre.so, pcre.h) ...
DEBUG: PCRE_PATH=/lib/i386-linux-gnu/libpcre
DEBUG: PCRE_IPATH=/usr/include/pcre.h
                                       ... found
Checking for Postgres (libpq.so, libpq-fe.h) ...
DEBUG: POSTGRES_PATH=/usr/lib/libpq
DEBUG: POSTGRES_IPATH=/usr/include/postgresql/libpq-fe.h
                                             ... found
Checking for SVN (libsvn_client-1 libapr-1.so libaprutil-1.so) ...
DEBUG: SVN_PATH=/usr/lib/x86_64-linux-gnu/libsvn_client-1
DEBUG: APR_PATH=/usr/lib/x86_64-linux-gnu/libapr
DEBUG: SVN_IPATH=/usr/include/apr-1.0/
DEBUG: APR_IPATH=/usr/include/apr-1.0/
                                                               ... found
Checking for firebird (libfbclient.so) ...
DEBUG: FIREBIRD_PATH=/usr/lib/x86_64-linux-gnu/libfbclient
DEBUG: FIREBIRD_IPATH=/usr/include/ibase.h
                                       ... found
Checking for MYSQL client (libmysqlclient.so, math.h) ...
DEBUG: MYSQL_PATH=/usr/lib/x86_64-linux-gnu/libmysqlclient
DEBUG: MYSQL_IPATH=/usr/include/mysql/mysql.h
                                                      ... found
Checking for AFP (libafpclient.so) ...
DEBUG: AFP_PATH=/libafpclient
DEBUG: AFP_IPATH=/afp.h
                                   ... NOT found, module Apple Filing Protocol disabled - Apple sucks anyway
Checking for NCP (libncp.so / nwcalls.h) ...
DEBUG: NCP_PATH=/libncp
DEBUG: NCP_IPATH=/ncp/nwcalls.h
                                         ... NOT found, module NCP disabled
Checking for SAP/R3 (librfc/saprfc.h) ...
DEBUG: SAPR3_PATH=include/librfc
DEBUG: SAPR3_IPATH=/saprfc.h
                                      ... NOT found, module sapr3 disabled
Get it from http://www.sap.com/solutions/netweaver/linux/eval/index.asp
Checking for libssh (libssh/libssh.h) ...
DEBUG: SSH_PATH=/usr/lib/x86_64-linux-gnu/libssh
DEBUG: SSH_IPATH=/usr/include/libssh/libssh.h
                                      ... found
Checking for Oracle (libocci.so libclntsh.so / oci.h and libaio.so) ...
DEBUG: ORACLE_LIB= include /etc/ld.so.conf.d/fakeroot-x86_64-linux-gnu.conf /etc/ld.so.conf.d/i386-linux-gnu_GL.conf /etc/ld.so.conf.d/i686-linux-gnu.conf /etc/ld.so.conf.d/libc.conf /etc/ld.so.conf.d/x86_64-linux-gnu.conf /etc/ld.so.conf.d/x86_64-linux-gnu_EGL.conf /etc/ld.so.conf.d/x86_64-linux-gnu_GL.conf /lib/i386-linux-gnu /lib/i686-linux-gnu /lib/x86_64-linux-gnu /usr/lib/i386-linux-gnu /usr/lib/i386-linux-gnu/mesa /usr/lib/i686-linux-gnu /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/libfakeroot /usr/lib/x86_64-linux-gnu/mesa /usr/lib/x86_64-linux-gnu/mesa-egl /usr/local/lib /lib64 /usr/lib64 /usr/local/lib64 /opt/local/lib64 /lib /usr/lib /usr/local/lib /opt/local/lib
DEBUG: ORACLE_INC=/usr/include /usr/local/include /opt/include /opt/local/include
DEBUG: ORACLE_PATH=/libocci
DEBUG: ORACLE_PATH=/libaio
DEBUG: ORACLE_IPATH=/oci.h
                                                                    ... NOT found, module Oracle disabled
Get basic and sdk package from http://www.oracle.com/technetwork/database/features/instant-client/index.html
Checking for GUI req's (pkg-config, gtk+-2.0) ...
                                              ... found
Checking for Android specialities ...
                                  ... rindex() found
                                  ... RSA_generate_key() found
Checking for secure compile option support in gcc ...
                                                  Compiling... yes
                                                  Linking... yes

**Comment by vanhauser-thc** [comment]
as you do not provider a link to the webserver I can not test myself, and the error openssl is non-descriptive ...

try the "-O" option (not a null, a capital o). it changes to obsolete ssl settings.

**Comment by jpprovost1988** [comment]
I tried with the -O option as well and it gives the same thing.
What is your email? I could give you the host by email since I don't want it to be public.

**Comment by jpprovost1988** [comment]
I found your email on your profile.
Email sent with host info.

**Comment by vanhauser-thc** [comment]
OK I found the issue.

hydra is fine (it always does TLS 1.2). it is the server that is not OK:

$ openssl s_client -connect secure.tsisports.ca:443
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---

The server does not have a certificate, and that what the connection is aborted. (why there is no descriptive error in openssl, sigh).

I don't know how to tell libopenssl to ignore that, and searching the Internet produced nothing either.

**Comment by jpprovost1988** [comment]
After I wrote you an email, I tried hydra with http-post-form on port 80 and it works like a charm.
However, I don't understand why it says that the server doesn't have any certificate since when I browse it I found a certificate from GeoTrust with TSL1.2, SHA256, etc..

It's weird.

**Comment by jpprovost1988** [comment]
Should I close this issue ?

**Comment by vanhauser-thc** [comment]
nah leave it. it should work.

**Comment by vanhauser-thc** [comment]
I added a fix for #129 - maybe this fixes this too? please test

**Comment by jpprovost1988** [comment]
I'll try soon.
Will let you know.

Thanks,

--
*Jean-Philippe Provost*

2016-06-14 4:54 GMT-04:00 van Hauser <notifications@github.com>:

**Comment by vanhauser-thc** [comment]
is it fixed?

**Comment by vanhauser-thc** [comment]
made another fix that ensures this is OK now :)
