### ISSUE TITLE
Child with pid [ERROR] 

### ISSUE THREAD

**Issue by DMT-MIND** [vanhauser-thc/thc-hydra#115]
New to hydra, keep getting the same issue any help would be greatly appreciated.
 
hydra -l admin -p rockyou.txt -s 80 -V 82.81.xxx.xxx https-post-form "/admin/login.php:parent%5Buname%5D=^USER^&parent%5Bpassword%5D=^PASS^:&_adminLogin=YES&SAVE=Login"
Hydra v8.1 (c) 2014 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2016-05-11 00:39:47
[DATA] max 1 task per 1 server, overall 64 tasks, 1 login try (l:1/p:1), ~0 tries per task
[DATA] attacking service http-post-form on port 80 with SSL
[ATTEMPT] target 82.81.xxx.xxx - login "admin" - pass "rockyou.txt" - 1 of 1 [child 0]
[STATUS] 1.00 tries/min, 1 tries in 00:01h, 1 todo in 00:01h, 1 active
[ERROR] Child with pid 3174 terminating, cannot connect
[RE-ATTEMPT] target 82.81.xxx.xxx - login "admin" - pass "rockyou.txt" - 1 of 1 [child 0]
[STATUS] 0.50 tries/min, 1 tries in 00:02h, 1 todo in 00:01h, 1 active
[ERROR] Child with pid 3177 terminating, cannot connect
[RE-ATTEMPT] target 82.81.xxx.xxx - login "admin" - pass "rockyou.txt" - 1 of 1 [child 0]
[STATUS] 0.33 tries/min, 1 tries in 00:03h, 1 todo in 00:01h, 1 active
[ERROR] Child with pid 3182 terminating, cannot connect
[STATUS] attack finished for 82.81.xxx.xxx (waiting for children to finish) ...
1 of 1 target completed, 0 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2016-05-11 00:42:49

Waited a while... 

...And now this

[REDO-ATTEMPT] target 82.81.xxx.xxx - login "admin" - pass "" - 8 of 9 [child 0]
[STATUS] 1.60 tries/min, 8 tries in 00:05h, 4294967291 todo in 1193046:26h, 3 active
[ERROR] Child with pid 4381 terminating, cannot connect
[REDO-ATTEMPT] target 82.81.xxx.xxx - login "admin" - pass "rockyou.txt" - 9 of 10 [child 2]
[REDO-ATTEMPT] target 82.81.xxx.xxx - login "admin" - pass "" - 10 of 11 [child 1]
[ERROR] Child with pid 9142 terminating, cannot connect
[REDO-ATTEMPT] target 82.81.xxx.xxx - login "admin" - pass "rockyou.txt" - 11 of 12 [child 0]
The session file ./hydra.restore was written. Type "hydra -R" to resume session.

**Comment by vanhauser-thc** [comment]
1. this is only for bugs. not for help.
2. you are not using the github version.

and you are using the wrong command line options. -P not -p.
And finally you can not connect to the server/port.
seriously. you have no clue what you are doing.
