### ISSUE TITLE
http-post-form cuts off last character of redirect location

### ISSUE THREAD

**Issue by darrencocco** [vanhauser-thc/thc-hydra#116]
Analyzed the output in debug mode and noticed that it was cutting down /login/index.php to /login/index.ph and /login/index.php?sessionid=2 to /login/index.php?sessionid=

Command run: 
./hydra example.com https-form-post "/login/index.php:username=^USER^&password=^PASS^:S=session has timed out" -l admin -P ~/passwords -t 64 -f -v -d

This is against the latest master commit as of the date of writing

**Comment by vanhauser-thc** [comment]
duplicate and fixed
