### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by theman480** [vanhauser-thc/thc-hydra#118]
Hello thc-hydra,

Fist i have to say that i love your tool.
My doubt is:
There is any way to set custom variable? Some site have Token , with username and password in the POST ACTION, i can set user with = ^USER and with= ^PASS with hydra but i dont know how to configure a custom token. Can you help me?
Thank you in advice! And sorry for my bad english.

**Comment by vanhauser-thc** [comment]
that is not supported (and would make things very complicated to code and to users to use). And it is something I have never seen needed anywhere so it is nothing (yet) I would put on the todo list.

workaround: select a fix username to attack, and use the ^USER^ / -L file  for your custom parameter.

**Comment by theman480** [comment]
Thank you for your reply.
But i did not get it, what is the  ^USER^ / -L file ?

**Comment by vanhauser-thc** [comment]
sigh

command line option "-L file.txt" supplies login names. instead you can put your custom data in there.
for the login form, ^USER^ is used to fill in the individual login name from the -L input file.

is this still makes no sense ... sorry  you are on your own :)

**Comment by theman480** [comment]
I think you do not understand me, i am talking about the token that is generated when you log in with some sites.
