### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by ShadowGamer225** [vanhauser-thc/thc-hydra#120]
Hello there. I'm new to using thc hydra. I have a problem becuse if i'm using -l ommand with -x on ftp the following error appears : [ERROR] no login/password combination given. I will be thankful for help.

**Comment by vanhauser-thc** [comment]
please post the full command line

**Comment by ShadowGamer225** [comment]
Hydra (http://www.thc.org/thc-hydra) starting at 2016-05-18 18:03:48
[ERROR] No login/password combination given!

C:\Users\Michal\Desktop\thc-hydra-windows-master>hydra.exe -vV -f  -s 21  -l qmo
carzq -x 15:15:a www.margonem.pl ftp

Is this what you want?

**Comment by vanhauser-thc** [comment]
you need to update hydra to the current version here, and then rerun your command.
you will get a correct error message: too many combinations
