### ISSUE TITLE
[feature] Use shared memory area instead of UNIX sockets

### ISSUE THREAD

**Issue by renatoalencar** [vanhauser-thc/thc-hydra#123]
As I could see in the Hydra code, the tasks share the wordlists (both users and passwords) through a UNIX socket. The problem is: UNIX sockets uses `read` and `write` system calls, so the process blocks waiting for the response of the parent process.

I propose to use a shared memory space with `shm_open` POSIX function, `mmap`, and semaphores in order to handle concurrence.

## Pros

* Hydra could be faster, since child processes would not be blocked by the OS because of a `read` call waiting;
* Could use some data structures to manage the wordlists like queues;
* Could make communication between "hydra heads" in a easier way.

## Cons

* It would have to reimplements communication between modules by hand;
* It would make things more complex, since it would have to use semaphores;
* I do not know if it can really makes some performance effects.

Thanks.

**Comment by vanhauser-thc** [comment]
Oh hydra could be made more performant by a lots of things, e.g threading, how to watch the many file descriptors, talking to the childs, etc.

but every single one of these options hurt portability. One of the main design goals of hydra was to make it run everywhere. seriously everwhere. so even if you find an old Ultrix 4.0 Unix machine on the Internet it should still compile and run there.

And of course portability hurts efficiency to some degree.

However - all the things you can do to make hydra more efficient basically do very, very little impact on the cracking speed, and rather help for a better RAM and CPU usage. RAM and CPU are not a big issue today, so I rather stay with portability (and not needing tons of code changes).

However, if you come up with some good changes that do not hurt portability, do not hesitate to send me a message, write here or send a patch.

**Comment by crondaemon** [comment]
Have you ever tried to profile it with some tools like google profiler or similar to point out which are the functions most used? Sometimes tricks like avoiding free(), and instead do all the frees at the end could help. My 2 cents.

**Comment by vanhauser-thc** [comment]
No I havent. my guess is the central select call on the sockets in hydra.c that is used to control the heads, because otherwise only the module heads are what is active.

but feel free to look for optimizations.

**Comment by renatoalencar** [comment]
Really, portability matters a lot.

**Comment by vanhauser-thc** [comment]
portability maybe is not important today for most people. Most people just want to be able to compile on Linux Windows, OS X.
For me it is important because if you do complex pentests in grown, big, complex environments it is a very useful feature :)
So it is important for me and is one of the design goals of hydra.

changing this would basically require a recoding of hydra.c and hydra-mod.c

**Comment by crondaemon** [comment]
What other projects (like libpcap, that is really portable) do is to have conditional compilation. For instance they use mmap() on linux and not on other platforms where it is not. That requires a big check effort to generate a bunch of compilation flags that allow the actual code to take different branches. 
In the above example, the configure could check for the existence of shm functions, and some abstraction function could expose a common way to communicate data that use shm functions or file, depending on the compilation.

**Comment by vanhauser-thc** [comment]
@crondaemon this is correct

if you want to implement this  - feel free to send a patch! :)

**Comment by vanhauser-thc** [comment]
I am closing this now. If you want to implement this, send in a patch. if you have any questions or trouble just email me
