### ISSUE TITLE
Password rules

### ISSUE THREAD

**Issue by la0wei** [vanhauser-thc/thc-hydra#127]
Hello,
Hcan support password like %username% to match username,hydra use "-e s" option to match username.
But what about password like acount Admin:Admin123?Hcan support password "%username%123" to match combination like this,when can a lot account,it's very useful.Hydra has function like that?

I googled hydra regular expression regex password .etc,found nothing helpful.

Need your help,thanks.

**Comment by vanhauser-thc** [comment]
no you have to create your own wordlists for that.

how hydra is implemented that would be very complicated to support.

you can use john or any other tools like that to create a wordlist

**Comment by la0wei** [comment]
for example,I have 1000 account ,only one of them use "username123"password,but I don't know which one.
In hscan,I just need one pass "%username%123" to match.
But in Hydra,I need to generate 1000 passwords,and it will take too much time to scan.

**Comment by vanhauser-thc** [comment]
if you use your brain it is way easier to do (hint: generate a file for -C parameter)

**Comment by la0wei** [comment]
I git it.I used to seperated user and password file,never used one file that user and passwords in pair,that will avoid what I worry about.
Will try that,thanks.
PS:john for "john the ripper“? I'm totally a newbie.
