### ISSUE TITLE
Writing plugins

### ISSUE THREAD

**Issue by icamys** [vanhauser-thc/thc-hydra#130]
Is there a way to write plugins for hydra? For example: I want to use a list of proxies, not just one that was assigned as environment variable.

If there is no easy way, could you specify places where I should look to modify standard behavior, please?

**Comment by vanhauser-thc** [comment]
the "plugin" mechanism is catered to the attack modules (protocols).

what you want is a new functionality. so you have to patch that in directly.

how to? My recommendation would be to watch a new environment variable (E.g. HYDRA_PROXY_FILE), write code for that in hydra.c that loads the proxies from the file into a global array of  type proxy_string_ip[] and and set use_proxy=3.

Then patch hydra-mod.c internal__hydra_connect() function to use a random proxy from the array if use_proxy == 3.

if you need any help, write here or email me.

**Comment by vanhauser-thc** [comment]
I just did a big patch to hydra, be sure to check out the newest version when/if you start on this

**Comment by icamys** [comment]
@vanhauser-thc Ok, thanks for the tip. I just started to work on it. It may take some time to warm up because I've not written C code for quite a while.
