### ISSUE TITLE
HTTP Host header used in HTTP 1.0 requests

### ISSUE THREAD

**Issue by meitar** [vanhauser-thc/thc-hydra#131]
When using a command such as `./hydra -l admin -p password -d www.myserver123.com https-post-form "/login.php:usr=^USER^&passwd=^PASS^:incorrect"` the debug output shows that an HTTP `Host` header is sent despite all the requests declared as the HTTP 1.0 protocol (not `HTTP/1.1`).

HTTP 1.0 does not actually have a `Host` header defined.

This isn't necessarily going to break anything I know of, but it is non-standard and somewhat unexpected, and I thought I should at least alert you to it.

**Comment by vanhauser-thc** [comment]
It does not hurt, and I have seen at least one browser in the past who sent it too.
so it is on purpose and it is safer to keep it IMHO - unless someone reports that this creates a problem.
