### ISSUE TITLE
Wrong address of the Free Software Foundation

### ISSUE THREAD

**Issue by xambroz** [vanhauser-thc/thc-hydra#133]
Hello,
the license files/ageements in the 8.2 release contain wrong address to Free Software Foundation.

Affected are these files:
LICENSE.OPENSSL
hmacmd5.h
hmacmd5.c

There is reference to wrong address:
LICENSE.OPENSSL:
Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
hmacmd5.h,hmacmd5.c:
Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

The correct address ( see http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt, http://www.fsf.org/about/contact/):
Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

Best regards
Michal Ambroz

**Comment by vanhauser-thc** [comment]
why anyone would actually look for that is beyond me - however thanks you did, updated it :)

**Comment by xambroz** [comment]
You know - lawyers stuff. Not that I would be so much paranoid myself ;) - I am just following the "Fedora Packaging Gudelines" and "rpmlint":: 
https://fedoraproject.org/wiki/Packaging:Guidelines#Use_rpmlint
https://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address

Thanks for fix. 
Mik
