### ISSUE TITLE
Documentation lacks the `-m` switch

### ISSUE THREAD

**Issue by boompig** [vanhauser-thc/thc-hydra#135]
`man hydra` has no `-m` flag, but error message for "http-form-post" module suggests using the `-m` option.

Input:

```bash
hydra -l admin -p 'bad password' 'localhost:8080/web:user=^USER^&pass=^PASS^:Login failed' http-form-post
```

Output:
```
Hydra (http://www.thc.org/thc-hydra) starting at 2016-06-20 17:03:01
[WARNING] You must supply the web page as an additional option or via -m, default path set to /
[ERROR] the variables argument needs at least the strings ^USER^ or ^PASS^: (null)
```

**Comment by vanhauser-thc** [comment]
man page is fixed, your command line is wrong though:

it is either one of these:
hydra -l admin -p 'bad password' -s 8080 localhost http-form-post '/web:user=^USER^&pass=^PASS^:Login failed'
hydra -l admin -p 'bad password' -s 8080 -m '/web:user=^USER^&pass=^PASS^:Login failed' localhost http-form-post 
hydra -l admin -p 'bad password' 'http-form-post://localhost:8080/web:user=^USER^&pass=^PASS^:Login failed'

also, you seem not to use the current version from github
