### ISSUE TITLE
socketpair creation failed: Too many open files

### ISSUE THREAD

**Issue by DarrenRainey** [vanhauser-thc/thc-hydra#137]
I have a targets file for ssh with over 20,000 ips in it but when I leave hydra running for a while it says 
socketpair creation failed: Too many open files how can I fix this ?

**Comment by vanhauser-thc** [comment]
hmm this is difficult.

I made a small code change, please check out the current repository, compile, install and try again. If it does not work, please check if the bug only comes up with the ssh module or also with a different module.

As an interim workaround try one of the following: 
 * increase file descriptors (ulimit -n 4096)
 * split your -M hostfile into several files and run them with different hydra instances

Greets,
vh

**Comment by DarrenRainey** [comment]
ok thanks ill check to see if that fixes the problem later today

**Comment by vanhauser-thc** [comment]
have you tried?

**Comment by DarrenRainey** [comment]
yes I've tried it. it still happens but after I recompiled hydra it doesnt seem to happen as often but the hydra.restore file gets corrupted when it happens

**Comment by theleestarr** [comment]
i can confirm this error still occurs when using large ip lists and the ssh module

**Comment by vanhauser-thc** [comment]
@theleestarr can you share your command line and the number of entries in the -M inputfile?
and please reproduce and put the full screen output here (add the -v option please)

also did you try to increase file descriptors (ulimit -n 2048)?

**Comment by theleestarr** [comment]
hydra ssh -v -t 6 -l ~/Documents/Wordlists/users.txt -P ~/Documents/Wordlists/pass.txt -M ~/Documents/Scans/Net22/xux -o ~/Documents/Loot/iot.txt

root@blackwidow:~/Documents/Scans/Net22# wc -l xux
1000 xux

**Comment by theleestarr** [comment]
![image](https://user-images.githubusercontent.com/4241200/29891538-47da4614-8d80-11e7-8239-a091a3fedfa7.png)
