### ISSUE TITLE
Uses deprecated gnome-common macros/variables

### ISSUE THREAD

**Issue by epsilon77** [vanhauser-thc/thc-hydra#139]
Hi!

gnome-common did a cleanup upstream and deprecated quite a few macros
and variables. More info Please see: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829897

Regards!

**Comment by vanhauser-thc** [comment]
thanks for the heads up!
this needs someone (else than me) to take care of the required changes.
I have no clue of gnome and gtk, and I never supported the GUI myself - all community support (which is very cool).
If anyone wants to take care of this, please write here.
