### ISSUE TITLE
1 of 1 target completed, 0 valid passwords found when i crack wifi router login passwd

### ISSUE THREAD

**Issue by zjhxmjl** [vanhauser-thc/thc-hydra#140]
Hi,guy!
    I can see that it is in fact attempting the attack with all the passwords, including the correct one.but hydra cannot find the password,then i test ftp,it can success!so i know if where some settings wrong?
this is my hydra command:
`./hydra -l admin -P ~/Desktop/1 -t 1 -f -v -V 192.168.2.1 http-post-form '/cgi-bin:password=^PASS^:login.html'`
hydra version:
`Hydra v8.3-dev (c) 2016 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.`
my wifi router:
`PHICOMM FIR304D`
router login site souce code:
[router.txt](https://github.com/vanhauser-thc/thc-hydra/files/360806/router.txt)

thks million!`

**Comment by vanhauser-thc** [comment]
can you please rerun it like this:

./hydra -d -l admin -p YOURREALPASSWORDHERE -t 1 -f -v -V 192.168.2.1 http-post-form '/cgi-bin:password=^PASS^:login.html'

and post the output? please search-replace your real password in the output before posting.

**Comment by zjhxmjl** [comment]
hi,this is result
[realResult.txt](https://github.com/vanhauser-thc/thc-hydra/files/360979/realResult.txt)

**Comment by vanhauser-thc** [comment]
Either you are not using the current github version (updated yesterday) or your web interface is not on port 80 - there is no server reply in your output

**Comment by zjhxmjl** [comment]
> Either you are not using the current github version (updated yesterday) 
i git clone and make install,so it must be the newest

> your web interface is not on port 80
sorry,what's mean? is there any solution?thks
