### ISSUE TITLE
Error: network size may only be between /16 and /31

### ISSUE THREAD

**Issue by Soheil2413** [vanhauser-thc/thc-hydra#143]
Hi
what this error means?
my code is :

`hydra www.atlasyar.com/myaccount/ -L '/root/Desktop/combo.txt' -P '/root/Desktop/combo.txt -V -f http-get /my-account_`

please help me

**Comment by vanhauser-thc** [comment]
this is not a help forum

hydra -L '/root/Desktop/combo.txt' -P '/root/Desktop/combo.txt -V -f www.atlasyar.com http-get /my-account/

**Comment by Soheil2413** [comment]
tnx for answering 
but when i run it

`[ERROR] Unknow service: http-get/my-account`

and picture:

[](http://uupload.ir/files/7fxt_capture.jpg)

**Comment by vanhauser-thc** [comment]
there is a space between http-get and /my...!!!!
