### ISSUE TITLE
2 different errors - brute force and false positives

### ISSUE THREAD

**Issue by ju4npabl0** [vanhauser-thc/thc-hydra#146]
Hello Van!

Good day!

I would like to request for assitance. I'm stumped right now.

My goals are:
* To be able to gain access to the test-website using brute force attack
* To be able to gain access to the test-website using dictionary attack

**Brute force issue** - I was trying your examples but I got this error.

```
root@kali[hydra]# hydra -t 1 -d -v -V -l admin -e snr -x 4:6:aA1 test-website.org http-post-form "/ucp.php:username=^USER^&password=^PASS^:S=success"
Hydra v8.2 (c) 2016 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

[DEBUG] Output color flag is 1
Hydra (http://www.thc.org/thc-hydra) starting at 2016-08-23 00:24:38
[DEBUG] cmdline: hydra -t 1 -d -v -V -l admin -e snr -x 4:6:aA1 test-website.org http-post-form /ucp.php:username=^USER^&password=^PASS^:S=success
[DEBUG] bfg INIT: from 4, to 6, len: 62, set: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
[DEBUG] bfg IN: len 62, from 4, current 4, to 6, state: 0 0 0 0, x: aaaa

[ERROR] definition for password bruteforce (-x) generates more than 4 billion passwords
root@kali[hydra]#
```

**False positives** - I'm having problems running hydra successfully. I always get passwords that don't work. Worst thing, I included the correct password `12p4$$w0rd34!` to the file but it is still not found. Please see the attached file for logs.

[false-positives.txt](https://github.com/vanhauser-thc/thc-hydra/files/431687/false-positives.txt)

Thanks!

**Comment by vanhauser-thc** [comment]
sorry, this is for bugs only and not a help forum.

it is not working because you have set it up wrong - what exactly nobody can tell you as depends on the exact form/cgi setup
