### ISSUE TITLE
aA1 features of character set unnecessary

### ISSUE THREAD

**Issue by tik0** [vanhauser-thc/thc-hydra#148]
The charset feature using -x of a (add all small letters), A (add all cap. letters), and 1 (add all numbers) doesn't make that much sense: They do not allow the explicit adding of a, A, or 1. So why not add a, A, 1 to the general character set, or adding an optional argument for interpreting the character set explicitly?

**Comment by vanhauser-thc** [comment]
the -x option was submitted code.
I agree it is not optimal.
You are free to submit a patch :)
(I do not have time for that for the next weeks)
