### ISSUE TITLE
xHydra - no subdirectories?

### ISSUE THREAD

**Issue by edent** [vanhauser-thc/thc-hydra#15]
I'm running a test against "192.168.0.123/admin/"

I put that path into the "Single Target" box, but I get this error when pressing "start"

```
Error: network size may only be between /16 and /31: 192.168.0.123/admin/
```

The same thing happens if I start the URL with `http://` or just `://`

Am I missing something obvious here?

**Comment by ivasku** [comment]
I have the same problem, I am trying to use crucnh and pipe it`s output to hydra. 
My command is:
crunch 0 5 asdfghjkllzxcvbnmqwrtyuiop | hydra -l "jack@PenTesterAcademy.com" -f -v -e ns http://pentesteracademylab.appspot.com/lab/webapp/1 http-get /

I am getting the same error:

error: network size may only be between /16 and /31:

Anyone have any idea ?

**Comment by vanhauser-thc** [comment]
1. it is not possible to use pipes. you must write to a file.
2. the correct command line would be

hydra -l "jack@PenTesterAcademy.com" -P crunch.out -f -v -e ns http-get://pentesteracademylab.appspot.com/lab/webapp/1

**Comment by ivasku** [comment]
Thank you for the correct command.

I have used on BackTrack before crunch directly with Hydra because I needed huge wordLists and I had a small hard drive. I remember it worked I just can`t remember how to do it again.

Are you sure you can`t redirect crunch generation to Hydra on the fly ?

**Comment by crondaemon** [comment]
Is it not possible to write/read from a named pipe? Something like:

```
crunch 0 5 asdfghjkllzxcvbnmqwrtyuiop > /tmp/mynamedpipe
hydra -l "jack@PenTesterAcademy.com" -f -v -e ns -P /tmp/mynamedpipe http://pentesteracademylab.appspot.com/lab/webapp/1 http-get /
```

**Comment by vanhauser-thc** [comment]
I am the developer of hydra.
trust me, it is impossible.
(hydra first reads in the whole file to count the lines etc and then rereads it. you can not reread from a pipe)

**Comment by crondaemon** [comment]
I trust you, trust me ;). Sometimes easiest solutions simply don't came in mind. That was not the case :).

**Comment by ivasku** [comment]
I probably mixed it with pyrit or aircrack then. I remember using crunch on the fly while cracking something :).

Thank you.

**Comment by ivasku** [comment]
I have tried with the command you provided:

hydra -l "jack@PenTesterAcademy.com" -P '/root/wordlist.txt' -f -v -e ns http-get://pentesteracademylab.appspot.com/lab/webapp/1 

and I am still getting the 

error: network size may only be between /16 and /31:

Any idea what am I doing wrong?

**Comment by vanhauser-thc** [comment]
yeah that is a bug. I might not have any time to fix this the next week I guess.

work around:
hydra -l "jack@PenTesterAcademy.com" -P '/root/wordlist.txt' -f -v -e ns pentesteracademylab.appspot.com  http-get  /lab/webapp/1

**Comment by ivasku** [comment]
Thanks, now it works, but it gives false positives, it finishes very quickly and gives the password the same as the username.

**Comment by vanhauser-thc** [comment]
if it gives false positives, then it is a form based login, and not http basic auth.
something completely different.
use http-form-post instead of http-get
it is more complex, read the docu (-U) and online examples by people

**Comment by ivasku** [comment]
I have followed this page http://null-byte.wonderhowto.com/how-to/hack-like-pro-crack-online-web-form-passwords-with-thc-hydra-burp-suite-0160643/ 

And studying that page I have come up with the command for Hydra:
hydra -l "jack@PentesterAcademy.com" -l wordlist.txt pentesteracademylac.appspot.com http-get /lab/webapp/1:email=^USER^&password=^PASS^

I cannot use the http-form-post (or atleast I think I can`t ) because the BURP showed that this form support the GET protocol on intercept.

**Comment by ivasku** [comment]
I have read some more on this subject, something like (http://insidetrust.blogspot.rs/2011/08/using-hydra-to-dictionary-attack-web.html).

I have composed a hydra command for this web page (http://pentesteracademylab.appspot.com/lab/webapp/1) 

hydra 173.194.67.141 http-get "/lab/webapp/1:email=^USER^&password=^PASS^:Failed!" -l jack@pentesteracademy.com -P word2.txt -t 20 -w 90 -o hydraAttack.txt

And I get 64 "positive results". Can you give me a hint (not a solution) what should I investigate from this point ?

Thank you.

**Comment by vanhauser-thc** [comment]
I would recommend to use a browser plus man in the middle proxy (e.g. zap or burp) and then look what exactly is sent where.
