### ISSUE TITLE
Hydra can't resolve website.

### ISSUE THREAD

**Issue by Vancer** [vanhauser-thc/thc-hydra#151]
So Basically I'm 100% sure of the website, and I tried sending a request using python and it returned with a status code [200] OK.

Here is what is happening with me in hydra.

**Command I used [I TRIED ALL] :**
hydra -s 443 -v -V -L fu.txt -p 2326690704 https://thewebsite.i.am.testing.on http-post-form "/login.php:studentNumber=^USER^&password=^PASS^:Something went wrong"

hydra -s 443 -v -V -L fu.txt -p 2326690704 https://thewebsite.i.am.testing.on https-post-form "/login.php:studentNumber=^USER^&password=^PASS^:Something went wrong"

hydra -v -V -L fu.txt -p 2326690704 thewebsite.i.am.testing.on https-post-form "/login.php:studentNumber=^USER^&password=^PASS^:Something went wrong"  

**Return Error Code:** 

_Hydra v7.5 (c)2013 by van Hauser/THC & David Maciejak - for legal purposes only

Hydra (http://www.thc.org/thc-hydra) starting at 2016-09-02 01:35:55
[DATA] 3 tasks, 1 server, 3 login tries (l:3/p:1), ~1 try per task
[DATA] attacking service http-post-form on port 443
[VERBOSE] Resolving addresses ... [failed for https://thewebsite.i.am.testing.on] done
Process 6540: Can not connect [unreachable], retrying (1 of 1 retries)
Process 6541: Can not connect [unreachable], retrying (1 of 1 retries)
0 of 1 target completed, 0 valid passwords found
[ERROR] 1 target did not resolve or could not be connected
Hydra (http://www.thc.org/thc-hydra) finished at 2016-09-02 01:35:55_

**Comment by vanhauser-thc** [comment]
you are doing it wrong and did not look in the help or documentation.
remove the https:// from the hostname
