### ISSUE TITLE
Bug : 

### ISSUE THREAD

**Issue by flostee** [vanhauser-thc/thc-hydra#152]
Hello,
I tryed to "hack" the website of a friend (who allowed me to do that), but whenever I try I get an error.
Here is the error:
Error: network size may only be between /16 and /31
Here is my text: 
hydra -l admin -P passlist.txt https://awebsite.com https-post-form /"input type=^USER^ size="9" name="A16" value="" id="A16" class="l-1 A16 padding webdevclass-riche"input type=^PASS^ size="9" name="A15" value="" id="A15" class="l-1 A15 padding webdevclass-riche"
Thanks for helping :smile:

**Comment by flostee** [comment]
Ups here is my text :
 hydra -l admin -P passlist.txt https://awebsite.com https-post-form /"<input type=^USER^ size="9" name="A16" value="" id="A16" class="l-1 A16 padding webdevclass-riche"><input type=^PASS^ size="9" name="A15" value="" id="A15" class="l-1 A15 padding webdevclass-riche">"

**Comment by flostee** [comment]
hydra -l admin -P passlist.txt https://awebsite.com https-post-form "input type=^USER^ size="9" name="A16" value="" id="A16" class="l-1 A16 padding webdevclass-riche"input type=^PASS^ size="9" name="A15" value="" id="A15" class="l-1 A15 padding webdevclass-riche"

**Comment by vanhauser-thc** [comment]
you are calling it the wrong way. https:// is not part of a valid hostname

**Comment by flostee** [comment]
It didn´t work so I tried something different:
hydra -l user -P passlist.txt xxxxxxxxxx.fr https-get-form "/xxxxxxxxx text=^USER^&password=^PASS^&Login=Authentification \'login/mot de passe\' échouée."
I get the error:
[ERROR] the variables argument needs at least the strings ^USER^ or ^PASS^: (null)

**Comment by vanhauser-thc** [comment]
this is not a help forum. this is for reporting bugs. if you can not read the README or the -U help output or search the intenet forums - bad for you
