### ISSUE TITLE
svn crack error

### ISSUE THREAD

**Issue by sechacking** [vanhauser-thc/thc-hydra#153]
[root@localhost tmp]# hydra -l **\* -p ***\* svn://192._._._/_**/ -v
Hydra v8.4-dev (c) 2016 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2016-09-03 12:55:31
[DATA] max 1 task per 1 server, overall 64 tasks, 1 login try (l:1/p:1), ~0 tries per task
[DATA] attacking service svn on port 3690
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[ERROR] Access refused (error code 170000) , message: “svn://192._._._:3690/_*_/”与“svn://192._._._:/_”并不在同一个版本库中
[STATUS] attack finished for 192._._._ (waiting for children to complete tests)
1 of 1 target completed, 0 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2016-09-03 12:55:32

**Comment by sechacking** [comment]
i guess hydra add port for svn URL like

[ERROR] Access refused (error code 170000) , message: “svn://192...:3690/*/”与“svn://192...:/

**Comment by vanhauser-thc** [comment]
sorry I do not understand what you are trying to trying to tell me. please try again
