### ISSUE TITLE
Hotmail SMTP - Error SSL

### ISSUE THREAD

**Issue by stifler6969** [vanhauser-thc/thc-hydra#154]
Hello,

I try Hydra v8.2 on Kali to make a test attack on Hotmail SMTP.
I use this command : hydra smtp.live.com smtp -l xxxx@hotmail.com -P /dico.txt -s 587 -S -v -V -t 1

I have this error : 

[ATTEMPT] target smtp.live.com - login "xxxx@hotmail.com" - pass "xxxx" - 1 of 10 [child 0]
[VERBOSE] Could not create an SSL session: error:00000000:lib(0):func(0):reason(0)
[ERROR] Child with pid 5095 terminating, can not connect

I think it's an error from SSL negociation...

Thanks for your help

Greg

**Comment by tidatida** [comment]
I met almost the same error: 
[ERROR] Child with pid 6678 terminating, can not connect
[ATTEMPT] target smtp-mail.outlook.com - login "mytestaccountxxx@outlook.com" - pass "<><><><>" -  1 of 9606691 [child 1] (0/25)
[VERBOSE] Could not create an SSL session: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
[ERROR] Child with pid 6711 terminating, can not connect

**Comment by vanhauser-thc** [comment]
it seems like microsoft is using some weird ssl config on their mail server. I will look into it.
it is really difficult to preconfigure ssl connections so they work with every possible target configuration.
and openssl especially sucks.

**Comment by vanhauser-thc** [comment]
Ah, found the issue.

you were using it wrong :)
-S activates directl SSL (like SMTPS on port 465/tcp)
But as you attack port 587 which is plaintext and needs the SMTP STARTTLS command you have to add the module option TLS and remove the -S command line option.

So this works:

hydra -l xxxx@hotmail.com -P /dico.txt -s 587 -S -v -V -t 1 smtp.live.com smtp tls


I will add a warning so this happens fewer people in the future.
