### ISSUE TITLE
[ERROR]: expected CC

### ISSUE THREAD

**Issue by mehranexpert** [vanhauser-thc/thc-hydra#156]
i Got error . [ERROR]: expected CC, got 0xcf45e970 while Cracking .

what that mean and how can i solve it ?

**Comment by vanhauser-thc** [comment]
it means that the RDP server send data that was different than it was expected to be in the protocol.
Most likely its a newer protocol or new functionality.

I did not program that module and have no experience with RDP sadly.

You play dirty and comment the check out, comile and see if a valid login/password is found and an invalid is still invalid, and then send me a patch :)

otherwise it needs someone (you?) to debug and fix it.

**Comment by mehranexpert** [comment]
Thanks for your answer , im try to find its find valid login or not and tell you .

other thing it be good if  -o option write immediately find crack to file , i test -o option after all jobs ends it write Valid on file .

**Comment by vanhauser-thc** [comment]
that is not true. it is written, however buffered. when it is written to the OS depends on the libc.
but I put now a flush in after a successful find.

**Comment by mehranexpert** [comment]
Yes , thanks now Its okey ,
Just one more Thing why hydra Reduce speed after some times 
```
[STATUS] 795.67 tries/min, 19096 tries in 00:24h, 95 to do in 00:01h, 17 active
[STATUS] 764.04 tries/min, 19101 tries in 00:25h, 95 to do in 00:01h, 17 active
[STATUS] 734.88 tries/min, 19107 tries in 00:26h, 95 to do in 00:01h, 17 active
[STATUS] 707.81 tries/min, 19111 tries in 00:27h, 95 to do in 00:01h, 17 active
[STATUS] 682.75 tries/min, 19117 tries in 00:28h, 95 to do in 00:01h, 17 active
[STATUS] 659.41 tries/min, 19123 tries in 00:29h, 95 to do in 00:01h, 17 active
[STATUS] 637.63 tries/min, 19129 tries in 00:30h, 95 to do in 00:01h, 17 active
[STATUS] 617.26 tries/min, 19135 tries in 00:31h, 95 to do in 00:01h, 17 active
[STATUS] 598.28 tries/min, 19145 tries in 00:32h, 96 to do in 00:01h, 17 active
[STATUS] 580.85 tries/min, 19168 tries in 00:33h, 89 to do in 00:01h, 16 active
[STATUS] 563.88 tries/min, 19172 tries in 00:34h, 89 to do in 00:01h, 16 active
[STATUS] 547.94 tries/min, 19178 tries in 00:35h, 89 to do in 00:01h, 16 active
[STATUS] 532.89 tries/min, 19184 tries in 00:36h, 89 to do in 00:01h, 16 active
```
its depend OS ? or something other ?

**Comment by vanhauser-thc** [comment]
it adapts to the target
