### ISSUE TITLE
"Weird bug detected"...

### ISSUE THREAD

**Issue by dimanester** [vanhauser-thc/thc-hydra#157]
root@kali:~/Desktop# hydra -L login.txt -P pass.txt ssh://10.4.2.2:1004
Hydra v8.2 (c) 2016 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2016-09-15 07:25:42
[WARNING] Many SSH configurations limit the number of parallel tasks, it is recommended to reduce the tasks: use -t 4
[DATA] max 16 tasks per 1 server, overall 64 tasks, 268 login tries (l:4/p:67), ~0 tries per task
[DATA] attacking service ssh on port 1004
[1004][ssh] host: 10.4.2.2   login: tat   password: TatAp@2
[1004][ssh] host: 10.4.2.2   login: tat   password: TatAp@2
[ERROR] Weird bug detected where more tests were performed than possible. Please post your command line here: https://github.com/vanhauser-thc/thc-hydra/issues/113 or send it in an email to vh@thc.org

**Comment by vanhauser-thc** [comment]
update to 8.3
