### ISSUE TITLE
How to set custom User-Agent

### ISSUE THREAD

**Issue by cdanger** [vanhauser-thc/thc-hydra#159]
Hello,
is there any way to customize the User-Agent HTTP header value?

**Comment by vanhauser-thc** [comment]
this is not a help forum, it is for reporting bugs.

# hydra -U http-post-form
...
The following parameters are optional:
...
 (h|H)=My-Hdr\: foo   to send a user defined HTTP header with each request
                 ^USER^ and ^PASS^ can also be put into these headers!
                 Note: 'h' will add the user-defined header at the end
                 regardless it's already being sent by Hydra or not.
                 'H' will replace the value of that header if it exists, by the
                 one supplied by the user, or add the header at the end
Note that if you are going to put colons (:) in your headers you should escape them with a backslash (\).
...


:H=User-Agent\: wget
