### ISSUE TITLE
Attack method using password, username and ip file

### ISSUE THREAD

**Issue by LucasRoot** [vanhauser-thc/thc-hydra#160]
When I'm making an attack with a list of passwords, usernames and ip files, does the hydra try for each ip all the possible combinations of users:passwords and go to another ip of the list?
Like this pseudo code:
```
for each ip
    for each username
        for each password
           attack(ip, username, password)
```
Or is something like this:

```
for each username
    for each password
        for each ip
           attack(ip, username, password)
```

**Comment by vanhauser-thc** [comment]
well, you can see that in the code.

basically it is "for each ip (can be in parallel)" 
the following oder is selectable.
username -> password (default)
password -> username (-u or -x option)
