### ISSUE TITLE
Error 113

### ISSUE THREAD

**Issue by Zairik** [vanhauser-thc/thc-hydra#167]
root@Zairik:~# hydra -s 465 -l "email" -P /root/Desktop/DPSJEDDAH-PASS -v -V -t 2 smtp.gmail.com smtp

This is the first time I am using hydra and I've been trying to bruteforce my own account for the test but I get this bug ---->>   EBUG: 5 10
[ERROR] Weird bug detected where more tests were performed than possible. Please post your command line here: https://github.com/vanhauser-thc/thc-hydra/issues/113 or send it in an email to vh@thc.org

**Comment by vanhauser-thc** [comment]
just use the current version in this repository (git clone ...)

**Comment by Zairik** [comment]
thanks @vanhauser-thc
