### ISSUE TITLE
[question] custom raw protocol?

### ISSUE THREAD

**Issue by CanadianJeff** [vanhauser-thc/thc-hydra#168]
there is a protocol im trying to login to thats fully custom

how do I train hydra to try to login?

example failed login looks like this

```
00000000  1b 5b 33 37 6d 55 73 65  72 6e 61 6d 65 3a 20 1b   .[37mUse rname: .
00000010  5b 33 30 6d 20 00                                  [30m .
    00000000  74 65 73 74 0d 0a                                  test..
00000016  1b 5b 33 37 6d 50 61 73  73 77 6f 72 64 3a 20 1b   .[37mPas sword: .
00000026  5b 33 30 6d 20 00                                  [30m .
    00000006  74 65 73 74 0d 0a                                  test..
0000002C  1b 5b 31 41 00                                     .[1A.
00000031  1b 5b 33 36 6d 57 52 4f  4e 47 20 41 4e 53 57 45   .[36mWRO NG ANSWE
00000041  52 20 42 49 54 43 48 21  21 0d 0a                  R BITCH! !..
    0000000C  0d 0a                                              ..
```

**Comment by CanadianJeff** [comment]
with hydra I notice it sends 0d 00 instead of 0d 0a which is '\r\n'

**Comment by CanadianJeff** [comment]
with hydra I notice it sends 0d 00 instead of 0d 0a which is '\r\n'

**Comment by vanhauser-thc** [comment]
you could just take the source code and modify hydra-telnet.c that would be the easiest solution for you.

for a real protocol that is worth supporting you would add a new hydra-PROTOCOL.c file and add it to the "//insert here" references in hydra.c and hydra.h

**Comment by CanadianJeff** [comment]
I tried to modify the telnet.c file with \r\n instead of \r\0 for some reason its still sending \r\0

**Comment by CanadianJeff** [comment]
https://github.com/CanadianJeff/thc-hydra/commit/583e35a395787507f3e11a2d940a63070f9fe14d
