### ISSUE TITLE
crack email

### ISSUE THREAD

**Issue by karencho777** [vanhauser-thc/thc-hydra#169]
hello wanna to crack my own email password with password list ,but when in password list is more 50 words hydra cant crack or giving a wrong password,why is that? was cracking gmail ,mail.ru ...there is no difference ,i tryed 10 times and could crack only one time and in password list was 25 words,why it is not cracking?

**Comment by vanhauser-thc** [comment]
if you read what hydra writes you would know:

[INFO] several providers have implemented cracking protection, check with a small wordlist first - and stay legal!
