### ISSUE TITLE
hydra taking much time

### ISSUE THREAD

**Issue by ashee69** [vanhauser-thc/thc-hydra#17]
though i am new to use this but i researched some forums and videos for attacking RDPs. so here is the issue:
i put this command for hydra
hydra -s 3389 -v -V -L /u1.txt -P /p1.txt -t 10 -w 30 -M /short.txt rdp
where only 4 IPs were to attack and 4 entries in username and 6 entries in password list. still its taking too much time to complete, even i m running it for 3 hours still no result. obviously i cant go for a big wordlist and more ips
still it saying these logs to me after completing
[STATUS] attack finished for 61.67.14.131 (waiting for children to complete tests)
[VERBOSE] Server RDP version is 4
[STATUS] 120.00 tries/min, 120 tries in 00:01h, 1 todo in 00:01h, 3 active
[STATUS] 60.00 tries/min, 120 tries in 00:02h, 1 todo in 00:01h, 3 active
[STATUS] 40.00 tries/min, 120 tries in 00:03h, 1 todo in 00:01h, 1 active
[STATUS] 30.00 tries/min, 120 tries in 00:04h, 1 todo in 00:01h, 1 active
[STATUS] 24.00 tries/min, 120 tries in 00:05h, 1 todo in 00:01h, 1 active
[STATUS] 20.00 tries/min, 120 tries in 00:06h, 1 todo in 00:01h, 1 active
[STATUS] 17.14 tries/min, 120 tries in 00:07h, 1 todo in 00:01h, 1 active
[STATUS] 15.00 tries/min, 120 tries in 00:08h, 1 todo in 00:01h, 1 active
[STATUS] 13.33 tries/min, 120 tries in 00:09h, 1 todo in 00:01h, 1 active
[STATUS] 12.00 tries/min, 120 tries in 00:10h, 1 todo in 00:01h, 1 active
[STATUS] 10.91 tries/min, 120 tries in 00:11h, 1 todo in 00:01h, 1 active
[STATUS] 10.00 tries/min, 120 tries in 00:12h, 1 todo in 00:01h, 1 active
[STATUS] 9.23 tries/min, 120 tries in 00:13h, 1 todo in 00:01h, 1 active
[STATUS] 8.57 tries/min, 120 tries in 00:14h, 1 todo in 00:01h, 1 active
[STATUS] 8.00 tries/min, 120 tries in 00:15h, 1 todo in 00:01h, 1 active
[STATUS] 7.50 tries/min, 120 tries in 00:16h, 1 todo in 00:01h, 1 active
[STATUS] 7.06 tries/min, 120 tries in 00:17h, 1 todo in 00:01h, 1 active
[STATUS] 6.67 tries/min, 120 tries in 00:18h, 1 todo in 00:01h, 1 active
[STATUS] 6.32 tries/min, 120 tries in 00:19h, 1 todo in 00:01h, 1 active
[STATUS] 6.00 tries/min, 120 tries in 00:20h, 1 todo in 00:01h, 1 active
[STATUS] 5.71 tries/min, 120 tries in 00:21h, 1 todo in 00:01h, 1 active
[STATUS] 5.45 tries/min, 120 tries in 00:22h, 1 todo in 00:01h, 1 active
[STATUS] 5.22 tries/min, 120 tries in 00:23h, 1 todo in 00:01h, 1 active
[STATUS] 5.00 tries/min, 120 tries in 00:24h, 1 todo in 00:01h, 1 active
[STATUS] 4.80 tries/min, 120 tries in 00:25h, 1 todo in 00:01h, 1 active
[STATUS] 4.62 tries/min, 120 tries in 00:26h, 1 todo in 00:01h, 1 active
[STATUS] 4.44 tries/min, 120 tries in 00:27h, 1 todo in 00:01h, 1 active
[STATUS] 4.29 tries/min, 120 tries in 00:28h, 1 todo in 00:01h, 1 active
[STATUS] 4.14 tries/min, 120 tries in 00:29h, 1 todo in 00:01h, 1 active
[STATUS] 4.00 tries/min, 120 tries in 00:30h, 1 todo in 00:01h, 1 active
[STATUS] 3.87 tries/min, 120 tries in 00:31h, 1 todo in 00:01h, 1 active
[STATUS] 3.75 tries/min, 120 tries in 00:32h, 1 todo in 00:01h, 1 active
[STATUS] 3.64 tries/min, 120 tries in 00:33h, 1 todo in 00:01h, 1 active
[STATUS] 3.53 tries/min, 120 tries in 00:34h, 1 todo in 00:01h, 1 active
[STATUS] 3.43 tries/min, 120 tries in 00:35h, 1 todo in 00:01h, 1 active
[STATUS] 3.33 tries/min, 120 tries in 00:36h, 1 todo in 00:01h, 1 active
[STATUS] 3.24 tries/min, 120 tries in 00:37h, 1 todo in 00:01h, 1 active
[STATUS] 3.16 tries/min, 120 tries in 00:38h, 1 todo in 00:01h, 1 active
[STATUS] 3.08 tries/min, 120 tries in 00:39h, 1 todo in 00:01h, 1 active
[STATUS] 3.00 tries/min, 120 tries in 00:40h, 1 todo in 00:01h, 1 active
[STATUS] 2.93 tries/min, 120 tries in 00:41h, 1 todo in 00:01h, 1 active
[STATUS] 2.86 tries/min, 120 tries in 00:42h, 1 todo in 00:01h, 1 active
[STATUS] 2.79 tries/min, 120 tries in 00:43h, 1 todo in 00:01h, 1 active
[STATUS] 2.73 tries/min, 120 tries in 00:44h, 1 todo in 00:01h, 1 active
[STATUS] 2.67 tries/min, 120 tries in 00:45h, 1 todo in 00:01h, 1 active
[STATUS] 2.61 tries/min, 120 tries in 00:46h, 1 todo in 00:01h, 1 active
[STATUS] 2.55 tries/min, 120 tries in 00:47h, 1 todo in 00:01h, 1 active
[STATUS] 2.50 tries/min, 120 tries in 00:48h, 1 todo in 00:01h, 1 active
[STATUS] 2.45 tries/min, 120 tries in 00:49h, 1 todo in 00:01h, 1 active
[STATUS] 2.40 tries/min, 120 tries in 00:50h, 1 todo in 00:01h, 1 active
[STATUS] 2.35 tries/min, 120 tries in 00:51h, 1 todo in 00:01h, 1 active
[STATUS] 2.31 tries/min, 120 tries in 00:52h, 1 todo in 00:01h, 1 active
[STATUS] 2.26 tries/min, 120 tries in 00:53h, 1 todo in 00:01h, 1 active
[STATUS] 2.22 tries/min, 120 tries in 00:54h, 1 todo in 00:01h, 1 active
[STATUS] 2.18 tries/min, 120 tries in 00:55h, 1 todo in 00:01h, 1 active
[STATUS] 2.14 tries/min, 120 tries in 00:56h, 1 todo in 00:01h, 1 active
[STATUS] 2.11 tries/min, 120 tries in 00:57h, 1 todo in 00:01h, 1 active
[STATUS] 2.07 tries/min, 120 tries in 00:58h, 1 todo in 00:01h, 1 active
[STATUS] 2.03 tries/min, 120 tries in 00:59h, 1 todo in 00:01h, 1 active
[STATUS] 2.00 tries/min, 120 tries in 01:00h, 1 todo in 00:01h, 1 active
[STATUS] 1.97 tries/min, 120 tries in 01:01h, 1 todo in 00:01h, 1 active
[STATUS] 1.94 tries/min, 120 tries in 01:02h, 1 todo in 00:01h, 1 active
[STATUS] 1.90 tries/min, 120 tries in 01:03h, 1 todo in 00:01h, 1 active
[STATUS] 1.88 tries/min, 120 tries in 01:04h, 1 todo in 00:01h, 1 active
[STATUS] 1.85 tries/min, 120 tries in 01:05h, 1 todo in 00:01h, 1 active
[STATUS] 1.82 tries/min, 120 tries in 01:06h, 1 todo in 00:01h, 1 active
[STATUS] 1.79 tries/min, 120 tries in 01:07h, 1 todo in 00:01h, 1 active
[STATUS] 1.76 tries/min, 120 tries in 01:08h, 1 todo in 00:01h, 1 active
[STATUS] 1.74 tries/min, 120 tries in 01:09h, 1 todo in 00:01h, 1 active
[STATUS] 1.71 tries/min, 120 tries in 01:10h, 1 todo in 00:01h, 1 active
[STATUS] 1.69 tries/min, 120 tries in 01:11h, 1 todo in 00:01h, 1 active
[STATUS] 1.67 tries/min, 120 tries in 01:12h, 1 todo in 00:01h, 1 active
[STATUS] 1.64 tries/min, 120 tries in 01:13h, 1 todo in 00:01h, 1 active
[STATUS] 1.62 tries/min, 120 tries in 01:14h, 1 todo in 00:01h, 1 active
[STATUS] 1.60 tries/min, 120 tries in 01:15h, 1 todo in 00:01h, 1 active
[STATUS] 1.58 tries/min, 120 tries in 01:16h, 1 todo in 00:01h, 1 active
[STATUS] 1.56 tries/min, 120 tries in 01:17h, 1 todo in 00:01h, 1 active
[STATUS] 1.54 tries/min, 120 tries in 01:18h, 1 todo in 00:01h, 1 active
[STATUS] 1.52 tries/min, 120 tries in 01:19h, 1 todo in 00:01h, 1 active
[STATUS] 1.50 tries/min, 120 tries in 01:20h, 1 todo in 00:01h, 1 active
[STATUS] 1.48 tries/min, 120 tries in 01:21h, 1 todo in 00:01h, 1 active
[STATUS] 1.46 tries/min, 120 tries in 01:22h, 1 todo in 00:01h, 1 active
[STATUS] 1.45 tries/min, 120 tries in 01:23h, 1 todo in 00:01h, 1 active
[STATUS] 1.43 tries/min, 120 tries in 01:24h, 1 todo in 00:01h, 1 active
[STATUS] 1.41 tries/min, 120 tries in 01:25h, 1 todo in 00:01h, 1 active
[STATUS] 1.40 tries/min, 120 tries in 01:26h, 1 todo in 00:01h, 1 active
[STATUS] 1.38 tries/min, 120 tries in 01:27h, 1 todo in 00:01h, 1 active
[STATUS] 1.36 tries/min, 120 tries in 01:28h, 1 todo in 00:01h, 1 active
[STATUS] 1.35 tries/min, 120 tries in 01:29h, 1 todo in 00:01h, 1 active
[STATUS] 1.33 tries/min, 120 tries in 01:30h, 1 todo in 00:01h, 1 active
[STATUS] 1.32 tries/min, 120 tries in 01:31h, 1 todo in 00:01h, 1 active
[STATUS] 1.30 tries/min, 120 tries in 01:32h, 1 todo in 00:01h, 1 active
[STATUS] 1.29 tries/min, 120 tries in 01:33h, 1 todo in 00:01h, 1 active
[STATUS] 1.28 tries/min, 120 tries in 01:34h, 1 todo in 00:01h, 1 active
[STATUS] 1.26 tries/min, 120 tries in 01:35h, 1 todo in 00:01h, 1 active
[STATUS] 1.25 tries/min, 120 tries in 01:36h, 1 todo in 00:01h, 1 active
[STATUS] 1.24 tries/min, 120 tries in 01:37h, 1 todo in 00:01h, 1 active
[STATUS] 1.22 tries/min, 120 tries in 01:38h, 1 todo in 00:01h, 1 active
[STATUS] 1.21 tries/min, 120 tries in 01:39h, 1 todo in 00:01h, 1 active
[STATUS] 1.20 tries/min, 120 tries in 01:40h, 1 todo in 00:01h, 1 active
[STATUS] 1.19 tries/min, 120 tries in 01:41h, 1 todo in 00:01h, 1 active
[STATUS] 1.18 tries/min, 120 tries in 01:42h, 1 todo in 00:01h, 1 active
[STATUS] 1.17 tries/min, 120 tries in 01:43h, 1 todo in 00:01h, 1 active
[STATUS] 1.15 tries/min, 120 tries in 01:44h, 1 todo in 00:01h, 1 active
[STATUS] 1.14 tries/min, 120 tries in 01:45h, 1 todo in 00:01h, 1 active
[STATUS] 1.13 tries/min, 120 tries in 01:46h, 1 todo in 00:01h, 1 active
[STATUS] 1.12 tries/min, 120 tries in 01:47h, 1 todo in 00:01h, 1 active
[STATUS] 1.11 tries/min, 120 tries in 01:48h, 1 todo in 00:01h, 1 active
[STATUS] 1.10 tries/min, 120 tries in 01:49h, 1 todo in 00:01h, 1 active
[STATUS] 1.09 tries/min, 120 tries in 01:50h, 1 todo in 00:01h, 1 active
[STATUS] 1.08 tries/min, 120 tries in 01:51h, 1 todo in 00:01h, 1 active
[STATUS] 1.07 tries/min, 120 tries in 01:52h, 1 todo in 00:01h, 1 active
[STATUS] 1.06 tries/min, 120 tries in 01:53h, 1 todo in 00:01h, 1 active
[STATUS] 1.05 tries/min, 120 tries in 01:54h, 1 todo in 00:01h, 1 active
[STATUS] 1.04 tries/min, 120 tries in 01:55h, 1 todo in 00:01h, 1 active
[STATUS] 1.03 tries/min, 120 tries in 01:56h, 1 todo in 00:01h, 1 active
[STATUS] 1.03 tries/min, 120 tries in 01:57h, 1 todo in 00:01h, 1 active
[STATUS] 1.02 tries/min, 120 tries in 01:58h, 1 todo in 00:01h, 1 active
[STATUS] 1.01 tries/min, 120 tries in 01:59h, 1 todo in 00:01h, 1 active
[STATUS] 1.00 tries/min, 120 tries in 02:00h, 1 todo in 00:01h, 1 active
[STATUS] 0.99 tries/min, 120 tries in 02:01h, 1 todo in 00:01h, 1 active
[STATUS] 0.98 tries/min, 120 tries in 02:02h, 1 todo in 00:01h, 1 active
[STATUS] 0.98 tries/min, 120 tries in 02:03h, 1 todo in 00:01h, 1 active
[STATUS] 0.97 tries/min, 120 tries in 02:04h, 1 todo in 00:01h, 1 active
[STATUS] 0.96 tries/min, 120 tries in 02:05h, 1 todo in 00:01h, 1 active

please suggest me if i am going through wrong parameters.
thanx

**Comment by UmbraDeorum** [comment]
I've noticed that passing **^C** to the console and then resuming after a few seconds with _hydra -R_ seems to reset the protection - and thus the testing speed. Too manual to the extend of tedious for tough cases, but it does speed up things at times.

**Comment by vikramre1989** [comment]
FastRDP is a tool for brute force attacks on the Remote Desktop Protocol (RDP) on the Windows operating system, which allows users to remotely connect to computers and servers. This tool is written in C# programming language.

I tested this tool, and it works great! I’ll put the link to this tool below. I strongly recommend trying out this tool.

https://github.com/rensii-1996/RDP-Brute-Force
