### ISSUE TITLE
Option -x 12:12:aA1

### ISSUE THREAD

**Issue by badetitou** [vanhauser-thc/thc-hydra#173]
When I use hydra with option -x 12:12:aA1, I got this error : 
[ERROR] No login/password combination given!

But with -x 10:12:aA1 i didn't have error.
Is it normal that we cannot set the min lenth superior at 10 ?

**Comment by vanhauser-thc** [comment]
are you using the version of this repository? if not please do

**Comment by badetitou** [comment]
My bad. I used another version. With your version the Error is : definition for password bruteforce (-x) generates more than 4 billion passwords

I suppose it's normal.

**Comment by vanhauser-thc** [comment]
exactly :)
