### ISSUE TITLE
[question] How do I download this and use it on a website login?

### ISSUE THREAD

**Issue by RandomPieKevin** [vanhauser-thc/thc-hydra#174]
I would like to test this out on a website that I created, but I do not know how to download this program and run it so that I can hack the password. 

How should I do it? 

Thanks,
RandomPieKevin

**Comment by Wolodija** [comment]
Everything should be describe in README.md.
Especially `HOW TO COMPILE` and next sections

Regards,
Wolodija

**Comment by RandomPieKevin** [comment]
Where do I type in the compile instructions?

Also, when I click on the link to download, it says that there is a virus. 

Thanks,
Kevin

**Comment by vanhauser-thc** [comment]
hi kevin, this is for reporting bugs.
not a help forum for hydra, and neither a generic how to compile stuff.
sorry
