### ISSUE TITLE
every time 16 password finds and neither of them is right password..

### ISSUE THREAD

**Issue by ramines** [vanhauser-thc/thc-hydra#177]
i used hydra to crack my http://heyatim.az mobile chat mini portal account, my user name is "nesene" and password "19921992" , i want to know this is a bug or i did something wrong may be... and or site have any protection ?? please help i spent almost a day for this issue... and no any usefull result..

**Comment by vanhauser-thc** [comment]
post the command line you used

**Comment by ramines** [comment]
hydra -l 'nesene' -P passwords.txt -v -V heyatim.az http-post-form "/chat/index.php:us=^USER^npass=^PASS^&submits=Daxil+Ol:Şifre düz deyil!"
POSTDATA=us=nesene&npass=&submits=Daxil+Ol::H=Cookie: security=low;PHPSESSID=3a051702d1c4fab31dadb99604948bea" .........if you answered it means Hydra still works... please help can you test it with this login... with your command lines... thanks for your answer

**Comment by ramines** [comment]
hydra -l 'nesene' -P passwords.txt -v -V heyatim.az http-post-form "/chat/index.php:us=^USER^&npass=^PASS^&submits=Daxil+Ol:Şifre düz deyil!:H=Cookie: security=low;PHPSESSID=3a051702d1c4fab31dadb99604948bea" thanks for your answer. this is my last command line... please if you have time try it with your own command lines... if you answered it means Hydra still works...  i also tried gui HYDRA but no use... on windows with commandlines and GUI... and on the kali with sparta and Command lines always the same 16 valid passwords... and this site has not been limited with any password tryings... thanks

**Comment by vanhauser-thc** [comment]
you did not supply a success or failure string which helps hydra detect if the password worked or not.

see: hydra -U http-post-form

**Comment by ramines** [comment]
please.... i will never disturb you again, just show me a live example with your own commands by using these.....

**Comment by ramines** [comment]
ok thanks you,  I understand
