### ISSUE TITLE
Can't install GTK

### ISSUE THREAD

**Issue by Synthyy** [vanhauser-thc/thc-hydra#178]
Hello there! I can't somehow install gtk version of hydra.I installed the 8v3 terminal version withouth problems with ./configure but when I do that command in the directory of gtk hydra it says I need to specify some path for some other file I can't remember the name.Also when using hydra for the email smtp an error occurs something like it goes to bruteforce but it says something in a way "ATTEMPT CAN NOT CONNECT" Some help would really be appreciated,thanks in advance!

**Comment by vanhauser-thc** [comment]
so - with that bug report ... I no nothing what your problem is.
copy-paste all necessary output, including your command line

**Comment by Synthyy** [comment]
Okay this,is for the GTK folder I can't install it.
![this](https://cloud.githubusercontent.com/assets/25090942/21929403/3cd21816-d988-11e6-8613-0d12928b31cf.png)

**Comment by vanhauser-thc** [comment]
@Synthyy this means you do not have installed the necessary gtk development libraries.
I do not know which one you would need and it it beyond me to tell this to everyone with every different Linux OS.
try installing everything gtk*dev package

**Comment by Synthyy** [comment]
Where can I install that or download the necessary things for it?

**Comment by vanhauser-thc** [comment]
from your operating system software install tool. it's called "apt"
