### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by kishankishh** [vanhauser-thc/thc-hydra#180]
please help me to solve this error

Hydra v7.6 (c)2013 by van Hauser/THC & David Maciejak - for legal purposes only

Hydra (http://www.thc.org/thc-hydra) starting at 2017-01-15 12:01:49
[INFO] several providers have implemented cracking protection, check with a small wordlist first - and stay legal!
[DATA] 16 tasks, 1 server, 2000001 login tries (l:1/p:2000001), ~125000 tries per task
[DATA] attacking service smtp on port 465
[VERBOSE] Resolving addresses ... done
[ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "myemail@gmail.com" - 1 of 2000001 [child 0]
[ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "" - 2 of 2000001 [child 1]
[ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "8997394" - 3 of 2000001 [child 2]
[ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "amazing_me_2010" - 4 of 2000001 [child 3]
[ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "pwalkershit" - 5 of 2000001 [child 4]
[ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "emjhayarca" - 6 of 2000001 [child 5]
[ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "fackz95" - 7 of 2000001 [child 6]
[ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "greatness_personified" - 8 of 2000001 [child 7]
[ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "kaamasmukka" - 9 of 2000001 [child 8]
[ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "doveystar" - 10 of 2000001 [child 9]
[ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "b4rn0n3" - 11 of 2000001 [child 10]
[ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "blondetweetysweety" - 12 of 2000001 [child 11]
[ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "8a76e1" - 13 of 2000001 [child 12]
[ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "challex828" - 14 of 2000001 [child 13]
[ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "chandramouli 3 0" - 15 of 2000001 [child 14]
[ATTEMPT] target smtp.gmail.com - login "kishankishhh333@gmail.com" - pass "amos_rosenthal" - 16 of 2000001 [child 15]
[VERBOSE] Retrying connection for child 0
[VERBOSE] Retrying connection for child 1
[RE-ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "myemail@gmail.com" - 16 of 2000001 [child 0]
[RE-ATTEMPT] target smtp.gmail.com - login "myemail@gmail.com" - pass "" - 16 of 2000001 [child 1]
[VERBOSE] Disabled child 4 because of too many errors
[VERBOSE] Disabled child 3 because of too many errors
[VERBOSE] Disabled child 10 because of too many errors
[VERBOSE] Disabled child 8 because of too many errors
[VERBOSE] Disabled child 9 because of too many errors
[VERBOSE] Disabled child 11 because of too many errors
[VERBOSE] Disabled child 2 because of too many errors
[VERBOSE] Disabled child 5 because of too many errors
[VERBOSE] Disabled child 6 because of too many errors
[VERBOSE] Disabled child 13 because of too many errors
[VERBOSE] Disabled child 7 because of too many errors
[VERBOSE] Disabled child 12 because of too many errors
[VERBOSE] Disabled child 14 because of too many errors
[VERBOSE] Disabled child 15 because of too many errors
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4062 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4063 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4066 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4072 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4065 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4073 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4070 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4071 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4064 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4068 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4067 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4075 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4074 terminating, can not connect
[ERROR] Child with pid 4069 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4077 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4076 terminating, can not connect
[VERBOSE] Disabled child 1 because of too many errors
0 of 1 target completed, 0 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2017-01-15 12:01:50
<finished>

[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[VERBOSE] Could not create an SSL session: error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol
[ERROR] Child with pid 4080 terminating, can not connect
[ERROR] Child with pid 4078 terminating, can not connect
[ERROR] Too many connect errors to target, disabling smtp://smtp.gmail.com:465
[ERROR] 1 target did not resolve or could not be connected

**Comment by vanhauser-thc** [comment]
super old version.
checkout the github state and compile it

**Comment by kishankishh** [comment]
I don't get you will you please help me how to correct the error or give me
subs link

**Comment by vanhauser-thc** [comment]
sorry, this is not a help desk.
it is for reporting bugs in the problem.
there are many blog posts and examples in the web on how to use it correctly. you just have to invest your time yourself to look at them

**Comment by kishankishh** [comment]
Give me some clarity. I mean Iam not asking you to help me to crack the
password but Iam asking which part I did wrong  I mean what the issue is

**Comment by kishankishh** [comment]
Are you tell me that Iam using a older version of hydra

**Comment by kishankishh** [comment]
Iam I using an older version of hydra

**Comment by kishankishh** [comment]
Please give me some clarity

**Comment by XxSlay3r** [comment]
[ERROR] all children were disabled due too many connection errors

**Comment by craigvargovich** [comment]
why didnt you just answer his question. once in a while just do the kind thing even when it is in conflict with "your" right thing to do then u wont be a toolbox. thanks for all the help tool box
