### ISSUE TITLE
0 passwords found when using known password for rdp service

### ISSUE THREAD

**Issue by scenix007** [vanhauser-thc/thc-hydra#181]
I'm pretty sure my user name and password is correct, because I'm using the RDP service right now.
But hydra can not find a valid password.
So here is my output.(I replaced the IP address of my server with xx.xx :P) 
[output.txt](https://github.com/vanhauser-thc/thc-hydra/files/707636/output.txt)

**Comment by scenix007** [comment]
Well, by the way.
I did get some sort of certificate warning while connect using my remote desktop application, I had to choose ignore to continue.

**Comment by vanhauser-thc** [comment]
I hope you changed the password and login.
scanning a /16 subnet for vnc and trying the login and password in your output is a matter of minutes.

about your problem: which openssl version is installed? 1.1 or =< 1.0.x?

**Comment by scenix007** [comment]
I will change the password and login later, thanks.
```
brew info openssl                                                                                                                                                                                        17-01-16 17:17
openssl: stable 1.0.2j (bottled) [keg-only]
SSL/TLS cryptography library
https://openssl.org/
/usr/local/Cellar/openssl/1.0.2h_1 (1,691 files, 12M)
  Poured from bottle on 2016-06-22 at 15:16:11
/usr/local/Cellar/openssl/1.0.2j (1,695 files, 12M)
  Poured from bottle on 2016-12-26 at 14:20:45
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl.rb
==> Dependencies
Build: makedepend ✘
==> Options
--universal
	Build a universal binary
--without-test
	Skip build-time tests (not recommended)
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
    PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig
```

**Comment by vanhauser-thc** [comment]
hmm my guess is that the RDP module doe not work with newer RDP servers.

I did not write the RDP module so it will some time for me to debug and fix the issue.

thanks for reporting!

**Comment by miked531** [comment]
I have the same problem. The server I am testing against is Win2k16 and it appears to not support RDP v4. The rdesktop code  (currently 1.8.3) has been updated with a -5 flag. Running rdesktop with -4 fails. I'll attempt to see if I can port the changes to THC, but don't hold your breath

**Comment by vanhauser-thc** [comment]
@miked531 well if you can that would be awesome!

**Comment by hl0rey** [comment]
Is this problem solved now?

**Comment by vanhauser-thc** [comment]
no, still needs someone who wants to update the rdp module

**Comment by JohnZombie** [comment]
My issue is when I test it against a rdp domain it will run but does not lockout the target account. Is this still occurring?
