### ISSUE TITLE
Proposal: be able to change -t number of threads when doing a -R restore

### ISSUE THREAD

**Issue by tdewolff** [vanhauser-thc/thc-hydra#184]
It would be helpful to me if it were possible to change the number of threads after pausing/canceling a previous run. This is at the moment not possible, but doesn't seem to be inherently mutually exclusive. I haven't looked into the code yet, but I guess I could make a PR if you like.

**Comment by vanhauser-thc** [comment]
this would be a larger code change I guess.
I have to look into it.
however why do you think this is needed? hydra notices if connections fail and reduces the number automatically.

**Comment by vanhauser-thc** [comment]
just changed -R so that any opton after -R is honored.
