### ISSUE TITLE
Could not connect to SSH

### ISSUE THREAD

**Issue by borekon** [vanhauser-thc/thc-hydra#189]
When i try ssh i receive this error:

> [ERROR] could not connect to ssh://x.x.x.x:x - kex error : no match for method mac algo client->server: server [hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160], client [hmac-sha1]

But when i do _ssh user@x.x.x.x_ i can connect with no problems.
I wonder how to change the algorithms supported when compiling.

**Comment by vanhauser-thc** [comment]
http://api.libssh.org/master/ shows libssh supports these:

MAC hashes: hmac-sha1, none

so as long as the library has not support for other algos you either have to write your own or use a tool that uses libssh2 (that one supports some of the algorithms of your target)

**Comment by vanhauser-thc** [comment]
uh actually there is more:

https://www.libssh.org/features/

MAC hashes: hmac-sha2-512, hmac-sha2-256, hmac-sha1, none

looks like the previous page I quoted is outdated.
However you need libssh v0.7.0 or newer (0.7.3 at least recommended)

Kali Linux has 0.7.3-2

**Comment by vanhauser-thc** [comment]
can you confirm that libssh 0.7+ works for you?

**Comment by borekon** [comment]
Not tried yet

**Comment by vanhauser-thc** [comment]
please try with the new library version within a week or I will close the issue
