### ISSUE TITLE
Ignore Invaild Format

### ISSUE THREAD

**Issue by DarrenRainey** [vanhauser-thc/thc-hydra#190]
Is there a way for hydra to ignore lines that aren't in the correct format for example if my user:pass file is like this:

root:toor
root-toor

it would ignore root-toor because it doesn't have the correct format and just try the user:pass's that are the correct format of root:toor

**Comment by vanhauser-thc** [comment]
without looking at the code I would suspect hydra using root-toor as login and empty password.

it is your job to supply a good valid file. you can simply do "grep : file > file.new" to ensure lines have a colon
