### ISSUE TITLE
SVN Compile Error

### ISSUE THREAD

**Issue by FireFart** [vanhauser-thc/thc-hydra#200]
Compile Error on Redhat Linux 6:
```
hydra-svn.c: In function ‘start_svn’:
hydra-svn.c:86: warning: assignment makes pointer from integer without a cast
hydra-svn.c:111: warning: assignment makes pointer from integer without a cast
hydra-svn.c:113: error: ‘svn_client_list_func2_t’ undeclared (first use in this function)
hydra-svn.c:113: error: (Each undeclared identifier is reported only once
hydra-svn.c:113: error: for each function it appears in.)
hydra-svn.c:113: error: expected ‘)’ before ‘print_dirdummy’
make: *** [hydra-svn.o] Error 1
```
Subversion installed:
subversion-devel-1.6.11-15.el6_7.x86_64

**Comment by klensy** [comment]
Quite old svn version.

There commented out code without this cast, maybe it will work for you (cant check with your env)?

**Comment by FireFart** [comment]
@klensy yeah it's an old svn version but the latest supported by redhat 6 :/

**Comment by FireFart** [comment]
@klensy compiling worked after i used the commented out lines in
https://github.com/vanhauser-thc/thc-hydra/blob/2e1b0c2487bc70b5b5b04ab551ea8c30f7bcda48/hydra-svn.c#L112
and
https://github.com/vanhauser-thc/thc-hydra/blob/2e1b0c2487bc70b5b5b04ab551ea8c30f7bcda48/hydra-svn.c#L85

Do you think it's possible to switch back to the old API? The old functions currently commented out are still present for backward compatibility:
http://svn.apache.org/repos/asf/subversion/trunk/subversion/include/svn_client.h

PS: In the latest trunk version of subversion the methods called from hydra are also marked as deprecated

**Comment by vanhauser-thc** [comment]
@klensy I won't support old versions.

why? you can simply download the current library version, compile and install it, e.g. to /usr/local/ and modify the hydra Makefile after ./configure to point there

**Comment by anoircp** [comment]
on another vesion maybe i have in comment line 85 and comment line 86 and such for 109 & 110 and
work as it below :
 
`  if ((err = svn_client_create_context(&ctx, pool))) {
  //if ((err = svn_client_create_context2(&ctx, NULL, pool))) {
    svn_handle_error2(err, stderr, FALSE, "hydra: ");
    return 4;
  }`

`  err = svn_client_list2(canonical, &revision, &revision, svn_depth_unknown, dirents, FALSE, print_dirdummy, NULL, ctx, pool);
  //err = svn_client_list3(canonical, &revision, &revision, svn_depth_unknown, dirents, FALSE, FALSE, (svn_client_list_func2_t) print_dirdummy, NULL, ctx, pool);`
