### ISSUE TITLE
[ERROR] Weird bug detected where more tests were performed than possible.

### ISSUE THREAD

**Issue by Thomas66526** [vanhauser-thc/thc-hydra#201]
hydra -s 3389 -t 64 -f -v -V -L /root/admin.txt -P /root/12345.txt -o /root/good.txt -M /root/IPs.txt rdp

[ERROR] Weird bug detected where more tests were performed than possible. Please post your command line here: https://github.com/vanhauser-thc/thc-hydra/issues/113 or send it in an email to vh@thc.org

**Comment by vanhauser-thc** [comment]
fixed. long ago. update to a newer version.
