### ISSUE TITLE
bypass google blocking attempts

### ISSUE THREAD

**Issue by jeanmartin77** [vanhauser-thc/thc-hydra#202]
Hello,
I love hydra but I cannot use it as I am always blocked after a limited numbers of login attempts, by google and almost all of the others mail providers. How can we pass through this?

**Comment by thecarterb** [comment]
Google rate limits all requests, even API requests. It is not likely _anybody_ is going to get past their rate limit easily.

**Comment by tjgerot** [comment]
@jeanmartin77 Unless you have a bypass method to suggest, you should close this issue,
