### ISSUE TITLE
RSTP not recognised

### ISSUE THREAD

**Issue by b0bcarlson** [vanhauser-thc/thc-hydra#203]
`hydra -l admin -p ~/wordlist.txt -u -vV -e snr -s 554  172.16.12.151 rtsp`
Gives output
```
Hydra v7.5 (c)2013 by van Hauser/THC & David Maciejak - for legal purposes only

Hydra (http://www.thc.org/thc-hydra) starting at 2017-03-25 17:22:35
[ERROR] Unknown service: rtsp
```

Installed from source 03/25/2017
Linux Mint 18 (Ubuntu based) 64 bit
apt-get upgraded first, everything is up to date

**Comment by vanhauser-thc** [comment]
why dont you check the latest available version? current is 8.4 your distro ist just outdated. and likely openssl-dev is not installed either.
clone this repository, install the required libraries, compile.
