### ISSUE TITLE
got a little problem here

### ISSUE THREAD

**Issue by EdwardAutumn** [vanhauser-thc/thc-hydra#204]
@vanhauser-thc hc 
sorry about my English.This is the site i'm trying to brute force
http://pentesteracademylab.appspot.com/lab/webapp/1
username:admin@pentesteracademy.com
password:zzzxy

but this is what i got...any ideas?
![screenshot from 2017-03-30 22-17-42](https://cloud.githubusercontent.com/assets/19833520/24508876/5bcf8f52-1554-11e7-80b1-3aff696a977a.png)

**Comment by vanhauser-thc** [comment]
you can use the -d switch to see debug output.

I'd guess your linux  can not connect to the server

**Comment by EdwardAutumn** [comment]
@vanhauser-thc 
Thanks for reminding.i'm in China,this site has been attacked by DNS cache poisoning,i can access this site with my vpn through firefox,but it seems the hydra doesn't support the proxychains.i'm really exhausted :( but thanks anyway.
