### ISSUE TITLE
Could not create an SSL session: unable to get local issuer certificate

### ISSUE THREAD

**Issue by gaia** [vanhauser-thc/thc-hydra#205]
current version was compiled on Windows Linux Subsystem today. it works fine btw (only needed to install libssl-dev).

`hydra -l "user" -p "pword" -f server.com -t 1  -vV  https-post-form "/:user=^USER^&password=^PASS^submit=true:no access"`

yields

`[VERBOSE] Could not create an SSL session: error:00000000:lib(0):func(0):reason(0)`

and

`openssl s_client -connect server.com:443`

returns

`Verify return code: 20 (unable to get local issuer certificate)`

but 

`openssl s_client -CApath /etc/ssl/certs/ -connect server.com:443`

returns no errors.

server.com gets an A on SSLlabs test: 3 cert chain (2 sent by server + root CA).

Any advice?

**Comment by vanhauser-thc** [comment]
this is weird. hydra does not check the certificate so having CA certs or not does not make a difference.

I can see on stackoverflow etc. that others have the same issue with openssl on some sites. 

I don't know the best way to solve this.
hard code CA certs? that means that you might not have the necessary ones and if they are outdated at some point you have the same problem.
Make the user supply one? too much hassle on the user, and many users have no clue what file is actually neede.
Try some magic and find the CA file on the file system itself - again too many user issues as a user experiences hydra working find on one system but not on the other.

ideas?

**Comment by gaia** [comment]
As you probably know, openssl trusts nothing by default. "unable to get local issuer certificate" is the default error if you don't supply a cert or a path for certs, You can try it on any site.

I wanted to illustrate how openssl is not behaving as expected. Hopefully we can get to the bottom of why hydra can't create an SSL session.

Anything else I should look into?

**Comment by vanhauser-thc** [comment]
I never had this message on any pentest. it is not a standard thing but a special occasion ...

**Comment by gaia** [comment]
Not sure which one of the messages you are referring to. As far as openssl's "20 (unable to get local issuer certificate)", see http://serverfault.com/a/671631/34560.

Would it be wise to allow passing `-CApath` to hydra, so it can use it for openssl?

**Comment by vanhauser-thc** [comment]
can you please provide an an URL where this is happening?
I have not found a single one which makes it unable to debug for me otherwise.

**Comment by gaia** [comment]
emailed.

**Comment by vanhauser-thc** [comment]
Finally had time for this and fixed it.
Was a oneliner that does not require any CAcert stuff.

Using the -O option woud have been a workaround.
