### ISSUE TITLE
Error in hydra free double or corruption

### ISSUE THREAD

**Issue by hyh19962008** [vanhauser-thc/thc-hydra#207]
First time run is all good,but when resume a project using hydra -R it constantly prompt that information.
Test environment is Ubuntu 16.10 and problem inccur in ssh mode.

**Comment by xlc** [comment]
This happens to me to. Any suggestions?

**Comment by vanhauser-thc** [comment]
@xlc have you tried the current repository state?

**Comment by xlc** [comment]
No. I will build from master later and try again.
