### ISSUE TITLE
Passwords found but incorrect

### ISSUE THREAD

**Issue by thefreelancerZA** [vanhauser-thc/thc-hydra#210]
Hi guys,

I have tried hydra with several gmail accounts and used darc0de and another big pasword lists. However after a couple of minutes hydra said it found 1 valid password. Knowing my own passwords I know they were wrong.

Can you please assist?

**Comment by vanhauser-thc** [comment]
read the hydra messages.

fprintf(stderr, "[WARNING] Google Mail has bruteforce detection and sends false positives. You are not doing anything illegal right?!\n");

**Comment by thefreelancerZA** [comment]
Hi,

thanks for the info. No I was testing it on my own gmail accounts.
Thanks for the info.
