### ISSUE TITLE
xHydra giving me error about USER and PASS strings.

### ISSUE THREAD

**Issue by projectFRiNK** [vanhauser-thc/thc-hydra#211]
I am new to xHydra and THC-Hydra in general, and I am trying to brute-force my router and I am constantly getting this error: 
`[ERROR] the variables argument needs at least the strings ^USER^ or ^PASS^: (null)`
I am brute-forcing with http-post-form as my protocol.
I don't know if this is a bug or an issue on my part.

**Comment by vanhauser-thc** [comment]
this is solely for reporting bugs, not user help.
read the README or search the internet.
