### ISSUE TITLE
[ERROR] Weird bug detected where more tests were performed than possible.

### ISSUE THREAD

**Issue by global4g** [vanhauser-thc/thc-hydra#212]
I got this error when performing a brute force attack on ssh with 500 passwords and one user.

Command line 

`hydra -l  bob  -V -P 500-worst-passwords.txt  10.x.y.z  ssh`

Also, not sure why the logs indicated 629 when expected # was 500

[ATTEMPT] target 10.x.y.z - login "bob" - pass "mistress" - 496 of 629 [child 11]
[ATTEMPT] target 10.x.y.z - login "bob" - pass "phantom" - 497 of 629 [child 12]
[ATTEMPT] target 10.x.y.z - login "bob" - pass "billy" - 498 of 629 [child 2]
[ATTEMPT] target 10.x.y.z - login "bob" - pass "6666" - 499 of 629 [child 0]
[ATTEMPT] target 10.x.y.z - login "bob" - pass "albert" - 500 of 629 [child 1]
[REDO-ATTEMPT] target 10.x.y.z - login "bob" - pass "baseball" - 501 of 629 [child 3]
[REDO-ATTEMPT] target 10.x.y.z - login "bob" - pass "master" - 502 of 629 [child 4]
[REDO-ATTEMPT] target 10.x.y.z - login "bob" - pass "michael" - 503 of 629 [child 5]
[REDO-ATTEMPT] target 10.x.y.z - login "bob" - pass "football" - 504 of 629 [child 6
.
.
.
[REDO-ATTEMPT] target 10.x.y.z - login "bob" - pass "edward" - 623 of 629 [child 13]
[REDO-ATTEMPT] target 10.x.y.z - login "bob" - pass "charles" - 624 of 629 [child 14]
[REDO-ATTEMPT] target 10.x.y.z - login "bob" - pass "girls" - 625 of 629 [child 15]
[REDO-ATTEMPT] target 10.x.y.z - login "bob" - pass "bulldog" - 626 of 629 [child 0]
[REDO-ATTEMPT] target 10.x.y.z - login "bob" - pass "booboo" - 627 of 629 [child 1]
[REDO-ATTEMPT] target 10.11.1.35 - login "bob" - pass "coffee" - 628 of 629 [child 2]

[ERROR] Weird bug detected where more tests were performed than possible. Please post your command line here: https://github.com/vanhauser-thc/thc-hydra/issues/113 or send it in an email to vh@thc.org

**Comment by vanhauser-thc** [comment]
just update
