### ISSUE TITLE
Hydra issue: Could not create an ssl session

### ISSUE THREAD

**Issue by thestt** [vanhauser-thc/thc-hydra#236]
i use the command 
hydra -S -l mym@m.com -P /root/desktop/pwd.txt -v -V -e ns -s 465 etc..
but i get the issue Could not create an SSL session: error: 00000000 lib(0): func (0) reason (0)
I really dont know why dont work now. 5 days ago hydra work.
any help please?

**Comment by vanhauser-thc** [comment]
try adding the -O option.

Also, update to the current repository state here.

**Comment by thestt** [comment]
i try, i have update the repository and use -O but dont works

**Comment by vanhauser-thc** [comment]
can you please send the full output of:

hydra -d -l test -p test -t 1 -s 465 smtps://YOUR-TARGET

**Comment by thestt** [comment]
[DEBUG] Code: attack   Time: 1498759163
[DEBUG] Options: mode 0  ssl 1  restore 0  showAttempt 0  tasks 1  max_use 64 tnp 0  tpsal 0  tprl 0  exit_found 0  miscptr (null)  service smtp
[DEBUG] Brains: active 0  targets 1  finished 0  todo_all 1  todo 1  sent 0  found 0  countlogin 1  sizelogin 5  countpass 1  sizepass 5
[DEBUG] Target 0 - target smtp.mail.com  ip 74.208.5.15  login_no 0  pass_no 0  sent 0  pass_state 0  redo_state 0 (0 redos)  use_count 0  failed 0  done 0  fail_count 0  login_ptr test  pass_ptr test
[DEBUG] Task 0 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 1 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 2 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 3 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 4 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 5 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 6 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 7 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 8 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 9 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 10 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 11 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 12 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 13 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 14 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 15 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 16 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 17 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 18 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 19 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 20 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 21 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 22 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 23 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 24 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 25 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 26 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 27 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 28 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 29 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 30 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 31 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 32 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 33 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 34 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 35 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 36 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 37 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 38 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 39 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 40 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 41 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 42 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 43 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 44 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 45 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 46 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 47 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 48 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 49 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 50 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 51 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 52 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 53 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 54 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 55 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 56 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 57 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 58 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 59 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 60 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 61 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 62 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Task 63 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Tasks 64 inactive  0 active
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 1453
[DEBUG] child 1 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 1, kill 0, fail 3
[DEBUG] child 2 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 2, kill 0, fail 3
[DEBUG] child 3 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 3, kill 0, fail 3
[DEBUG] child 4 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 4, kill 0, fail 3
[DEBUG] child 5 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 5, kill 0, fail 3
[DEBUG] child 6 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 6, kill 0, fail 3
[DEBUG] child 7 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 7, kill 0, fail 3
[DEBUG] child 8 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 8, kill 0, fail 3
[DEBUG] child 9 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 9, kill 0, fail 3
[DEBUG] child 10 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 10, kill 0, fail 3
[DEBUG] child 11 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 11, kill 0, fail 3
[DEBUG] child 12 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 12, kill 0, fail 3
[DEBUG] child 13 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 13, kill 0, fail 3
[DEBUG] child 14 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 14, kill 0, fail 3
[DEBUG] child 15 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 15, kill 0, fail 3
[DEBUG] child 16 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 16, kill 0, fail 3
[DEBUG] child 17 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 17, kill 0, fail 3
[DEBUG] child 18 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 18, kill 0, fail 3
[DEBUG] child 19 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 19, kill 0, fail 3
[DEBUG] child 20 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 20, kill 0, fail 3
[DEBUG] child 21 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 21, kill 0, fail 3
[DEBUG] child 22 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 22, kill 0, fail 3
[DEBUG] child 23 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 23, kill 0, fail 3
[DEBUG] child 24 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 24, kill 0, fail 3
[DEBUG] child 25 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 25, kill 0, fail 3
[DEBUG] child 26 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 26, kill 0, fail 3
[DEBUG] child 27 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 27, kill 0, fail 3
[DEBUG] child 28 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 28, kill 0, fail 3
[DEBUG] child 29 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 29, kill 0, fail 3
[DEBUG] child 30 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 30, kill 0, fail 3
[DEBUG] child 31 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 31, kill 0, fail 3
[DEBUG] child 32 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 32, kill 0, fail 3
[DEBUG] child 33 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 33, kill 0, fail 3
[DEBUG] child 34 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 34, kill 0, fail 3
[DEBUG] child 35 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 35, kill 0, fail 3
[DEBUG] child 36 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 36, kill 0, fail 3
[DEBUG] child 37 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 37, kill 0, fail 3
[DEBUG] child 38 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 38, kill 0, fail 3
[DEBUG] child 39 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 39, kill 0, fail 3
[DEBUG] child 40 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 40, kill 0, fail 3
[DEBUG] child 41 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 41, kill 0, fail 3
[DEBUG] child 42 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 42, kill 0, fail 3
[DEBUG] child 43 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 43, kill 0, fail 3
[DEBUG] child 44 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 44, kill 0, fail 3
[DEBUG] child 45 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 45, kill 0, fail 3
[DEBUG] child 46 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 46, kill 0, fail 3
[DEBUG] child 47 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 47, kill 0, fail 3
[DEBUG] child 48 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 48, kill 0, fail 3
[DEBUG] child 49 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 49, kill 0, fail 3
[DEBUG] child 50 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 50, kill 0, fail 3
[DEBUG] child 51 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 51, kill 0, fail 3
[DEBUG] child 52 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 52, kill 0, fail 3
[DEBUG] child 53 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 53, kill 0, fail 3
[DEBUG] child 54 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 54, kill 0, fail 3
[DEBUG] child 55 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 55, kill 0, fail 3
[DEBUG] child 56 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 56, kill 0, fail 3
[DEBUG] child 57 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 57, kill 0, fail 3
[DEBUG] child 58 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 58, kill 0, fail 3
[DEBUG] child 59 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 59, kill 0, fail 3
[DEBUG] child 60 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 60, kill 0, fail 3
[DEBUG] child 61 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 61, kill 0, fail 3
[DEBUG] child 62 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 62, kill 0, fail 3
[DEBUG] child 63 got target -1 selected
[DEBUG] hydra_select_target() reports no more targets left
[DEBUG] head_no 63, kill 0, fail 3
[DEBUG] head_no 0 has pid 1453
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 0, redo_state 0, pass_state 0. loop_mode 0, curlogin (null), curpass (null), tlogin test, tpass test, logincnt 0/1, passcnt 0/1, loop_cnt 1
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin test, cpass test, tlogin -p, tpass test, redo 0
[ATTEMPT] target smtp.mail.com - login "test" - pass "test" - 1 of 1 [child 0] (0/0)
DEBUG_CONNECT_OK
[VERBOSE] Could not create an SSL session: error:00000000:lib(0):func(0):reason(0)
[ERROR] Child with pid 1453 terminating, can not connect
[DEBUG] pid 1453 called child_exit with code 1
[DEBUG] head_no[0] read C
[ATTEMPT-ERROR] target smtp.mail.com - login "test" - pass "test" - child 0 - 1 of 1
[DEBUG] hydra_increase_fail_count: 1 >= 3 => disable
[DEBUG] head_no 0, kill 1, fail 1
[VERBOSE] Retrying connection for child 0
[DEBUG] child 0 spawned for target 0 with pid 1454
[DEBUG] head_no 0 has pid 1454
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 0, redo_state 0, pass_state 0. loop_mode 0, curlogin test, curpass test, tlogin -p, tpass test, logincnt 1/1, passcnt 0/1, loop_cnt 1
[COMPLETED] target smtp.mail.com - login "test" - pass "test" - child 0 - 1 of 1
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin test, cpass test, tlogin -p, tpass test, redo 0
[DEBUG] send_next_pair_redo done 1, pass_state 0, clogin test, cpass test, tlogin -p, tpass test, is_redo 1
[RE-ATTEMPT] target smtp.mail.com - login "test" - pass "test" - 1 of 1 [child 0] (0/0)
DEBUG_CONNECT_OK

**Comment by vanhauser-thc** [comment]
hmm from your output everything seems ok.

but for me (you left the target IP in the output) it works fine:

$ hydra -l test -p test -vV smtps://74.208.5.15
**Hydra v8.6-dev** (c) 2017 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2017-06-30 09:00:15
[INFO] several providers have implemented cracking protection, check with a small wordlist first - and stay legal!
[DATA] max 1 task per 1 server, overall 1 tasks, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking service smtp on port 465 with SSL
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[ATTEMPT] target 74.208.5.15 - login "test" - pass "test" - 1 of 1 [child 0] (0/0)
[VERBOSE] using SMTP LOGIN AUTH mechanism
[STATUS] attack finished for 74.208.5.15 (waiting for children to complete tests)
1 of 1 target completed, 0 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2017-06-30 09:00:17


so my guess is that either you are not using 8.6-dev but an older version that is still installed in parallel, or your openssl installation is old.

**Comment by thestt** [comment]
thanks for reply.
But, if i not using 8.6 but older version or too my openssl its old, how i can fix?
just do inside hydra apt-get update apt-get upgrade?
or I can do something else?
Because i remember 1 week ago hydra works fine...

**Comment by vanhauser-thc** [comment]
type "hydra" and look at the version. you should see 8.6-dev

when I wrote "update the repository" I did not mean kali but this github source code repository:

sudo apt-get install libssl-dev libssh-dev
git clone https://github.com/vanhauser-thc/thc-hydra
cd thc-hydra
./configure
make
sudo make install

**Comment by thestt** [comment]
Yes, my hydra was 8.3 now its 8.6. Thanks.
But now i have write your command sudo apt-get install libssl-dev libssh-dev, and i see this error:

" Some packages can not be installed. 
This may mean
That an impossible situation was required or, If you are
Using a deployed development, That some packages are required
Have not yet been created Or have been removed from Incoming. 
The following information can help you resolve the situation: 
The following packages have unsatisfactory dependencies:
libssh-dev : Depends: libssl1.0-dev But it is not going to be installed
E: Unable to fix problems, there are blocked damaged packages. "
So, after this issue, i try to use hydra, i dont have see the last error.
But when hydra "work" for find my password i see this:
[WARNING] hydra was compiled without SSL support. Install openssl and recompile! Option ignored...
Why?

**Comment by vanhauser-thc** [comment]
something is fucked up with your package installation that is why the ssl packages could not be installed (the apt-get install error you got)

that is something you have to fix on your own

**Comment by thestt** [comment]
thanks for help anyway.
I think i reinstall kali linux, i dont have problems to do that.

**Comment by SamuelDiCenta** [comment]
Vanhauser could help me I can't get positive results, and I've already tried to find my error, the email I want to have access to is from hotmail.  The Rockyou wordlist I already downloaded and unzipped in Cygwin's tmp folder.  can you help me please?!

![20220408_224401](https://user-images.githubusercontent.com/102611303/162527843-b586221a-22b2-4efd-82f2-71b677fb6bf8.jpg)
