### ISSUE TITLE
Unable to use Hydra with ipv6

### ISSUE THREAD

**Issue by HuskerC** [vanhauser-thc/thc-hydra#237]
I'm trying to do the following call

hydra -l user -P /usr/share/wordlists/metasploit/password.lst -6 ssh://[fe80::a00:27ff:febe:21fc]

I still keep getting this
[ERROR] could not connect to ssh://fe80::a00:27ff:febe:21fc:22 - Failed to connect: Invalid argument

I'm using kali linux with version 8.3 of hydra. Would be great if someone could help. 
I can ping the host via v6, i can also ssh directly to it, but I cannot get hydra to bruteforce it.

Is there problem or am I doing something wrong. 

Best regards

**Comment by vanhauser-thc** [comment]
you are doing it wrong.

its a link local address which is on every interface. you must specify the outgoing adapter, like on ping6.

try:

hydra -l user -P /usr/share/wordlists/metasploit/password.lst -6 fe80::a00:27ff:febe:21fc%eth0 ssh

(if eth0 is the adapter)

**Comment by vanhauser-thc** [comment]
can you please report if this fixes your issue and if yes close it?

**Comment by HuskerC** [comment]
Hi, I'll test it this evening (GMT+1) an will then close it.

**Comment by HuskerC** [comment]
Hi, unfortunatelly this does not solve the problem.
My call is
hydra -l user -P /usr/share/wordlists/metasploit/password.lst -6 fe80::a00:27ff:febe:21fc%eth1 ssh

I keep getting 
[DATA] attacking service ssh on port 22
[ERROR] could not connect to ssh://fe80::a00:27ff:febe:21fc:22 - Failed to connect: Invalid argument

The interface identifier seems to vanish.

**Comment by vanhauser-thc** [comment]
oh man, this took me much too much time to figure this out because I was busy tweaking output to be more helpful etc.

reason is simple: the ssh module uses the libssh library. and this library does not support link local addresses.

so nothing I can do, sorry.

**Comment by HuskerC** [comment]
Oh, ok. 
So IPv6 is still on the move ;).
Thank you for your support.
