### ISSUE TITLE
Proxychains & segmentationfault

### ISSUE THREAD

**Issue by BigJ80** [vanhauser-thc/thc-hydra#238]
Hi there,

I'm not able to use Hydra with Proxychains at all.
I always get a segmentation fault error, no matter if I'm testing against Http, ftp or smtp.
Tried many parameters combinations, no success.
OS: Kali 2017
Hydra v 3.6 development (current)

Thank you very much for your support.

Here is a sample output against my hotmail account:

ProxyChains-3.1 (http://proxychains.sf.net)
Hydra v8.6-dev (c) 2017 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.
[DEBUG] Ouput color flag is 0
Hydra (http://www.thc.org/thc-hydra) starting at 2017-07-06 09:39:40
[DEBUG] cmdline: ./hydra -m TLS -l xxx@hotmail.com -P wordlist.txt -V -e ns -s 587 -t 1 -c 45 -f -d smtp.live.com smtp
[INFO] several providers have implemented cracking protection, check with a small wordlist first - and stay legal!
[DATA] max 1 task per 1 server, overall 1 tasks, 54 login tries (l:1/p:54), ~54 tries per task
[DATA] attacking service smtp on port 587
[DATA] with additional data TLS
[VERBOSE] Resolving addresses ...
[DEBUG] resolving smtp.live.com
|DNS-request| smtp.live.com
|D-chain|-<>-127.0.0.1:9050-<><>-4.2.2.2:53-<><>-OK
Segmentation fault

**Comment by BigJ80** [comment]
Sorry, false issue.

Works with latest Proxychains v 4
Unfortunately Proxychains in kali repository is very outdated (v 3.1)

Consider my report only if interested in fixing Hydra for older Proxychains versions.

BR

**Comment by vanhauser-thc** [comment]
well the question is if proxychains was segfaulting or hydra. if it was hydra can you please do:

make clean
./configure
vi Makefile
# change OPTS line to OPTS=-g 
make

and then run
ulimit -c unlimited
./hydra -d -l test -p test smtps://smtp.live.com/TLS
with out proxychaings and paste all output here?
then also paste the output of

gdb ./hydra core
=> at the prompt enter "bt" 
and also here post all output generated by gdb

thanks
