### ISSUE TITLE
http-post-form issue

### ISSUE THREAD

**Issue by xzynx** [vanhauser-thc/thc-hydra#240]
Hi, 

I am having a serious problem using the service http-post-form. 
- It register the first password as a match always, no matter what I do. 
- I have tried running it against both ssl and http on different sites of mine. 
- Now I am trying on Wordpress because of so many guides about it, but no difference.
- I am using the built in Hydra with the latest Kali version! 
- Hydra works perfect on ssh, smtp etc.
- I have tried with different login failed messages.
- I did read somewhere I could append "S=Success message" and "F=Failed message" as the last argument. The onlys difference is that "S=" just bypass everything and runs even though I change almost anything in the command, like login reefer. 

My latest wordpress try on port 80:
hydra -l admin -P pass.txt -vV -f mysite.com http-post-form "/wp-login.php:log=^USER^&pwd=^PASS^:login_error"
Hydra v8.3 (c) 2016 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2017-07-15 03:56:30
[DATA] max 16 tasks per 1 server, overall 64 tasks, 4413388 login tries (l:1/p:4413388), ~4309 tries per task
[DATA] attacking service http-post-form on port 80
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[ATTEMPT] target mysite.com - login "admin" - pass "````````" - 1 of 4413388 [child 0] (0/0)
[ATTEMPT] target mysite.com - login "admin" - pass "````````" - 2 of 4413388 [child 1] (0/0)
[ATTEMPT] target mysite.com - login "admin" - pass "``````" - 3 of 4413388 [child 2] (0/0)
[ATTEMPT] target mysite.com - login "admin" - pass "``````" - 4 of 4413388 [child 3] (0/0)
[ATTEMPT] target mysite.com - login "admin" - pass "`````" - 5 of 4413388 [child 4] (0/0)
[ATTEMPT] target mysite.com - login "admin" - pass "````" - 6 of 4413388 [child 5] (0/0)
[ATTEMPT] target mysite.com - login "admin" - pass "````" - 7 of 4413388 [child 6] (0/0)
[ATTEMPT] target mysite.com - login "admin" - pass "^^^^^^" - 8 of 4413388 [child 7] (0/0)
[ATTEMPT] target mysite.com - login "admin" - pass "^^^^" - 9 of 4413388 [child 8] (0/0)
[ATTEMPT] target mysite.com - login "admin" - pass "^^" - 10 of 4413388 [child 9] (0/0)
[ATTEMPT] target mysite.com - login "admin" - pass "^!@^##" - 11 of 4413388 [child 10] (0/0)
[ATTEMPT] target mysite.com - login "admin" - pass "^)" - 12 of 4413388 [child 11] (0/0)
[ATTEMPT] target mysite.com - login "admin" - pass "^****(" - 13 of 4413388 [child 12] (0/0)
[ATTEMPT] target mysite.com - login "admin" - pass "^&*()" - 14 of 4413388 [child 13] (0/0)
[ATTEMPT] target mysite.com - login "admin" - pass "^" - 15 of 4413388 [child 14] (0/0)
[ATTEMPT] target mysite.com - login "admin" - pass "~~~~~~~~~~" - 16 of 4413388 [child 15] (0/0)
[80][http-post-form] host: mysite.com   login: admin   password: ````````
[STATUS] attack finished for mysite.com (valid pair found)
1 of 1 target successfully completed, 1 valid password found

Thanks in advance! //xzynx

**Comment by xzynx** [comment]
Is there anybody who can give me support?

// xzynx

**Comment by vanhauser-thc** [comment]
1. this is for bugs, not for support
2. old version
3. looks like used wrong. read documentation (-U option, blogs, etc.)
