### ISSUE TITLE
 make: *** [hydra] Error 1

### ISSUE THREAD

**Issue by huang5528918** [vanhauser-thc/thc-hydra#241]
hydra.c: In function ‘hydra_restore_write’:
hydra.c:757: warning: ignoring return value of ‘fwrite’, declared with attribute warn_unused_result
hydra-ssh.o: In function `start_ssh':
hydra-ssh.c:(.text+0x44d): undefined reference to `ssh_is_connected'
hydra-svn.o: In function `start_svn':
hydra-svn.c:(.text+0x23d): undefined reference to `svn_client_create_context2'
collect2: ld returned 1 exit status
make: *** [hydra] Error 1

**Comment by vanhauser-thc** [comment]
please do proper bug reporting.
which hydra version? current github checkout?
are the proper libraries installed? (libssh1-dev, etc.) are they in their newest version? which?
etc.
