### ISSUE TITLE
Weird Bug Detected Where More Test Where performed than possible.

### ISSUE THREAD

**Issue by papakri** [vanhauser-thc/thc-hydra#243]
hydra -V -l jackie -P /root/wordlist/ -e ns -t 16 1.1.1.1 ftp

When I enter after "hydra", the port ("-s 8000"), it works fine and finds the password

**Comment by vanhauser-thc** [comment]
are you running the current version?

and is the FTP server running on port 8000?

**Comment by papakri** [comment]
I am running version 8.2 and yes the ftp is on port 8000. 
When I know the port it works fine and it finds the correct password.

**Comment by vanhauser-thc** [comment]
it is your responsibiltiy to specify the correct port, not hydra.
also, your version is very old. update.

**Comment by papakri** [comment]
Thanks a lot for the help!!
