### ISSUE TITLE
MySQL module hangs

### ISSUE THREAD

**Issue by jakehm** [vanhauser-thc/thc-hydra#245]
Using 8.5, not from this repo.  The service I am testing is MySQL.

`[STATUS] 4.00 tries/min, 4 tries in 00:01h, 104 to do in 00:27h, 4 active
`
That status is gradually showing Hydra getting slower and slower.  No user/pass are being checked after the first few. 

Right now the only time out option is -w, which is maximum response time.  The problem arises when the attacker's IP gets blocked by the victim, and hydra keeps trying to connect again and again.  Shouldn't there be some overarching timeout that allows it to fail gracefully in that circumstance?

**Comment by vanhauser-thc** [comment]
Hi,

the connect errors are counted, and reset if a successful connection could be made.
what *should* happen is that hydra tries for several minutes after it has been blocked, and at some time terminate (and leave a restore file).

how long did you wait?

**Comment by jakehm** [comment]
I waited for hours.  This is the cycle it goes through:
```
DEBUG_DISCONNECT                                                          
DEBUG_CONNECT_OK                                                          
[VERBOSE] using default db 'mysql'                                        
DEBUG_RECV_BEGIN||END[0A]                                                 
[DEBUG] SEND [pid:948] (5 bytes):                                         
0000:  0100 0000 01                               [ .....            ]    
DEBUG_DISCONNECT                                                          
DEBUG_CONNECT_OK                                                          
[VERBOSE] using default db 'mysql'                                        
[STATUS] 0.02 tries/min, 1 tries in 00:44h, 107 to do in 78:29h, 1 active 
[DEBUG] Code: STATUS   Time: 1501769826                                   
[DEBUG] Options: mode 51  ssl 0  restore 0  showAttempt 1  tasks 1  max_us
e 1 tnp 1  tpsal 1  tprl 0  exit_found 0  miscptr (null)  service mysql   
[DEBUG] Brains: active 1  targets 1  finished 0  todo_all 108  todo 108  s
ent 1  found 0  countlogin 12  sizelogin 81  countpass 9  sizepass 53     
[DEBUG] Target 0 - target 64.111.175.19  ip 64.111.175.19  login_no 0  pas
s_no 1  sent 1  pass_state 1  redo_state 0 (0 redos)  use_count 1  failed 
0  done 0  fail_count 0  login_ptr root  pass_ptr password                
[DEBUG] Task 0 - pid 948  active 1  redo 0  current_login_ptr root  curren
t_pass_ptr root                                                           
[DEBUG] Tasks 0 inactive  1 active                                        
DEBUG_RECV_BEGIN||END[0A]                                                 
[DEBUG] SEND [pid:948] (5 bytes):                                         
0000:  0100 0000 01                               [ .....            ]    
DEBUG_DISCONNECT                                                          
DEBUG_CONNECT_OK                                                          

```

**Comment by vanhauser-thc** [comment]
I was on vacation and now swamped with work.

this is absolutely a bug, however the question is where, hydra main or the mysql module.
does the same happen if you target e.g. SSH?

**Comment by vanhauser-thc** [comment]
could you do the testing?

**Comment by jakehm** [comment]
Yeah I'll try to do some testing on it tonight.

**Comment by jakehm** [comment]
SSH worked fine.  This is an issue with the MySQL module.

**Comment by jakehm** [comment]
Actually not too confident that it is MySQL specific.  I don't have a good setup to test it properly.

**Comment by vanhauser-thc** [comment]
what is it that makes you say that? if ssh work and mysql not, its the mysql module.
for ssh, just use a non-existing user and insert an iptables rule once it tried a few passwords
