### ISSUE TITLE
 Could not create an SSL session

### ISSUE THREAD

**Issue by at4x** [vanhauser-thc/thc-hydra#248]
Hi, when i try to use hydra, i see this issue:
[ERROR] Child with pid 13691 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:00000000:lib(0):func(0):reason(0)

Any idea?

**Comment by vanhauser-thc** [comment]
using the newest version?

**Comment by at4x** [comment]
8.5 version.

**Comment by vanhauser-thc** [comment]
Always:
 1. update to the newest version before bug reporting
 2. report the version you are using.

fix log for 8.6:
* Fix for SSL connections that failed with error:00000000:lib(0):func(0):reason(0) (thanks gaia@github for reporting)

does updating fix your problem?

**Comment by at4x** [comment]
Ok, now i have 8.7, but the issue don't fix.
I have the same error:
[ERROR] Child with pid 1274 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:00000000:lib(0):func(0):reason(0)

**Comment by vanhauser-thc** [comment]
can you please add the -d switch and post all output?

**Comment by at4x** [comment]
Sure.

DEBUG] Output color flag is 0
Hydra (http://www.thc.org/thc-hydra) starting at 2017-08-17 18:17:15
[DEBUG] cmdline: hydra -d -l test -p test -t 1 -s 465 smtps://74.208.5.15 
[DEBUG] opt:10 argc:11 mod:smtps tgt:74.208.5.15 port:465 misc:(null)
[INFO] several providers have implemented cracking protection, check with a small wordlist first - and stay legal!
[WARNING] Restorefile (you have 10 seconds to abort... (use option -I to skip waiting)) from a previous session found, to prevent overwriting, ./hydra.restore
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking smtps://74.208.5.15:465/
[VERBOSE] Resolving addresses ... 
[DEBUG] resolving 74.208.5.15
[VERBOSE] resolving done
[DEBUG] Code: attack   Time: 1502986645
[DEBUG] Options: mode 0  ssl 1  restore 0  showAttempt 0  tasks 1  max_use 1 tnp 0  tpsal 0  tprl 0  exit_found 0  miscptr (null)  service smtp
[DEBUG] Brains: active 0  targets 1  finished 0  todo_all 1  todo 1  sent 0  found 0  countlogin 1  sizelogin 5  countpass 1  sizepass 5
[DEBUG] Target 0 - target 74.208.5.15  ip 74.208.5.15  login_no 0  pass_no 0  sent 0  pass_state 0  redo_state 0 (0 redos)  use_count 0  failed 0  done 0  fail_count 0  login_ptr test  pass_ptr test
[DEBUG] Task 0 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Tasks 1 inactive  0 active
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 1323
[DEBUG] head_no 0 has pid 1323
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 0, redo_state 0, pass_state 0. loop_mode 0, curlogin (null), curpass (null), tlogin test, tpass test, logincnt 0/1, passcnt 0/1, loop_cnt 1
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin test, cpass test, tlogin -p, tpass test, redo 0
[ATTEMPT] target 74.208.5.15 - login "test" - pass "test" - 1 of 1 [child 0] (0/0)
DEBUG_CONNECT_OK
[VERBOSE] SSL negotiated cipher: ECDHE-RSA-AES256-GCM-SHA384
[DEBUG] hydra_receive_line: waittime: 32, conwait: 0, socket: 5, pid: 1323
[DEBUG] RECV [pid:1323] (54 bytes):
0000:  3232 3020 676d 782e 636f 6d20 286d 7267    [ 220 gmx.com (mrg ]
0010:  6d78 7573 3030 3229 204e 656d 6573 6973    [ mxus002) Nemesis ]
0020:  2045 534d 5450 2053 6572 7669 6365 2072    [  ESMTP Service r ]
0030:  6561 6479 0d0a                             [ eady..           ]
[DEBUG] SEND [pid:1323] (12 bytes):
0000:  4548 4c4f 2068 7964 7261 0d0a              [ EHLO hydra..     ]
[DEBUG] hydra_receive_line: waittime: 32, conwait: 0, socket: 5, pid: 1323
[DEBUG] RECV [pid:1323] (83 bytes):
0000:  3235 302d 676d 782e 636f 6d20 4865 6c6c    [ 250-gmx.com Hell ]
0010:  6f20 6879 6472 6120 5b38 372e 3134 2e32    [ o hydra [87.14.2 ]
0020:  3335 2e32 3037 5d0d 0a32 3530 2d41 5554    [ 35.207]..250-AUT ]
0030:  4820 4c4f 4749 4e20 504c 4149 4e0d 0a32    [ H LOGIN PLAIN..2 ]
0040:  3530 2053 495a 4520 3134 3135 3537 3736    [ 50 SIZE 14155776 ]
0050:  300d 0a                                    [ 0..              ]
[VERBOSE] using SMTP LOGIN AUTH mechanism
[DEBUG] SEND [pid:1323] (12 bytes):
0000:  4155 5448 204c 4f47 494e 0d0a              [ AUTH LOGIN..     ]
[DEBUG] hydra_receive_line: waittime: 32, conwait: 0, socket: 5, pid: 1323
[DEBUG] RECV [pid:1323] (18 bytes):
0000:  3333 3420 5658 4e6c 636d 3568 6257 5536    [ 334 VXNlcm5hbWU6 ]
0010:  0d0a                                       [ ..               ]
[DEBUG] SEND [pid:1323] (10 bytes):
0000:  6447 567a 6441 3d3d 0d0a                   [ dGVzdA==..       ]
[DEBUG] hydra_receive_line: waittime: 32, conwait: 0, socket: 5, pid: 1323
[DEBUG] RECV [pid:1323] (18 bytes):
0000:  3333 3420 5547 467a 6333 6476 636d 5136    [ 334 UGFzc3dvcmQ6 ]
0010:  0d0a                                       [ ..               ]
[DEBUG] SEND [pid:1323] (10 bytes):
0000:  6447 567a 6441 3d3d 0d0a                   [ dGVzdA==..       ]
[DEBUG] hydra_receive_line: waittime: 32, conwait: 0, socket: 5, pid: 1323
[DEBUG] RECV [pid:1323] (40 bytes):
0000:  3533 3520 4175 7468 656e 7469 6361 7469    [ 535 Authenticati ]
0010:  6f6e 2063 7265 6465 6e74 6961 6c73 2069    [ on credentials i ]
0020:  6e76 616c 6964 0d0a                        [ nvalid..         ]
[DEBUG] head_no[0] read N
[STATUS] attack finished for 74.208.5.15 (waiting for children to complete tests)
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] all targets done and all heads finished
[DEBUG] while loop left with 1
1 of 1 target completed, 0 valid passwords found
[DEBUG] killing all remaining children now that might be stuck
Hydra (http://www.thc.org/thc-hydra) finished at 2017-08-17 18:17:27

**Comment by vanhauser-thc** [comment]
the output shows that the SSL connections worked fine and that the login/password combination was wrong.

**Comment by at4x** [comment]
Really? i write this command for hydra:
hydra -S -l mymail@mail.com -P /root/Desktop/rockyou.txt -v -V -e ns -s 587 smtp.mail.com smtp
Do you see error on this command? 
for login/password wrong, you mean the letter ( -l and -P) or (mymail@mail.com and rockyou.txt)
Sorry but im not very expert with kali.

**Comment by vanhauser-thc** [comment]
no you understood me wrong.
your command line is OK.

however the BUG you were reporting is not showing in the debug output you posted. there you see that the SSL connection could be successfully made:

DEBUG_CONNECT_OK
[VERBOSE] SSL negotiated cipher: ECDHE-RSA-AES256-GCM-SHA384
[DEBUG] RECV [pid:1323] (54 bytes):
0000: 3232 3020 676d 782e 636f 6d20 286d 7267 [ 220 gmx.com (mrg ]
0010: 6d78 7573 3030 3229 204e 656d 6573 6973 [ mxus002) Nemesis ]
0020: 2045 534d 5450 2053 6572 7669 6365 2072 [ ESMTP Service r ]
0030: 6561 6479 0d0a [ eady.. ]

so by updating to the newest version the bug you reported is gone. just be sure to use the newest version (I guess you still have the old version installed in parallel)

**Comment by at4x** [comment]
Ok, do you know how i can check if i have old version installed in parallel?
I really need to fix this issue because i can't use hydra.

**Comment by vanhauser-thc** [comment]
find command ...
