### ISSUE TITLE
OS X math.h was not found

### ISSUE THREAD

**Issue by Dunzilein** [vanhauser-thc/thc-hydra#255]
Hi guys,

I have the same issue as this guy : https://github.com/vanhauser-thc/thc-hydra/issues/22

When i try : 
`hydra -l login -x 5:5:aA1 192.168.0.*** ssh`

I got this error : 
`[ERROR] -x option is not available as math.h was not found at compile time`

I have been serching for a few days and can't find a way to make it work.

I'm on macOS Sierra 10.12.6 and my version of xcode is 8.3.3.
I'm pretty sure that hydra is not searching in the good directory to find math.h...
But when i try `mdfind math.h` i can see : 
`/usr/local/Cellar/gcc/7.2.0/include/c++/7.2.0/tr1/math.h
/usr/local/Cellar/gcc/7.2.0/include/c++/7.2.0/math.h`
Is their a way to change the path hydra is loocking for ?

My lack of skills isn't helping :/
So if you have a solution, I would be gratefull !

**Comment by vanhauser-thc** [comment]
/usr/local/Cellar ? what is this?
obivous hydra can not find it there.
I would need more information from other users using different OSX and Xcode versions to see what the pattern is - otherwise a fix will most likely only help solely you

**Comment by Dunzilein** [comment]
As I said in my first post, the guy from this issue : https://github.com/vanhauser-thc/thc-hydra/issues/22 had the same problem.

He fixed it by unlinking GCC and installing hydra again : 
`brew unlink GCC`
`brew install hydra --with-gtk+ --with-libssh`
I tried it (and a lot of other things), but I still got the same error again and again, no matter what I do...

Assuming that [DomT4](https://github.com/DomT4) is right, math.h should be in this path :  `/System/Library/Frameworks/` ?

Thanks again

**Comment by vanhauser-thc** [comment]
it is not that easy.

first: the math.h on your systems are in /usr/local/Cellar/, not in /System/Library/Frameworks - so there is a discrepance already.
second: if I just look for a math.h on the system (e.g. with find command, which can take up to 30 minutes on large systems), the compilation could fail because the math.h might be a different one (not the "official" one).

so without enough information to cope with the issue it is hard to get right properly.

maybe you can do some research which package installs the math.h commonly on OS X (at a minimum gcc brew, gcc dmg, xcode install) for a few different versions (each) and send me all the directories the math.h would be.
then I can do the coding to find the proper math.h

(that is kinda the issue with OS X. everything not apple standard is a pain in the ass ...)

**Comment by Dunzilein** [comment]
If I search for math.h, I got the following paths : 

`/Applications/MAMP/Library/include/python2.7/pymath.h
/Applications/MAMP/bin/php/php5.4.45/include/php/ext/standard/php_math.h
/Applications/MAMP/bin/php/php5.5.38/include/php/ext/standard/php_math.h
/Applications/MAMP/bin/php/php5.6.25/include/php/ext/standard/php_math.h
/Applications/MAMP/bin/php/php7.0.10/include/php/ext/standard/php_math.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/simd/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/include/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/include/simd/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/2.0/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/core/include/numpy/npy_math.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6/pymath.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include/numpy/npy_math.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pymath.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1/tr1/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1/tr1/tgmath.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/php/ext/standard/php_math.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/simd/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/usr/include/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/usr/include/simd/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/usr/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/simd/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/c++/4.2.1/tr1/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/c++/4.2.1/tr1/tgmath.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/simd/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/c++/4.2.1/tr1/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/c++/4.2.1/tr1/tgmath.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/simd/math.h
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/lib/swift/clang/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/tgmath.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include/__clang_cuda_cmath.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/AppleTVOS.sdk/usr/include/math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/AppleTVOS.sdk/usr/include/simd/math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/AppleTVOS.sdk/usr/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/AppleTVSimulator.sdk/usr/include/math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/AppleTVSimulator.sdk/usr/include/simd/math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/AppleTVSimulator.sdk/usr/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/MacOSX.sdk/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/2.0/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/MacOSX.sdk/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/core/include/numpy/npy_math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/MacOSX.sdk/System/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6/pymath.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/MacOSX.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include/numpy/npy_math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/MacOSX.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pymath.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/MacOSX.sdk/usr/include/math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/MacOSX.sdk/usr/include/php/ext/standard/php_math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/MacOSX.sdk/usr/include/simd/math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/MacOSX.sdk/usr/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/WatchOS.sdk/usr/include/math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/WatchOS.sdk/usr/include/simd/math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/WatchOS.sdk/usr/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/WatchSimulator.sdk/usr/include/math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/WatchSimulator.sdk/usr/include/simd/math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/WatchSimulator.sdk/usr/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/iPhoneOS.sdk/usr/include/math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/iPhoneOS.sdk/usr/include/simd/math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/iPhoneOS.sdk/usr/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/iPhoneSimulator.sdk/usr/include/math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/iPhoneSimulator.sdk/usr/include/simd/math.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdks/iPhoneSimulator.sdk/usr/include/tgmath.h
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/swift/clang/include/tgmath.h
/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Resources/Clang/include/__clang_cuda_cmath.h
/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Resources/Clang/include/tgmath.h
/Applications/android-sdk-macosx/build-tools/23.0.1/renderscript/clang-include/tgmath.h
/Applications/android-sdk-macosx/build-tools/25.0.1/renderscript/clang-include/tgmath.h
/Library/Frameworks/Python.framework/Versions/2.7/Resources/English.lproj/Documentation/library/cmath.html
/Library/Frameworks/Python.framework/Versions/2.7/Resources/English.lproj/Documentation/library/math.html
/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pymath.h
/Library/Frameworks/Python.framework/Versions/3.4/Resources/English.lproj/Documentation/library/cmath.html
/Library/Frameworks/Python.framework/Versions/3.4/Resources/English.lproj/Documentation/library/math.html
/Library/Frameworks/Python.framework/Versions/3.4/include/python3.4m/pymath.h
/Library/Frameworks/Python.framework/Versions/3.5/Resources/English.lproj/Documentation/library/cmath.html
/Library/Frameworks/Python.framework/Versions/3.5/Resources/English.lproj/Documentation/library/math.html
/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m/pymath.h
/Library/Frameworks/R.framework/Versions/3.3/PrivateHeaders/Rmath.h0.in
/Library/Frameworks/R.framework/Versions/3.3/Resources/include/Rmath.h
/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include/Rcpp/Rmath.h
/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include/Rcpp/sugar/functions/math.h
/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include/Rcpp/sugar/undoRmath.h
/System/Library/Frameworks/OpenCL.framework/Versions/A/lib/clang/2.0/include/tgmath.h
/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/core/include/numpy/npy_math.h
/System/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6/pymath.h
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include/numpy/npy_math.h
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/pymath.h
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/A/Libraries/lib/clang/3.5/include/tgmath.h
/Users/****/anaconda/include/Qt/qmath.h
/Users/****/anaconda/include/QtCore/qmath.h
/Users/****/anaconda/include/dynd/dynd_math.hpp
/Users/****/anaconda/include/python2.7/pymath.h
/Users/****/anaconda/lib/python2.7/site-packages/astropy/wcs/include/wcslib/wcsmath.h
/Users/****/anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h
/Users/****/anaconda/pkgs/astropy-0.4.2-np19py27_0/lib/python2.7/site-packages/astropy/wcs/include/wcslib/wcsmath.h
/Users/****/anaconda/pkgs/libdynd-0.6.5-0/include/dynd/dynd_math.hpp
/Users/****/anaconda/pkgs/numpy-1.9.0-py27_0/lib/python2.7/site-packages/numpy/core/include/numpy/npy_math.h
/Users/****/anaconda/pkgs/python-2.7.8-1/include/python2.7/pymath.h
/Users/****/anaconda/pkgs/qt-4.8.5-3/include/Qt/qmath.h
/Users/****/anaconda/pkgs/qt-4.8.5-3/include/QtCore/qmath.h
/usr/local/Cellar/gcc/7.2.0/include/c++/7.2.0/math.h
/usr/local/Cellar/gcc/7.2.0/include/c++/7.2.0/tgmath.h
/usr/local/Cellar/gcc/7.2.0/include/c++/7.2.0/tr1/math.h
/usr/local/Cellar/gcc/7.2.0/include/c++/7.2.0/tr1/tgmath.h
/usr/local/Cellar/gcc/7.2.0/lib/gcc/7/gcc/x86_64-apple-darwin16.7.0/7.2.0/include/quadmath.h
/usr/local/Cellar/gcc/7.2.0/lib/gcc/7/gcc/x86_64-apple-darwin16.7.0/7.2.0/include/tgmath.h
/usr/local/Cellar/gcc/7.2.0/lib/gcc/7/gcc/x86_64-apple-darwin16.7.0/7.2.0/include-fixed/math.h
/usr/local/Cellar/harfbuzz/1.4.8_1/include/harfbuzz/hb-ot-math.h
/usr/local/Cellar/harfbuzz/1.4.8_1/share/gtk-doc/html/harfbuzz/harfbuzz-hb-ot-math.html
/usr/local/Cellar/harfbuzz/1.5.0/include/harfbuzz/hb-ot-math.h
/usr/local/Cellar/harfbuzz/1.5.0/share/gtk-doc/html/harfbuzz/harfbuzz-hb-ot-math.html
/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/include/python2.7/pymath.h`

As you can see, Xcode have several math.h files and GCC is providing some too.
I'm not sure if it is what you ask ?

The `/usr/local/Cellar/gcc/7.2.0/include/c++/7.2.0/math.h` file is looking like that : 
`// -*- C++ -*- compatibility header.

// Copyright (C) 2002-2017 Free Software Foundation, Inc.
//
// This file is part of the GNU ISO C++ Library.  This library is free
// software; you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the
// Free Software Foundation; either version 3, or (at your option)
// any later version.

// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// Under Section 7 of GPL version 3, you are granted additional
// permissions described in the GCC Runtime Library Exception, version
// 3.1, as published by the Free Software Foundation.

// You should have received a copy of the GNU General Public License and
// a copy of the GCC Runtime Library Exception along with this program;
// see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
// <http://www.gnu.org/licenses/>.

/** @file math.h
 *  This is a Standard C++ Library header.
 */

#if !defined __cplusplus || defined _GLIBCXX_INCLUDE_NEXT_C_HEADERS
# include_next <math.h>
#else

#ifndef _GLIBCXX_MATH_H
#define _GLIBCXX_MATH_H 1
#define _GLIBCXX_MATH_H 1

# include <cmath>

using std::abs;
using std::acos;
using std::asin;
using std::atan;
using std::atan2;
using std::cos;
using std::sin;
using std::tan;
using std::cosh;
using std::sinh;
using std::tanh;
using std::exp;
using std::frexp;
using std::ldexp;
using std::log;
using std::log10;
using std::modf;
using std::pow;
using std::sqrt;
using std::ceil;
using std::fabs;
using std::floor;
using std::fmod;

#if _GLIBCXX_USE_C99_MATH
using std::fpclassify;
using std::isfinite;
using std::isinf;
using std::isnan;
using std::isnormal;
using std::signbit;
using std::isnormal;
using std::signbit;
using std::isgreater;
using std::isgreaterequal;
using std::isless;
using std::islessequal;
using std::islessgreater;
using std::isunordered;
#endif

#if __cplusplus >= 201103L && defined(_GLIBCXX_USE_C99_MATH_TR1)
using std::acosh;
using std::asinh;
using std::atanh;
using std::cbrt;
using std::copysign;
using std::erf;
using std::erfc;
using std::exp2;
using std::expm1;
using std::fdim;
using std::fma;
using std::fmax;
using std::fmin;
using std::hypot;
using std::ilogb;
using std::lgamma;
using std::llrint;
using std::llround;
using std::log1p;
using std::log2;
using std::logb;
using std::lrint;
using std::lround;
using std::nearbyint;
using std::lround;
using std::nearbyint;
using std::nextafter;
using std::nexttoward;
using std::remainder;
using std::remquo;
using std::rint;
using std::round;
using std::scalbln;
using std::scalbn;
using std::tgamma;
using std::trunc;
#endif // C++11 && _GLIBCXX_USE_C99_MATH_TR1

#if __STDCPP_WANT_MATH_SPEC_FUNCS__ == 1
using std::assoc_laguerref;
using std::assoc_laguerrel;
using std::assoc_laguerre;
using std::assoc_legendref;
using std::assoc_legendrel;
using std::assoc_legendre;
using std::betaf;
using std::betal;
using std::beta;
using std::comp_ellint_1f;
using std::comp_ellint_1l;
using std::comp_ellint_1;
using std::comp_ellint_2f;
using std::comp_ellint_2l;
using std::comp_ellint_2;
using std::comp_ellint_3f;
using std::comp_ellint_3l;
using std::comp_ellint_3;
using std::cyl_bessel_if;
using std::cyl_bessel_il;
using std::cyl_bessel_if;
using std::cyl_bessel_il;
using std::cyl_bessel_i;
using std::cyl_bessel_jf;
using std::cyl_bessel_jl;
using std::cyl_bessel_j;
using std::cyl_bessel_kf;
using std::cyl_bessel_kl;
using std::cyl_bessel_k;
using std::cyl_neumannf;
using std::cyl_neumannl;
using std::cyl_neumann;
using std::ellint_1f;
using std::ellint_1l;
using std::ellint_1;
using std::ellint_2f;
using std::ellint_2l;
using std::ellint_2;
using std::ellint_3f;
using std::ellint_3l;
using std::ellint_3;
using std::expintf;
using std::expintl;
using std::expint;
using std::hermitef;
using std::hermitel;
using std::hermite;
using std::laguerref;
using std::laguerrel;
using std::laguerre;
using std::legendref;
using std::legendrel;
using std::legendre;
using std::riemann_zetaf;
using std::riemann_zetal;
using std::riemann_zetaf;
using std::riemann_zetal;
using std::riemann_zeta;
using std::sph_besself;
using std::sph_bessell;
using std::sph_bessel;
using std::sph_legendref;
using std::sph_legendrel;
using std::sph_legendre;
using std::sph_neumannf;
using std::sph_neumannl;
using std::sph_neumann;
#endif // __STDCPP_WANT_MATH_SPEC_FUNCS__

#endif // _GLIBCXX_MATH_H
#endif // __cplusplus`

What does hydra need to work? Is it enough ? Are Am I missing something ?

Yea being on OS X is sometimes really annoying... =/

**Comment by vanhauser-thc** [comment]
yeah you did not really understand what I would need .... maybe you know someone who knows more about coding and compiling and you give him my last comment to read and he can help you getting the data?

**Comment by DomT4** [comment]
> Assuming that DomT4 is right, math.h should be in this path : /System/Library/Frameworks/ ?

Brave person to quote me from three years ago. I wouldn't trust myself from three years ago 😄. Looking at your dump of _(I presume)_ `mdfind` up there, I guess you've never installed the Command Line Tools package & run a pure Xcode development system?

**Comment by Dunzilein** [comment]
> maybe you know someone who knows more about coding and compiling

If it was the case, I wouldn't be here... :/

> I guess you've never installed the Command Line Tools package

That's right ! I changed my computer a few months ago and I didn't reinstall it after that I guess ?

So after a quick `xcode-select --install`, I uninstalled Hydra and installed it again.
It's seems to work now !

Thanks guys for your time and sorry to have bothered you.

**Comment by DomT4** [comment]
> It's seems to work now !

As way of an explanation, `/usr/include` does not exist on macOS unless you specifically install the Command Lines Tools package. If you run an Xcode-only system the headers are located inside the SDK at:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/
```

Or if you're running a beta Xcode:
```
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/
```

The problem with `hydra` here being that it _only_ checks `/usr/include` in [attempting to find that header](https://github.com/vanhauser-thc/thc-hydra/blob/07acbda42226107d5ca926b35f6a2cc401c46ffd/configure#L648-L660).

**Comment by vanhauser-thc** [comment]
@DomT4  what would you recommend how to improve the process of finding the math.h on OS X?

**Comment by Dunzilein** [comment]
> The problem with hydra here being that it only checks /usr/include in attempting to find that header.

Thanks for the explanation ! Seen like that, it's pretty obvious...

**Comment by DomT4** [comment]
> what would you recommend how to improve the process of finding the math.h on OS X?

I'll follow up with a PR at some point in the next couple days. Just trying a few things out locally in terms of trying to work out what the best approach is here specifically. My initial implementation was interesting but probably more complicated than it needed to be.
