### ISSUE TITLE
Hydra is not finding the password

### ISSUE THREAD

**Issue by ThatOtherGuy7** [vanhauser-thc/thc-hydra#256]
Hey.
So im trying to Brute Force a HTTP login form with Hydra and everytime i start it and try, it says that 16 matches (correct pws) were found. But all the first 16 PWs it tested were wrong and it stopped and said yep found it. Im useing this code:

hydra 192.168.101.10 -s 88 http-form-post "/index.php?module=Users&action=Login:__vtrftk=sid%0efd4ec7731142fb8daa19cc44e8e89f1c9ed983,1504131670&username=^USER^&password=^PASS^:Invalid username or password.:H=Cookie: security=medium; PHPSESSID=7a067e1759a70fab986cb" -l admin -P ~/Desktop/test.txt -v -t 20

I tried it without the H=Cookies and the PHPSESSID and its also not working. The "vtrftk=sid" value changes after some time and i always used the newest value which i got from burpsuit. I think i know what the issue is but im not sure. Everytime Hydra tries the credentials it redirects to an error URL when the PW is wrong. Maybe Hydra is confused and doesnt jump back to the the URL i told it to check. I also tried to change the "stop point" to when hydra finds a logout label somewhere on the site but its also not working. Im trying for 3h now and im really frustrated. 
The strange thing about all this is when i dont set the -t value it checks the first 16 PWS (default value). When i set the value to 64 it checks the first 64 PWs in the wordlist. Same when i do 20 instead of 16 or 64. 

Extra infos:
im useing Kali 2017 (or whatever the newest version is called)
yesterday, 30. Aug. 2k17 i did an system update and upgrade. restarted it without any warning issues whatsoever
The site im testing is on a network im connected via VPN
The wordlist contains 7 phrases and the last one in the list is the correct one
The user "admin" is 100% correct
The way i tried it with the code above or shortened worked for a friend of mine. Same OS, same software versions

Pls send halp.THX

**Comment by fwx1987** [comment]
I encountered the same issue. the hydra is sending http-post-form with http 1.0 instead of 1.1.

where can i configure it?

**Comment by vanhauser-thc** [comment]
@ThatOtherGuy7 try the following:
just use one password (-p switch), add the -d switch for debug output, and try once the correct password and once the incorrect password, and check what the result page (that the debug output prints) tells you. most likely you are missing a cookie or form variable or your identifier for success/failure is wrong

@fwx1987 are you sure your problem is that the web page does not allow authentication with 1.0? if so, you are in bad luck as 1.1 is not supported. (until someone submits a http11 library)

**Comment by ThatOtherGuy7** [comment]
Thx for the quick response but still no luck. I did what you said and put in a wrong password and then the correct one manually and checked the output. Im not quite sure what to look for but noticed that Hydra checks the PW on the form, a "Invalid username or password." Message appears beneath the Login Form and the site gets redirected to "index.php?module=Users&parent=Settings&view=Login&error=1" (as you can see from the pastebin link). Im so confused because it says both PW i entered separately are correct even tho only one is correct and i get redirected to the Error Page  with both PWs. Here are both outputs if you want to have a look at them. Im a noob and maybe i missed something important in the output. 
Correct PW: https://pastebin.com/2hMGr9Ee
Wrong PW: https://pastebin.com/kx3MvURM
Im not sure if its just a stupid user error by me but as i said before the same exact syntax worked for a friend of mine and a few others. My colleague and me are both using the newest version of Kali Linux and all packages are also up to date.

**Comment by vanhauser-thc** [comment]
append this and it should work: :F=error=1

you did not tell hydra what to look for for success or failure

**Comment by ThatOtherGuy7** [comment]
That would make sense i thought the ":Invalid usern...." was enough. I tried the same code with the :F=error=1 but its still not working. I tried it with a PW list, without the list, with the wrong and the correct PW and i always get the same result: https://pastebin.com/QY2GvU42
I stopped the process after "0.25 tries/min" because it wasnt working anyways. I let it do its thing until i got to "0.3 tries/min" or something. 

On the second try i left out the ":Invalid us..." and just put the ":F=error=1" behind the URL but i got the same output as ealier this day:
Wrong PW: https://pastebin.com/kwFCauLS
Corret PW: https://pastebin.com/bVLxumts

**Comment by vanhauser-thc** [comment]
ah sorry, I did not explain well how the command line should be:

hydra  -l admin -P ~/Desktop/test.txt -v -t 20 -s 88 192.168.101.10 http-form-post "/index.php?module=Users&action=Login:__vtrftk=sid%0efd4ec7731142fb8daa19cc44e8e89f1c9ed983,1504131670&username=^USER^&password=^PASS^:error=1:H=Cookie: security=medium; PHPSESSID=7a067e1759a70fab986cb"

**Comment by fwx1987** [comment]
@vanhauser-thc  i forward the traffic to my burp proxy and the difference is the http verrsion. for the 302 redirection, it shows the HOST header incorrectly even I added the host header in my hydra parameters. 

i tried another tools "Medusa", it shows the same, http 1.0 is used but manually is 1.1. how can i configure it? what's library of hydra is using?

**Comment by ThatOtherGuy7** [comment]
Wow that actually worked!!! 
Thank you very much for your help!

**Comment by vanhauser-thc** [comment]
knowing the tool is winning :)
