### ISSUE TITLE
Unexpected issue about the failure message !!

### ISSUE THREAD

**Issue by nohope91** [vanhauser-thc/thc-hydra#260]
Hello Sir, one thing I couldn't solve about the failure message
What if the failure message contains one or more break lines </br> ?
it's typically like that :
{

    
         Authentication failed. Please enter a valid userId and password.}

Nothing at the first line, then 4 spaces in the second line, then 9 spaces before the text message at the third line, I can copy the third line with its 9 spaces, but how could I include all the lines in hydra?
When I try to copy/paste it to the terminal, it simply quit !!
I hope you have a solution for this :)

Thank you

**Comment by vanhauser-thc** [comment]
what protocol are you even talking about?

**Comment by nohope91** [comment]
Ahh sorry I forgot to mention that  >> http(s)-post-form
I'm pretty sure that my syntax is 100% correct

**Comment by vanhauser-thc** [comment]
and how would we be able to check the syntax if you didn't post it?
man, turn on your brain and write a detailed error report in the first place.

**Comment by nohope91** [comment]
Sir, you got me wrong, I didn't mean to ask you to check out my syntax
I only need to know is it possible to include the failure message in the syntax if it contains one or more break lines < b r > ??

"<URL_of_the_page>:<form parameters>:<failure message>"
But in this case it would be like this :
"<URL_of_the_page>:<form parameters>:"
    
         Authentication failed. Please enter a valid userId and password."

- Nothing at the first line
- 4 spaces in the second line
- Then 9 spaces before the text message at the third line

I can copy the third line with its 9 spaces
But hydra will QUIT because of the break lines !!
What to do if the break lines and spaces are part of the failure message?
Sorry if you got me wrong or I didn't explain it properly :)

**Comment by vanhauser-thc** [comment]
hmmm if hydra is compiled with regex support you can use regex, but I am not sure if it is applied to one line or multiple lines. you would need to try that out.

what why that trouble? why do you not just set "Authentication failed" as the failure trigger? I don't need the necessity why you would need to look at more than 2+ words in a single line to determine success from failure.

**Comment by nohope91** [comment]
Because I have tried before, and when I do so, it throws false positives
I'm going to try out regex, and will tell you what happens :)
