### ISSUE TITLE
Hydra 8.6 uses 100% CPU on VM Kali

### ISSUE THREAD

**Issue by T0T3NK0PF** [vanhauser-thc/thc-hydra#262]
Hydra 8.6 updated from Kali Linux Repos on VM uses 100% of all CPU's, hangs up and doesn't continue brute force attack or error out. just sits. 
Using wordlist with ~10 entries
Using http-post-form module 
I haven't tested it with other services.  

![capture](https://user-images.githubusercontent.com/24560595/30509723-6f52c60a-9ab7-11e7-92b4-3800fe450bb1.JPG)

**Comment by vanhauser-thc** [comment]
how about you post your command line and all output generated so I can try to see what is going wrong? I am not a psychic, you know ;)

**Comment by T0T3NK0PF** [comment]
Hey thanks for the reply... 

Command Used: 
hydra -I -V -o /root/Hydra-Projects/Hydra-success.txt -f -l TestAdmin -P /root/wordlists/Lavalamp-all-words.txt www.demosite.org http-post-form "/demo/fg/wp-login.php:log=^USER^&pwd=^PASS^&wp-submit=Log:S=Location: .*/wp-admin/"

It runs the first 16 Attempts. The CPU immediately jumps to 100% on all threads / Cores... 

[ATTEMPT] target www.demosite.org - login "TestAdmin" - pass "!!!!%%" - 1 of 571179 [child 0] (0/0)
[ATTEMPT] target www.demosite.org - login "TestAdmin" - pass "!!!4basketball" - 2 of 571179 [child 1] (0/0)
[ATTEMPT] target www.demosite.org - login "TestAdmin" - pass "!!!abc123" - 3 of 571179 [child 2] (0/0)
[ATTEMPT] target www.demosite.org - login "TestAdmin" - pass "!!!devv" - 4 of 571179 [child 3] (0/0)
[ATTEMPT] target www.demosite.org - login "TestAdmin" - pass "!!42VincentZ42!!" - 5 of 571179 [child 4] (0/0)
[ATTEMPT] target www.demosite.org - login "TestAdmin" - pass "!!Z!32" - 6 of 571179 [child 5] (0/0)
[ATTEMPT] target www.demositen.org - login "TestAdmin" - pass "!!eassc88" - 7 of 571179 [child 6] (0/0)
[ATTEMPT] target www.demosite.org - login "TestAdmin" - pass "!"!!(=" - 8 of 571179 [child 7] (0/0)
[ATTEMPT] target www.demosite.org - login "TestAdmin" - pass "!$**texas3" - 9 of 571179 [child 8] (0/0)
[ATTEMPT] target www.demosite.org - login "TestAdmin" - pass "!$jan!(%!" - 10 of 571179 [child 9] (0/0)
[ATTEMPT] target www.demositeorg - login "TestAdmin" - pass "!19032014" - 11 of 571179 [child 10] (0/0)
[ATTEMPT] target www.demosite.org - login "TestAdmin" - pass "!1Baggervance" - 12 of 571179 [child 11] (0/0)
[ATTEMPT] target www.demosite.org - login "TestAdmin" - pass "!1Vegeta77" - 13 of 571179 [child 12] (0/0)
[ATTEMPT] target www.demosite.org - login "TestAdmin" - pass "!1dyedejq" - 14 of 571179 [child 13] (0/0)
[ATTEMPT] target www.demosite.org - login "TestAdmin" - pass "!1moretime" - 15 of 571179 [child 14] (0/0)
[ATTEMPT] target www.demosite.org - login "TestAdmin" - pass "!1p6h1i8!" - 16 of 571179 [child 15] (0/0)

Then after this... Nothing else happens. 
Hydra just sits here. While returning periodically.

[STATUS] 16.00 tries/min, 16 tries in 00:01h, 571163 to do in 594:58h, 16 active

No further attacks are carried out.... Nothing else happens but the CPU's sits at 100%.
Now before I updated Kali... 2 days ago 15 Sep 17
Hydra was working perfectly in this VM. I had it running for a good 2 days. Continuously without issues. 

The test site I own is a Wordpress 4.8.1 site with no added security plugins at all. Vanilla install and a theme. 

Screenshot of Entire Terminal:
I redacted the actual URL of the server in the screenshot. 

![capture2](https://user-images.githubusercontent.com/24560595/30549352-d1f89972-9c94-11e7-9f80-ef7401da255e.JPG)

**Comment by vanhauser-thc** [comment]
the problem is that hydra is unable to connect to the remote server. it should not result in 100%CPU though

**Comment by T0T3NK0PF** [comment]
Mmmm remote test server is UP and I can access it with curl in terminal and from Firefox within the VM.
Im kinda lost at the moment... WPScan can also reach the site and bruteforce it.

![capture3](https://user-images.githubusercontent.com/24560595/30551309-62772392-9c9a-11e7-8748-7f6e596d5f49.JPG)
![capture4](https://user-images.githubusercontent.com/24560595/30551313-63d837b2-9c9a-11e7-922a-616cd99825b9.JPG)

**Comment by vanhauser-thc** [comment]
that might be but you see no information in the debug output that a connection is ever established and if that would have succeeded, the POST request would be shown as well as the server reply.

how about you compile it fresh yourselve from the current state of this github repository, and run one attempt (-l admin -p test) with debug (-d) enabled?

**Comment by T0T3NK0PF** [comment]
**Ok so I have compiled hydra from git.**
Seems to be Hydra 2.7-Dev 
When running ./configure I notices a lot of NOT Found modules but it compiled anyways. 
[HydraConfigureOutput.txt](https://github.com/vanhauser-thc/thc-hydra/files/1313186/HydraConfigureOutput.txt)

**Here is the output from a single attack with the correct login details of the test site.**
[Hydra-Attack-Output.txt](https://github.com/vanhauser-thc/thc-hydra/files/1313187/Hydra-Attack-Output.txt)
I eventually canceled it since it just looped. 
I also noticed the CPU usage doesn't go to 100% on all cores now all at the same time however they take turns.
CORE1 jumps to 100% for a few seconds then it drops while Core2 jumps to 100% then Core3 then Core4 and so on. Only one core at a time now spikes to 100%. 

**Then I ran WPScan just to make sure, here is the output:**
[WPScan-Output.txt](https://github.com/vanhauser-thc/thc-hydra/files/1313188/WPScan-Output.txt)

**Comment by vanhauser-thc** [comment]
look into the INSTALL file for the packages you need.

OK, so its the regex functionality that is a problem, I will look into that.

**Comment by T0T3NK0PF** [comment]
Appears so yes. 
Okay cool. Ill recompile when I get a chance... and report back with any findings.
Thank you for your time and efforts.
