### ISSUE TITLE
Should we not repeat a parameter in the string?

### ISSUE THREAD

**Issue by nohope91** [vanhauser-thc/thc-hydra#263]
Is it wrong to use the ^USER^ parameter in the string twice?
Why twice? I've the same question, but that's the intercepted data of the form : 
"/index.php:User=^USER^&EnteredUser=^USER^&Password=^PASS^:Authentication Failed"

Should I include it twice or skip one of them?

**Comment by vanhauser-thc** [comment]
I did not write the module, but I think you can put it twice.

why dont you just try it and take a look at the request generated? (e.g. by activating debug with -d)

**Comment by nohope91** [comment]
You're right and I'm pretty sure now it can be used twice :)
You may close this thread
Thank you Sir <3
