### ISSUE TITLE
S7-300 [ERROR] did not received data from the service (3)

### ISSUE THREAD

**Issue by MarcosZornitta** [vanhauser-thc/thc-hydra#264]
I am trying to search the password of an S7-300 PLC, but when I start reading, hydra returns the error "**[ERROR] did not receive data from service (3)**".

What I need to do?

Command: hydra -p test -t 8 10.12.12.10 s7-300

**Comment by vanhauser-thc** [comment]
I did not write the module.

Looking at the code it seems the initial send + reply has to be working, however to the second step there is no reply from the server.

maybe the auth type is not supported or its a different protocol version.

if you look into the source file you will find an email address of the original author you could contact what might be the issue and what you could do:
https://github.com/vanhauser-thc/thc-hydra/blob/master/hydra-s7-300.c
the second author's email address is gordey@ at the same company.
