### ISSUE TITLE
issue with specific command

### ISSUE THREAD

**Issue by stevenanthonyr** [vanhauser-thc/thc-hydra#272]
hello,

I'm trying to use hydra for a ctf challenge and am having issues with my command. Normally I would think this is my misunderstanding, but I have tried every combination and cannot get hydra to run without showing me the syntax info and no error info or without throwing the following error:

`[ERROR] Invalid target definition!
[ERROR] Either you use "www.example.com module [optional-module-parameters]" *or* you use the "module://www.example.com/optional-module-parameters" syntax!`

The commands I have tried to run are (i have obfuscated the ip, path, and first arg, but everything else is the same as I input it):

`hydra -l test -P md5_password_list.txt 'http-post-form://**.***.**.**/part/of/path/login.php:weird_arg=reallylongstringwitha%signsomewhereinthere&username=^USER^&challenge-password=&secure_password=^PASS^&login.php+file+created+with+vim=:incorrect username or password' -f -V`

... which throws the error shown above, and

`hydra -l test -P md5_password_list.txt **.***.**.** http-post-form '/part/of/path/login.php:weird_arg=reallylongstringwitha%signsomewhereinthere&username=^USER^&challenge-password=&secure_password=^PASS^&login.php+file+created+with+vim=:incorrect username or password' -f -V`

which simply fails silently in the following manner:

```Hydra v8.6 (c) 2017 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2017-10-10 13:27:45
Syntax: hydra [[[-l LOGIN|-L FILE] [-p PASS|-P FILE]] | [-C FILE]] [-e nsr] [-o FILE] [-t TASKS] [-M FILE [-T TASKS]] [-w TIME] [-W TIME] [-f] [-s PORT] [-x MIN:MAX:CHARSET] [-c TIME] [-ISOuvVd46] [service://server[:PORT][/OPT]]

Options:
...
```

I have also tried running both commands with the -m flag to no avail. What am I doing wrong with my command?

**Comment by vanhauser-thc** [comment]
wrong usage.

either

hydra -l test -P md5_password_list.txt -f -V -m '/part/of/path/login.php:weird_arg=reallylongstringwitha%signsomewhereinthere&username=^USER^&challenge-password=&secure_password=^PASS^&login.php+file+created+with+vim=:incorrect username or password' 127.0.0.1 http-post-form

or

hydra -l test -P md5_password_list.txt -f -V 'http-post-form://**.**.**.**/part/of/path/login.php:weird_arg=reallylongstringwitha%signsomewhereinthere&username=^USER^&challenge-password=&secure_password=^PASS^&login.php+file+created+with+vim=:incorrect username or password'

**Comment by Godsongmg2** [comment]
i want to access the gmail passwd, can anyone direct me in the simplest language ,its my first time to use kali

**Comment by monkeymonkeyaap** [comment]
dont try to hack google,
