### ISSUE TITLE
Too many "todo"

### ISSUE THREAD

**Issue by aysufhne** [vanhauser-thc/thc-hydra#273]
And this is never end.
Don't know what to do in that case, can u help or fix it? thx

![31406306-7372cb12-adf0-11e7-8dde-8ec7512dbac2](https://user-images.githubusercontent.com/32685319/31432654-9c00e5ac-ae66-11e7-87c6-92d0c5bf90f7.png)

**Comment by vanhauser-thc** [comment]
dont waste anybodys time and make a good report.
what version? what command line? etc.

**Comment by aysufhne** [comment]
I am sorry for that. 
Here is my command line - `hydra -s 22 -C /home/user/Desktop/Work/B/LogPassList -t 64w 5 -M '/home/user/Desktop/Work/B/Working SSH' ssh `

Hydra Version is v8.1 

And another screenshot with problem. After some time of working(real working, with real result as u can see at picture below) hydra falling in some endless loop of "to do" log\pass pair. 

![screenshot_20171019_124704](https://user-images.githubusercontent.com/32685319/31765343-965ecb2a-b4b3-11e7-9ba7-b6e1888f449a.png)

**Comment by vanhauser-thc** [comment]
update to the newest version then retest. also try to update libssh to the newest version

**Comment by vanhauser-thc** [comment]
any update on the issue after you updated hydra and libssh to the newest version?

**Comment by aysufhne** [comment]
Very sorry for leaving this open. 

libssh didn't help, and hydra was already  newest. I'd recommend you to test it with huge amount IP list with wide pass\login lists, it is appear only in case of huge lists to crack. I don't have much time to test it, and since my "project" is no longer actual, I don't need hydra much.
