### ISSUE TITLE
[WARNING] hydra was compiled without SSL support

### ISSUE THREAD

**Issue by csrx007** [vanhauser-thc/thc-hydra#274]
[WARNING] hydra was compiled without SSL support. Install openssl and recompile! Option ignored...

Linux e02b88 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Command:
hydra -s 465 -S -v -V -l theemail@gmail.com -p thepass -t 1 smtp.gmail.com smtp

root:~/hydra# which openssl
/usr/bin/openssl
root:~/hydra# which hydra
/usr/local/bin/hydra

i did the ./configure make make install again but no success...

**Comment by vanhauser-thc** [comment]
what was the output of ./configure? you noticed that it writes stuff on the screen it finds?
very likely you have not the openssl-dev package installed

**Comment by csrx007** [comment]
Fixed that issue, was the cache i did a CLEAN install and all working but now, i dont have any hit... i think is for the IP verification by Gmail.. i dont know if i can use Proxy in Command  line, but i will read again the Documentation. Thanks!
