### ISSUE TITLE
math.h was not found at compile time

### ISSUE THREAD

**Issue by F4125h4d** [vanhauser-thc/thc-hydra#281]
Hi there,
I`m using Hydra with cygwin.
Can anyone help me with this problem?
my package consists mostly recommended packages and even more than that (125MBs)

**Comment by vanhauser-thc** [comment]
I am also using cygwin and dont have this issue.

can you please paste the output of "./configure --debug"
and "find / -name math.h"

**Comment by F4125h4d** [comment]
But you wrote that man.

> DNS server not authoritative for zone.

> FIND: Invalid switch

**Comment by vanhauser-thc** [comment]
if you have no clue what you are doing then I see it is difficult to do a proper issue report.

try to find someone with some linux/unix knowledge to help you
