### ISSUE TITLE
Segmentation Fault (Hydra V8.6)

### ISSUE THREAD

**Issue by LandyLane** [vanhauser-thc/thc-hydra#285]
On Kali VM: `hydra -t 2 -V -f -l Administrator -P passList.txt rdp://x.x.x.x`

x.x.x.x represents target IP address

getting a segmentation fault as soon as the program launches.
[Picture of terminal](https://i.gyazo.com/7167425ec2ef761822f038ea475c1a6a.png)

**Comment by vanhauser-thc** [comment]
I cannot reproduce it, but I do not have an rdp service running anywhere.

what you could do: recompile hydra with -g flag (./configure then edit the Makefile and switch -O2 with -g, make, make install) then enable dumping cores (ulimit -c unlimited), rerun the program and send me the core file and the compiled hydra
