### ISSUE TITLE
Annoying message error!

### ISSUE THREAD

**Issue by HeCosmin** [vanhauser-thc/thc-hydra#287]
`[ERROR] ssh protocol error
[ERROR] ssh protocol error
[ERROR] ssh protocol error
[ERROR] ssh protocol error
[ERROR] ssh protocol error
[ERROR] ssh protocol error
[ERROR] ssh protocol error
[ERROR] Too many connect errors to target, disabling ssh://XX.XX.XX.XX:22
[ERROR] 1 target did not resolve or could not be connected`

I don't want see this message error, help me tips command ignore message error? thanks

**Comment by vanhauser-thc** [comment]
for it might be annoying, for other people its an important information that the attack could be sped up by decreases the number of parallel tasks ...

if you do not want to see it drop error output:

hydra .... options ... 2> /dev/null

**Comment by HeCosmin** [comment]
It's perfect `2> /dev/null` thanks tips! <3
