### ISSUE TITLE
An endless redirect prevents you from recording the success of the attempt.

### ISSUE THREAD

**Issue by deret00000** [vanhauser-thc/thc-hydra#289]
When the password is successfully matched, the target page gives 302 redirects.
After that, the hydra tries to go to this page, but for some reason gets again a 302 redirect. In the end, it ends in an endless cycle.

The problem is that such an attempt is not marked as successful. I've already spent about 5 hours experimenting with all the possible settings of the script in order to achieve the success of password selection

Is it possible to somehow get the desired match of the text from the response header, for example (Location: http://newpage.com)? And to stop the redirect cycle, because the attempt is already successful.
And maybe there is some other solution to the problem?
Now, as far as I understand, until the redirection does not end, the hydra does not verify the coincidence of the text.

The problem was formed with the selection of the http form.

**Comment by deret00000** [comment]
The problem was formed with the selection of the http form.

**Comment by vanhauser-thc** [comment]
are you using the current state from the repository? if not try it please as there was a fix.
the match for success/failure string can be from anything, http header or body.

**Comment by deret00000** [comment]
thntx. you are right. I have old version app
