### ISSUE TITLE
continuation mode with proxies list

### ISSUE THREAD

**Issue by deret00000** [vanhauser-thc/thc-hydra#290]
1) I started the hydra with the http proxylist.
Then in the process of work began to appear these lines:

> Process 3505: Can not connect [unreachable], retrying (1 of 1 retries)
> Process 3505: Can not connect [unreachable]
> [ERROR] Child with pid 3505 terminating, can not connect

As I understand it, part of the proxies from the list was not working. What does a hydra do if it is impossible to get an answer through a proxy? Does Hydra try to make a new request from the next proxy list? Or is the current request unsuccessful due to a non-working proxy?

2) Then I stopped the search of passwords and cleaned the list of proxies. And launched app with the command -R.
 As a result, the hydra began to work without any proxies at all. Is this a bug?

**Comment by vanhauser-thc** [comment]
1. no the login/password pairs are not lost. but unavailable proxies will slow down the scanning a lot, so clean before start.

2. no, proxies are not in the restore file as you might need to change them (see 1. for example) - they are only used if you supply them in the environment.
if you did supply them in the environment and used -R and they were not used - then its a bug.
