### ISSUE TITLE
Hydra finds login with oddly charactered password

### ISSUE THREAD

**Issue by alaaemad15** [vanhauser-thc/thc-hydra#293]
For some reason while attempting http-get, hydra returns this after a while [80][http-get-form] host: xxx.com   login: admin   password: ¿Êî?véTíZ¨oî£¤
I am using the rockyou password list.

**Comment by vanhauser-thc** [comment]
how should I fix this bug with this little information? seriously.
which version are you using? if it is not the newest - use the newest.
I need the full command line
I need the first 10 lines of the output generated
I need the lines around where this weird password is printed.

best add the -d switch for debug output (and dont post everything - that would be too much)

**Comment by vanhauser-thc** [comment]
8.1 is outdated, so use the newest version.
