### ISSUE TITLE
The oracle module didn't work properly

### ISSUE THREAD

**Issue by anti-decoy** [vanhauser-thc/thc-hydra#295]
I compile hydra with oracle instantclient 12.2.  But when I test the oracle module, it can't work.

[root@localhost bin]# ./hydra -l SYS -p password oracle://172.16.102.9/MYSID
Hydra v8.5 (c) 2017 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2017-12-28 13:53:25
[DATA] max 1 task per 1 server, overall 1 tasks, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking service oracle on port 1521
[DATA] with additional data MYSID
[ERROR] ORACLE SID is not valid, you should try to enumerate them.
1 of 1 target completed, 0 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2017-12-28 13:53:25

[root@localhost bin]# ./hydra -l MYSID oracle-sid://172.16.102.9
Hydra v8.5 (c) 2017 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2017-12-28 13:55:46
[DATA] max 1 task per 1 server, overall 1 tasks, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking service oracle-sid on port 1521
[1521][oracle-sid] host: 172.16.102.9   login: MYSID
1 of 1 target successfully completed, 1 valid password found
Hydra (http://www.thc.org/thc-hydra) finished at 2017-12-28 13:55:47

**Comment by vanhauser-thc** [comment]
1st - current version is 8.6 - but this will not change your problem.

can you please show that it is actually working? like with sqlplus?

**Comment by anti-decoy** [comment]
I can connect to oracle server by sqlplus using the same sid.

**Comment by vanhauser-thc** [comment]
weird.
without access to the server i can not debug/fix the issue.
you would need to check what the problem is ...

**Comment by anti-decoy** [comment]
I found that was when calling the Ocilogon function to connect with oracle, it return ORA-12514.  
So I search it by google,  I got this solution, is it?
https://stackoverflow.com/questions/24758806/ocilogon-error-ora-12514

**Comment by vanhauser-thc** [comment]
that page is about php ...

with your changed code it does work with your database?

My guess is actually that it has nothing to do with hydra, but that your sqlplus command line uses that in your tnsnames.ora file which lists a service entry for the database, and that if you would use that service entry (e.g. foo.dbservice.bar or whatever is in there) for hydra's SID option it would work.

so:
example tnsnames.ora entry:

(DESCRIPTION =
  (ADDRESS_LIST =
    (ADDRESS = (PROTOCOL = TCP)(HOST = myHostname)(PORT = 1521))
  )
  (CONNECT_DATA =
    (SERVICE_NAME = mySID.whereever.com)
    (SID = mySID)
    (SERVER = DEDICATED)
  )
)

give mySID.whereever.com to hydra

**Comment by vanhauser-thc** [comment]
@anti-decoy did you test my recommendation?
