### ISSUE TITLE
hotmail recovery email password hack

### ISSUE THREAD

**Issue by beyqusey** [vanhauser-thc/thc-hydra#297]
I'm writing with google translation

Is there a Hydra program that I can use 7-digit password trial and error system that sends hotmail to e-mail address to recover?
if there is a video link to the construction

**Comment by vvv87** [comment]
have a look@this: http://textmechanic.com/text-tools/combination-permutation-tools/permutation-generator/.   I had your similar issue and I’ve used it to generate a small list of permutations to use on hydra as a password list; you may want to have a look to this too(I think is already in kali if you are using Linux). https://null-byte.wonderhowto.com/how-to/hack-like-pro-crack-passwords-part-4-creating-custom-wordlist-with-crunch-0156817/


I wish I helped you
Sweet

**Comment by azimkhan2020** [comment]
My hotmail account get hacked and its a old id.i dont have any information. im trying to recover with security question bt i cant back my mail..
any one please help me to get this account. or give me any idea, how to get back my mail
