### ISSUE TITLE
hydra(pls refer to the previous issue      vvv87)

### ISSUE THREAD

**Issue by vvv87** [vanhauser-thc/thc-hydra#298]
hi!!THANKS SO MUCH 4 the prompt replay!!.....I gave up my family weekend trip 2 get back 2 my Kali and try to sort it out and....here I am: so basically I've followed through your steps and I've ended up with Hydra v8.7( which is great !!)...the only thing is that i keep having the same issue: as soon as I initialize it, it just freezes(I mean the cursor on the console is blinking but no outputs at all)....no signs whatsover.....and the same thing about the CPU usage, still @ 100%;
so this is the command I run:

hydra smtp.gmail.com smtp -l *********@gmail.com -P /root/Desktop/password/ -s 465 -S -v -V

and this is what I get:

root@vvv87:~# hydra smtp.gmail.com smtp -l ********@gmail.com -P /root/Desktop/password/ -s 465 -S -v -V
Hydra v8.7-dev (c) 2018 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

[WARNING] hydra was compiled without SSL support. Install openssl and recompile! Option ignored...
Hydra (http://www.thc.org/thc-hydra) starting at 2018-01-05 17:29:18
[INFO] several providers have implemented cracking protection, check with a small wordlist first - and stay legal!
[WARNING] Google Mail has bruteforce detection and sends false positives. You are not doing anything illegal right?!

here is my scrnshot:

![for github](https://user-images.githubusercontent.com/35132421/34651390-5c569842-f395-11e7-83b5-32f010cbc0f7.jpeg)

PS: I've just noticed the the [WARNING] hydra was compiled without SSL support. Install openssl and recompile!.........this kind of warning was not present in the previous version(v8.6.1) i was running.....it was something else i don't really remember!......however I keep getting the same outcome and got stucked in here.
I have no idea where else I can put my hands on.

If there is anything I can provide you for further analysis on the matter please let me know. I really appreciate your help
@vvv87
vvv87 commented 2 days ago

I FORGOT THIS......

![forgotthis](https://user-images.githubusercontent.com/35132421/34651392-6e9c6310-f395-11e7-9378-403fcb8f58ab.jpeg)

**Comment by vanhauser-thc** [comment]
this is not a help forum.
this is solely to report bugs.
go here for help: http://forums.kali.org/

without compiling it with openssl you wont get far and testing gmail will be unsuccessful:
[WARNING] Google Mail has bruteforce detection and sends false positives.
