### ISSUE TITLE
After  installed the "libssh-0.4.8" , get an error when i compile hydra

### ISSUE THREAD

**Issue by zuisengxw** [vanhauser-thc/thc-hydra#299]
My OS: CentOS Linux release 7.4.1708 (Core) 
kernel version: 4.14.7-1.el7.elrepo.x86_64
hydra version : 8.6
hydra-svn.c: In function ‘start_svn’:
hydra-svn.c:86:12: warning: assignment makes pointer from integer without a cast [enabled by default]
   if ((err = svn_client_create_context2(&ctx, NULL, pool))) {
            ^
hydra-svn.c:110:102: error: ‘svn_client_list_func2_t’ undeclared (first use in this function)
   err = svn_client_list3(canonical, &revision, &revision, svn_depth_unknown, dirents, FALSE, FALSE, (svn_client_list_func2_t) print_dirdummy, NULL, ctx, pool);
                                                                                                      ^
hydra-svn.c:110:102: note: each undeclared identifier is reported only once for each function it appears in
hydra-svn.c:110:127: error: expected ‘)’ before ‘print_dirdummy’
   err = svn_client_list3(canonical, &revision, &revision, svn_depth_unknown, dirents, FALSE, FALSE, (svn_client_list_func2_t) print_dirdummy, NULL, ctx, pool);
                                                                                                                               ^
make: *** [hydra-svn.o] Error 1

**Comment by zuisengxw** [comment]
/configure --debug

Starting hydra auto configuration ...
Detected 64 Bit Linux OS

Checking for zlib (libz.so, zlib.h) ...
                                        ... found
Checking for openssl (libssl, libcrypto, ssl.h, sha.h) ...
DEBUG: SSL_LIB=hwcap 1 nosegneg include ld.so.conf.d/*.conf /usr/lib64/dyninst /usr/lib64/heimdal /usr/lib64/mysql /usr/lib64/xulrunner /usr/local/lib /usr/local/ssl/lib /lib64 /usr/lib64 /usr/local/lib64 /opt/local/lib64 /lib /usr/lib /usr/local/lib /opt/local/lib /usr/local/ssl /usr/local/ssl/lib
DEBUG: SSL_INC=/usr/include /usr/local/include /opt/include /opt/local/include /usr/local/ssl/include
DEBUG: SSL_PATH=/usr/local/ssl/lib/libssl
DEBUG: CRYPTO_PATH=/usr/local/ssl/lib/libcrypto
DEBUG: SSL_INC=/usr/include/openssl/ssl.h
                                                       ... found
Checking for gcrypt (libgcrypt.so) ...
                                        ... gcrypt not found, radmin2 module disabled
Checking for idn (libidn.so) ...
DEBUG: IDN_PATH=/libidn
DEBUG: IDN_IPATH=/stringprep.h
DEBUG: PR29_IPATH=/pr29.h
                             ... NOT found, unicode logins and passwords will not be supported
Checking for curses (libcurses.so / term.h) ...
DEBUG: CURSES_PATH=/lib64/libcurses
DEBUG: CURSES_IPATH=/usr/include/ncurses/term.h
                                            ... found, color output enabled
Checking for pcre (libpcre.so, pcre.h) ...
DEBUG: PCRE_PATH=/lib64/libpcre
DEBUG: PCRE_IPATH=/usr/include/pcre.h
                                       ... found
Checking for Postgres (libpq.so, libpq-fe.h) ...
DEBUG: POSTGRES_PATH=/lib64/libpq
DEBUG: POSTGRES_IPATH=/usr/include/libpq-fe.h
                                             ... found
Checking for SVN (libsvn_client-1 libapr-1.so libaprutil-1.so) ...
DEBUG: SVN_PATH=/lib64/libsvn_client-1
DEBUG: APR_PATH=/lib64/libapr
DEBUG: SVN_IPATH=/usr/include/apr-1/
DEBUG: APR_IPATH=/usr/include/apr-1/
                                                               ... found
Checking for firebird (libfbclient.so) ...
DEBUG: FIREBIRD_PATH=/libfbclient
DEBUG: FIREBIRD_IPATH=/ibase.h
                                       ... NOT found, module firebird disabled
Checking for MYSQL client (libmysqlclient.so, math.h) ...
DEBUG: MYSQL_PATH=/usr/lib64/mysql/libmysqlclient
DEBUG: MYSQL_IPATH=/mysql.h
                                                      ... NOT found, module Mysql will not support version > 4.x
Checking for AFP (libafpclient.so) ...
DEBUG: AFP_PATH=/libafpclient
DEBUG: AFP_IPATH=/afp.h
                                   ... NOT found, module Apple Filing Protocol disabled - Apple sucks anyway
Checking for NCP (libncp.so / nwcalls.h) ...
DEBUG: NCP_PATH=/libncp
DEBUG: NCP_IPATH=/ncp/nwcalls.h
                                         ... NOT found, module NCP disabled
Checking for SAP/R3 (librfc/saprfc.h) ...
DEBUG: SAPR3_PATH=hwcap/librfc
DEBUG: SAPR3_IPATH=/saprfc.h
                                      ... NOT found, module sapr3 disabled
Get it from http://www.sap.com/solutions/netweaver/linux/eval/index.asp
Checking for libssh (libssh/libssh.h) ...
DEBUG: SSH_PATH=/lib64/libssh
DEBUG: SSH_IPATH=/usr/include/libssh/libssh.h
                                      ... found
Checking for Oracle (libocci.so libclntsh.so / oci.h and libaio.so) ...
DEBUG: ORACLE_LIB=hwcap 1 nosegneg include ld.so.conf.d/*.conf /usr/lib64/dyninst /usr/lib64/heimdal /usr/lib64/mysql /usr/lib64/xulrunner /usr/local/lib /usr/local/ssl/lib /lib64 /usr/lib64 /usr/local/lib64 /opt/local/lib64 /lib /usr/lib /usr/local/lib /opt/local/lib
DEBUG: ORACLE_INC=/usr/include /usr/local/include /opt/include /opt/local/include
DEBUG: ORACLE_PATH=/libocci
DEBUG: ORACLE_PATH=/libaio
DEBUG: ORACLE_IPATH=/oci.h
                                                                    ... NOT found, module Oracle disabled
Get basic and sdk package from http://www.oracle.com/technetwork/database/features/instant-client/index.html
Checking for GUI req's (pkg-config, gtk+-2.0) ...
                                              ... NOT found, optional anyway
Checking for Android specialities ...
                                  ... strrchr() found
                                  ... RSA_generate_key() found
Checking for secure compile option support in gcc ...
                                                  Compiling... yes
                                                  Linking... yes

Hydra will be installed into .../bin of: /usr/local
  (change this by running ./configure --prefix=path)

DEBUG: XDEFINES= -DLIBOPENSSL -DLIBNCURSES -DHAVE_PCRE -DLIBPOSTGRES -DLIBSVN -DLIBSSH -DHAVE_ZLIB -DHAVE_MATH_H
DEBUG: XLIBS= -lz -lcurses -lssl -lpcre -lpq -lsvn_client-1 -lapr-1 -laprutil-1 -lsvn_subr-1 -lssh -lcrypto
DEBUG: XLIBPATHS=-L/usr/lib -L/usr/local/lib -L/lib -L/usr/local/ssl/lib -L/lib64 -L/usr/local/ssl/lib -L/lib64
DEBUG: XIPATHS= -I/usr/include/ncurses -I/usr/include -I/usr/include -I/usr/include/subversion-1 -I/usr/include/apr-1 -I/usr/include/subversion-1
DEBUG: PREFIX=/usr/local
DEBUG: XHYDRA_SUPPORT=
DEBUG: STRIP=strip
Writing Makefile.in ...
now type "make"

**Comment by vanhauser-thc** [comment]
the error shows that libsvn is the problem, not libssh.

if - after running ./configure - you remove -DLIBSVN from the Makefile, you should be able to compile.

I have no clue why hydra-svn is not compiling though.

can you please send the output of

rpm -qa|grep svn

(centos has rpm, right?)

**Comment by zuisengxw** [comment]
rpm -qa | grep svn

texlive-babelbib-svn25245.1.31-38.el7.noarch
texlive-luaotfload-svn26718.1.26-38.el7.noarch
texlive-eso-pic-svn21515.2.0c-38.el7.noarch
texlive-ms-svn24467.0-38.el7.noarch
texlive-pst-fill-svn15878.1.01-38.el7.noarch
texlive-pstricks-svn29678.2.39-38.el7.noarch
texlive-ctable-svn26694.1.23-38.el7.noarch
texlive-metalogo-svn18611.0.12-38.el7.noarch
texlive-typehtml-svn17134.0-38.el7.noarch
texlive-collection-fontsrecommended-svn28082.0-38.20130427_r30134.el7.noarch
texlive-hyphen-base-svn29197.0-38.el7.noarch
texlive-amsfonts-svn29208.3.04-38.el7.noarch
texlive-pdftex-svn29585.1.40.11-38.el7.noarch
texlive-subfig-svn15878.1.3-38.el7.noarch
texlive-index-svn24099.4.1beta-38.el7.noarch
texlive-latexconfig-svn28991.0-38.el7.noarch
texlive-texconfig-bin-svn27344.0-38.20130427_r30134.el7.noarch
texlive-glyphlist-svn28576.0-38.el7.noarch
texlive-mflogo-svn17487.0-38.el7.noarch
texlive-crop-svn15878.1.5-38.el7.noarch
texlive-zapfchan-svn28614.0-38.el7.noarch
texlive-tex-gyre-math-svn29045.0-38.el7.noarch
texlive-etex-svn22198.2.1-38.el7.noarch
texlive-pspicture-svn15878.0-38.el7.noarch
texlive-chngcntr-svn17157.1.0a-38.el7.noarch
texlive-filecontents-svn24250.1.3-38.el7.noarch
texlive-fancybox-svn18304.1.4-38.el7.noarch
texlive-algorithms-svn15878.0.1-38.el7.noarch
texlive-thumbpdf-svn26689.3.15-38.el7.noarch
texlive-filehook-svn24280.0.5d-38.el7.noarch
texlive-l3packages-svn29361.SVN_4467-38.el7.noarch
texlive-pst-grad-svn15878.1.06-38.el7.noarch
texlive-unicode-math-svn29413.0.7d-38.el7.noarch
texlive-seminar-svn18322.1.5-38.el7.noarch
texlive-jknapltx-svn19440.0-38.el7.noarch
texlive-xdvi-svn26689.22.85-38.el7.noarch
texlive-kpathsea-svn28792.0-38.el7.noarch
texlive-xkeyval-svn27995.2.6a-38.el7.noarch
texlive-carlisle-svn18258.0-38.el7.noarch
texlive-latex-fonts-svn28888.0-38.el7.noarch
texlive-plain-svn26647.0-38.el7.noarch
texlive-dvipdfm-svn26689.0.13.2d-38.el7.noarch
texlive-enumitem-svn24146.3.5.2-38.el7.noarch
texlive-footmisc-svn23330.5.5b-38.el7.noarch
texlive-qstest-svn15878.0-38.el7.noarch
texlive-cm-svn29581.0-38.el7.noarch
texlive-type1cm-svn21820.0-38.el7.noarch
texlive-mdwtools-svn15878.1.05.4-38.el7.noarch
texlive-sepnum-svn20186.2.0-38.el7.noarch
texlive-helvetic-svn28614.0-38.el7.noarch
texlive-utopia-svn15878.0-38.el7.noarch
texlive-ifluatex-svn26725.1.3-38.el7.noarch
texlive-varwidth-svn24104.0.92-38.el7.noarch
texlive-bera-svn20031.0-38.el7.noarch
texlive-thumbpdf-bin-svn6898.0-38.20130427_r30134.el7.noarch
texlive-xcolor-svn15878.2.11-38.el7.noarch
texlive-listings-svn15878.1.4-38.el7.noarch
texlive-pst-text-svn15878.1.00-38.el7.noarch
texlive-oberdiek-svn26725.0-38.el7.noarch
texlive-pst-slpe-svn24391.1.31-38.el7.noarch
texlive-ae-svn15878.1.4-38.el7.noarch
texlive-kpathsea-bin-svn27347.0-38.20130427_r30134.el7.x86_64
texlive-ifxetex-svn19685.0.5-38.el7.noarch
texlive-colortbl-svn25394.v1.0a-38.el7.noarch
texlive-dvips-bin-svn26509.0-38.20130427_r30134.el7.x86_64
texlive-tex-bin-svn26912.0-38.20130427_r30134.el7.x86_64
texlive-dvipdfm-bin-svn13663.0-38.20130427_r30134.el7.noarch
texlive-makeindex-bin-svn26509.0-38.20130427_r30134.el7.x86_64
texlive-gsftopk-svn26689.1.19.2-38.el7.noarch
texlive-fancyref-svn15878.0.9c-38.el7.noarch
texlive-eurosym-svn17265.1.4_subrfix-38.el7.noarch
texlive-ntgclass-svn15878.0-38.el7.noarch
texlive-lua-alt-getopt-svn29349.0.7.0-38.el7.noarch
texlive-pst-math-svn20176.0.61-38.el7.noarch
texlive-wasysym-svn15878.2.0-38.el7.noarch
texlive-kastrup-svn15878.0-38.el7.noarch
texlive-beton-svn15878.0-38.el7.noarch
texlive-marginnote-svn25880.v1.1i-38.el7.noarch
texlive-babel-svn24756.3.8m-38.el7.noarch
texlive-tipa-svn29349.1.3-38.el7.noarch
texlive-luatexbase-svn22560.0.31-38.el7.noarch
texlive-hyperref-svn28213.6.83m-38.el7.noarch
texlive-pgf-svn22614.2.10-38.el7.noarch
texlive-pst-3d-svn17257.1.10-38.el7.noarch
texlive-koma-script-svn27255.3.11b-38.el7.noarch
texlive-fontspec-svn29412.v2.3a-38.el7.noarch
texlive-pst-coil-svn24020.1.06-38.el7.noarch
texlive-pstricks-add-svn28750.3.59-38.el7.noarch
texlive-breakurl-svn15878.1.30-38.el7.noarch
texlive-latex-bin-bin-svn14050.0-38.20130427_r30134.el7.noarch
texlive-tex-gyre-svn18651.2.004-38.el7.noarch
texlive-powerdot-svn25656.1.4i-38.el7.noarch
texlive-pdfpages-svn27574.0.4t-38.el7.noarch
texlive-beamer-svn29349.3.26-38.el7.noarch
texlive-ltxmisc-svn21927.0-38.el7.noarch
texlive-collection-basic-svn26314.0-38.20130427_r30134.el7.noarch
xmlrpc-c-client-1.32.5-1905.svn2451.el7.x86_64
texlive-collection-latexrecommended-svn25795.0-38.20130427_r30134.el7.noarch
texlive-graphics-svn25405.1.0o-38.el7.noarch
texlive-tools-svn26263.0-38.el7.noarch
texlive-etex-pkg-svn15878.2.0-38.el7.noarch
texlive-etoolbox-svn20922.2.1-38.el7.noarch
texlive-pdftex-bin-svn27321.0-38.20130427_r30134.el7.x86_64
texlive-multido-svn18302.1.42-38.el7.noarch
texlive-dvips-svn29585.0-38.el7.noarch
texlive-metafont-bin-svn26912.0-38.20130427_r30134.el7.x86_64
texlive-tex-svn26689.3.1415926-38.el7.noarch
texlive-texlive.infra-bin-svn22566.0-38.20130427_r30134.el7.x86_64
texlive-dvipdfmx-def-svn15878.0-38.el7.noarch
texlive-mfware-svn26689.0-38.el7.noarch
texlive-makeindex-svn26689.2.12-38.el7.noarch
texlive-bibtex-bin-svn26509.0-38.20130427_r30134.el7.x86_64
texlive-gsftopk-bin-svn26509.0-38.20130427_r30134.el7.x86_64
texlive-euro-svn22191.1.1-38.el7.noarch
texlive-txfonts-svn15878.0-38.el7.noarch
texlive-rsfs-svn15878.0-38.el7.noarch
texlive-sauerj-svn15878.0-38.el7.noarch
texlive-sansmath-svn17997.1.1-38.el7.noarch
texlive-cmap-svn26568.0-38.el7.noarch
texlive-soul-svn15878.2.4-38.el7.noarch
texlive-palatino-svn28614.0-38.el7.noarch
texlive-cmextra-svn14075.0-38.el7.noarch
texlive-fpl-svn15878.1.002-38.el7.noarch
texlive-charter-svn15878.0-38.el7.noarch
texlive-enctex-svn28602.0-38.el7.noarch
texlive-ifetex-svn24853.1.2-38.el7.noarch
texlive-avantgar-svn28614.0-38.el7.noarch
texlive-textcase-svn15878.0-38.el7.noarch
texlive-parallel-svn15878.0-38.el7.noarch
texlive-pslatex-svn16416.0-38.el7.noarch
texlive-mathpazo-svn15878.1.003-38.el7.noarch
texlive-collection-documentation-base-svn17091.0-38.20130427_r30134.el7.noarch
texlive-xunicode-svn23897.0.981-38.el7.noarch
texlive-geometry-svn19716.5.6-38.el7.noarch
texlive-currfile-svn29012.0.7b-38.el7.noarch
texlive-lualatex-math-svn29346.1.2-38.el7.noarch
texlive-pst-eps-svn15878.1.0-38.el7.noarch
texlive-amscls-svn29207.0-38.el7.noarch
texlive-pst-blur-svn15878.2.0-38.el7.noarch
texlive-ucs-svn27549.2.1-38.el7.noarch
texlive-xdvi-bin-svn26509.0-38.20130427_r30134.el7.x86_64
xmlrpc-c-1.32.5-1905.svn2451.el7.x86_64
texlive-amsmath-svn29327.2.14-38.el7.noarch
texlive-psnfss-svn23394.9.2a-38.el7.noarch
texlive-fp-svn15878.0-38.el7.noarch
texlive-metafont-svn26689.2.718281-38.el7.noarch
texlive-setspace-svn24881.6.7a-38.el7.noarch
texlive-mfware-bin-svn26509.0-38.20130427_r30134.el7.x86_64
texlive-float-svn15878.1.3d-38.el7.noarch
texlive-csquotes-svn24393.5.1d-38.el7.noarch
texlive-marvosym-svn29349.2.2a-38.el7.noarch
texlive-parskip-svn19963.2.0-38.el7.noarch
texlive-courier-svn28614.0-38.el7.noarch
texlive-zapfding-svn28614.0-38.el7.noarch
texlive-section-svn20180.0-38.el7.noarch
texlive-anysize-svn15878.0-38.el7.noarch
texlive-rcs-svn15878.0-38.el7.noarch
texlive-misc-svn24955.0-38.el7.noarch
texlive-luatex-bin-svn26912.0-38.20130427_r30134.el7.x86_64
texlive-luaotfload-bin-svn18579.0-38.20130427_r30134.el7.noarch
texlive-attachfile-svn21866.v1.5b-38.el7.noarch
texlive-showexpl-svn27790.v0.3j-38.el7.noarch
texlive-fancyvrb-svn18492.2.8-38.el7.noarch
texlive-pst-tree-svn24142.1.12-38.el7.noarch
texlive-rotating-svn16832.2.16b-38.el7.noarch
texlive-l3experimental-svn29361.SVN_4467-38.el7.noarch
texlive-cm-super-svn15878.0-38.el7.noarch
texlive-scheme-basic-svn25923.0-38.20130427_r30134.el7.noarch
texlive-tetex-bin-svn27344.0-38.20130427_r30134.el7.noarch
texlive-booktabs-svn15878.1.61803-38.el7.noarch
texlive-lm-svn28119.2.004-38.el7.noarch
texlive-mptopdf-bin-svn18674.0-38.20130427_r30134.el7.noarch
texlive-euler-svn17261.2.5-38.el7.noarch
texlive-underscore-svn18261.0-38.el7.noarch
texlive-texconfig-svn29349.0-38.el7.noarch
texlive-dvipdfmx-bin-svn26509.0-38.20130427_r30134.el7.x86_64
texlive-wasy-svn15878.0-38.el7.noarch
texlive-psfrag-svn15878.3.04-38.el7.noarch
texlive-bookman-svn28614.0-38.el7.noarch
texlive-fix2col-svn17133.0-38.el7.noarch
texlive-paralist-svn15878.2.3b-38.el7.noarch
texlive-symbol-svn28614.0-38.el7.noarch
texlive-hyph-utf8-svn29641.0-38.el7.noarch
texlive-pdftex-def-svn22653.0.06d-38.el7.noarch
texlive-times-svn28614.0-38.el7.noarch
texlive-luatex-svn26689.0.70.1-38.el7.noarch
texlive-memoir-svn21638.3.6j_patch_6.0g-38.el7.noarch
texlive-latex-svn27907.0-38.el7.noarch
texlive-pst-node-svn27799.1.25-38.el7.noarch
texlive-l3kernel-svn29409.SVN_4469-38.el7.noarch
texlive-pst-plot-svn28729.1.44-38.el7.noarch
texlive-latex-bin-svn26689.0-38.el7.noarch
texlive-mh-svn29420.0-38.el7.noarch
texlive-extsizes-svn17263.1.4a-38.el7.noarch
texlive-collection-latex-svn25030.0-38.20130427_r30134.el7.noarch
texlive-tetex-svn29585.3.0-38.el7.noarch
texlive-url-svn16864.3.2-38.el7.noarch
texlive-caption-svn29026.3.3__2013_02_03_-38.el7.noarch
texlive-mptopdf-svn26689.0-38.el7.noarch
texlive-texlive.infra-svn28217.0-38.el7.noarch
texlive-natbib-svn20668.8.31b-38.el7.noarch
texlive-bibtex-svn26689.0.99d-38.el7.noarch
texlive-dvipdfmx-svn26765.0-38.el7.noarch
texlive-pxfonts-svn15878.0-38.el7.noarch
texlive-microtype-svn29392.2.5-38.el7.noarch
texlive-mparhack-svn15878.1.4-38.el7.noarch
texlive-fancyhdr-svn15878.3.1-38.el7.noarch
texlive-mfnfss-svn19410.0-38.el7.noarch
texlive-ncntrsbk-svn28614.0-38.el7.noarch
texlive-ec-svn25033.1.0-38.el7.noarch
texlive-cite-svn19955.5.3-38.el7.noarch
texlive-lm-math-svn29044.1.958-38.el7.noarch

**Comment by zuisengxw** [comment]
After remove DLIBSVN from the Makefile, compile success.  thank you!

**Comment by zuisengxw** [comment]
If I installed the libssh-0.7.5, didn't get the error when I compile hydra

**Comment by vanhauser-thc** [comment]
can you please send also the output of
  rpm -qa|grep subversion
? 
I think I got the package name for your system wrong.

**Comment by zuisengxw** [comment]
rpm -qa | grep subversion
subversion-libs-1.7.14-11.el7_4.x86_64
subversion-devel-1.7.14-11.el7_4.x86_64
subversion-1.7.14-11.el7_4.x86_64
