### ISSUE TITLE
What is the mean of " ~0 tries per task" ?

### ISSUE THREAD

**Issue by adibikar** [vanhauser-thc/thc-hydra#300]
I use hydra with default option `-t 16`, and it says:
`[DATA] max 16 tasks per 1 server, overall 16 tasks, 192 login tries (l:16/p:12), ~0 tries per task`
And I try with option `-t 1`, and it says:
`[DATA] max 1 task per 1 server, overall 1 tasks, 192 login tries (l:16/p:12), ~192 tries per task`
What I has been understood is:
`[DATA] max x task per 1 server, overall 1 tasks`: Hydra sent login-data to server x thread at once. If it more than 1, so Hydra create more child, am I right ?
`192 login tries (l:16/p:12)`: This is just the number my lists.
`~y tries per task`: I don't get with this. I think each child is trying to sent login-data to server. Why it's says `~0 tries per task` ? O_o

**Comment by vanhauser-thc** [comment]
This is not what is happening for me:

[DATA] max 16 tasks per 1 server, overall 16 tasks, 192 login tries (l:16/p:12), ~12 tries per task

so my guess is you have an old version? (current is 8.6)

**Comment by adibikar** [comment]
It works!! Thank you. I remove 8.6 version and following your steps in issue/247. Now I get 8.7-dev version of hydra.

> [DATA] max 16 tasks per 1 server, overall 16 tasks, 192 login tries (l:16/p:0), ~12 tries per task

I think there are 2 issues with this version or because this is still under development:
1. I use -P passlist. Where my passlist contain 12 passwords. but it print  zero `(l:16/p:0)`.
2. In older version when username and password match it will be printed with color red and green. But in this version it does not. So if I use -V there are white color print out to the terminal.
Thank you @vanhauser-thc

**Comment by vanhauser-thc** [comment]
as you can see from my pasting I did the same but it correctly shows p:12
as it has to be the same repository state I have no clue what the issue is for you.

can you please paste the output of:

uname -a

and your hydra command line you are using and the full output? Please change the host to 127.0.0.1 and add the -v switch.

**Comment by adibikar** [comment]
I use 32bit [Bunsen OS](https://www.bunsenlabs.org/). `uname -a`:
`Linux labz 3.16.0-5-686-pae #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) i686 GNU/Linux`. `labz` is just my hostname. And here my hydra command:
```
hydra 127.0.0.1 -v -L userlist -P passlist http-get-form "/dvwa/vulnerabilities/brute/:\
username=^USER^&password=^PASS^&Login=Login:S=Welcome:\
H=Cookie: PHPSESSID=$sess; security=low"
```
and the output:
```
Hydra v8.7-dev (c) 2018 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2018-01-23 21:09:39
[DATA] max 16 tasks per 1 server, overall 16 tasks, 192 login tries (l:16/p:0), ~12 tries per task
[DATA] attacking http-get-form://127.0.0.1:80/dvwa/vulnerabilities/brute/:username=^USER^&password=^PASS^&Login=Login:S=Welcome:H=Cookie: PHPSESSID=ejmv7u5k5ubudrprbgarh2s4n3; security=low
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[80][http-get-form] host: 127.0.0.1   login: admin   password: password
[80][http-get-form] host: 127.0.0.1   login: gordonb   password: abc123
[80][http-get-form] host: 127.0.0.1   login: 1337   password: charley
[80][http-get-form] host: 127.0.0.1   login: pablo   password: letmein
[80][http-get-form] host: 127.0.0.1   login: smithy   password: password
[STATUS] attack finished for 127.0.0.1 (waiting for children to complete tests)
1 of 1 target successfully completed, 5 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2018-01-23 21:09:59
```
5 true user and pass found, but with white color print out as you can see [here](https://i.imgur.com/P5m4rIM.png).
