### ISSUE TITLE
Automatic update hydra in Ubuntu 16.04

### ISSUE THREAD

**Issue by AiratHalitov** [vanhauser-thc/thc-hydra#301]
Hi!

Can anyone update hydra in official ubuntu's repository? 
Or how can I update hydra with using ppa repository? 

Ubuntu 16.04
hydra 8.1

**Comment by AiratHalitov** [comment]
I get an error when i try build version 8.6
```
$ make
...
...
hydra-sip.c:302:1: error: unknown type name ‘int32_t’
 int32_t service_sip_init(char *ip, int32_t sp, unsigned char options, char *miscptr, FILE * fp, int32_t port, char *hostname) {
 ^
hydra-sip.c:302:36: error: unknown type name ‘int32_t’
 int32_t service_sip_init(char *ip, int32_t sp, unsigned char options, char *miscptr, FILE * fp, int32_t port, char *hostname) {
                                    ^
hydra-sip.c:302:97: error: unknown type name ‘int32_t’
 int32_t service_sip_init(char *ip, int32_t sp, unsigned char options, char *miscptr, FILE * fp, int32_t port, char *hostname) {
```
Version 8.5 installed normal.

**Comment by jugaso** [comment]
For you view my sources.list. good luck

backup your file and paste file on directory

/etc/apt/sources.list

*apt-get update && apt-get upgrade && apt-get install hydra*

""  hydra -v
Hydra v8.1 (c) 2014 by van Hauser/THC - Please do not use in military or
secret service organizations, or for illegal purposes.""


Júlio Gadioli Soares.
jugaso@gmail.com
 _______________________________
/  Nunca encontrei uma companhia tão \
| companheira quanto a solidão             |
\ --Thoreau                                             /
  -------------------------------------------------
      \
        \   ^__^
         \  (oo)\_______
            (__)\              )\/\
                   ||------w  |
                   ||           ||


2018-01-22 14:31 GMT-02:00 Airat Halitov <notifications@github.com>:

**Comment by vanhauser-thc** [comment]
this is the wrong place to ask that. 
for Ubuntu you have to contact the hydra maintainer at Ubuntu, etc etc.
