### ISSUE TITLE
Oracle logins not FOUND.

### ISSUE THREAD

**Issue by JFox77** [vanhauser-thc/thc-hydra#302]
Hi vanhouser,

I downloaded the lastest version of thc-hydra (8.7-dev) from Github, I wanted to use it to brute force oracle credentials. The compilation was a bit weird, calling --with-oracle pointing to my  instant-client folder doesn't work, so I edited the config file and added the following line:

/oracle-instantclient-path -L/oracle-instantclient-path to the following variables:

> ORACLE_PATH
> ORACLE_IPATH
> WORACLE_PATH
> WORACLE_LIB_PATH

Without forcing the -L it worked on the "./configure" telling that all was found, but during compilation it failed saying that oci.h doesn't exist. My LD_LIBRARY_PATH was fine too. I was able to connect with sqlplus on my database without any issues (passing connection string as parameter - no tnsnames.ora).

Anyway, I compiled, just to let you know, maybe you want to provide more guidance for next users or it could help someone to compile (If what I did is correct :).

Below are details of my client and server version and a proof that sqlplus is working perfectly. 

> SQL*Plus: Release 11.2.0.2.0 Production on XXX YYY AB CD:EF:GH IJLM
> 
> Copyright (c) 1982, 2010, Oracle.  All rights reserved.
> 
> 
> Connected to:
> Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
> With the Partitioning, Automatic Storage Management, OLAP, Data Mining
> and Real Application Testing options

From there I executed some queries and all worked perfectly.

I used the current user and password that I know to test hydra-thc and to my surprise, nothing is found, even with a valid credential.

The only thing is that my connection is really slow, with sqlplus it takes like 45 seconds more or less in some cases, when using thc-hydra I see the traffic going and coming back on port 1521 with tcpdump and thc-hydra insist in say that no credential was found - I tested at least 4 times changing options such as -w and -c and no correct results. Between each false negative I connected via sqlplus and confirmed that it was working.

> ./hydra -w 2100 -l TEST -p PwdOracle oracle://127.0.0.1/MyService
> Hydra v8.7-dev (c) 2018 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.
> 
> Hydra (http://www.thc.org/thc-hydra) starting at ABCD-EF-GH IJ:KL:MN
> [DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
> [DATA] attacking oracle://127.0.0.1:1521/MyService
> [STATUS] 1.00 tries/min, 1 tries in 00:01h, 1 to do in 00:01h, 1 active
> 1 of 1 target completed, 0 valid passwords found
> Hydra (http://www.thc.org/thc-hydra) finished at ABCD-EF-GH IJ:KL:MN

The time difference on thc-hydra from start and end was of exactly 1 minute and 3 seconds.

Is the module broken?

Thanks

**Comment by vanhauser-thc** [comment]
Hi,

I checked a few weeks ago and the library should be working without problems.
HOWEVER - it depends on if you know what you are doing.

can you show the full line you use for sqlplus? plus the correspondening lines for that server in your .ora file? you can xxx the password and the IP address if you want.

**Comment by JFox77** [comment]
Hi,

Thanks for quick reply. Sure, below is my sqlplus command line and thy-hydra command-line. BTW, I don't have a tnsnames.ora or sqlnet.ora configured on this client machine, it's not necessary since I can pass all parameters via command-line.

SQLPlus command (working perfectly):

> ./sqlplus TEST/PwdOracle@127.0.0.1:1521/MyService

THC-Hydra command line (not founding valid accounts):

> ./hydra -d -l TEST -p PwdOracle oracle://127.0.0.1/MyService
> Hydra v8.7-dev (c) 2018 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.
> 
> [DEBUG] Output color flag is 0
> Hydra (http://www.thc.org/thc-hydra) starting at 2018-01-26 13:04:37
> [DEBUG] cmdline: ./hydra -d -l TEST -p PwdOracle oracle://127.0.0.1/MyService 
> [DEBUG] opt:6 argc:7 mod:oracle tgt:127.0.0.1 port:0 misc:MyService
> [DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
> [DATA] attacking oracle://127.0.0.1:1521/MyService
> [VERBOSE] Resolving addresses ... 
> [DEBUG] resolving 127.0.0.1
> [VERBOSE] resolving done
> [DEBUG] Code: attack   Time: 1516989877
> [DEBUG] Options: mode 0  ssl 0  restore 0  showAttempt 0  tasks 1  max_use 1 tnp 0  tpsal 0  tprl 0  exit_found 0  miscptr MyService  service oracle
> [DEBUG] Brains: active 0  targets 1  finished 0  todo_all 1  todo 1  sent 0  found 0  countlogin 1  sizelogin 10  countpass 1  sizepass 9
> [DEBUG] Target 0 - target 127.0.0.1  ip 127.0.0.1  login_no 0  pass_no 0  sent 0  pass_state 0  redo_state 0 (0 redos)  use_count 0  failed 0  done 0  fail_count 0  login_ptr TEST  pass_ptr PwdOracle
> [DEBUG] Task 0 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
> [DEBUG] Tasks 1 inactive  0 active
> [DEBUG] child 0 got target 0 selected
> [DEBUG] child 0 spawned for target 0 with pid 46920
> [DEBUG] head_no 0 has pid 46920
> [DEBUG] head_no[0] read n
> [DEBUG] send_next_pair_init target 0, head 0, redo 0, redo_state 0, pass_state 0. loop_mode 0, curlogin (null), curpass (null), tlogin TEST, tpass PwdOracle, logincnt 0/1, passcnt 0/1, loop_cnt 1
> [DEBUG] send_next_pair_mid done 1, pass_state 0, clogin TEST, cpass PwdOracle, tlogin -p, tpass PwdOracle, redo 0
> [ATTEMPT] target 127.0.0.1 - login "TEST" - pass "PwdOracle" - 1 of 1 [child 0] (0/0)
> DEBUG_CONNECT_OK
> [STATUS] 1.00 tries/min, 1 tries in 00:01h, 1 to do in 00:01h, 1 active
> [DEBUG] Code: STATUS   Time: 1516989937
> [DEBUG] Options: mode 0  ssl 0  restore 0  showAttempt 0  tasks 1  max_use 1 tnp 0  tpsal 0  tprl 0  exit_found 0  miscptr MyService  service oracle
> [DEBUG] Brains: active 1  targets 1  finished 0  todo_all 1  todo 1  sent 1  found 0  countlogin 1  sizelogin 10  countpass 1  sizepass 9
> [DEBUG] Target 0 - target 127.0.0.1  ip 127.0.0.1  login_no 1  pass_no 0  sent 1  pass_state 0  redo_state 0 (0 redos)  use_count 1  failed 0  done 0  fail_count 0  login_ptr -p  pass_ptr PwdOracle
> [DEBUG] Task 0 - pid 46920  active 1  redo 0  current_login_ptr TEST  current_pass_ptr PwdOracle
> [DEBUG] Tasks 0 inactive  1 active
> [VERBOSE] database: oracle_error: ORA-12637: Packet receive failed
> 
> [DEBUG] head_no[0] read N
> [STATUS] attack finished for 127.0.0.1 (waiting for children to complete tests)
> [DEBUG] head_no 0, kill 1, fail 0
> [DEBUG] all targets done and all heads finished
> [DEBUG] while loop left with 1
> 1 of 1 target completed, 0 valid passwords found
> [DEBUG] killing all remaining children now that might be stuck

See the ORA-12637, looks like it may be related with time / slow connection, the weird thing is that sqlplus takes a long time but never fails.

I found this:

http://www.dba-oracle.com/t_tns_12637_packet_receive_failed.htm

Just to test, is there a way to tell hydra to retry each attempt before fail for example 5 times? And also set a insane amount of timeout to try avoid ORA-12637?

Any idea / workaround?

Thanks.

**Comment by vanhauser-thc** [comment]
I am still pretty sure that the reason is an .ora definiton that sqlplus is using.
hydra ignores .ora files.

check if you have an tnsnames.ora or sqlnet.ora file and if MyService is specified there.

also, always use a service name (foo.bar.test) and not a SID to connect.

**Comment by JFox77** [comment]
Hi Vanhauser,

Thanks for reply. I don't want to be a pain, but it's not the case. As I mentioned below I'm using a instant client (which doesn't require tnsnames or other oracle files). I installed from a clean install, anyway I'm listing to satisfy your request.

> root@kali:/home/jf/oracle/instantclient# find / -name *.oraa
> root@kali:/home/jf/oracle/instantclient# 

Thanks

**Comment by vanhauser-thc** [comment]
ist not "*.oraa" but "*.ora" you would have to look for.

on the other hand - if that is not the issue, then I have no clue how to resolve this.

have you tried to use the service name instead of the sid?
