### ISSUE TITLE
Decreasing tries/min during brutefrocing http-get 

### ISSUE THREAD

**Issue by ReverseBrain** [vanhauser-thc/thc-hydra#303]
I'm bruteforcing http-get service of a series of IP:PORT stored into a text file. I used the -M switch to enable the multi host feature but I noticed that, during the bruteforcing time, the tries/min decrease.

`[STATUS] 298.00 tries/min, 298 tries in 00:01h, 2376 to do in 00:08h, 64 active`
`[STATUS] 264.00 tries/min, 792 tries in 00:03h, 2383 to do in 00:10h, 64 active`
`[STATUS] 266.43 tries/min, 1865 tries in 00:07h, 2382 to do in 00:09h, 64 active`
`[STATUS] 227.58 tries/min, 2731 tries in 00:12h, 2373 to do in 00:11h, 64 active`
`[STATUS] 195.88 tries/min, 3330 tries in 00:17h, 2374 to do in 00:13h, 64 active`
`[STATUS] 174.77 tries/min, 3845 tries in 00:22h, 2381 to do in 00:14h, 64 active`
`...`
`[STATUS] 102.41 tries/min, 9958 tries in 01:37h, 2167 to do in 00:22h, 64 active`
`[STATUS] 93.82 tries/min, 10999 tries in 01:57h, 2157 to do in 00:23h, 64 active`

Going like that, the bruteforcing is really slow. What can be the problem?

**Comment by vanhauser-thc** [comment]
it is all about how fast the server replies. the tries/min are not the measurement of the last 5 minutes but ther overall amount.

[STATUS] 195.88 tries/min, 3330 tries in 00:17h, 2374 to do in 00:13h, 64 active
[STATUS] 174.77 tries/min, 3845 tries in 00:22h, 2381 to do in 00:14h, 64 active
here you can see that in 5 minutes 515 attempts were made which is 103 tries per minute.

so initially the servers responded fast, but then throttled down.

and as you are testing many in parallel, the first ones might be fast, and the current ones slower
