### ISSUE TITLE
settings.cfg is cleared after reboot NAS

### ISSUE THREAD

**Issue by Miicker** [vanhauser-thc/thc-hydra#305]
Hi everyone,

Yesterday (or the day before), out of the blue, Hydra stopped working. I use Hydra with Medusa and NZBGet. When I wanted to check what was wrong, I could not enter the interface of Hydra, I got this error:
502 Bad Gateway

So I took a look at the config file, and I saw that it was completely empty. I've reinstalled Hydra, restored the settings from a previous backup and had the same problem again. So than I reinstalled Hydra, manually changed all settings, set up new search providers, etc, it seemed to work, I could send downloads when searchin in Hydra to NZBGet and NZBGet would start downloading. But I still had a problem, when I downloaded with Medusa, NZBGet would just keep fetching the file.
After a reboot, the settings.cfg file was empty again. Whatever I do, when I reboot, the settings file is empty again.

I am using Hydra on a Synology NAS in a Docker container behind a reverse proxy. Until l yesterday, or the day before (not sure when) it all worked fine..

Thanks in advance!

**Comment by vanhauser-thc** [comment]
hydra is not using any .cfg file, everything is command line options plus the input files for logins, passwords and targets ...

so I have no clue what you are talking about.

**Comment by Miicker** [comment]
Well, at least on Synology Hydra definitely uses settings.cfg and it does so as long as I remember..

**Comment by vanhauser-thc** [comment]
then what is in this file?

**Comment by Miicker** [comment]
Well, this (I made it anonymous):
`{
    "auth": {
        "authType": "form", 
        "rememberUsers": true, 
        "rememberUsersExpiry": 14, 
        "restrictAdmin": true, 
        "restrictDetailsDl": true, 
        "restrictIndexerSelection": true, 
        "restrictSearch": true, 
        "restrictStats": true, 
        "users": [
            {
                "maySeeAdmin": true, 
                "maySeeDetailsDl": true, 
                "maySeeStats": true, 
                "password": "XXXX", 
                "showIndexerSelection": true, 
                "username": "XXXX"
            }
        ]
    }, 
    "categories": {
        "categories": {
            "anime": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 15000, 
                "min": 50, 
                "newznabCategories": [
                    5070
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "audio": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 2000, 
                "min": 1, 
                "newznabCategories": [
                    3000
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "audiobook": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 1000, 
                "min": 50, 
                "newznabCategories": [
                    3030
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "comic": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 250, 
                "min": 1, 
                "newznabCategories": [
                    7030
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "console": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 40000, 
                "min": 100, 
                "newznabCategories": [
                    1000
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "ebook": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 100, 
                "min": null, 
                "newznabCategories": [
                    7020, 
                    8010
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "flac": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 2000, 
                "min": 10, 
                "newznabCategories": [
                    3040
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "movies": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 20000, 
                "min": 500, 
                "newznabCategories": [
                    2000
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "movieshd": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 20000, 
                "min": 3000, 
                "newznabCategories": [
                    2040, 
                    2050, 
                    2060
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "moviessd": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 3000, 
                "min": 500, 
                "newznabCategories": [
                    2030
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "mp3": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 500, 
                "min": 1, 
                "newznabCategories": [
                    3010
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "pc": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 50000, 
                "min": 100, 
                "newznabCategories": [
                    4000
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "tv": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 5000, 
                "min": 50, 
                "newznabCategories": [
                    5000
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "tvhd": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 4500, 
                "min": 300, 
                "newznabCategories": [
                    5040
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "tvsd": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 1000, 
                "min": 50, 
                "newznabCategories": [
                    5030
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "xxx": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "both", 
                "max": 10000, 
                "min": 100, 
                "newznabCategories": [
                    6000
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }
        }, 
        "enableCategorySizes": true
    }, 
    "downloaders": [
        {
            "downloadType": "nzb", 
            "enabled": true, 
            "host": "192.168.1.XXX", 
            "iconCssClass": "", 
            "name": "NZBGet", 
            "nzbAddingType": "nzb", 
            "nzbaccesstype": "redirect", 
            "password": "XXXX", 
            "port": 33334, 
            "ssl": false, 
            "type": "nzbget", 
            "username": "XXXX"
        }
    ], 
    "indexers": [
        {
            "accessType": "both", 
            "categories": [
                "anime"
            ], 
            "downloadLimit": null, 
            "enabled": true, 
            "generate_queries": true, 
            "hitLimit": 0, 
            "hitLimitResetTime": null, 
            "host": "https://anizb.org", 
            "loadLimitOnRandom": null, 
            "name": "anizb", 
            "password": null, 
            "preselect": true, 
            "score": 0, 
            "searchTypes": [], 
            "search_ids": [], 
            "showOnSearch": true, 
            "timeout": null, 
            "type": "anizb", 
            "username": null
        }, 
        {
            "accessType": "both", 
            "categories": [], 
            "downloadLimit": null, 
            "enabled": true, 
            "hitLimit": 0, 
            "hitLimitResetTime": null, 
            "host": "https://binsearch.info", 
            "loadLimitOnRandom": null, 
            "name": "Binsearch", 
            "password": null, 
            "preselect": true, 
            "score": 0, 
            "searchTypes": [], 
            "search_ids": [], 
            "showOnSearch": true, 
            "timeout": null, 
            "type": "binsearch", 
            "username": null
        }, 
        {
            "accessType": "both", 
            "categories": [], 
            "downloadLimit": null, 
            "enabled": true, 
            "hitLimit": 0, 
            "hitLimitResetTime": null, 
            "host": "https://www.nzbclub.com", 
            "loadLimitOnRandom": null, 
            "name": "NZBClub", 
            "password": null, 
            "preselect": true, 
            "score": 0, 
            "searchTypes": [], 
            "search_ids": [], 
            "showOnSearch": true, 
            "timeout": null, 
            "type": "nzbclub", 
            "username": null
        }, 
        {
            "accessType": "both", 
            "categories": [], 
            "downloadLimit": null, 
            "enabled": true, 
            "generalMinSize": 1, 
            "hitLimit": 0, 
            "hitLimitResetTime": null, 
            "host": "https://nzbindex.com", 
            "loadLimitOnRandom": null, 
            "name": "NZBIndex", 
            "password": null, 
            "preselect": true, 
            "score": 0, 
            "searchTypes": [], 
            "search_ids": [], 
            "showOnSearch": true, 
            "timeout": null, 
            "type": "nzbindex", 
            "username": null
        },
    "main": {
        "apikey": "XXXX", 
        "branch": "master", 
        "configVersion": 40, 
        "debug": false, 
        "dereferer": "http://www.dereferer.org/?$s", 
        "downloadCounterExecuted": true, 
        "externalUrl": "XXXX", 
        "firstStart": 1517514961, 
        "flaskReloader": false, 
        "gitPath": null, 
        "host": "0.0.0.0", 
        "httpProxy": null, 
        "httpsProxy": null, 
        "isFirstStart": false, 
        "keepSearchResultsForDays": 7, 
        "logging": {
            "consolelevel": "INFO", 
            "keepLogFiles": 25, 
            "logIpAddresses": true, 
            "logMaxSize": 1000, 
            "logRotateAfterDays": null, 
            "logfileUmask": "0640", 
            "logfilelevel": "INFO", 
            "logfilename": "nzbhydra.log", 
            "rolloverAtStart": false
        }, 
        "pollShown": 0, 
        "port": 5075, 
        "repositoryBase": "https://github.com/theotherp", 
        "runThreaded": true, 
        "secret": "V543G6A00PNFZ1VZ", 
        "shutdownForRestart": false, 
        "socksProxy": null, 
        "ssl": false, 
        "sslca": null, 
        "sslcert": null, 
        "sslkey": null, 
        "startupBrowser": true, 
        "theme": "grey", 
        "urlBase": null, 
        "useLocalUrlForApiAccess": true, 
        "verifySsl": true
    }, 
    "searching": {
        "alwaysShowDuplicates": false, 
        "applyRestrictions": "both", 
        "duplicateAgeThreshold": 2, 
        "duplicateSizeThresholdInPercent": 1, 
        "forbiddenGroups": null, 
        "forbiddenPosters": null, 
        "forbiddenRegex": null, 
        "forbiddenWords": "", 
        "generate_queries": [
            "internal"
        ], 
        "htmlParser": "html.parser", 
        "idFallbackToTitle": [], 
        "idFallbackToTitlePerIndexer": false, 
        "ignorePassworded": false, 
        "ignoreTemporarilyDisabled": false, 
        "maxAge": "", 
        "nzbAccessType": "redirect", 
        "removeTrailing": ".mp4, .mkv, .subs, .REPOST, repost, ~DG~, .DG, -DG, -1, .1, (1), ReUp, ReUp2, -RP, -AsRequested, -Obfuscated, -Scrambled, -Chamele0n, -BUYMORE, -[TRP], -DG, .par2, .part01, part01.rar, .part02.rar, .jpg, [rartv], [rarbg], [eztv], English, Korean, Spanish, French, German, Italian, Danish, Dutch, Japanese, Cantonese, Mandarin, Russian, Polish, Vietnamese, Swedish, Norwegian, Finnish, Turkish, Portuguese, Flemish, Greek, Hungarian", 
        "requiredRegex": null, 
        "requiredWords": "", 
        "timeout": 20, 
        "userAgent": "NZBHydra"
    }
}`

**Comment by crondaemon** [comment]
@Miicker are you sure you're talking about hydra the password cracker? And not about NZBHydra on synology (https://drfrankenstein.co.uk/2016/08/01/setting-up-nzb-hydra-in-docker-on-a-synology-nas/)?

**Comment by vanhauser-thc** [comment]
yeah what you are looking for is https://github.com/theotherp/nzbhydra - not this repository
