### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by Hritik14** [vanhauser-thc/thc-hydra#307]
I've burp suite running at 127.0.0.1:8080 and I ran hydra with
` HYDRA_PROXY_HTTP='http://127.0.0.1:8080' hydra site.com -l loginID http-form-post '/page/login:username=^USER^&password=^PASS^:F=INVALID:H=Cookie: SESSID=1234' -x 6:6:1`
and in my burp suite window I see nothing. Plain blank.

With hydra verbose I can see
`[VERBOSE] Resolving addresses ... [VERBOSE] resolving done`

and my CPU usage goes to 100% and I cannot see a single HTTP request. I doubt if it is even working.

Hydra v8.6

**Comment by vanhauser-thc** [comment]
can you please post the output of:

HYDRA_PROXY_HTTP='http://127.0.0.1:8080' hydra -vVd -l loginID  -x 6:6:1 'http-form-post://site.com/page/login:username=^USER^&password=^PASS^:F=INVALID:H=Cookie: SESSID=1234'

**Comment by Hritik14** [comment]
My bad. Turns out in my SESSID there was an unescaped colon. I would expect an error or warning in such cases. Maybe add it as a suggestion ?
