### ISSUE TITLE
Some sort of glitch

### ISSUE THREAD

**Issue by gitxmax** [vanhauser-thc/thc-hydra#309]
This often happens, just before the job is complete:
[STATUS] 3257.18 tries/min, 55372 tries in 00:17h, 3815 todo in 00:02h, 48 active
[STATUS] 3167.78 tries/min, 57020 tries in 00:18h, 2167 todo in 00:01h, 44 active
[STATUS] 3059.53 tries/min, 58131 tries in 00:19h, 1056 todo in 00:01h, 42 active
[STATUS] 2962.35 tries/min, 59247 tries in 00:20h, 18446744073709551556 todo in 5124095576030431:01h, 42 active
[STATUS] 2694.59 tries/min, 59281 tries in 00:22h, 18446744073709551522 todo in 5124095576030431:01h, 29 active
That's a long way to go..

Perhaps has something to do with running several instances of Hydra on a single Ubuntu machine?
They all are installed in different subfolders though an each has it's restore file.

**Comment by vanhauser-thc** [comment]
I have seen similar issues with integers going wrong.
it has however nothing to do with running several instances.
which version are you running? are you on x64?

**Comment by gitxmax** [comment]
the latest version, compiled from the source 2 days back, Ubuntu x64

**Comment by dmaciejak** [comment]
Looks to be the same issue reported at https://github.com/vanhauser-thc/thc-hydra/issues/273
