### ISSUE TITLE
Multiplex Hosts

### ISSUE THREAD

**Issue by luckydonald** [vanhauser-thc/thc-hydra#310]
I want to bootforce SSH to a VM.
Now SSH seems to be very limited in tries per minute, so I spun up multiple Instances of it.

In my Host list file, I have 
```hosts
localhost:2201
localhost:2202
localhost:2203
localhost:2204
...
```
It now seems to try each password on each Host.
```
[ATTEMPT] target localhost - login "hackme" - pass "" - 1 of 440693 [child 0] (0/0)
[ATTEMPT] target localhost - login "hackme" - pass "" - 1 of 440693 [child 1] (0/0)
[ATTEMPT] target localhost - login "hackme" - pass "" - 1 of 440693 [child 2] (0/0)
[ATTEMPT] target localhost - login "hackme" - pass "" - 1 of 440693 [child 3] (0/0)
[ATTEMPT] target localhost - login "hackme" - pass "test" - 2 of 440693 [child 4] (0/0)
[ATTEMPT] target localhost - login "hackme" - pass "test" - 2 of 440693 [child 5] (0/0)
[ATTEMPT] target localhost - login "hackme" - pass "test" - 2 of 440693 [child 6] (0/0)
[ATTEMPT] target localhost - login "hackme" - pass "test" - 2 of 440693 [child 7] (0/0)
[ATTEMPT] target localhost - login "hackme" - pass "admin" - 3 of 440693 [child 8] (0/0)
[ATTEMPT] target localhost - login "hackme" - pass "admin"" - 3 of 440693 [child 9] (0/0)
[ATTEMPT] target localhost - login "hackme" - pass "admin"" - 3 of 440693 [child 10] (0/0)
[ATTEMPT] target localhost - login "hackme" - pass "admin"" - 3 of 440693 [child 11] (0/0)
[ATTEMPT] target localhost - login "hackme" - pass "root" - 4 of 440693 [child 0] (0/0)
```

I couldn't quite find how to take advantage of multiple hosts.

**Comment by luckydonald** [comment]
In fact that could even be a real life

**Comment by luckydonald** [comment]
This was not the cancel button.

**Comment by vanhauser-thc** [comment]
you start the tool with the same commands and you are surprised that they do the same thing? ;)

you could use the "split" command on linux to split the user or password file into as many as you run hydra parallel so you have no doubles.

**Comment by luckydonald** [comment]
I was hoping there could be a `--multiplex` option or siliar.

Sorry to keep bothering you with questions, but how can I keep the session restore files `-R` separated from each other?

**Comment by vanhauser-thc** [comment]
such a -multiplex/... option would be a huge amount of work to implement - and is so easy to do with "split" ... in the followng example you attack one user for 4 differnt ssh instances and split the password file into four pieces which have the port number appended to their filename.
for the restore file you just need to run them from different directories, e.g.:

```
for port in 2001 2002 2003 2004; do
 {
  mkdir $port
  cd $port && /usr/local/bin/hydra -l test -p /path/to/list.txt.$port -t16 ssh://target:$port
 } &
done
```

**Comment by luckydonald** [comment]
Oh, i was mistaken, that the restore file would be in `~/.hydra/`.
Huge thanks!
