### ISSUE TITLE
Hydra unstable results on ssh dictionary attack

### ISSUE THREAD

**Issue by NnB01** [vanhauser-thc/thc-hydra#311]
I'm using Parrot OS latest version and i'm testing Hydra's abilities on ssh dictionary attack. There is an ssh service running on host 192.168.1.14 and the only correct creds to log in is U: luigi  P: luigi1
What i found out is that hydra is acting really strange, some times she finds passwords correctly, some others she finds wrong passwords as correct but most of the times she doesn't find the contained (in wordlist) password at all.

Below are some screenshots that describe that strange behavior.
(All scans are using the same username and password wordlist. Password "luigi1" is contained into password wordlist.)

1) Success.
![selection_001](https://user-images.githubusercontent.com/21063734/37008835-b9c19f2a-20ec-11e8-8879-cb188cc9c8c3.png)

2) Fail.
![selection_002](https://user-images.githubusercontent.com/21063734/37008856-cecb4a10-20ec-11e8-900a-911c717eabfd.png)

3) False positive.
![selection_003](https://user-images.githubusercontent.com/21063734/37008874-ea4f362a-20ec-11e8-8672-d79524098f31.png)

4) And another fail.
![selection_004](https://user-images.githubusercontent.com/21063734/37008895-fdbb197c-20ec-11e8-9bc5-2bca1a81e791.png)

Anyone knows why is this happening? 
PS. same behavior with Hydra version 8.7-dev.

**Comment by vanhauser-thc** [comment]
well hydra is using the library libssh and can only react on what the library reports.
My guess is that because you are using 64 parallel tasks this overwhelms the server and therefore drops connections, doesnt react as it should etc.

does that matter resolves itself when you specify -t 16 ?

**Comment by NnB01** [comment]
I tried the same attack with less threads as you suggested but she found nothing :/

![selection_005](https://user-images.githubusercontent.com/21063734/37042701-ae930852-2167-11e8-9406-080aabca0a88.png)

**Comment by vanhauser-thc** [comment]
you still have way too many errors. lower the -t threads until you get no or rarely errors

**Comment by vanhauser-thc** [comment]
does it work when you set -t 4 ?
