### ISSUE TITLE
[ERROR] definition for password bruteforce (-x) generates more than 4 billion passwords

### ISSUE THREAD

**Issue by itjwd-works** [vanhauser-thc/thc-hydra#314]
Hi!

Please can you help me, I always get the same error. I just want to make clarify if the -x min:max is just up to 6 characters?

Thank you!

**Comment by vanhauser-thc** [comment]
its not up to 6 characters its up to max 4 billion combinations.
you can reach with just 5 characters is you have a very large character set or up to 8 characters if its only numbers.

**Comment by itjwd-works** [comment]
Ok, I got it!

Thank you vanhauser-thc!
