### ISSUE TITLE
cant get it to work in termux

### ISSUE THREAD

**Issue by negadave** [vanhauser-thc/thc-hydra#319]
So here’s my problem, besides the fact that I’m a total noob to pen-testing. I’ve been playing around with hydra in a non-rooted android and i figured i’d put hydra to the test on account that have known passwords. And here’s the rub, i’m watching it in verbose mode passing right over the target passes on several different site. Same result. I’m using cupp to make my word lists and picking the passes from it. So here’s the set-up, minus my username and a url:
hydra -v -l mylogin -P /data/data/com.termux/files/home/tattoo.txt -c 7 -w 5 -s 80 someurl.com http-form-post “/login.php:user=^USER64^&pass=^PASS64^&colon=colon:escape:S=authlog=.*success”
and i’m using torsocks as my proxy. Can someone help me? What could be wrong?

**Comment by vanhauser-thc** [comment]
if it can not detect the successful password then your success string match is not good (authlog=.*success in your example". but I think the problem is that you have a colon there "colon:escape" that is not escaped. try colon\\:escape
