### ISSUE TITLE
Cookies/request headers with http-get

### ISSUE THREAD

**Issue by blincoln-ncc** [vanhauser-thc/thc-hydra#321]
I'm trying to use Hydra to test HTTP basic auth credentials. The system in question will only handle this correctly if a fixed cookie is included in the request along with the HTTP basic auth credentials.

I don't see a way to add cookies or custom request headers when using the http-get module, only the form and POST-related modules. Am I misreading the help? I don't want to send the username and password as URL or body parameters, which is why I'm using http-get.

Additionally, the behaviour of the target system is that when the cookie is *not* present, it sends an HTTP 403 response. Hydra is interpreting this as if the password is valid, because usually a 403 will be returned if authentication is successful, but authorization is not. Is there any chance of making it a command-line option to treat 403, 404, etc. as failed auth? Right now Hydra is telling me that all of the passwords in my list are valid, which is not the case.

**Comment by vanhauser-thc** [comment]
Hi,

you are correct, this is so far not supported in hydra, as it was never an issue before.
Its easy to implement (using the -m option to, e.g. -m Cookie=Value) but someone needs to do it and I currently have not time for that, so it would be on my growing todo list.

if you want to have a go at it, I can assist you though.

**Comment by mathewmarcus** [comment]
I would be interested in implementing this feature if it's still something you'd like to see added. If so, would it make sense to reuse some of the code from hydra-http-form.c which provides the ability to pass headers via `(h|H)=My-Hdr\: foo`?

**Comment by vanhauser-thc** [comment]
Hi,

sure if you want to go for that - that would be great :)
you can reuse the code, obivously!
