### ISSUE TITLE
[ERROR]: Failed to extract public key from certificate

### ISSUE THREAD

**Issue by Margular** [vanhauser-thc/thc-hydra#322]
When using hydra to crack rdp for windows, notice this error.
Maybe hydra can't support the version of that rdp?

**Comment by Margular** [comment]
using rdesktop to connect, -4 was going wrong, -5 works perfectly.So hydra don't support version 5 of rdp?

**Comment by vanhauser-thc** [comment]
yes, hydra only supports version 4.
someone needs to upgrade the module to support v5.
if you want to have a go at it, I can support you.
(I am currently too busy :( )

**Comment by Margular** [comment]
Thank you, that was a nice decision!

**Comment by vanhauser-thc** [comment]
duplicate #390
