### ISSUE TITLE
Anyway to bypass "[INFO] Testing if password authentication is supported by ssh://*"

### ISSUE THREAD

**Issue by syrius01** [vanhauser-thc/thc-hydra#323]
Hi!

Thank you for sharing this awesome tool with the community :). I was wondering if there was a way I could bypass the "[INFO] Testing if password authentication is supported by ssh://*" process when attempting to bruteforce a targets.list.txt file for SSH ? I understand the concept that Hydra wants to make sure that the target first is really a SSH server but it's really time consuming on a huge list of targets because it tries one by one without multiple threads.

Thank you for your time!

**Comment by syrius01** [comment]
Thank you for your quick reply. Can you tell me which line exactly to replace the return function to 'return 0' ?

**Comment by syrius01** [comment]
I changed the line #189 in hydra-ssh.c to 'return 0' (originally return 1) but I'm still getting this after re-compiling Hydra;

"[INFO] Testing if password authentication is supported by ssh://..."

I probably didn't changed the right line in 'hydra-ssh.c' in order to get rid of the verification if the servers in 'target.list.txt' 

Sorry for my very limited knowledge in C#, could you tell me which line numbers I have to edit to replace them for: 'return 0' ?

Thanks

**Comment by vanhauser-thc** [comment]
insert the line, not modify anything. and where I told you, not somewhere else :)

**Comment by syrius01** [comment]
I've inserted the line 'return 0' on line 172 (you can see source available here; https://pastebin.com/Bwzsn47V) but when i try to compile Hydra with the modified source I get this;

hydra-ssh.c:160:127: error: expected declaration specifiers or ‘...’ before ‘return’
 int32_t service_ssh_init(char *ip, int32_t sp, unsigned char options, char *miscptr, FILE * fp, int32_t port, char *hostname, return 0) {
                                                                                                                               ^~~~~~
make: *** [hydra-ssh.o] Error 1
sirius@blackb0x:~/sploits/SSH/2018/HYDRA/modded/thc-hydra$ nano hydra-ssh.c
sirius@blackb0x:~/sploits/SSH/2018/HYDRA/modded/thc-hydra$ make
cc -I. -O3 -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wl,-z,now -Wl,-z,relro   -c hydra-ssh.c -DLIBOPENSSL -DLIBNCURSES -DLIBIDN -DHAVE_PR29_H -DHAVE_PCRE -DLIBPOSTGRES -DLIBSSH -DHAVE_ZLIB -DHAVE_GCRYPT -DHAVE_MATH_H -I/usr/include -I/usr/include -I/usr/include -I/usr/include/postgresql -I/usr/include
hydra-ssh.c: In function ‘service_ssh_init’:
hydra-ssh.c:174:3: error: expected ‘;’ before ‘int32_t’
   int32_t rc, method;
   ^~~~~~~
hydra-ssh.c:192:3: error: ‘rc’ undeclared (first use in this function)
   rc = ssh_userauth_none(session, NULL);
   ^~
hydra-ssh.c:192:3: note: each undeclared identifier is reported only once for each function it appears in
hydra-ssh.c:193:3: error: ‘method’ undeclared (first use in this function)
   method = ssh_userauth_list(session, NULL);
   ^~~~~~
make: *** [hydra-ssh.o] Error 1



I must be missing something here... Thanks for your support :)

**Comment by vanhauser-thc** [comment]
you are missing a semicolon after "return 0" -> "return 0;"
otherwise its fine
