### ISSUE TITLE
Hydra returns an error code of 255 instead of 0

### ISSUE THREAD

**Issue by DruKot** [vanhauser-thc/thc-hydra#325]
The error returned.

https://github.com/vanhauser-thc/thc-hydra/issues/279

**Comment by vanhauser-thc** [comment]
please put more effort in a bug report or dont even try.
which version of hydra were you using? if is not the newest, try the newest first.
post full command line and screen output

**Comment by DruKot** [comment]
All information (command&output) exist in the link I wrote, I see no reason to duplicate the whole text.
Bug returned in the last version.

**Comment by vanhauser-thc** [comment]
then you append to the closed issue instead of creating a new one with no content if you want to be lazy ...
