### ISSUE TITLE
make: *** [hydra-svn.o] Error 1

### ISSUE THREAD

**Issue by KingJiJi** [vanhauser-thc/thc-hydra#326]
by the time 'make'

error:
hydra-svn.c: In function ‘start_svn’:
hydra-svn.c:86: warning: assignment makes pointer from integer without a cast
hydra-svn.c:108: warning: assignment makes pointer from integer without a cast
hydra-svn.c:110: error: ‘svn_client_list_func2_t’ undeclared (first use in this function)
hydra-svn.c:110: error: (Each undeclared identifier is reported only once
hydra-svn.c:110: error: for each function it appears in.)
hydra-svn.c:110: error: expected ‘)’ before ‘print_dirdummy’
make: *** [hydra-svn.o] Error 1

Version:License show  Version 3, 19 November 2007
i git clone the git at time:2018-4-27

linux 2.6.32-504.el6.x86_64  GNU/Linux

**Comment by KingJiJi** [comment]
105   revision.kind = svn_opt_revision_head;
106   snprintf(URL, sizeof(URL), "svn://%s:%d/%s", hydra_address2string_beautiful(ip), port, URLBRANCH);
107   dirents = SVN_DIRENT_KIND;
108   canonical = svn_uri_canonicalize(URL, pool);
109   //err = svn_client_list2(canonical, &revision, &revision, svn_depth_unknown, dirents, FALSE, print_dirdummy, NULL, ctx, pool);
110   err = svn_client_list3(canonical, &revision, &revision, svn_depth_unknown, dirents, FALSE, FALSE, (svn_client_list_func2_t) print_dirdummy, NULL, ctx, pool);

**Comment by 937325203** [comment]
I'have a same issues 
Have you solved this problem?

**Comment by KingJiJi** [comment]
change another version

**Comment by lovechina1221** [comment]
I'have a same issues 
centos
![image](https://user-images.githubusercontent.com/29085376/48189913-3afe6300-e37c-11e8-925b-1ec0aedf7ae3.png)

**Comment by lovechina1221** [comment]
because the version of svn(subversion)is too low
upgrade it and make again

**Comment by vanhauser-thc** [comment]
@lovechina1221 exactly, just use a more modern libsvn.
the old ones can work, you would need to edit hydra-svn.c for that and uncomment/comment the lines for svn_client_list*
