### ISSUE TITLE
error

### ISSUE THREAD

**Issue by drupaltwo** [vanhauser-thc/thc-hydra#328]
hydra.c:3932:14: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘long long unsigned int’ [-Wformat=]
hydra.c:3932:14: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘long long unsigned int’ [-Wformat=]
hydra.c:3932:14: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 6 has type ‘uint64_t {aka long long unsigned int}’ [-Wformat=]
hydra.c:3932:14: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 7 has type ‘long long unsigned int’ [-Wformat=]
hydra.c:3932:14: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 8 has type ‘long long unsigned int’ [-Wformat=]
hydra.c:3977:10: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 6 has type ‘uint64_t {aka long long unsigned int}’ [-Wformat=]
   printf("%d of %d target%s%scompleted, %lu valid password",
          ^
hydra.c:4051:33: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘uint64_t {aka long long unsigned int}’ [-Wformat=]
       fprintf(hydra_brains.ofp, "\n\t],\n\"success\": %s,\n\"errormessages\": [ %s ],\n\"quantityfound\"
                                 ^
hydra-ssh.o: In function `start_ssh.constprop.0':
hydra-ssh.c:(.text+0x1ae): undefined reference to `ssh_is_connected'
hydra-ssh.o: In function `start_ssh':
hydra-ssh.c:(.text+0x566): undefined reference to `ssh_is_connected'
collect2: error: ld returned 1 exit status
Makefile:61: recipe for target 'hydra' failed
make: *** [hydra] Error 1

**Comment by vanhauser-thc** [comment]
something wrong with the libssh library or its detection.

what is the output of ./configure --debug ?

**Comment by drupaltwo** [comment]
Hydra will be installed into .../bin of: /usr/local
  (change this by running ./configure --prefix=path)

DEBUG: XDEFINES= -DHAVE_MYSQL_MYSQL_H -DLIBOPENSSL -DLIBNCURSES -DLIBFIREBIRD -DLIBIDN -DHAVE_PR29_H -DHA     VE_PCRE -DLIBMYSQLCLIENT -DLIBPOSTGRES -DLIBSVN -DLIBSSH -DHAVE_ZLIB -DHAVE_MATH_H
DEBUG: XLIBS= -lz -lcurses -lssl -lfbclient -lidn -lpcre -lmysqlclient -lpq -lsvn_client-1 -lapr-1 -lapru     til-1 -lsvn_subr-1 -lssh -lcrypto
DEBUG: XLIBPATHS=-L/usr/lib -L/usr/local/lib -L/lib -L/lib/i386-linux-gnu -L/usr/lib/i386-linux-gnu -L/li     b/i386-linux-gnu -L/usr/lib/i386-linux-gnu -L/lib/i386-linux-gnu -L/usr/lib/i386-linux-gnu
DEBUG: XIPATHS= -I/usr/include/mysql -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/i     nclude/postgresql -I/usr/include -I/usr/include/subversion-1 -I/usr/include/apr-1.0 -I/usr/include/subver     sion-1
DEBUG: PREFIX=/usr/local
DEBUG: XHYDRA_SUPPORT=xhydra
DEBUG: STRIP=strip
Writing Makefile.in ...
now type "make"

**Comment by vanhauser-thc** [comment]
the *full* output ...
