### ISSUE TITLE
Testing sequence

### ISSUE THREAD

**Issue by ahtoxa1114** [vanhauser-thc/thc-hydra#329]
Dear Sir,

I need to recover passwords for a stack of quite similar devices with the same login.

PASSWORD.TXT:
pass1
pass2
[...]
pass10

SERVICES.TXT:
service1
service2:8080
[...]
serviceN

For example, each device requires not less than 5 minutes timeout.

hydra -c 300 -l Admin -P PASSWORD.TXT -M SERVICES.TXT http-post-form [....]

As far as I understand, the testing sequence is as follows:

-attempt to connect to service1 with Admin:pass1;
-wait for 300 seconds;
-attempt to connect to service1 with Admin:pass2;
-wait for 300 seconds;
[...]
-attempt to connect to service1 with Admin:pass10;
-wait for 300 seconds;
-attempt to connect to service2 with Admin:pass1;
-wait for 300 seconds;
-attempt to connect to service2 with Admin:pass2;
-wait for 300 seconds;
[...]
-attempt to connect to service2 with Admin:pass10;
-wait for 300 seconds;
[...]
-attempt to connect to serviceN with Admin:pass1;
-wait for 300 seconds;
-attempt to connect to serviceN with Admin:pass2;
-wait for 300 seconds;
[...]
-attempt to connect to serviceN with Admin:pass10;

We test each device with all possible passwords with full 5 min timeouts between attempts. But we could save significant time if the testing sequence would be as follows:

hydra -c 30 -l Admin -P PASSWORD.TXT -M SERVICES.TXT http-post-form [....]

-attempt to connect to service1 with Admin:pass1;
-wait for 30 seconds;
-attempt to connect to service2 with Admin:pass1;
-wait for 30 seconds;
[...]
-attempt to connect to serviceN with Admin:pass1;
-wait for 30 seconds;
-attempt to connect to service1 with Admin:pass2;
-wait for 30 seconds;
-attempt to connect to service2 with Admin:pass1;
-wait for 30 seconds;
[...]
-wait for 30 seconds;
-attempt to connect to serviceN with Admin:pass10;

Could we test each password pair against all possible devices with proportionally reduced timeouts and then take another password? Is it possible to adjust testing sequence in such a way?

Thank you very much for any help you could provide.

**Comment by vanhauser-thc** [comment]
The -W timeout is per connection, so what you would do is:

-W 300 -t 1 -T 32 (or higher -T)

this will run on attack thread per target, waiting 300 seconds between connections, running up to 32 (or higher) targets in parallel

**Comment by vanhauser-thc** [comment]
actually try -c 300 insted of -W 300 if the above does not work. it kinda depends on how the targets react which of the two will work
