### ISSUE TITLE
Wrong Password Found

### ISSUE THREAD

**Issue by kalihack2014** [vanhauser-thc/thc-hydra#33]
@vanhauser-thc 

I'm reporting this for a friend although I've used hydra to crack gmail accounts with a similar error:

She is using Kali Linux inside virtual Box and using version Hydra 8.1 command as shown:
hydra -l <username> -P <path to password file> www.nairaland.com http-form-post "/do_login:User Name=^USER^&Password=^PASS^:wrong" 

After about half an hour it gives the wrong password after trying.

On a Twitter account via this command:

hydra -l <username> -P <path to password file> https://login.skype.com https-form-post “/login:Skype Name=^USER^&Password=^PASS^:failed”﻿ 

she says this: "For Skype, it isnt working at all.  It does not execute even. After typing the command and pressed Enter, the cusor just goes to the next line with the ">" sign before it﻿"

Any ideas about why this is happening? Thank-you very much! ;)

**Comment by vanhauser-thc** [comment]
first command: very likely the server sometimes responds with a different web page (e.g. an overload error) and this is then a false positive. instead of ":wrong" use ":S=a_success_string". you must know what a string is that is sent after a successful login.

second command: if there is just a ">" sign on the next line, she put a lonely " somewhere which is not closed.

**Comment by kalihack2014** [comment]
@vanhauser-thc  Thank-you very much for your help. So in an html document where is the success string located?

**Comment by kalihack2014** [comment]
@vanhauser-thc  Thank-you very much for your help. So in an html document where is the success string located?

**Comment by vanhauser-thc** [comment]
you can take any string in the html output (or server header) that is unique to the successful login page.

note: this is for BUGS IN THE SOFTWARE ONLY - not a help system.

**Comment by Aspect9** [comment]
why does xHydra keep giving false positives? is it because of security protocols? colour me interested...*
