### ISSUE TITLE
RTSP Failed with true Credentials?

### ISSUE THREAD

**Issue by Delikt** [vanhauser-thc/thc-hydra#336]
Hi,

i try to find my Login/Password over RTSP of my IP Camera with hydra and for testing i take the best credentials of the world admin/admin.

i using xhydra and feed it with my login and password (no wordlist etc just the true Login/password)

the command look like this: hydra -s 554 -l admin -p admin -t 64 -f LOCAL_IPADRESS rtsp

so i expected i get back finished and found in 1 try ofc but i get:

[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking rtsp://IP_ADRESS:554/
1 of 1 target completed, 0 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at TIME
<finished>

what is wrong with it? the IP Camera is Online, RTSP Port open and i can also connect with VLC Media Player...

**Comment by Delikt** [comment]
i try the same on my raspberry over SSH - worked

**Comment by vanhauser-thc** [comment]
do you need the credentials for VLC as well? many stream without needing any credentials.

If you need the credentials then there is a bug. 
I did not write the module nor do I have an RTSP device.
So ... in that case it would be good if you could make a pcap of the RTSP with VLC and one with hydra, so the issue can be spotted and fixed.
And it would be amazing if you could even send in a patch to fix it :)

**Comment by Delikt** [comment]
Yeah i need the credentials with VLC. I take a look in the Cyber Security Präsentation what i got from the manufacture (i working as Sales representative for Security Cameras and other electrical Security Systems).  

There i see a Hint (short translated from German): 

Password Anti Cracking:
If the Device feel a Cracking behavior from a User, it will not authorize the Login from this IP - dont matter are the credentials right or false.

The Manufacture is Dahua - sad i dont have any other IP Camera from another Manufacture to test the module.

**Comment by vanhauser-thc** [comment]
if you just try with the real login and password (no list) it must work.
otherwise there is a bug.
please compare the request hydra send with the one vlc sends and post it here (e.g. with wireshark).

**Comment by digital-freedom-services** [comment]
Hydra doesn't send Authorization info in header files.

I've dumped packets with ngrep and found:

`T from-ip:59366 -> to-ip:554 [AP] DESCRIBE rtsp://to-ip:554 RTSP/1.0..CSeq: 2....`

`T to-ip:554 -> from-ip:59368 [AP] RTSP/1.0 401 Unauthorized..CSeq: 2..WWW-Authenticate: Digest realm="abcdefg", nonce="238cac9efffd46fa7d65b201fd4f74fc", stale="FALSE"..WWW-Authenticate: Basic realm="abcdefg"..Date:  Sun, Aug 19 2018 17:29:19 GMT...`

I run hydra with following args:
`hydra -l admin -P pass.txt -V rtsp://to-ip:554/medias2`

**Comment by Testing554** [comment]
still saame issue is it fixed
