### ISSUE TITLE
BUG? incorrect syntax?

### ISSUE THREAD

**Issue by BerKut81** [vanhauser-thc/thc-hydra#337]
Hello Hydra God, I'm a super rookie hydra user. 

I'm not sure if is an incorrrect usage of the tool or if is a bug. I can't get any response from server after post a login attempt with Hydra.

I'm using this syntax:
hydra -d -l admin -p SuperPassword 192.168.1.1 http-post-form "/:userName=^USER^&pcPassword=^PASS^&loginBtn=PCSubWin():incorrect"

And Getting this Response:
DEBUG: no response from server

Attached is the full debug log. [Debug.TXT](https://github.com/vanhauser-thc/thc-hydra/files/2151386/Debug.TXT)

This is the login form of the http web page:
`
<input class="text" id="userName" type="input" maxlength="14">
<input class="text" id="pcPassword" type="password" maxlength="14">
<label id="loginBtn" class="loginBtn" onclick="PCSubWin()"></label>
`

At the other hand, I have this javascript:
`
function PCSubWin()
{
	if(isLocked == true)
	{
		return;
	}
	if(!CheckUserPsw("userName"))
	{
		$("note").innerHTML = "NOTE:";
		$("tip").innerHTML = "The username should only consist of letters, numbers or quotation marks.";
		$("userName").value = "";
		$("userName").focus();
		return;
	}
	if(!CheckUserPsw("pcPassword"))
	{
		$("note").innerHTML = "NOTE:";
		$("tip").innerHTML = "The password should only consist of letters, numbers or quotation marks.";
		$("pcPassword").value = "";
		$("pcPassword").focus();
		return;
	}
    var auth;
	var password = $("pcPassword").value;
	var userName = $("userName").value;
	auth = "Basic "+Base64Encoding(userName+":"+password);
	document.cookie = "Authorization="+escape(auth)+";path=/";
	location.href = "/";
}
`
I have to build the form parameters based on web page or based on the javascript is sending?

Thanks in advance.-

**Comment by vanhauser-thc** [comment]
this is for reporting bugs, not asking for help.

as you can see in the javascript the login/password is converted to basic auth, so mabye the correct module would be http-post or https-get.
use zap to intercept the real web request the browser does and then either use http-form or http-get with the proper arguments.

**Comment by BerKut81** [comment]
Hi VH, thanks a lot for your help. Sorry for reopen this issue again.

I understand this is not a place to ask for help, but I think that I detected a bug or a new situation not viewed before. Please, let me explain you:

I was checking the GETs to the login page (there is no POSTs). Everything looks very normal, is a basic http authentication, just like you said (user:password, all encoded in base64). But, I found there is no matter what password I'm using, Hydra always understand that the password is correct using http-get.

I was taking a look at the response packets and the server always answer with a 200. The only way I can recognize a successful or unsuccessful login attempt whas using http-get-form.

Is there any way to do a basic http authentication using http-get-form with Hydra? I can't find anything clear at Hydra documentation.

Thanks in advance, again.-

**Comment by vanhauser-thc** [comment]
Hi,

well if the server does not reply to a wrong basic auth with the corresponding status code like they should be, but just render a different page than this is something hydra does not support..
There are many weird non-standard implementations out there, and to support weirdness for a device that is not very common I do not see the value of my time spent well.
But feel free to write a patch to add regex support for the output page (but likely you will also need to support cookies) for the http-get/post module. most of the code is present in the http-form module.

If you need help I can support you.

**Comment by BerKut81** [comment]
Sounds good, thanks!

I will try to do that, I expect contact you after a few tests.

**Comment by BerKut81** [comment]
I was trying to figure out where is the analysis of the server response at hydra-http.c, but I can't figure out. I guess is between lines 165 and 234.

I just want to use analyze_server_response from http-form replacing the response check at http mode, but I'm not sure which place is it.

So embarrassing for me!
