### ISSUE TITLE
i got error cod when i type (make) - (make install)

### ISSUE THREAD

**Issue by MDMN92** [vanhauser-thc/thc-hydra#338]
HP@LAPTOP-NFA4U5FC ~/thc-hydra-master
$ make
cc -I. -O3     -o pw-inspector  pw-inspector.c
make: cc: Command not found
make: [Makefile:70: pw-inspector] Error 127 (ignored)
cc -I. -O3    -c hydra-vnc.c -DNO_STRRCHR
make: cc: Command not found
make: *** [Makefile:73: hydra-vnc.o] Error 127

**Comment by crondaemon** [comment]
```
make: cc: Command not found
```

This does point you in the right direction, doesn't it? You need to install the compiler if you want to compile something.
