### ISSUE TITLE
Hydra marks password as valid,while it isn't

### ISSUE THREAD

**Issue by Dontutrustme** [vanhauser-thc/thc-hydra#339]
Hi! Im trying hydra on my router. 
hydra -s 80 -l admin -p 1111 -V -f 192.168.1.1 http-get
The answer:
Hydra (http://www.thc.org/thc-hydra) starting at 2018-07-09 01:51:42
[WARNING] You must supply the web page as an additional option or via -m, default path set to /
[DATA] max 1 task per 1 server, overall 1 tasks, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking service http-get on port 80
[DATA] with additional data /
[ATTEMPT] target 192.168.1.1 - login "admin" - pass "1111" - 1 of 1 [child 0] (0/0)
[80][http-get] host: 192.168.1.1   login: admin   password: 1111
[STATUS] attack finished for 192.168.1.1 (valid pair found)
1 of 1 target successfully completed, 1 valid password found
Hydra (http://www.thc.org/thc-hydra) finished at 2018-07-09 01:51:43

The problem is its not valid pass,infact i can type anything in -p and the answer would be the same.
Did i miss something?
This is an ASUS router if it helps.

**Comment by vanhauser-thc** [comment]
are you sure it is really http basic auth? more like its an authentication form ... (http-form-post)

**Comment by Dontutrustme** [comment]
I think it isn't,my bad. Tested via Telnet channel,it works just fine. And after i managed to capture post request with proxy. But the problem is - that request dont contain any 'login,passwd' strings,just a sript,login_authorization and some sort of token i think. Could this be an encryption or smth? I'm preety new at this:P

**Comment by BerKut81** [comment]
Can you post the request and response headers? 

Please keep on mind that a basic authorization has this format, admin:password, (encoded in base64). Did you tried to decode the "token" using base64?

Good luck!

**Comment by BerKut81** [comment]
Sorry, Is solved or is not a bug? I tested the last version and still is not working with some soho wifi routers http authentication.

**Comment by vanhauser-thc** [comment]
its non-standard so cant be supported
