### ISSUE TITLE
does not support password authentication

### ISSUE THREAD

**Issue by isdarktarget** [vanhauser-thc/thc-hydra#340]
hydra -l root -M ip.txt -P pass.txt -t 32 ssh
Hydra v8.5 (c) 2017 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2018-07-13 02:23:28
[WARNING] Many SSH configurations limit the number of parallel tasks, it is recommended to reduce the tasks: use -t 4
[DATA] max 32 tasks per 20046 servers, overall 64 tasks, 44 login tries (l:1/p:44), ~13782 tries per task
[DATA] attacking service ssh on port 22
**[ERROR] target ssh://46.4.0.56:22/ does not support password authentication.**

how can fix this ? i trying with  windows version of hydra

**Comment by vanhauser-thc** [comment]
... and what are you trying to tell me?
