### ISSUE TITLE
No way to set failure header

### ISSUE THREAD

**Issue by lwahonen** [vanhauser-thc/thc-hydra#349]
I'm attacking a http-form-post with Hydra. With bad auth, the server returns just a "HTTP/1.1 403 Forbidden" header without a body.

I do not know what the success page looks like (this is for a CTF). It seems like there is no way to tell Hydra to treat status 403 as a failed attempt?

**Comment by vanhauser-thc** [comment]
it should have done that, but the function that checks for that returned the wrong code.

I fixed it, please check if it works now.

**Comment by vanhauser-thc** [comment]
can you please test?
