### ISSUE TITLE
Empty target address when reading from a file provided by bash's process substitution

### ISSUE THREAD

**Issue by mwulftange** [vanhauser-thc/thc-hydra#35]
When trying to use [bash's process substitution `<(…)`](http://www.gnu.org/software/bash/manual/bashref.html#Process-Substitution) to provide a file for parameters like `-M` from dynamically generated data like a `grep` result, *hydra* fails to recognize the input somehow:

    # echo <(grep '3306/' 192.168.0.0.gnmap | cut -d ' ' -f 2)
    /dev/fd/63
    # cat <(grep '3306/' 192.168.0.0.gnmap | cut -d ' ' -f 2)
    192.168.0.1
    192.168.0.2
    # hydra -l root -p '' -M <(grep '3306/' 192.168.0.0.gnmap | cut -d ' ' -f 2) mysql
    Hydra v7.6 (c)2013 by van Hauser/THC & David Maciejak - for legal purposes only
    
    Hydra (http://www.thc.org/thc-hydra) starting at 2015-01-30 09:04:08
    [INFO] Reduced number of tasks to 4 (mysql does not like many parallel connections)
    [DATA] 1 task, 2 servers, 1 login try (l:1/p:1), ~2 tries per task
    [DATA] attacking service mysql on port 3306
    [ERROR] could not resolve address: 
    [ERROR] could not resolve address: 
    0 of 2 targets completed, 0 valid passwords found
    [ERROR] 2 targets did not resolve or could not be connected
    Hydra (http://www.thc.org/thc-hydra) finished at 2015-01-30 09:04:09

**Comment by vanhauser-thc** [comment]
-M expects a FILENAME which is clearly stated in the help output
so write that grep output to a file and use that for -M

**Comment by mwulftange** [comment]
But as bash's process substitution returns the path to a file, shouldn’t that work as well?

**Comment by vanhauser-thc** [comment]
no. you are reading from a pipe, not a file. the data has to be read twice (first to count the lines). that is why it can't work.
