### ISSUE TITLE
Is this a bug?（mysql server）

### ISSUE THREAD

**Issue by lovechina1221** [vanhauser-thc/thc-hydra#355]
the mysql service is on a different default port（33066）
But the request to enter an account password will be sent to port 3306.
![image](https://user-images.githubusercontent.com/29085376/46070494-8683f580-c1b0-11e8-9655-b353f0cad068.png)
![image](https://user-images.githubusercontent.com/29085376/46070582-bdf2a200-c1b0-11e8-80d2-ce5bc2ec395e.png)

**Comment by vanhauser-thc** [comment]
there was a bug, but it should be fixed in the repository here. did you "git clone" it and try or were you using a thc-hydra-8.x.tar.gz release? if the latter, clone the git and retry

**Comment by lovechina1221** [comment]
I am pleased to receiveyour reply.Today I tried to compile and install the latest version（v8.6) and apt-get install the latest version in kali.But this vulnerability seems to exist

V8.5 is sent to 3306 with or without -s ，now part of the packet is sent to 3306

**Comment by vanhauser-thc** [comment]
no - clone the github and compile it, not a .tar.gz or kali apt-get instal.

**Comment by vanhauser-thc** [comment]
?

**Comment by vanhauser-thc** [comment]
@lovechina1221 then please report back when you retested it. thanks

**Comment by lovechina1221** [comment]
好的~

**Comment by lovechina1221** [comment]
In the v8.7 version everything works fine.  (๑•́ ∀ •̀๑)
Thank you for your patience. ∠(°ゝ°）敬礼
