### ISSUE TITLE
undefined reference to `ssh_is_connected'

### ISSUE THREAD

**Issue by 937325203** [vanhauser-thc/thc-hydra#356]
I have a issues when compiled, at first i remove -DLIBSSH in Makefile line 3 to fix first issues.But nuw issues come:
```
hydra.c: 在函数‘hydra_restore_write’中:
hydra.c:715: 警告：忽略声明有 warn_unused_result 属性的‘fwrite’的返回值
hydra-ssh.o: In function `start_ssh':
hydra-ssh.c:(.text+0x45d): undefined reference to `ssh_is_connected'
collect2: ld 返回 1
make: *** [hydra] 错误 1
```
I have compiled and installed libssh0.4.8
My English is awful,I'm sorry

**Comment by vanhauser-thc** [comment]
please paste the output of "./configure --debug" and "find / -name "libssh*"

**Comment by KingJiJi** [comment]
same issues:
# find / -name "libssh*"
/etc/safedog/libs/safedog/libssh_bruteforce.so
/usr/local/lib/libssh.so.4.1.4
/usr/local/lib/libssh.so.4
/usr/local/lib/libssh.so
/usr/local/include/libssh
/usr/local/include/libssh/libssh.h
/usr/include/libssh
/usr/include/libssh/libssh.h
/usr/lib64/libssh2.so.1
/usr/lib64/libssh.so.4
/usr/lib64/libssh_threads.so.4
/usr/lib64/libssh_threads.so
/usr/lib64/libssh_threads.so.4.2.5
/usr/lib64/pkgconfig/libssh_threads.pc
/usr/lib64/pkgconfig/libssh.pc
/usr/lib64/libssh.so.4.2.5
/usr/lib64/libssh.so
/usr/lib64/libssh2.so.1.0.1
/usr/share/doc/libssh-0.5.5
/usr/share/doc/libssh-devel-0.5.5
/usr/share/doc/libssh-devel-0.5.5/html/libssh_tutor_guided_tour.html
/usr/share/doc/libssh-devel-0.5.5/html/libssh_tutor_shell.html
/usr/share/doc/libssh-devel-0.5.5/html/libssh_linking.html
/usr/share/doc/libssh-devel-0.5.5/html/libssh_tutorial.html
/usr/share/doc/libssh-devel-0.5.5/html/libssh_tutor_forwarding.html
/usr/share/doc/libssh-devel-0.5.5/html/libsshpp_8hpp_source.html
/usr/share/doc/libssh-devel-0.5.5/html/libssh_tutor_threads.html
/usr/share/doc/libssh-devel-0.5.5/html/libssh_tutor_command.html
/usr/share/doc/libssh-devel-0.5.5/html/libssh_tutor_todo.html
/usr/share/doc/libssh-devel-0.5.5/html/libssh_8h_source.html
/usr/share/doc/libssh-devel-0.5.5/html/libssh_tutor_authentication.html
/usr/share/doc/libssh-devel-0.5.5/html/libssh_tutor_sftp.html
/usr/share/doc/libssh-devel-0.5.5/html/libssh.TAGFILE
/usr/share/doc/libssh-devel-0.5.5/html/libssh_tutor_scp.html
/usr/share/doc/libssh2-1.4.2



# ./configure --debug

Starting hydra auto configuration ...
Detected 64 Bit Linux OS

Checking for zlib (libz.so, zlib.h) ...
                                        ... found
Checking for openssl (libssl, libcrypto, ssl.h, sha.h) ...
DEBUG: SSL_LIB=hwcap 1 nosegneg include ld.so.conf.d/*.conf /opt/pf_ring_6.0.3/lib/usr/lib64/tcl8.5 /usr/lib64/heimdal /usr/lib64/mysql /usr/lib/vmware-tools/lib32/libDeployPkg.so /usr/lib/vmware-tools/lib32/libvmGuestLibJava.so /usr/lib/vmware-tools/lib32/libvmGuestLib.so /usr/lib/vmware-tools/lib64/libDeployPkg.so /usr/lib/vmware-tools/lib64/libvmGuestLibJava.so /usr/lib/vmware-tools/lib64/libvmGuestLib.so /lib64 /usr/lib64 /usr/local/lib64 /opt/local/lib64 /lib /usr/lib /usr/local/lib /opt/local/lib
DEBUG: SSL_INC=/usr/include /usr/local/include /opt/include /opt/local/include
DEBUG: SSL_PATH=/usr/lib64/libssl
DEBUG: CRYPTO_PATH=/usr/lib64/libcrypto
DEBUG: SSL_INC=/usr/include/openssl/ssl.h
                                                       ... found
Checking for gcrypt (libgcrypt.so) ...
                                        ... found
Checking for idn (libidn.so) ...
DEBUG: IDN_PATH=/libidn
DEBUG: IDN_IPATH=/stringprep.h
DEBUG: PR29_IPATH=/pr29.h
                             ... NOT found, unicode logins and passwords will not be supported
Checking for curses (libcurses.so / term.h) ...
DEBUG: CURSES_PATH=/usr/lib64/libcurses
DEBUG: CURSES_IPATH=/usr/include/ncurses/term.h
                                            ... found, color output enabled
Checking for pcre (libpcre.so, pcre.h) ...
DEBUG: PCRE_PATH=/lib64/libpcre
DEBUG: PCRE_IPATH=/usr/include/pcre.h
                                       ... found
Checking for Postgres (libpq.so, libpq-fe.h) ...
DEBUG: POSTGRES_PATH=/usr/lib64/libpq
DEBUG: POSTGRES_IPATH=/usr/include/libpq-fe.h
                                             ... found
Checking for SVN (libsvn_client-1 libapr-1.so libaprutil-1.so) ...
DEBUG: SVN_PATH=/usr/lib64/libsvn_client-1
DEBUG: APR_PATH=/usr/lib64/libapr
DEBUG: SVN_IPATH=/usr/include/apr-1/
DEBUG: APR_IPATH=/usr/include/apr-1/
                                                               ... found
Checking for firebird (libfbclient.so) ...
DEBUG: FIREBIRD_PATH=/libfbclient
DEBUG: FIREBIRD_IPATH=/ibase.h
                                       ... NOT found, module firebird disabled
Checking for MYSQL client (libmysqlclient.so, math.h) ...
DEBUG: MYSQL_PATH=/usr/lib64/mysql/libmysqlclient
DEBUG: MYSQL_IPATH=/usr/include/mysql/mysql.h
                                                      ... found
Checking for AFP (libafpclient.so) ...
DEBUG: AFP_PATH=/libafpclient
DEBUG: AFP_IPATH=/afp.h
                                   ... NOT found, module Apple Filing Protocol disabled - Apple sucks anyway
Checking for NCP (libncp.so / nwcalls.h) ...
DEBUG: NCP_PATH=/libncp
DEBUG: NCP_IPATH=/ncp/nwcalls.h
                                         ... NOT found, module NCP disabled
Checking for SAP/R3 (librfc/saprfc.h) ...
DEBUG: SAPR3_PATH=hwcap/librfc
DEBUG: SAPR3_IPATH=/saprfc.h
                                      ... NOT found, module sapr3 disabled
Get it from http://www.sap.com/solutions/netweaver/linux/eval/index.asp
Checking for libssh (libssh/libssh.h) ...
DEBUG: SSH_PATH=/usr/lib64/libssh
DEBUG: SSH_IPATH=/usr/include/libssh/libssh.h
                                      ... found
Checking for Oracle (libocci.so libclntsh.so / oci.h and libaio.so) ...
DEBUG: ORACLE_LIB=hwcap 1 nosegneg include ld.so.conf.d/*.conf /opt/pf_ring_6.0.3/lib/usr/lib64/tcl8.5 /usr/lib64/heimdal /usr/lib64/mysql /usr/lib/vmware-tools/lib32/libDeployPkg.so /usr/lib/vmware-tools/lib32/libvmGuestLibJava.so /usr/lib/vmware-tools/lib32/libvmGuestLib.so /usr/lib/vmware-tools/lib64/libDeployPkg.so /usr/lib/vmware-tools/lib64/libvmGuestLibJava.so /usr/lib/vmware-tools/lib64/libvmGuestLib.so /lib64 /usr/lib64 /usr/local/lib64 /opt/local/lib64 /lib /usr/lib /usr/local/lib /opt/local/lib
DEBUG: ORACLE_INC=/usr/include /usr/local/include /opt/include /opt/local/include
DEBUG: ORACLE_PATH=/libocci
DEBUG: ORACLE_PATH=/libaio
DEBUG: ORACLE_IPATH=/oci.h
                                                                    ... NOT found, module Oracle disabled
Get basic and sdk package from http://www.oracle.com/technetwork/database/features/instant-client/index.html
Checking for GUI req's (pkg-config, gtk+-2.0) ...
                                              ... NOT found, optional anyway
Checking for Android specialities ...
                                  ... strrchr() found
                                  ... RSA_generate_key() found
Checking for secure compile option support in gcc ...
                                                  Compiling... yes
                                                  Linking... yes

Hydra will be installed into .../bin of: /usr/local
  (change this by running ./configure --prefix=path)

DEBUG: XDEFINES= -DHAVE_MYSQL_MYSQL_H -DLIBOPENSSL -DLIBNCURSES -DHAVE_PCRE -DLIBMYSQLCLIENT -DLIBPOSTGRES -DLIBSVN -DLIBSSH -DHAVE_ZLIB -DHAVE_GCRYPT -DHAVE_MATH_H
DEBUG: XLIBS= -lgcrypt -lz -lcurses -lssl -lpcre -lmysqlclient -lpq -lsvn_client-1 -lapr-1 -laprutil-1 -lsvn_subr-1 -lssh -lcrypto
DEBUG: XLIBPATHS=-L/usr/lib -L/usr/local/lib -L/lib -L/usr/lib64 -L/lib64 -L/usr/lib64 -L/usr/lib64/mysql
DEBUG: XIPATHS= -I/usr/include/mysql -I/usr/include/ncurses -I/usr/include -I/usr/include -I/usr/include/subversion-1 -I/usr/include/apr-1 -I/usr/include/subversion-1
DEBUG: PREFIX=/usr/local
DEBUG: XHYDRA_SUPPORT=
DEBUG: STRIP=strip
Writing Makefile.in ...
now type "make"

**Comment by vanhauser-thc** [comment]
can you please try the following:

make clean
./configure
vi Makefile  =>
  here you insert in XLIBPATHS=-L/usr/local/lib and XIPATHS=-I/usr/local/include (they come later in the list, so make them the first entry instead)
make

**Comment by KingJiJi** [comment]
i vi  Makefile:


---
CC=gcc
STRIP=strip
XDEFINES= -DHAVE_MYSQL_MYSQL_H -DLIBOPENSSL -DLIBNCURSES -DHAVE_PCRE -DLIBMYSQLCLIENT -DLIBPOSTGRES  -DLIBSSH -DHAVE_ZLIB -DHAVE_GCRYPT -DHAVE_MATH_H
XLIBS= -lgcrypt -lz -lcurses -lssl -lpcre -lmysqlclient -lpq -lsvn_client-1 -lapr-1 -laprutil-1 -lsvn_subr-1 -lssh -lcrypto
XLIBPATHS=-L/usr/local/lib -L/usr/lib -L/usr/local/lib -L/lib -L/usr/lib64 -L/lib64 -L/usr/lib64 -L/usr/lib64/mysql
XIPATHS= -I/usr/local/include -I/usr/include/mysql -I/usr/include/ncurses -I/usr/include -I/usr/include -I/usr/include/subversion-1 -I/usr/include/apr-1 -I/usr/include/subversion-1
PREFIX=/usr/local
XHYDRA_SUPPORT=
STRIP=strip
……
---

then:
make
---error  show---
hydra.c: In function ‘hydra_restore_write’:
hydra.c:715: warning: ignoring return value of ‘fwrite’, declared with attribute warn_unused_result
hydra-ssh.o: In function `start_ssh':
hydra-ssh.c:(.text+0x45d): undefined reference to `ssh_is_connected'
collect2: ld returned 1 exit status
make: *** [hydra] Error 1

**Comment by vanhauser-thc** [comment]
for me it looks like that you have multiple libssh instances installed:

```
/usr/local/lib/libssh.so.4.1.4
/usr/local/include/libssh/libssh.h
/usr/include/libssh/libssh.h
/usr/lib64/libssh.so.4
```

so this is IMHO the root of the problem. I would recommend to remove both (the one from the  system via the package manager, plus the other one by hand), download the current libssh.org code, compile, install, and then retry with hydra. the libssh version you have is super old too.

**Comment by KingJiJi** [comment]
i usually install package use 'yum install ……'
but your INSTALL show error .

'Redhat/Fedora:  yum install openssl-devel pcre-devel ncpfs-devel postgresql-devel libssh-devel subversion-devel libncurses-devel'

**ERROR**  
‘Package openssl-devel-1.0.1e-57.el6.x86_64 already installed and latest version
Package pcre-devel-7.8-7.el6.x86_64 already installed and latest version
**_No package ncpfs-devel available_.**
Package postgresql-devel-8.4.20-8.el6_9.x86_64 already installed and latest version
Package libssh-devel-0.5.5-5.el6.x86_64 already installed and latest version
Package subversion-devel-1.6.11-15.el6_7.x86_64 already installed and latest version
**_No package libncurses-devel available._**’

**Comment by vanhauser-thc** [comment]
newer Linux OS versions do not have all packages (because old, outdated protocols). you can ignore that.

I will update the documentation.
