### ISSUE TITLE
Each printf digit expands to take two places

### ISSUE THREAD

**Issue by deargle** [vanhauser-thc/thc-hydra#357]
```
uname -a
Linux kali 4.18.0-kali1-686-pae #1 SMP Debian 4.18.6-1kali1 (2018-09-10) i686 GNU/Linux
```
`Hydra v8.7-dev (c) 2018` (I'm on master branch, pulled today)

Hydra verbosity logs are borked for a head-scratching reason. Each `printf` digit expansions from the hydra functions is taking _two_ positions. 

An odd example: I added this in `hydra.c:3460`, where `math2=896525`

```
printf("foo %lu bar %lu foobar %lu %lu, math2, math2)
```
Output:

```
foo 896525 bar 0 foobar 896525 0
```

This is a problem because the verbose logs end up looking like this:

```
[ATTEMPT] target <target> - login "<login>" - pass "123456" - 1 of 0 [child 14344399] (0/0)
[ATTEMPT] target <target> - login "<login>" - pass "12345" - 2 of 0 [child 14344399] (0/1)
```

...when they should look like:

```
[ATTEMPT] target <target> - login "<login>" - pass "123456" - 1 of 14344399 [child 0] (0/0)
[ATTEMPT] target <target> - login "<login>" - pass "12345" - 2 of 14344399 [child 1] (0/0)
```

I'm novice in c, so I'm banging my head. Perhaps something to do with output buffering that hydra is doing? Scratching my head.

**Comment by deargle** [comment]
Seems to fix it if all `%lu`'s are changed to `%llu`.

**Comment by dmaciejak** [comment]
Should be fixed now, please test.
