### ISSUE TITLE
Cant compile on Android

### ISSUE THREAD

**Issue by TumorenSapjes** [vanhauser-thc/thc-hydra#36]
Errors while compiling on Android while using c4droid with gcc support.
Some error about lssp and pw-inspector.
http://i.imgur.com/aYPYYoZ.png

**Comment by vanhauser-thc** [comment]
I do not have android, so I can not test this.
make try this: run ./configure and then edit the Makefile and remove the SEC=... line

**Comment by LOOLOOOL** [comment]
no need to compile for android just egt linux deploy 
and get kali or whatever linux then install hydra on there

you can make linux image small aswell

**Comment by Joe12323231** [comment]
How do I install the gz file on my Android device? Whenever I type ./configure it would say permission denied? How do I fix this?

**Comment by Joe12323231** [comment]
By the way if I ran Kali linux would it be slow or OK by the way where is the smaller image file?

**Comment by vanhauser-thc** [comment]
you have to compile it first with a cross compiler for Android.
Dont ask me about specifics, I have never done this, nor do I have an Android phone ...
sorry.

**Comment by Joe12323231** [comment]
Ok Thanks :) Is there a way to run Hydra through a proxy that will actually
work. Because I tried to run this through TOR and it did not crack my
password whereas without using proxy, it managed to crack my password. So
is there a way to run Hydra through a proxy where it will be able to
confirm my password. ThankYou :)

**Comment by vanhauser-thc** [comment]
read the README -> "HOW TO SCAN/CRACK OVER A PROXY"

**Comment by Joe12323231** [comment]
You have received a new fax.



Please check your fax document in the attachment to this e-mail.



Date of scan:      Thu, 19 Nov 2015 11:31:25 +0300

Quality:           100 DPI

Pages sent:        9

Scanned in:        23 seconds

Filesize:          116 Kb

Author:            Larry Locke

Filename:          scan-0000573657.doc



Thanks for choosing Interfax!

**Comment by Joe12323231** [comment]
New incoming fax document.

You can find your fax document in the attachment.

Resolution:       100 DPI
Author:           Jamie Meyer
Scan date:        Fri, 20 Nov 2015 06:27:41 +0300
Pages:            7
Fax name:         task_00000439261.doc
Scan time:        6 seconds
Filesize:         269 Kb

Thanks for choosing Interfax!
