### ISSUE TITLE
Hydra Sleep instead of die

### ISSUE THREAD

**Issue by Finlaydag33k** [vanhauser-thc/thc-hydra#37]
can I make Hydra-GTK sleep for a certain amount of time, then re-try (and if it fails, sleep again etc.) instead of that it just dies... I've been bruteforcing my own FTP (i forgot the password, but got some clues) but it just dies after a while because of connection errors (server temp-bans the hydrabox)

**Comment by vanhauser-thc** [comment]
I did not write xhydra, nor do I maintain it. I - and most people - use the console.
But if you want to write a fix - that would be appreciated.
