### ISSUE TITLE
Use crunch to give password 

### ISSUE THREAD

**Issue by maelfosso** [vanhauser-thc/thc-hydra#371]
Hi,

I tried to use `crunch` so that it generates password for `hydra`. As I don't have too much space in my hard drive, I wanted to use it inline using pipe.
I tried many command without success. You will find them below

- crunch 4 6 -f /usr/share/crunch/charset.lst lalpha | hydra -l maelelvis -p - 192.168.1.105 ftp
- crunch 4 6 -f /usr/share/crunch/charset.lst lalpha | hydra -l maelelvis -P - 192.168.1.105 ftp
- crunch 4 6 -f /usr/share/crunch/charset.lst lalpha --stdout | hydra -l maelelvis -p - 192.168.1.105 ftp
- crunch 4 6 -f /usr/share/crunch/charset.lst lalpha | hydra -vV -l maelelvis 192.168.1.105 ftp -p -
- crunch 4 6 -f /usr/share/crunch/charset.lst lalpha | xargs hydra -vV -l maelelvis 192.168.1.105 ftp -p {}
- crunch 4 6 -f /usr/share/crunch/charset.lst lalpha | xargs hydra -vV -l maelelvis -p {} 192.168.1.105 ftp
- crunch 4 6 -f /usr/share/crunch/charset.lst lalpha | xargs -I % hydra -vV -l maelelvis -p % 192.168.1.105 ftp
- crunch 4 6 -f /usr/share/crunch/charset.lst lalpha | xargs hydra -vV -l maelelvis 192.168.1.105 ftp -p {}
- crunch 4 6 -f /usr/share/crunch/charset.lst lalpha | xargs -L1 % hydra -vV -l maelelvis -p % 192.168.1.105 ftp
- crunch 4 6 -f /usr/share/crunch/charset.lst lalpha | tr '\n' '\0' | xargs -L1  hydra 192.168.1.105 ftp -vV -l maelelvis -p
- crunch 4 6 -f /usr/share/crunch/charset.lst lalpha | xargs -L1  hydra 192.168.1.105 ftp -vV -l maelelvis -p
- crunch 4 6 -f /usr/share/crunch/charset.lst lalpha --stdout | hydra 192.168.1.105 ftp -vV -l maelelvis -P-
- crunch 4 6 -f /usr/share/crunch/charset.lst lalpha --stdout | hydra 192.168.1.105 ftp -vV -l maelelvis -p

Could you help to find a solution ?

**Comment by vanhauser-thc** [comment]
yes it is not possible, and making it possible to support this would be a big rewrite and features like -R recovery would not work.
you can use the -x option for similar functionality or pipe crunch to an file and load that file with hydra
