### ISSUE TITLE
Cygwin64 Terminal

### ISSUE THREAD

**Issue by master202020** [vanhauser-thc/thc-hydra#372]
Good afternoon -

I am trying to connect Cygwin following a guide online but tells me to use cd /cygdrive/c/hydra-8.1.tar but the problem is i do not see any files with .tar? So how am i able to connect Cygwin with Hydra? Can you give me some information in doing so?

**Comment by vanhauser-thc** [comment]
this is not a problem with hydra but basic unix/cygwin usage, and downloading files and compiling it.
this is not a help forum and solely for reporting bugs in the software, sory.

**Comment by Robin6464** [comment]
I can only confirm that hydra 9.0 and xhydra-gtk works in cygwin with gtk and cygwin xserver installed.

**Comment by asdat3** [comment]
Hey,

you probably have the folder...
just cd into the folder and launch ./configure there

Have a great day

@master202020
