### ISSUE TITLE
 hydra was compiled without SSL support. Install openssl and recompile!

### ISSUE THREAD

**Issue by nolan-buller** [vanhauser-thc/thc-hydra#375]
i tried reinstalling openssl and hydra but nothing worked. heres the output: 
Hydra v8.7-dev (c) 2018 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

[WARNING] hydra was compiled without SSL support. Install openssl and recompile! Option ignored...
Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2018-11-11 23:22:46
[ERROR] Compiled without SSL support, module not available

heres my code: 
hydra -s 443 -S -V -l xxl3gi7amixx -P /root/Desktop/pwlist.txt www.instagram.com https-post-form "/accounts/login/?hl=en&source=auth_switcher:username=^USER^&password=^PASS^&queryParams=%7B%22source%22%3A%22auth_switcher%22%7D:S=logout" -vV -f

 right now im trying to crack my old instagram account i made and im having trouble enabling ssl support. Do you know a way to fix this?

**Comment by nolan-buller** [comment]
sudo apt-get install libssl-dev libssh-dev
git clone https://github.com/vanhauser-thc/thc-hydra
cd thc-hydra
./configure
make
sudo make install

heres the fix follow this

**Comment by vanhauser-thc** [comment]
that is explained in the README :)

**Comment by 42u3** [comment]
have the same issue on OSX
