### ISSUE TITLE
Keeps running when done, negative "to do"

### ISSUE THREAD

**Issue by gdudek** [vanhauser-thc/thc-hydra#38]
For me it keeps running when finished, and since the "to do" count is negative and printed with %u a crazy huge number gets printed out.

**Comment by vanhauser-thc** [comment]
please write a helpful entry.
exact command line. full output.
I do not own a crystal ball to be able to see what your issue is or when it is happending.

**Comment by vanhauser-thc** [comment]
please supply the necessary information the next days

**Comment by gdudek** [comment]
I appreciate you effort in writing the code and making it available, but writing snarky replies to issue postings isn't a great way to encourage useful feedback.   Anyhow, I do not currently have access to the machine where I was testing, but the command line was:
  The command line was: ./hydra  -L  admin  -P passwords.txt ssh://XXX [actual URL dleted]
The computed number of entries was obviously after a while negative and the %u format in the code made the number appear to be a huge int, but the program did not exit.  Nothing more informative regarding the problem was logged.  It's all I can report just now.

 I can make a different bug report/observation.  With:
    hydra -v -V -t 6 -e nsr -L names.txt -P wordlist-combined.txt ssh://XXX
the feedback looked like:
Hydra v8.2-dev (c) 2014 by van Hauser/THC - ....
.. irrelevant stuff deleted ...
[ATTEMPT] target XXX - login "admin" - pass "admin" - 1 of 78820911 [child 0]
    .. more attempts deleted
[ERROR] could not connect to target port 22
[ERROR] ssh protocol error
-- I am pretty sure this is symptomatic of excessive (6) parallel attempts.

But with:
        hydra -t 6 -e nsr -L names.txt -P wordlist-combined.txt ssh://XXX
no errors are logged and just status messages appear, whereas I suggest the errors should still
be logged without -V or -v since they are significant.

Obviously this can be worked around with a smaller thread count, but logging the errors no matter what would be appropriate IMHO.  In other words, line 198 in hydra-ssh.c should not be prefixed by an "if verbose",  Likewise for other error cases.
