### ISSUE TITLE
Specifying targets by CIDR doesn't work

### ISSUE THREAD

**Issue by wrffrz** [vanhauser-thc/thc-hydra#383]
Rather than providing a list of individual hostnames or IP addresses, I'd like to scan an entire network segment and the documentation claims that you can do this by specifying targets in CIDR format like 192.168.0.0/24, but this doesn't work:

$ hydra -C ../credentials -t 4 172.16.0.0/24 ssh
Hydra v8.9-dev (c) 2019 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2019-01-08 16:33:49
[ERROR] You seem to mix up "service://target:port/options" syntax with "target service options" syntax. Read the README on how to use hydra correctly!
$ hydra -C ../credentials -t 4 ssh://172.16.0.0/24
Hydra v8.9-dev (c) 2019 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2019-01-08 16:34:29
[DATA] max 2 tasks per 1 server, overall 2 tasks, 2 login tries, ~1 try per task
[DATA] attacking ssh://172.16.0.0:22/24
[ERROR] could not connect to ssh://172.16.0.0:22 - Failed to connect: Network is unreachable
$ hydra -C ../credentials -t 4 ssh://172.16.0.0/24/
Hydra v8.9-dev (c) 2019 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2019-01-08 16:34:34
[DATA] max 2 tasks per 1 server, overall 2 tasks, 2 login tries, ~1 try per task
[DATA] attacking ssh://172.16.0.0:22/24/
[ERROR] could not connect to ssh://172.16.0.0:22 - Failed to connect: Network is unreachable
$

**Comment by vanhauser-thc** [comment]
thanks for reporting this.
fix is in the repository now, please test
