### ISSUE TITLE
Issue while installing

### ISSUE THREAD

**Issue by stxrmhook** [vanhauser-thc/thc-hydra#389]
I'm on mac OS X and whenever I try to install hydra with homebrew I get this error:

==> make all install
Last 15 lines from /Users/Stxrm/Library/Logs/Homebrew/hydra/02.make:
clang -I. -O3 -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2   -c hydra-rpcap.c -DLIBOPENSSL -DLIBNCURSES -DHAVE_PCRE -DLIBSSH -DHAVE_ZLIB -DHAVE_MATH_H -I/opt/local/include -I/opt/local/include -I/usr/local/include
clang -I. -O3 -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2   -c hydra-radmin2.c -DLIBOPENSSL -DLIBNCURSES -DHAVE_PCRE -DLIBSSH -DHAVE_ZLIB -DHAVE_MATH_H -I/opt/local/include -I/opt/local/include -I/usr/local/include
clang -I. -O3 -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2   -c crc32.c -DLIBOPENSSL -DLIBNCURSES -DHAVE_PCRE -DLIBSSH -DHAVE_ZLIB -DHAVE_MATH_H -I/opt/local/include -I/opt/local/include -I/usr/local/include
clang -I. -O3 -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2   -c d3des.c -DLIBOPENSSL -DLIBNCURSES -DHAVE_PCRE -DLIBSSH -DHAVE_ZLIB -DHAVE_MATH_H -I/opt/local/include -I/opt/local/include -I/usr/local/include
clang -I. -O3 -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2   -c bfg.c -DLIBOPENSSL -DLIBNCURSES -DHAVE_PCRE -DLIBSSH -DHAVE_ZLIB -DHAVE_MATH_H -I/opt/local/include -I/opt/local/include -I/usr/local/include
clang -I. -O3 -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2   -c ntlm.c -DLIBOPENSSL -DLIBNCURSES -DHAVE_PCRE -DLIBSSH -DHAVE_ZLIB -DHAVE_MATH_H -I/opt/local/include -I/opt/local/include -I/usr/local/include
clang -I. -O3 -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2   -c sasl.c -DLIBOPENSSL -DLIBNCURSES -DHAVE_PCRE -DLIBSSH -DHAVE_ZLIB -DHAVE_MATH_H -I/opt/local/include -I/opt/local/include -I/usr/local/include
clang -I. -O3 -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2   -c hmacmd5.c -DLIBOPENSSL -DLIBNCURSES -DHAVE_PCRE -DLIBSSH -DHAVE_ZLIB -DHAVE_MATH_H -I/opt/local/include -I/opt/local/include -I/usr/local/include
clang -I. -O3 -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2   -c hydra-mod.c -DLIBOPENSSL -DLIBNCURSES -DHAVE_PCRE -DLIBSSH -DHAVE_ZLIB -DHAVE_MATH_H -I/opt/local/include -I/opt/local/include -I/usr/local/include
clang -I. -O3 -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2   -c hydra-time.c -DLIBOPENSSL -DLIBNCURSES -DHAVE_PCRE -DLIBSSH -DHAVE_ZLIB -DHAVE_MATH_H -I/opt/local/include -I/opt/local/include -I/usr/local/include
hydra-mod.c:10:10: fatal error: 'pcre.h' file not found
#include <pcre.h>
         ^
1 error generated.
make: *** [hydra-mod.o] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

**Comment by vanhauser-thc** [comment]
you need to install libpcre-dev or pcre-dev.
seriously. look at the stuff and dont create issues ...
