### ISSUE TITLE
configure '--disable-xhydra' option broken

### ISSUE THREAD

**Issue by maaaaz** [vanhauser-thc/thc-hydra#39]
Hello, 

The `--disable-xhydra` option in `configure` is currently broken.

I have been able to fix it by replacing the line #1125:
* from  `if [ "X" = "X$XHYDRA_SUPPORT" ]; then`
* to `if [ "Xdisable" = "X$XHYDRA_SUPPORT" ]; then`, because that variable value is either empty or "disable" before that check.

I don't know whether it is the most elegant way to do it but it does work.

Best regards

**Comment by vanhauser-thc** [comment]
the fix was a little bit more complicated, but not much :)
thanks!
