### ISSUE TITLE
socketpair creation failed: Too many open files

### ISSUE THREAD

**Issue by mahdi-cll** [vanhauser-thc/thc-hydra#393]
After some hours hydra started to give error. code:
`hydra -m TLS -V -l khedmat-moghaddas -P rockyou.txt -t 16 -f mail.police.ir imap`
error:
`socketpair creation failed: Too many open files`
Hydra v8.9.1 
OS: Archlinux 

-----
(I can't not mention it) reporting security flaws to companies are accepted except for 2 thing 
1-wifi internet hacking and 2- chipset copy protections

**Comment by caoya171193579** [comment]
Excuse me, have you found a solution?

**Comment by vanhauser-thc** [comment]
@caoya171193579 no, but he was using an old version of hydra. What version are you using, what is your command line and when does this happen to you?
