### ISSUE TITLE
hydra none use in gmail?

### ISSUE THREAD

**Issue by Bruce3677** [vanhauser-thc/thc-hydra#397]
I create an account and try to crack it ,but even though i type my password in wordlist ,it still shows "0 valid passwords founds"
Here is my code ----    hydra -S -l ****@gmail.com -P /root/Documents/test11 -v -V -e ns -s 465 smtp.gmail.com smtp

**Comment by vanhauser-thc** [comment]
reading is hard .... ->

"[WARNING] Google Mail has bruteforce detection and sends false positives. You are not doing anything illegal right?"
