### ISSUE TITLE
Failure message in hex format

### ISSUE THREAD

**Issue by nohope91** [vanhauser-thc/thc-hydra#398]
hello  Mr. Van Hauser, I have a quick question
I got the failure message response from a web form which uses http-post-form
but I'm a little bit confused, because it's in HEX format :
lockparams|invalid_credentials|0

should I include all of it? or just the ( invalid_credentials ) ?
Thanks ..

**Comment by vanhauser-thc** [comment]
1. this is not a help forum but solely for reporting bugs

2. I have no clue what you are talking about. way too little context

**Comment by nohope91** [comment]
Ok Sir no problem, you may delete the thread :)

**Comment by nohope91** [comment]
I have included only the (invalid_credentials) and it worked :)
