### ISSUE TITLE
[ERROR] definition for password bruteforce (-x) generates more than 4 billion passwords

### ISSUE THREAD

**Issue by sylerxin** [vanhauser-thc/thc-hydra#399]
Hello. when i use your program, there has some error. i tried to google it, but it doesn't have work. I  tried to use the standard brute force with this command
 ` hydra -l root -x 6:12:aA1 -f -t 4 -vV -e ns my_test_ip mysql` 
but it have this error. i don't know why happen this. can u tell me how to solve this ? the error is 

> Hydra v8.9-dev (c) 2019 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.
> Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2019-04-04 11:00:19
> [ERROR] definition for password bruteforce (-x) generates more than 4 billion passwords

**Comment by vanhauser-thc** [comment]
your definition produces too many possible password combinations. reduce the complexity.

**Comment by sylerxin** [comment]
yeah, I tried it. But it still have the same error. I tried the `-x 6:12:a` option.
However, it also makes mistakes .:-(

**Comment by SagenKoder** [comment]
> 
> 
> yeah, I tried it. But it still have the same error. I tried the `-x 6:12:a` option.
> However, it also makes mistakes .:-(

26^6 = 308915776 = 308 million passwords
26^7 = 8031810176 = 8 billion passwords
26^8 = 208827064576 = 208 billion passwords

Your definition produces a LOT of password combinations. A lot more than 4 billion.

**Comment by DarthVader1108** [comment]
Then how are we gonna fix this? I also tried just maximum 8 and minimum 7 characters with just lowercase letters, and it says the same thing. The limit is too small. How can we change the limit? Honestly, I don't care how long the password cracking would take, I just care about the limit.

**Comment by vanhauser-thc** [comment]
then you create a wordlist with all possible entries (lots of tools for this) and feed this to hydra

**Comment by DarthVader1108** [comment]
> then you create a wordlist with all possible entries (lots of tools for this) and feed this to hydra
I can create a wordlist if I want to. The problem is, I don't have enough storage space. That is why I want to brute force attack. It is simpler and has more success rate. Isn't there really a way to change the limit? Some accounts use long passwords. I really need it.

**Comment by vanhauser-thc** [comment]
how long would it need to crack a password with a length of 8, only lowercase characters, if you have 100 cracking sessions in parallel, and you can do 10 per session per second? (these all overly optimistic assumptions.)  if you do the math, you will see that what you want is pointless.

**Comment by DarthVader1108** [comment]
> how long would it need to crack a password with a length of 8, only lowercase characters, if you have 100 cracking sessions in parallel, and you can do 10 per session per second? (these all overly optimistic assumptions.) if you do the math, you will see that what you want is pointless.

Well, 8 is the minimum number of characters in social media sites. Just answer me, can the limit be changed or not?

**Comment by vanhauser-thc** [comment]
Can’t

**Comment by mooleshacat** [comment]
How to force? I have 32 cores.

**Comment by tomschall** [comment]
You guys could fork the code, do the changes that are needed to stop the program from executing and compile by yourself...
