### ISSUE TITLE
Password list usage improvement

### ISSUE THREAD

**Issue by Onepamopa** [vanhauser-thc/thc-hydra#413]
Would it be possible to specify a min:max length for a password in a huge password list?

The list could then be loaded into memory with all the passwords matching min/max length, and read from there. I know this can be done with 2 commands to a new list, but still, it would be more convenient if hydra can handle it.

**Comment by vanhauser-thc** [comment]
this increases the complexity of hydra unnecessarily when it can just be done with a single command
