### ISSUE TITLE
I have error with [ERROR] Compiled without FREERDP2 support, module not available!

### ISSUE THREAD

**Issue by pawaritp** [vanhauser-thc/thc-hydra#420]
I have error with **[ERROR] Compiled without FREERDP2 support, module not available!**
I try to fix following issue #390

try synced the github repository
./configure
make
make install

Version is Hydra v9.1-dev (c) 2019 by van Hauser/THC

**Comment by vanhauser-thc** [comment]
did you do a make clean?

**Comment by vanhauser-thc** [comment]
and did you install libfreerdp? check the output of ./configure if it says its missing !

**Comment by pawaritp** [comment]
> and did you install libfreerdp? check the output of ./configure if it says its missing !
What command install libfreerdp
You mean sudo apt-get install libssl-dev libssh-dev libidn11-dev libpcre3-dev \ libgtk2.0-dev libmysqlclient-dev libpq-dev libsvn-dev \ firebird-dev libncp-dev? I try it.

No error 
Hydra will be installed into .../bin of: /usr/local
  (change this by running ./configure --prefix=path)

Writing Makefile.in ...
now type "make"

**Comment by pawaritp** [comment]
I use make clean and ./config ; make; make install
Now It's work!
No [ERROR] Compiled without FREERDP2 support, module not available!
but show this
**[ERROR] freerdp: The connection failed to establish.**

**Comment by vanhauser-thc** [comment]
I would recommend to look with wireshark. maybe that service had more security?

**Comment by griffinpa0** [comment]
Hi  There,
I'm having the exact same issue, Is there a workaround 
[ERROR] complied without FREERDP2 support,module not available

See below 
root@kali:~/thc-hydra# ./configure 

Starting hydra auto configuration ...
Detected 64 Bit Linux OS

Checking for zlib (libz.so, zlib.h) ...
                                        ... found
Checking for openssl (libssl, libcrypto, ssl.h, sha.h) ...
                                                       ... found
Checking for gcrypt (libgcrypt.so) ...
                                        ... gcrypt not found, radmin2 module disabled
Checking for idn (libidn.so) ...
                             ... found
Checking for curses (libcurses.so / term.h) ...
                                            ... found, color output enabled
Checking for pcre (libpcre.so, pcre.h) ...
                                       ... found
Checking for Postgres (libpq.so, libpq-fe.h) ...
                                             ... NOT found, module postgres disabled
Checking for SVN (libsvn_client-1 libapr-1.so libaprutil-1.so) ...
                                                               ... NOT found, module svn disabled
Checking for firebird (libfbclient.so) ...
                                       ... NOT found, module firebird disabled
Checking for MYSQL client (libmysqlclient.so, math.h) ...
                                                      ... NOT found, module Mysql will not support version > 4.x
Checking for AFP (libafpclient.so) ...
                                   ... NOT found, module Apple Filing Protocol disabled - Apple sucks anyway
Checking for NCP (libncp.so / nwcalls.h) ...
                                         ... NOT found, module NCP disabled
Checking for SAP/R3 (librfc/saprfc.h) ...
                                      ... NOT found, module sapr3 disabled
Get it from http://www.sap.com/solutions/netweaver/linux/eval/index.asp
Checking for libssh (libssh/libssh.h) ...
                                      ... found
Checking for Oracle (libocci.so libclntsh.so / oci.h and libaio.so) ...
                                                                    ... NOT found, module Oracle disabled
Get basic and sdk package from http://www.oracle.com/technetwork/database/features/instant-client/index.html
Checking for Memcached (libmemcached.so, memcached.h) ...
                                             ... NOT found, module memcached disabled
Checking for Freerdp2 (libfreerdp2.so, freerdp/*.h, libwinpr2.so, winpr/*.h) ...
                                             ... NOT found, module rdp disabled
Checking for Mongodb (libmongoc-1.0.so, mongoc.h, libbson-1.0.so, bson.h) ...
                                             ... NOT found, module mongodb disabled
Checking for GUI req's (pkg-config, gtk+-2.0) ...
                                              ... NOT found, optional anyway
Checking for Android specialities ...
                                  ... strrchr() found
                                  ... RSA_generate_key() found
Checking for secure compile option support in gcc ...
                                                  Compiling... yes
                                                  Linking... yes

Hydra will be installed into .../bin of: /usr/local
  (change this by running ./configure --prefix=path)

Writing Makefile.in ...
now type "make"
root@kali:~/thc-hydra#

**Comment by griffinpa0** [comment]
Checking for Freerdp2 (libfreerdp2.so, freerdp/.h, libwinpr2.so, winpr/.h) ...
... NOT found, module rdp disabled

**Comment by pawaritp** [comment]
@vanhauser-thc Thank you. Now I can use it.
@griffinpa0 I use follow this
**for ubuntu 18.04:**
sudo apt install freerdp2-dev
make clean
./configure
make
make install

**Comment by mellisarunn** [comment]
I am having this exact same problem. Can you please help?
I am running hydra with cygwin on windows. 
"complied without FREERDP2 support, rdp module not available"

**Comment by nachancan** [comment]
> 
> 
> @vanhauser-thc Thank you. Now I can use it.
> @griffinpa0 I use follow this
> **for ubuntu 18.04:**
> sudo apt install freerdp2-dev
> make clean
> ./configure
> make
> make install

This fix the problem of not working. But is not working properly anyway. Always match with the user or password. I tried with user root, roott and roottt.
Is a CTF and I don't know the correct one, but those are not valid.

```
/hydra -V -t2 -f -l roottt -P /usr/share/metasploit-framework/data/wordlists/vnc_passwords.txt rdp://10....
Hydra v9.1-dev (c) 2019 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2019-06-14 21:05:08
[WARNING] the rdp module is experimental. Please test, report - and if possible, fix.
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking rdp://10.....:3389/
[ATTEMPT] target 10...... - login "roottt" - pass "password" - 1 of 1 [child 0] (0/0)
[3389][rdp] host: 10........   login: roottt   password: password
[STATUS] attack finished for 10........ (valid pair found)
1 of 1 target successfully completed, 1 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2019-06-14 21:05:09
```

**Comment by blueskea** [comment]
I solved the problem on CentOS7
### 1. Install FreeRDP
```
wget https://github.com/FreeRDP/FreeRDP/archive/2.0.0-rc4.tar.gz
tar -zxvf 2.0.0-rc4.tar.gz
cd FreeRDP-2.0.0-rc4/
mkdir build
cd build/
cmake ../
make
make install
```
After install, the  .so package is here：
```
/usr/local/lib64/libfreerdp2.so.2.0.0
/usr/local/lib64/libfreerdp2.so.2
/usr/local/lib64/libfreerdp2.so
```
### 2. ReInstall Hydra
```
# Skip: wget https://github.com/vanhauser-thc/thc-hydra/archive/v9.0.tar.gz
# Skip tar -zxvf v9.0.tar.gz
cd thc-hydra-9.0/
make clean
./configure
make
make install
```
### 3. Use With RDP
```
export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH
hydra -l administrator -p testpass rdp://192.168.1.1
```

**Comment by DaddyBigFish** [comment]
./configure --with-freerdp=3

Kali now supports xfreerdp version 3
