### ISSUE TITLE
I entered my correct username and password in the file.

### ISSUE THREAD

**Issue by sunozil** [vanhauser-thc/thc-hydra#421]
Hi developer,
i have the error "1 of 1 target completed, 0 valid password found"，
I am trying to crack my mysql password，hydra -L /user.txt -P /pass.txt XXXX mysql，I entered my correct username and password in the file.

**Comment by vanhauser-thc** [comment]
does this also happen when you only use -l and -p with the correct values?

**Comment by sunozil** [comment]
> does this also happen when you only use -l and -p with the correct values?

Yes, only use -l and -p show “1 of 1 target completed, 0 valid passwords found”。 my operating system is macOS10.14.5, I used homebrew to install hydra v8.9.1。

**Comment by vanhauser-thc** [comment]
a) compile yourself and dont use homebrew. too much in it is broken, e.g. libssh
b) current is 9.0

but that would not change anything about your problem.

so when you use "mysql -p pass -u user ..." does that work?
Maybe you need to specify the database name? (-m dbname    for hydra mysql)

**Comment by sunozil** [comment]
Of course, I can start my database normally via mysql... I don't think this has anything to do with homebrew because I just use the MySQL protocol, but I will also try to compile it myself and use other versions.

**Comment by vanhauser-thc** [comment]
is your database name you connect to different than "mysql"?

**Comment by sunozil** [comment]
Is mysql

**Comment by vanhauser-thc** [comment]
then I have no clue what the issue is.
you might have a look with wireshark and check what the difference is from the mysql  and the hydra what they are sending.

**Comment by liuliu663** [comment]
i got the same problem too

**Comment by sunozil** [comment]
你的操作环境是什么，hydra版本呢

**Comment by NaheelSalman** [comment]
Heyy developer
could you help me?
i have got the same error:
i have tried the following commands on my own accounts
hydra -l [username]@mail.com -P "/root/Desktop/Hackings/PasswordLists/passtest.txt" -e ns -V -s 465 smtp://smtp.mail.yahoo.com
and in that text file i have written correct passwords
but it gives me result like this:
1 of 1 target completed, 0 valid passwords found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2019-07-01 05:43:11
and it just passes the correct passwords and jumps to the next one
Thanks in advance

**Comment by sunozil** [comment]
I downloaded kali-linux through docker, downloaded hydra v8.8, and solved the problem of unsuccessful mysql password.

**Comment by NaheelSalman** [comment]
Would you like to illustrate which command did you use?
please ! @sunozil 
**Because** 
i have used the following commands:

> `hydra -l [correct_mail] -p [actual_password] smtp://smtp.mail.yahoo.com

` in updated version of hydra 8.8 but it gives me this result :

> [DATA] attacking smtp://smtp.mail.yahoo.com:25/
> [STATUS] 2.00 tries/min, 2 tries in 00:01h, 1 to do in 00:01h, 1 active
> [STATUS] 2.00 tries/min, 4 tries in 00:02h, 1 to do in 00:01h, 1 active
> 1 of 1 target completed, 0 valid passwords found

**Comment by sunozil** [comment]
@NaheelSalman you can try it smtps://smtp.mail.yahoo.com

I can't give you a better suggestion because I haven't cracked the email password. If you are successful, please teach me here.

**Comment by sunozil** [comment]
@vanhauser-thc Hi developer,
Via Wireshark
docker kali hydra:1.three times handshake,2.MySQL Server Greeting proto,3.TCP、Request Quit、Response Error,4.Five times TCP RST,5.MySQL Server Greeting proto、TCP ACK、MySQL Login Request user=root  db= MySQL、TCP ACK、Response OK.
homebrew hydra:Always Request Quit、Response Error,and after TCP RST have UDP Pro Protocol.

**Comment by vanhauser-thc** [comment]
@sunozil can you please upload the wireshark capture? for one hydra login attempt (which does not work) and one where you use the mysql client (and the auth works with the same credentials).
beware though that by posting the wireshark capture other people will be able to see the password.

**Comment by sunozil** [comment]
<img width="1639" alt="unsuccess" src="https://user-images.githubusercontent.com/37857351/60937250-4dadab00-a302-11e9-8f0f-e117a238a0c4.png">

**Comment by sunozil** [comment]
<img width="1629" alt="kalisuccess" src="https://user-images.githubusercontent.com/37857351/60938107-489e2b00-a305-11e9-923e-b870f7b7d21e.png">

**Comment by sunozil** [comment]
@vanhauser-thc The first one is unsuccessful, the second one is successful in kali.
No password and this database is not important.

**Comment by vanhauser-thc** [comment]
@sunozil 
the .pcap capture file itself. not a screenshot.
how can I see the packet data when you make such a screenshot? ;)
just drag and drop ...

**Comment by sunozil** [comment]
[pcap.zip](https://github.com/vanhauser-thc/thc-hydra/files/3378139/pcap.zip)

**Comment by vanhauser-thc** [comment]
@sunozil

thanks for the pcap. I do not see a successful connection there. did you only use hydra for that capture?
I also need one with a successful login, e.g. with mysql client

**Comment by sunozil** [comment]
@vanhauser-thc mysql client
[mysql.pcapng.zip](https://github.com/vanhauser-thc/thc-hydra/files/3380772/mysql.pcapng.zip)

**Comment by vanhauser-thc** [comment]
@sunozil 

hmm that did not help as much as I hoped. can you please paste the full output of:

hydra -l root -p THEREALPASSWORD -v -d mysql://10.10.10.172

**Comment by sunozil** [comment]
[mysql.pcapng.zip](https://github.com/vanhauser-thc/thc-hydra/files/3382200/mysql.pcapng.zip)
this mysql client can find something?

**Comment by vanhauser-thc** [comment]
@sunozil  - please paste the tool output of that hydra command. not a pcap :)

**Comment by sunozil** [comment]
Hydra v9.0 (c) 2019 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2019-07-15 13:22:55
[INFO] Reduced number of tasks to 4 (mysql does not like many parallel connections)
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking mysql://10.10.10.172:3306/
1 of 1 target completed, 0 valid passwords found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2019-07-15 13:22:56

**Comment by vanhauser-thc** [comment]
@sunozil  please dont waste your time and mine.

I specifically asked you to send the full output of:
hydra -l root -p THEREALPASSWORD -v -d mysql://10.10.10.172

but you executed it with different command line options.
(note you have to put the real password in there)

**Comment by hurricane618** [comment]
hurricane618@hurricane618-mbp: hydra -l root -p root -v -d mysql://127.0.0.1
Hydra v9.0 (c) 2019 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

[DEBUG] Output color flag is 1
Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2019-12-05 17:33:06
[DEBUG] cmdline: hydra -l root -p root -v -d mysql://127.0.0.1
[DEBUG] opt:7 argc:8 mod:mysql tgt:127.0.0.1 port:0 misc:(null)
[INFO] Reduced number of tasks to 4 (mysql does not like many parallel connections)
[VERBOSE] More tasks defined than login/pass pairs exist. Tasks reduced to 1
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking mysql://127.0.0.1:3306/
[VERBOSE] Resolving addresses ...
[DEBUG] resolving 127.0.0.1
[VERBOSE] resolving done
[DEBUG] Code: attack   Time: 1575538386
[DEBUG] Options: mode 0  ssl 0  restore 0  showAttempt 0  tasks 1  max_use 1 tnp 0  tpsal 0  tprl 0  exit_found 0  miscptr (null)  service mysql
[DEBUG] Brains: active 0  targets 1  finished 0  todo_all 1  todo 1  sent 0  found 0  countlogin 1  sizelogin 5  countpass 1  sizepass 5
[DEBUG] Target 0 - target 127.0.0.1  ip 127.0.0.1  login_no 0  pass_no 0  sent 0  pass_state 0  redo_state 0 (0 redos)  use_count 0  failed 0  done 0  fail_count 0  login_ptr root  pass_ptr root
[DEBUG] Task 0 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Tasks 1 inactive  0 active
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 71977
[DEBUG] head_no 0 has pid 71977
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 0, redo_state 0, pass_state 0. loop_mode 0, curlogin (null), curpass (null), tlogin root, tpass root, logincnt 0/1, passcnt 0/1, loop_cnt 1
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin root, cpass root, tlogin -p, tpass root, redo 0
[ATTEMPT] target 127.0.0.1 - login "root" - pass "root" - 1 of 1 [child 0] (0/0)
DEBUG_CONNECT_OK
[VERBOSE] using default db 'mysql'
DEBUG_RECV_BEGIN|J|END[0A]
[DEBUG] SEND [pid:71977] (5 bytes):
0000:  0100 0000 01                               [ .....            ]
DEBUG_DISCONNECT
[DEBUG] pid 71977 called child_exit with code 2
[DEBUG] head_no[0] read E
[ATTEMPT-ERROR] target 127.0.0.1 - login "root" - pass "root" - child 0 - 1 of 1
[DEBUG] hydra_increase_fail_count: 1 >= 0 => disable
[DEBUG] - will be retried at the end: ip 127.0.0.1 - login root - pass root - child 0
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 71978
[DEBUG] head_no 0 has pid 71978
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 1, redo_state 0, pass_state 0. loop_mode 0, curlogin , curpass , tlogin -p, tpass root, logincnt 1/1, passcnt 0/1, loop_cnt 1
[COMPLETED] target 127.0.0.1 - login "" - pass "" - child 0 - 1 of 2
[DEBUG] send_next_pair_mid done 0, pass_state 0, clogin , cpass , tlogin -p, tpass root, redo 1
[DEBUG] Entering redo_state
[DEBUG] send_next_pair_init target 0, head 0, redo 1, redo_state 1, pass_state 0. loop_mode 0, curlogin , curpass , tlogin -p, tpass root, logincnt 1/1, passcnt 0/1, loop_cnt 2
[COMPLETED] target 127.0.0.1 - login "" - pass "" - child 0 - 1 of 2
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin root, cpass root, tlogin -p, tpass root, redo 1
[REDO-ATTEMPT] target 127.0.0.1 - login "root" - pass "root" - 2 of 2 [child 0] (1/1)
DEBUG_CONNECT_OK
[VERBOSE] using default db 'mysql'
DEBUG_RECV_BEGIN|J|END[0A]
[DEBUG] SEND [pid:71978] (5 bytes):
0000:  0100 0000 01                               [ .....            ]
DEBUG_DISCONNECT
[DEBUG] pid 71978 called child_exit with code 2
[DEBUG] head_no[0] read E
[ATTEMPT-ERROR] target 127.0.0.1 - login "root" - pass "root" - child 0 - 2 of 1
[DEBUG] hydra_increase_fail_count: 2 >= 0 => disable
[DEBUG] - will be retried at the end: ip 127.0.0.1 - login root - pass root - child 0
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 71979
[DEBUG] head_no 0 has pid 71979
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 2, redo_state 2, pass_state 0. loop_mode 0, curlogin , curpass , tlogin -p, tpass root, logincnt 1/1, passcnt 0/1, loop_cnt 1
[COMPLETED] target 127.0.0.1 - login "" - pass "" - child 0 - 2 of 3
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin root, cpass root, tlogin -p, tpass root, redo 2
[REDO-ATTEMPT] target 127.0.0.1 - login "root" - pass "root" - 3 of 3 [child 0] (2/2)
DEBUG_CONNECT_OK
[VERBOSE] using default db 'mysql'
DEBUG_RECV_BEGIN|J|END[0A]
[DEBUG] SEND [pid:71979] (5 bytes):
0000:  0100 0000 01                               [ .....            ]
DEBUG_DISCONNECT
[DEBUG] pid 71979 called child_exit with code 2
[DEBUG] head_no[0] read E
[ATTEMPT-ERROR] target 127.0.0.1 - login "root" - pass "root" - child 0 - 3 of 1
[DEBUG] hydra_increase_fail_count: 3 >= 0 => disable
[DEBUG] - will be retried at the end: ip 127.0.0.1 - login root - pass root - child 0
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 71980
[DEBUG] head_no 0 has pid 71980
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 3, redo_state 3, pass_state 0. loop_mode 0, curlogin , curpass , tlogin -p, tpass root, logincnt 1/1, passcnt 0/1, loop_cnt 1
[COMPLETED] target 127.0.0.1 - login "" - pass "" - child 0 - 3 of 4
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin root, cpass root, tlogin -p, tpass root, redo 3
[REDO-ATTEMPT] target 127.0.0.1 - login "root" - pass "root" - 4 of 4 [child 0] (3/3)
DEBUG_CONNECT_OK
[VERBOSE] using default db 'mysql'
DEBUG_RECV_BEGIN|J|END[0A]
[DEBUG] SEND [pid:71980] (5 bytes):
0000:  0100 0000 01                               [ .....            ]
DEBUG_DISCONNECT
[DEBUG] pid 71980 called child_exit with code 2
[DEBUG] head_no[0] read E
[ATTEMPT-ERROR] target 127.0.0.1 - login "root" - pass "root" - child 0 - 4 of 1
[DEBUG] hydra_increase_fail_count: 4 >= 0 => disable
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 71981
[DEBUG] head_no 0 has pid 71981
[DEBUG] head_no[0] read n
[STATUS] attack finished for 127.0.0.1 (waiting for children to complete tests)
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] all targets done and all heads finished
[DEBUG] while loop left with 1
1 of 1 target completed, 0 valid passwords found
[DEBUG] killing all remaining children now that might be stuck
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2019-12-05 17:33:07

OS: MacOS 10.15.1
Version: Hydra v9.0 (c) 2019 by van Hauser/THC (brew install hydra)

**Comment by vanhauser-thc** [comment]
@hurricane618 as you can see in your output the server is sending no replies, so of course nothing can happen.

what happens if you do "mysqladmin -h host -p root <some command>"?

**Comment by hurricane618** [comment]
emmm I don't have mysqladmin, so I use `mysql -e "show databases;" -uroot -proot`. That is ok

**Comment by hurricane618** [comment]
But I use the msf, that is work.
![image](https://user-images.githubusercontent.com/17878977/70229015-56f75280-1790-11ea-9489-911d89a001cd.png)

**Comment by vanhauser-thc** [comment]
can you please try again with the github state and not an old version?

**Comment by hurricane618** [comment]
I use `./configure && sudo make && sudo make install` to finish installation. However it doesn't work either. Maybe some wrong in `./configure`? 
```
Starting hydra auto configuration ...
Detected 64 Bit Darwin OS

Checking for zlib (libz.so, zlib.h) ...
                                        ... found
Checking for openssl (libssl, libcrypto, ssl.h, sha.h) ...
                                                       ... NOT found, SSL support disabled
Get it from http://www.openssl.org
Checking for gcrypt (libgcrypt.so) ...
                                        ... gcrypt not found, radmin2 module disabled
Checking for idn (libidn.so) ...
                             ... NOT found, unicode logins and passwords will not be supported
Checking for curses (libcurses.so / term.h) ...
                                            ... found, color output enabled
Checking for pcre (libpcre.so, pcre.h) ...
                                       ... found
Checking for Postgres (libpq.so, libpq-fe.h) ...
                                             ... NOT found, module postgres disabled
Checking for SVN (libsvn_client-1 libapr-1.so libaprutil-1.so) ...
                                                               ... NOT found, module svn disabled
Checking for firebird (libfbclient.so) ...
                                       ... NOT found, module firebird disabled
Checking for MYSQL client (libmysqlclient.so, math.h) ...
                                                      ... NOT found, module Mysql will not support version > 4.x
Checking for AFP (libafpclient.so) ...
                                   ... NOT found, module Apple Filing Protocol disabled - Apple sucks anyway
Checking for NCP (libncp.so / nwcalls.h) ...
                                         ... NOT found, module NCP disabled
Checking for SAP/R3 (librfc/saprfc.h) ...
                                      ... NOT found, module sapr3 disabled
Get it from http://www.sap.com/solutions/netweaver/linux/eval/index.asp
Checking for libssh (libssh/libssh.h) ...
                                      ... found
Checking for Oracle (libocci.so libclntsh.so / oci.h and libaio.so) ...
                                                                    ... NOT found, module Oracle disabled
Get basic and sdk package from http://www.oracle.com/technetwork/database/features/instant-client/index.html
Checking for Memcached (libmemcached.so, memcached.h) ...
                                             ... NOT found, module memcached disabled
Checking for Freerdp2 (libfreerdp2.so, freerdp/*.h, libwinpr2.so, winpr/*.h) ...
                                             ... NOT found, module rdp disabled
Checking for Mongodb (libmongoc-1.0.so, mongoc.h, libbson-1.0.so, bson.h) ...
                                             ... NOT found, module mongodb disabled
Checking for GUI req's (pkg-config, gtk+-2.0) ...
                                              ... NOT found, optional anyway
Checking for Android specialities ...
                                  ... strrchr() found
Checking for secure compile option support in gcc ...
                                                  Compiling... yes
                                                  Linking... no

Hydra will be installed into .../bin of: /usr/local
  (change this by running ./configure --prefix=path)

Writing Makefile.in ...
now type "make"
```
many libraries not found. But I check in  `brew`, mysql-client is installed. Is there a problem with gcc?
run `gcc --version`
 ```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by vanhauser-thc** [comment]
your problem is right there:
```
Checking for MYSQL client (libmysqlclient.so, math.h) ...
                                                      ... NOT found, module Mysql will not support version > 4.x
```
you installed the mysql client, but not libmysql-dev (or whatever that package would be called in brew. not a MacOS guy)

**Comment by hurricane618** [comment]
thanks a lot, I give up ... Mac is too difficult  ( •̥́ ˍ •̀  )
