### ISSUE TITLE
Makefile:73: recipe for target 'hydra-mongodb.o' failed

### ISSUE THREAD

**Issue by shanpenghui** [vanhauser-thc/thc-hydra#423]
Hi,@vanhauser-thc, I encounter a problem that i cant compile the project.
After enter the command "./configure -DEBUG", it come out the result below:
`
./configure -DEBUG

Starting hydra auto configuration ...
Detected 64 Bit Linux OS

Checking for zlib (libz.so, zlib.h) ...
                                        ... found
Checking for openssl (libssl, libcrypto, ssl.h, sha.h) ...
                                                       ... found
Checking for gcrypt (libgcrypt.so) ...
                                        ... gcrypt not found, radmin2 module disabled
Checking for idn (libidn.so) ...
                             ... found
Checking for curses (libcurses.so / term.h) ...
                                            ... found, color output enabled
Checking for pcre (libpcre.so, pcre.h) ...
                                       ... found
Checking for Postgres (libpq.so, libpq-fe.h) ...
                                             ... found
Checking for SVN (libsvn_client-1 libapr-1.so libaprutil-1.so) ...
                                                               ... found
Checking for firebird (libfbclient.so) ...
                                       ... found
Checking for MYSQL client (libmysqlclient.so, math.h) ...
                                                      ... found
Checking for AFP (libafpclient.so) ...
                                   ... NOT found, module Apple Filing Protocol disabled - Apple sucks anyway
Checking for NCP (libncp.so / nwcalls.h) ...
                                         ... NOT found, module NCP disabled
Checking for SAP/R3 (librfc/saprfc.h) ...
                                      ... NOT found, module sapr3 disabled
Get it from http://www.sap.com/solutions/netweaver/linux/eval/index.asp
Checking for libssh (libssh/libssh.h) ...
                                      ... found
Checking for Oracle (libocci.so libclntsh.so / oci.h and libaio.so) ...
                                                                    ... NOT found, module Oracle disabled
Get basic and sdk package from http://www.oracle.com/technetwork/database/features/instant-client/index.html
Checking for Memcached (libmemcached.so, memcached.h) ...
                                             ... found
Checking for Freerdp2 (libfreerdp2.so, freerdp/*.h, libwinpr2.so, winpr/*.h) ...
                                             ... NOT found, module rdp disabled
Checking for Mongodb (libmongoc-1.0.so, mongoc.h, libbson-1.0.so, bson.h) ...
                                             ... found
Checking for GUI req's (pkg-config, gtk+-2.0) ...
                                              ... found
Checking for Android specialities ...
                                  ... strrchr() found
                                  ... RSA_generate_key() found
Checking for secure compile option support in gcc ...
                                                  Compiling... yes
                                                  Linking... yes

Hydra will be installed into .../bin of: /usr/local
  (change this by running ./configure --prefix=path)

Writing Makefile.in ...
now type "make"
`

It seem there is no problems. But when i make it, error comes.
So many error that I have to cut a bit from beging and the end.
The error display in begin is :
`
sph@sph-ThinkPad-W530:~/CLionProjects/thc-hydra$ make
cc -I. -O3 -march=native -flto -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wl,-z,now -Wl,-z,relro   -c hydra-mongodb.c -DHAVE_MYSQL_MYSQL_H -DLIBOPENSSL -DLIBNCURSES -DLIBFIREBIRD -DLIBIDN -DHAVE_PR29_H -DHAVE_PCRE -DLIBMYSQLCLIENT -DLIBPOSTGRES -DLIBSVN -DLIBSSH -DHAVE_ZLIB -DLIBMCACHED -DLIBMONGODB -DLIBBSON -DHAVE_MATH_H -DHAVE_SYS_PARAM_H -I/usr/include/mysql -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include/postgresql -I/usr/include -I/usr/include/subversion-1 -I/usr/include/apr-1.0 -I/usr/include/subversion-1 -I/usr/include/libmemcached-1.0 -I/usr/include/libmongoc-1.0 -I/usr/local/include/libbson-1.0
In file included from /usr/include/libmongoc-1.0/mongoc-collection.h:29:0,
                 from /usr/include/libmongoc-1.0/mongoc-client.h:26,
                 from /usr/include/libmongoc-1.0/mongoc.h:26,
                 from hydra-mongodb.c:6:
/usr/include/libmongoc-1.0/mongoc-index.h: In function ‘mongoc_index_opt_get_default’:
/usr/include/libmongoc-1.0/mongoc-index.h:77:71: error: expected declaration specifiers before ‘BSON_GNUC_CONST’
 const mongoc_index_opt_t     *mongoc_index_opt_get_default     (void) BSON_GNUC_CONST;
                                                                       ^~~~~~~~~~~~~~~
/usr/include/libmongoc-1.0/mongoc-index.h:78:71: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘BSON_GNUC_CONST’
 const mongoc_index_opt_geo_t *mongoc_index_opt_geo_get_default (void) BSON_GNUC_CONST;
                                                                       ^~~~~~~~~~~~~~~
/usr/include/libmongoc-1.0/mongoc-index.h:79:71: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘BSON_GNUC_CONST’
 const mongoc_index_opt_wt_t  *mongoc_index_opt_wt_get_default  (void) BSON_GNUC_CONST;
                                                                       ^~~~~~~~~~~~~~~
In file included from /usr/include/libmongoc-1.0/mongoc-collection.h:30:0,
                 from /usr/include/libmongoc-1.0/mongoc-client.h:26,
                 from /usr/include/libmongoc-1.0/mongoc.h:26,
                 from hydra-mongodb.c:6:
/usr/include/libmongoc-1.0/mongoc-read-prefs.h:30:37: error: storage class specified for parameter ‘mongoc_read_prefs_t’
 typedef struct _mongoc_read_prefs_t mongoc_read_prefs_t;
                                     ^~~~~~~~~~~~~~~~~~~
/usr/include/libmongoc-1.0/mongoc-read-prefs.h:40:3: error: storage class specified for parameter ‘mongoc_read_mode_t’
 } mongoc_read_mode_t;
   ^~~~~~~~~~~~~~~~~~
/usr/include/libmongoc-1.0/mongoc-read-prefs.h:43:1: error: expected declaration specifiers before ‘mongoc_read_prefs_t’
 mongoc_read_prefs_t *mongoc_read_prefs_new      (mongoc_read_mode_t         read_mode);
 ^~~~~~~~~~~~~~~~~~~
/usr/include/libmongoc-1.0/mongoc-read-prefs.h:44:1: error: expected declaration specifiers before ‘mongoc_read_prefs_t’
 mongoc_read_prefs_t *mongoc_read_prefs_copy     (const mongoc_read_prefs_t *read_prefs);
 ^~~~~~~~~~~~~~~~~~~
/usr/include/libmongoc-1.0/mongoc-read-prefs.h:45:50: error: expected declaration specifiers or ‘...’ before ‘mongoc_read_prefs_t’
 void                 mongoc_read_prefs_destroy  (mongoc_read_prefs_t       *read_prefs);
                                                  ^~~~~~~~~~~~~~~~~~~
/usr/include/libmongoc-1.0/mongoc-read-prefs.h:46:1: error: expected declaration specifiers before ‘mongoc_read_mode_t’
 mongoc_read_mode_t   mongoc_read_prefs_get_mode (const mongoc_read_prefs_t *read_prefs);
 ^~~~~~~~~~~~~~~~~~
/usr/include/libmongoc-1.0/mongoc-read-prefs.h:47:50: error: expected declaration specifiers or ‘...’ before ‘mongoc_read_prefs_t’
 void                 mongoc_read_prefs_set_mode (mongoc_read_prefs_t       *read_prefs,
                                                  ^~~~~~~~~~~~~~~~~~~
/usr/include/libmongoc-1.0/mongoc-read-prefs.h:48:50: error: expected declaration specifiers or ‘...’ before ‘mongoc_read_mode_t’
                                                  mongoc_read_mode_t         mode);
                                                  ^~~~~~~~~~~~~~~~~~
/usr/include/libmongoc-1.0/mongoc-read-prefs.h:49:56: warning: type defaults to ‘int’ in declaration of ‘mongoc_read_prefs_t’ [-Wimplicit-int]
 const bson_t        *mongoc_read_prefs_get_tags (const mongoc_read_prefs_t *read_prefs);
                                                        ^~~~~~~~~~~~~~~~~~~

`

I confused and guess is my mongoc-1.0 version too high or too low?
There comes the error in the end :
`
hydra-mod.h:48:16: error: storage class specified for parameter ‘hydra_memsearch’
 extern int32_t hydra_memsearch(char *haystack, int32_t hlen, char *needle, int32_t nlen);
                ^~~~~~~~~~~~~~~
hydra-mod.h:49:14: error: storage class specified for parameter ‘hydra_strrep’
 extern char *hydra_strrep(char *string, char *oldpiece, char *newpiece);
              ^~~~~~~~~~~~
hydra-mod.h:70:17: error: storage class specified for parameter ‘BOOL’
 typedef int32_t BOOL;
                 ^~~~
hydra-mongodb.c:17:16: error: storage class specified for parameter ‘hydra_data_ready_timed’
 extern int32_t hydra_data_ready_timed(int32_t socket, long sec, long usec);
                ^~~~~~~~~~~~~~~~~~~~~~
hydra-mongodb.c:19:14: error: storage class specified for parameter ‘HYDRA_EXIT’
 extern char *HYDRA_EXIT;
              ^~~~~~~~~~
hydra-mongodb.c:24:29: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 int is_error_msg(char *msg) {
                             ^
hydra-mongodb.c:33:32: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 int require_auth(int32_t sock) {
                                ^
hydra-mongodb.c:54:107: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 int32_t start_mongodb(int32_t s, char *ip, int32_t port, unsigned char options, char *miscptr, FILE * fp) {
                                                                                                           ^
hydra-mongodb.c:115:123: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 void service_mongodb(char *ip, int32_t sp, unsigned char options, char *miscptr, FILE * fp, int32_t port, char *hostname) {
                                                                                                                           ^
hydra-mongodb.c:146:131: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 int32_t service_mongodb_init(char *ip, int32_t sp, unsigned char options, char *miscptr, FILE * fp, int32_t port, char *hostname) {
                                                                                                                                   ^
hydra-mongodb.c:182:41: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 void usage_mongodb(const char* service) {
                                         ^
In file included from /usr/include/libmongoc-1.0/mongoc-collection.h:29:0,
                 from /usr/include/libmongoc-1.0/mongoc-client.h:26,
                 from /usr/include/libmongoc-1.0/mongoc.h:26,
                 from hydra-mongodb.c:6:
/usr/include/libmongoc-1.0/mongoc-index.h:77:31: error: old-style parameter declarations in prototyped function definition
 const mongoc_index_opt_t     *mongoc_index_opt_get_default     (void) BSON_GNUC_CONST;
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
hydra-mongodb.c:184:1: error: expected ‘{’ at end of input
 }
 ^
Makefile:73: recipe for target 'hydra-mongodb.o' failed
make: *** [hydra-mongodb.o] Error 1

`

Most errors look like so i cut into two parts and paste upon.
Hope can solve this problem.

**Comment by vanhauser-thc** [comment]
I am on mongo 1.14 and have no issues ... try to update?

**Comment by shanpenghui** [comment]
I edit the ./configure file.After delete the statement related to mongodb, compiling success finally.Im trying to locate the problem.

**Comment by vanhauser-thc** [comment]
@shanpenghui any luck? if you gave up on it, please close the issue ;)

**Comment by dmaciejak** [comment]
From the first error log: "/usr/include/libmongoc-1.0/mongoc-index.h:77:71: error: expected declaration specifiers before ‘BSON_GNUC_CONST’" I believe you should check the version of your BSON lib, which seems to be located in your system at /usr/local/include/libbson-1.0, maybe a version conflict?
