### ISSUE TITLE
Missing libgpg-error-dev in doc

### ISSUE THREAD

**Issue by cryptax** [vanhauser-thc/thc-hydra#424]
In the `README.md`, add that you need to install `sudo apt-get install libgpg-error-dev libgcrypt11-dev libgcrypt20-dev`

or you will run in compilation issue:

```
In file included from hydra-radmin2.c:5:0:
/usr/include/gcrypt.h:30:23: fatal error: gpg-error.h: No such file or directory
compilation terminated.
```

**Comment by dmaciejak** [comment]
Thanks, should be fixed now.
