### ISSUE TITLE
Too many REDO-ATTAMPT

### ISSUE THREAD

**Issue by mxsadegh** [vanhauser-thc/thc-hydra#426]
I used this command:
 hydra -s 80 -V -l ****** -p ****** -t 64 -w 5   -m http:// -M /home/*****/ip.txt -I http-get

and this is my output:
[DATA] max 1 task per 6400 servers, overall 64 tasks, 1 login try (l:1/p:1), ~100 tries per task
[DATA] attacking http-get://(6400 targets):80/http://
.
.
[REDO-ATTEMPT] target ******** - login "*****" - pass "******" - 129 of 129 [child 60] (128/128)

I have 6400 target and its try about 100 time for each target. What i could do if i want to once try for each target and it doesn't go to REDO-ATTEMPT?

**Comment by vanhauser-thc** [comment]
that would be actually a good feature.

I added the -K command line switch to disable redos ... please sync from github, recompile, test and report.

**Comment by mxsadegh** [comment]
In version 9.1 it go only to 63 child and it doesn't continue anything.
It wsa working on version 8.6 that was in ubuntu repository but it doesn't work on latest version
i use it in Xubuntu 18.04 LTS

**Comment by vanhauser-thc** [comment]
ah damn I had hoped it was so easily I could just quickly add it.
will have to look deeper into the code tomorrow

**Comment by mxsadegh** [comment]
I was trying other version ( like 8.8 to 9 ) before adding this but that wasn't working so.

**Comment by vanhauser-thc** [comment]
OK I think I fixed it. should work now.
