### ISSUE TITLE
Own Mail Always fail

### ISSUE THREAD

**Issue by firelord96** [vanhauser-thc/thc-hydra#428]
I am trying to use hydra in my **own** Gmail and hotmail with the password in the txt file and still do not find the correct one, what is the problem?

I am using the commands correctly, it no longer works in these emails?

Using v9.0 and v8.9.1

**Comment by firelord96** [comment]
Tried with these order:

`hydra -S -l example@gmail.com -P '/root/example.txt' -e -s -V -s 465 smtp.gmail.com smtp`
`hydra smtp.gmail.com smtp -l example@gmail.com -P '/root/example.txt' -s 465 -S -v -V`

**Comment by firelord96** [comment]
I'm trying to recover an old account and I can not get it

**Comment by vanhauser-thc** [comment]
gmail has protection against bruteforcing
