### ISSUE TITLE
[ERROR] Unknown service: ssh://***.**.*.***

### ISSUE THREAD

**Issue by zoukun120** [vanhauser-thc/thc-hydra#430]
[root@144 /]# **hydra -l -p /home/hacker/dictionary/SecLists/Passwords/Common-Credentials/10-million-password-list-top-100.txt ssh://***.**.*.*****

Hydra v9.0 (c) 2019 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2019-07-21 11:20:32
[ERROR] Unknown service: ssh://***.**.*.***

[root@144 /]# **uname -a**
Linux 144.34.174.186.16clouds.com 4.10.4-1.el7.elrepo.x86_64 #1 SMP Sat Mar 18 12:50:10 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

Not shown: 987 closed ports
PORT     STATE    SERVICE
22/tcp   open     ssh
80/tcp   open     http
135/tcp  filtered msrpc
139/tcp  filtered netbios-ssn
445/tcp  filtered microsoft-ds
593/tcp  filtered http-rpc-epmap
1434/tcp filtered ms-sql-m
4444/tcp filtered krb524
6669/tcp filtered irc
8009/tcp open     ajp13
8080/tcp open     http-proxy
8085/tcp open     unknown
8086/tcp open     d-s-n

what is it problem . could you help me

**Comment by vanhauser-thc** [comment]
you have not install libssh-dev so of course hydra wasnt compiled with it so no ssh module for you

**Comment by zoukun120** [comment]
> you have not install libssh-dev so of course hydra wasnt compiled with it so no ssh module for you

thanks You！
l had download libssh by yum install libssh-dev
but l got "Compiled without LIBSSH v0.4.x support, module is not available!"
where l should this lib put?

**Comment by devsec110** [comment]
hi i am having same issue of Unknown service error, have installed libssh-dev and opened ssh port 22 on host kali linux?

**Comment by lowk3v** [comment]
try without hydra command, it starts with options: `docker run --rm --name hydra -it -v ./:/wordlist vanhauser/hydra:latest -l root -P /wordlist/rockyou.txt -V ssh://target`
