### ISSUE TITLE
What does these RDP errors mean?

### ISSUE THREAD

**Issue by ghost** [vanhauser-thc/thc-hydra#431]
Hi @vanhauser-thc 
I have problem with RDP cracking.
```
[ERROR] freerdp: The connection failed to establish.
[ERROR] child 15 sent nonsense data, killing and restarting it!
[ERROR] child 29 sent nonsense data, killing and restarting it!
[ERROR] child 30 sent nonsense data, killing and restarting it!
[ERROR] child 39 sent nonsense data, killing and restarting it!
```
How can i fix those?
Are they normal?
I have to say it at last hydra is doing its job but i got these errors

**Comment by vanhauser-thc** [comment]
@NortonSec no clue, but I the code is not by me ... my guess would be that it is a different server (not rdp) or an incompatible rdp version.

@dmaciejak do you know?

**Comment by dmaciejak** [comment]
The first error log is displayed from hydra_rdp hydra_report(stderr, "[ERROR] freerdp: %s\n", "The connection failed to establish."); line when the freerdp_connect() call is returning the error code 0x0002000d which is a message reported when the library cannot establish rdp connection (either the port is not opened or it's not rdp). The 4 other lines are coming from hydra core itself (hydra.c). I would say maybe during your test you lost the connection to the rdp server or your source IP has been blacklisted.
