### ISSUE TITLE
http-form-post: Detect Invalid Login String?

### ISSUE THREAD

**Issue by peterfarge** [vanhauser-thc/thc-hydra#433]
Hi,

I want to use hydra on my OpenWRT Router. But the invalid String is not found. How does the Invalid String search work? Plain Ascii search for the word?

If I try this command, I find my password. Because on success I get a 302 http retval:
`hydra -v -V -d 192.168.178.1 http-form-post "/cgi-bin/luci:luci_username=^USER^&luci_password=^PASS^:**S=302**" -L users.txt -P pass.txt -t 1 -w 300 -o hydra-http-post-attack.txt`

This is the Invalid Login message I get from OpenWRT on a 403 page:

> Invalid username and/or password! Please try again.

But if I try this command, hydra answers me that the first password in the list is the login. Why?
`hydra -v -V -d 192.168.178.1 http-form-post "/cgi-bin/luci:luci_username=^USER^&luci_password=^PASS^:**F=Invalid**" -L users.txt -P pass.txt -t 1 -w 300 -W 1 -o hydra-http-post-attack.txt`

This is the answer:
https://pastebin.com/57WS71bQ

This is the error page in html format:
https://pastebin.com/9e0SEc23

**Comment by vanhauser-thc** [comment]
should not happen IMHO but why are you reporting a bug when using a very old version? always try with the newest version first before creating an issue. *always*

**Comment by peterfarge** [comment]
Excuse me, you are right. apt-get dist-upgrade solved the issue.
