### ISSUE TITLE
for the correct or error password,the respond packet of rdp server all   as shown in the figure: 

### ISSUE THREAD

**Issue by yangT1112** [vanhauser-thc/thc-hydra#434]
[DEBUG] RECV [pid:26523] (4 bytes):
0000:  0300 0022                                  [ ..."             ]
[DEBUG] RECV [pid:26523] (30 bytes):
0000:  02f0 8068 0001 03eb 7014 8002 0000 ff03    [ ...h....p....... ]
0010:  1000 0700 0000 0200 0000 0400 0000
the rdp server sent this packet to client after client sends the packet which  contains the usrname and password,for this packet contains flags which is 0x0280. however, the corect should be 0x0288, So why is the result? thanks very much!

**Comment by vanhauser-thc** [comment]
a) this misses context. what is this about? and what is your issue?
b) why are you asking here why a server sends that value? check the software running on the server or read the protocol spec.

reopen if you want to add something that makes this a useful issue
