### ISSUE TITLE
hydra redo attempt

### ISSUE THREAD

**Issue by johngeogin** [vanhauser-thc/thc-hydra#435]
I tried to brute force a http-get service using -M option with list of servers of which some host are down/offline.

However when hydra reaches to offline host it tries to redo-attempt many times on the same offline server which makes hydra very slow.

Syntax provided

 hydra -l admin -p admin -M (Target ip list) -f -V -t 5 -w 5  http-get
How can i skip offline host from Target ip list so that no redo attempt on offline host

Because of some offline server in -M (Target list) hydra is not proceeding/taking more time due to re attempt on offline server

**Comment by vanhauser-thc** [comment]
are did you compile from the current github state? if not please do and report if the issue is gone or not

**Comment by johngeogin** [comment]
i am using latest hydra version from vanhauser-thc/thc-hydra

**Comment by johngeogin** [comment]
hydra is showing redo-attempt on offline host

**Comment by vanhauser-thc** [comment]
how do you know they are offline? hydra just was not able to complete a login attempt. this can have many reasons.

if you *know* systems are offline, you remove them from your list (and why are they in there in the first place??)

Option -K disables redos.

**Comment by johngeogin** [comment]
Option -K 
hydra showing
hydra: unknown option -- K

**Comment by vanhauser-thc** [comment]
you have to compile hydra from github for the option

**Comment by johngeogin** [comment]
how can i do that

**Comment by johngeogin** [comment]
i downloaded from downloaded  hydra from  vanhauser-thc/thc-hydra
