### ISSUE TITLE
[ERROR] child 0 sent nonsense data, killing and restarting it!

### ISSUE THREAD

**Issue by johngeogin** [vanhauser-thc/thc-hydra#439]
hydra is showing 
[ERROR] child 0 sent nonsense data, killing and restarting it!
 
and Not moving further (i am doing a Mass scan)

**Comment by vanhauser-thc** [comment]
make good complete issues!

exact command lines, output, behaviour, etc.
how many systems are you scanning, are some of them dead.
how do you know its not moving further?

if you dont make effort in creating the issues I will block you.
