### ISSUE TITLE
dyld: malformed mach-o image: missing LC_DYSYMTAB

### ISSUE THREAD

**Issue by silvervalley** [vanhauser-thc/thc-hydra#440]
I tried to install it on my Mac with the following commands:
`./configure
make
make install`
when I ran hydra I got a message: "dyld: malformed mach-o image: missing LC_DYSYMTAB",
I couldn't find solution, had anyone met this before? thanks

**Comment by vanhauser-thc** [comment]
well I hope there were some semicolon in the command string ;)

I dont use Mac so I have no clue ... I will add "help wanted" label.

did looking with a search engine for this error not help you?

**Comment by silvervalley** [comment]
> well I hope there were some semicolon in the command string ;)
> 
> I dont use Mac so I have no clue ... I will add "help wanted" label.
> 
> did looking with a search engine for this error not help you?

yeah I did some searching but found no related info,  it worked fine on Ubuntu, so it could be my Macbook's problem

**Comment by vanhauser-thc** [comment]
@silvervalley I keep it open for the time being in case someone else stumbles upon it

**Comment by loonydev** [comment]
Hi @silvervalley. I just tested on Mojava 10.14.6, works fine. Can u provide more details about system, configure log, command?

**Comment by dmaciejak** [comment]
hum, I can not reproduce that issue too.

**Comment by loonydev** [comment]
I think we can close it, If somebody get the same just reopen this issue.

**Comment by 21k** [comment]
found on Mac10.14.6 、thc-hydra-9.0
![image](https://user-images.githubusercontent.com/13778916/71617404-df351000-2bf5-11ea-9900-cf09ddc7efb4.png)
