### ISSUE TITLE
Cert error with proxy?

### ISSUE THREAD

**Issue by peterfarge** [vanhauser-thc/thc-hydra#441]
Hi,
I want to test my website. My website is on a VPS in the internet. On my desktop computer I get the 'https-form-post' attack working. Now I want to see what hydra generates as traffic. Therefore I installed burp on my desktop computer and set the proxy settings in the bash shell and in the firefox settings. If I open firefox, I get the certificate warning like in [this thread](https://github.com/vanhauser-thc/thc-hydra/issues/191), because burp proxy acts like a MITM attacker. After adding the exception in firefox, I can login to my website (all burp intercepts are turned off). But with hydra, nothing works: No connection attemp is shown in hydra.

This command finds the correct login if HYDRA_PROXY is unset (burp bypassed):
```
unset HYDRA_PROXY
hydra -I -v -V -d -l peterfarge -p 12345678 -t 1 -W 4 -o hydra-https-post-attack.txt www.mydomain.de https-form-post "/de/Login:action=login&username=^USER^&password=^PASS^:F=failure:H=Cookie\: cookieOk=1; PHPSESSID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```

But if I set the proxy, burp shows no https GET requests and hydra does nothing.
```
export HYDRA_PROXY=socks5://127.0.0.1:8080 # for hydra
export https_proxy=127.0.0.1:8080 # for curl
```
stdout of hydra: https://pastebin.com/UCMvnULF
stderr of hydra:https://pastebin.com/XvmYrU2f

curl only works if I use the --insecure parameter (because of the burp mitm certificate), so I'm thinking its the same with burp? Bit in another thread you said that hydra does not validate the certificate?

Curently I'm using Hydra v9.0 (c) 2019 from the kali repo.
I tried to compile the last snapshot from github but I cant compile it (undefined reference to `hydra_string_match').
Error: https://pastebin.com/vkrFWFst
To get the latest dev snapshot is only important if it fixes the proxy problem

**Comment by RaduNico** [comment]
I am currently experiencing the same issue if I am using the proxy for https connections. No outgoing traffic seems to be generated, burp reports nothing being received from hydra and hydra itself just seems to hang. 

Trying to use the http proxy works just fine.

I used a manually compiled version of hydra and updated it today.

**Comment by vanhauser-thc** [comment]
you set the wrong proxy. burp is a http proxy, not a socks proxy
HYDRA_PROXY_HTTP=http://127.0.0.1:8080
