### ISSUE TITLE
vnc failed （rfb 005.000）

### ISSUE THREAD

**Issue by zsdevX** [vanhauser-thc/thc-hydra#445]
I try to force vncserver 6.2+，and found hydra does not support rfb 005.000.

is there a way to make it work?

**Comment by dmaciejak** [comment]
Send us a patch ;)

**Comment by dmaciejak** [comment]
That should do the trick
https://github.com/vanhauser-thc/thc-hydra/commit/273334df88f989a7e5eb4009370f8cb9c9c25c0e. But please note that for now only VNC security type is supported (meaning password only).

**Comment by zsdevX** [comment]
[ERROR] unknown VNC security type 0x5

> That should do the trick
> [273334d](https://github.com/vanhauser-thc/thc-hydra/commit/273334df88f989a7e5eb4009370f8cb9c9c25c0e). But please note that for now only VNC security type is supported (meaning password only).

[ERROR] unknown VNC security type 0x5

**Comment by dmaciejak** [comment]
yes that's what I said we are only supporting security type 0x1 (None) and 0x2 (VNC Auth), from my understanding 0x5 is for RA2. See some details at https://tools.ietf.org/html/rfc6143#page-32

**Comment by dmaciejak** [comment]
Any help is welcome if somebody knows how to support RA2 and RA2ne security types.
