### ISSUE TITLE
freerdp init failed

### ISSUE THREAD

**Issue by spooky18** [vanhauser-thc/thc-hydra#446]
fault:
RDP cracking tips
[ERROR] freerdp init failed

OS:Kali_2017.1
Hydra v9.1-dev

Compiler parameters
apt install freerdp2-dev libssl-dev postgresql-common libpq-dev -y
apt-get -f install
cd /thc-hydra
make clean
./configure;make;make install

**Comment by dmaciejak** [comment]
That error means freerdp is not able to initialize on your system. I believe you should better update the libs. I tried on kali 2019.3 and I was not able to reproduce your issue.

**Comment by spooky18** [comment]
CentOS 7 is fine. Thank you very much!
