### ISSUE TITLE
Set -t TASKS to 64(max) but it stops there.  I'm sure Hydra can do better

### ISSUE THREAD

**Issue by betty5588** [vanhauser-thc/thc-hydra#449]
root@kali:~/Desktop/thc-hydra# hydra -l admin -P /usr/share/wordlists/rockyou.txt testasp.vulnweb.com http-post-form "/Login.asp?RetURL=%2FDefault%2Easp%3F:tfUName=^USER^&tfUPass=^PASS^:S=logout" -vV -f -t 64

I added "-t 64" at the end of the cmd string because it defaults at 16 attempts per min.  
But it kinda stops after 64 attempts.  Notably slower than other password cracking tools.  I must have configured something wrongly
Kindly advise how to solve this?
Thank you

![image](https://user-images.githubusercontent.com/25699966/64903304-a590d580-d6e8-11e9-816f-d3443ed928eb.png)

**Comment by vanhauser-thc** [comment]
more is not better. it just uses more resourcen on your side and your sever. imagine a building and 64 people trying to get through the door. if your system, the network and the target system (and the service!) can handle it, it works fine, otherwise you reduce performance.

**Comment by betty5588** [comment]
Thank you for the fast response.
I actually started with default 16 tries per min, and it kinda of stops trying after that, similar to the image I posted earlier.Have I missed out something?

Sent from Yahoo Mail on Android 
 
  On Sat, 14 Sep 2019 at 18:03, van Hauser<notifications@github.com> wrote:   
Closed #449.

**Comment by vanhauser-thc** [comment]
it looks like something is wrong on the server side, there are no responses. try the -d switch and -t 1 and check out what is being sent and if the server sends anything back at all. from the picture it looks like there are no server replies. could it be its https and no service is running on http and a firewall is filtering that port?
