### ISSUE TITLE
Is there a way to execute multiple requests?

### ISSUE THREAD

**Issue by GitAntoinee** [vanhauser-thc/thc-hydra#451]
Hello, I know I can bruteforce passwords but i am limited to only 1 request.
How can I execute requests, like if the first request is a success

**Comment by vanhauser-thc** [comment]
your question is: you bruteforce accounts + passwords and if you find a valid combination you want to perform actions on that?

you could use the -f option which terminates when a combination is found. with the -o option you would have an output where the combination is documented. with that you can script your follow-up requests.
if you want to restart the tests though it will be manual work (remove users from the -L file that have been tested already etc.).

**Comment by GitAntoinee** [comment]
Not really, if the first request is a success (the response contains the required conditions), it do another request with conditions too

**Comment by vanhauser-thc** [comment]
so the second request is to verify that the authentication was successful, because the reply to the auth request is generic?

**Comment by GitAntoinee** [comment]
The second request, is to authenticate the user, whereas the first request was to verify the email exists.

**Comment by vanhauser-thc** [comment]
ah ok. no that is not supported. that would make everything more complex than it already is ...
