### ISSUE TITLE
build failed (iOS)

### ISSUE THREAD

**Issue by The-SamminAter** [vanhauser-thc/thc-hydra#452]
I know that this is a bit irregular, but I am trying to install hydra on iOS. I've downloaded hydra and ran ./configure successfully, but when I run make, I get this: `make: cc: Command not found`. 

I know that hydra can be successfully built and ran on iOS, because there there is a package for it on the modmyi repo. The only issue with that package is that hydra can't be run, which is why I'm trying to build it (hydra) myself.

The device is running iOS 10.3.3, x64 (it's an iPhone 6s)

Here is the terminal output: [terminal output.txt](https://github.com/vanhauser-thc/thc-hydra/files/3628083/terminal.output.txt)

**Comment by loonydev** [comment]
Hi, you haven't `build-essential` tools (clang compiler (cc)). And for linux it's easy to install `sudo apt-get install build-essential`. 
You can try to change Clang to another compiler in Makefile, for example gcc.

**Comment by The-SamminAter** [comment]
I have Clang installed in iOS

**Comment by vanhauser-thc** [comment]
hmmm I have not tried it, but if clang is installed you could try:

```
export CC=clang
make
```

**Comment by vanhauser-thc** [comment]
did that work?

**Comment by The-SamminAter** [comment]
`clang-5.0: error: the clang compiler does not support '-march=native'`

**Comment by vanhauser-thc** [comment]
well thats a step forward right?
edit the Makefile and remove -march=nattive ... and whatever other stuff it does not support

**Comment by The-SamminAter** [comment]
Now when attempting to run make, I get the following error:
```
# make
cc -I. -O3 -march=native -flto     -o pw-inspector  pw-inspector.c
make: cc: Command not found
make: cc: Command not found
```

**Comment by vanhauser-thc** [comment]
CC=clang make

or something like that

**Comment by The-SamminAter** [comment]
I'm 

> CC=clang make
> 
> or something like that

Should I put that at the start of Makefile or configure?

**Comment by The-SamminAter** [comment]
I tried running `./configure CC='clang'`, and got the same error when running make. I'm going to try to figure out if hydra could possibly be built with theos, but I wouldn't count on it.

**Comment by The-SamminAter** [comment]
It looks like I have to either figure out how to build clang for iOS or figure out how to build this in theos
