### ISSUE TITLE
help !! 

### ISSUE THREAD

**Issue by anas20155** [vanhauser-thc/thc-hydra#455]
root@kali-linuxxx:~/Desktop/thc-hydra# make install 

Now type make install
strip hydra pw-inspector
echo OK > /dev/null && test -x xhydra && strip xhydra || echo OK > /dev/null
mkdir -p /usr/local/bin
cp -f hydra-wizard.sh hydra pw-inspector /usr/local/bin && cd /usr/local/bin && chmod 755 hydra-wizard.sh hydra pw-inspector
echo OK > /dev/null && test -x xhydra && cp xhydra /usr/local/bin && cd /usr/local/bin && chmod 755 xhydra || echo OK > /dev/null
sed -e "s|^INSTALLDIR=.*|INSTALLDIR="/usr/local"|" dpl4hydra.sh | sed -e "s|^LOCATION=.*|LOCATION="/etc"|" > /usr/local/bin/dpl4hydra.sh
chmod 755 /usr/local/bin/dpl4hydra.sh
mkdir -p /usr/local/etc
cp -f *.csv /usr/local/etc
mkdir -p /usr/local/man/man1/
cp -f hydra.1 xhydra.1 pw-inspector.1 /usr/local/man/man1

**Comment by vanhauser-thc** [comment]
so? looks fine

**Comment by anas20155** [comment]
No it's not working
She's saying    “1 of 1 target completed, 0 valid passwords found”

**Comment by vanhauser-thc** [comment]
thats not what you pasted if you look at it ...

**Comment by anas20155** [comment]
This error is the result of guessing although I know that the password is correct, but it shows me this error I think it is the result of not updating hydra, when I update the hydra shows me the error above while when I see it in YouTube does not show the same error or never shows an error > What's the problem with the make install command

**Comment by anas20155** [comment]
When I type make install 
I see this error :- 
-------------------------------------------------------------------------------------------------------------
strip hydra pw-inspector
echo OK > /dev/null && test -x xhydra && strip xhydra || echo OK > /dev/null
mkdir -p /usr/local/bin
cp -f hydra-wizard.sh hydra pw-inspector /usr/local/bin && cd /usr/local/bin && chmod 755 hydra-wizard.sh hydra pw-inspector
echo OK > /dev/null && test -x xhydra && cp xhydra /usr/local/bin && cd /usr/local/bin && chmod 755 xhydra || echo OK > /dev/null
sed -e "s|^INSTALLDIR=.*|INSTALLDIR="/usr/local"|" dpl4hydra.sh | sed -e "s|^LOCATION=.*|LOCATION="/etc"|" > /usr/local/bin/dpl4hydra.sh
chmod 755 /usr/local/bin/dpl4hydra.sh
mkdir -p /usr/local/etc
cp -f *.csv /usr/local/etc
mkdir -p /usr/local/man/man1/
cp -f hydra.1 xhydra.1 pw-inspector.1 /usr/local/man/man1/

**Comment by vanhauser-thc** [comment]
there is no error
