### ISSUE TITLE
Hydra v9.1-dev memory leak

### ISSUE THREAD

**Issue by spooky18** [vanhauser-thc/thc-hydra#457]
When 10,000 IP's are loaded, 4G physical memory is exceeded and 2G switched memory is rapidly exhausted.

The number of concurrent connections is very low. Can you fix this memory problem? Thank you!

Start parameters:

Hydra-V-w 5-f-t 4-K-l administrator-P password.txt-o xx.txt-M xx_rdp.txt rdp

**Comment by vanhauser-thc** [comment]
the problem is that the rdp library needs quite some memory. if you would use ftp as target protocol that would be less of a problem.

you limit the number of concurrent connections, that would already help, e.g. -T 64 -t 2
