### ISSUE TITLE
Password found but not shown

### ISSUE THREAD

**Issue by ProGentle** [vanhauser-thc/thc-hydra#464]
Hi,

I have a funny problem. Hydra tells me that it found the password but refuses to show it.
It is neither written to the screen nor put into the output file. Also -vV is showing all tested passwords but no the one working.

![hydra-rockyou](https://user-images.githubusercontent.com/33968600/67167233-b7286580-f397-11e9-9f15-e55868199721.png)

As I already know the password (kittykat1) I can tell it is line 10002 in rockyou.txt. If I shorten the file to just a couple of 1000 lines hydra is working as expected.

![hydra-small](https://user-images.githubusercontent.com/33968600/67167239-c60f1800-f397-11e9-9d63-89b1cf4eae82.png)

I'm running hydra 9.0 under a Kali VM but also under native Linux Mint 18.1. Same result.

Any idea about the problem?

Thx

**Comment by e2002e** [comment]
i've had weird glitches with 9.1-dev but it looks like it has been just wiped away as master is now 9.0. maybe the new master is the old devel and so prone to glitches. you should stick to v8.8 if you don't need any of the new modules. cheers

**Comment by vanhauser-thc** [comment]
@e2002e @ProGentle if there is a bug in 9.1-dev then it needs to be fixed. just using an older version is not making the situation better :)

can you please examine what is going wrong? add the -d flag to show debug output of all traffic sent and received, and check why the wrong account is being reported as valid. My guess its because the connection got terminated so the "false login string" is not there.

It is always better to test on a success string than on a failure string

**Comment by parihacker** [comment]
ممنون

**Comment by parihacker** [comment]
Tnx

**Comment by ProGentle** [comment]
In the meanwhile I solved the/my issue. The problem was that rockyou.txt includes an empty line and that triggered another error message. Which of course was different to the one I used within Hydra and therefore considered as correct. And of course showing an empty passwords on the screen is resulting in seeing nothing. So the problem was in front of the PC but not with Hydra ;-)
Thx a lot

**Comment by bhartyrs** [comment]
Like @ProGentle stated 

hydra -V -l username-p /usr/share/wordlist/rockyou.txt <ip> http-post-form "/login.php:username=^USER^&password=^PASS^:The password you entered was not valid."

The last part is looking for the response with "The password you entered was not valid."  The server most likely responds with "Please enter a password" or something that does not match it and hydra thinks it is a hit. False postitive

**Comment by e2002e** [comment]
> The last part is looking for the response with "The password you entered was not valid." The server most likely responds with "Please enter a password" or something that does not match it and hydra thinks it is a hit. False positive

Of course, you must know the answer by inspecting the page returned when failing to connect or succeding when using S= instead of F= (which is the one applied when not giving the flag)

**Comment by jussDoinMyThing** [comment]
How do you find the http post form for a website? And hydra only shows me the file name and not the password...
