### ISSUE TITLE
mysql moduel:  How to disable REDO-ATTEMPT

### ISSUE THREAD

**Issue by 0xs1riu5** [vanhauser-thc/thc-hydra#466]
for example:
`[DATA] max 1 task per 4 servers, overall 4 tasks, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking mysql://(4 targets):3306/
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[ATTEMPT] target 10.6.20.35 - login "root" - pass "password" - 1 of 1 [child 0] (0/0)
[ATTEMPT] target 10.6.20.37 - login "root" - pass "password" - 1 of 1 [child 1] (0/0)
[ATTEMPT] target 10.6.20.10 - login "root" - pass "password" - 1 of 1 [child 2] (0/0)
[ATTEMPT] target 10.6.20.24 - login "root" - pass "password" - 1 of 1 [child 3] (0/0)
[VERBOSE] using default db 'mysql'
[VERBOSE] using default db 'mysql'
[ERROR] Host 'MACBOOKPRO-1408' is not allowed to connect to this MySQL server
[ERROR] Host '10.6.20.41' is not allowed to connect to this MySQL server
[STATUS] attack finished for 10.6.20.10 (waiting for children to complete tests)
[STATUS] attack finished for 10.6.20.24 (waiting for children to complete tests)
[WARNING] child 0 seems to have died, restarting (this only happens if a module is bad) ...
[REDO-ATTEMPT] target 10.6.20.35 - login "root" - pass "password" - 2 of 3 [child 1] (1/2)
[REDO-ATTEMPT] target 10.6.20.37 - login "root" - pass "password" - 2 of 2 [child 0] (1/1)
Process 156: Can not connect [unreachable], retrying (1 of 1 retries)
Process 156: Can not connect [unreachable]
[ERROR] Child with pid 156 terminating, can not connect
[REDO-ATTEMPT] target 10.6.20.35 - login "" - pass "" - 3 of 4 [child 1] (2/3)
[REDO-ATTEMPT] target 10.6.20.37 - login "root" - pass "password" - 3 of 3 [child 0] (2/2)
Process 159: Can not connect [unreachable], retrying (1 of 1 retries)`

my cmd :
hydra -l root -p password -vV -t 1 -I -w 3 -M  target.txt mysql

target.txt:
10.6.20.35
10.6.20.10
10.6.20.24

hydra:9.0 from source

**Comment by vanhauser-thc** [comment]
-K option, might need to use github option, dunno when I added that feature
