### ISSUE TITLE
Error: network size may only be between /16 and /31

### ISSUE THREAD

**Issue by hex406** [vanhauser-thc/thc-hydra#469]
using this command :

`hydra -l admin -P rockyou.txt 172.29.3.1/ifmgr.php http-get
`

trying to attack ifmgr.php, it's a basic http auth.

Getting error : 

> Error: network size may only be between /16 and /31

**Comment by vanhauser-thc** [comment]
wrong syntax, read the help -U and examples and README

**Comment by kovalensky** [comment]
> using this command :
> 
> `hydra -l admin -P rockyou.txt 172.29.3.1/ifmgr.php http-get `
> 
> trying to attack ifmgr.php, it's a basic http auth.
> 
> Getting error :
> 
> > Error: network size may only be between /16 and /31

Did you find the pass? Tryna find pass for same service
