### ISSUE TITLE
https-post-form report all passwords are ok but it is not true

### ISSUE THREAD

**Issue by rogermanich** [vanhauser-thc/thc-hydra#470]
Hi,
I am not sure if it is bug or misunderstood the options. Recently I am testing our web using your tool. The method used is https-form-post. I use a password.txt with 4 passowords. One of them is correct. The other is wrong. I just use one use with option -l. The problem is the tool report all passwords are valid. So, It is a bug or maybe the parameters passed are incorrect?

hydra -l myuser -P pass.txt xx.yy.zz.nn  https-form-post "/user.php?action=Login:username=^USER^&password=^PASSWORD^&Button=Inicia:Bad login"

Where pass.txt is file with 4 passwords, xx.yy.zz.nn is the IP (I tried with URL like www.mysite.com)

thank you

**Comment by vanhauser-thc** [comment]
could be good could be wrong, depends on the output of the website. "Bad login" is a text that must be in the web page that is displayed when the password is wrong.

debug your issue with "-d -t 1" 

and this is not a help forum, but for reporting bugs in the software, sorry.

**Comment by rogermanich** [comment]
I agree with you. But not sure if it was a bug. Bug is not connected to runtime error. Sometimes is behaviour. Clear is not a bug. Thanks. :)
