### ISSUE TITLE
Is hydra broken or am I doing something wrong? [pls help]

### ISSUE THREAD

**Issue by PauloChoupina** [vanhauser-thc/thc-hydra#472]
Hi, how you doing?

I'm trying to filter a combo list of user:pass in a https post form
used this command:

hydra -C "/root/combo.txt" www.website.com https-post-form "/portal/login:id=^USER^&pw=^PASS^&submit=Login:F=Access denied" -t 1 -o test2.txt -c 25

And I'm getting lots of false positives.

Am I missing something? or doing something wrong?
When I try a combo with my own account and a bunch of fake info, I get good results.
But with the original combo file I get mostly false positives..

Is hydra broken?
what is going on?

Best regards!

**Comment by vanhauser-thc** [comment]
add a -d switch and take a look at the debug output of the false positives. very likely the web server closes the connection or shows a different page/error. A S= success pattern would not have false positives.

**Comment by PauloChoupina** [comment]
ok i will try the S= 
ty

**Comment by vanhauser-thc** [comment]
if issues come up just open the issue again with a report
