### ISSUE TITLE
Children Crashed! while using RTSP. (Hydra v9.1-dev)

### ISSUE THREAD

**Issue by amdorj** [vanhauser-thc/thc-hydra#478]
( essentially a duplicate of #436 )
root@jamdev:~/thc-hydra# hydra -l user -p user  rtsp -d -I -T 1
Hydra v9.1-dev (c) 2019 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes.

[DEBUG] Output color flag is 1
Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2019-12-10 20:33:44
[DEBUG] cmdline: hydra -l user -p user -d -I -T 1 xx.xxx.xxx.xx rtsp
[WARNING] Restorefile (ignored ...) from a previous session found, to prevent overwriting, ./hydra.restore
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking rtsp://xx.xxx.xxx.xx:554/
[VERBOSE] Resolving addresses ...
[DEBUG] resolving xx.xxx.xxx.xx
[VERBOSE] resolving done
[DEBUG] Code: attack   Time: 1576010024
[DEBUG] Options: mode 0  ssl 0  restore 0  showAttempt 0  tasks 1  max_use 1 tnp 0  tpsal 0  tprl 0  exit_found 0  miscptr (null)  service rtsp
[DEBUG] Brains: active 0  targets 1  finished 0  todo_all 1  todo 1  sent 0  found 0  countlogin 1  sizelogin 5  countpass 1  sizepass 5
[DEBUG] Target 0 - target xx.xxx.xxx.xx  ip xx.xxx.xxx.xx  login_no 0  pass_no 0  sent 0  pass_state 0  redo_state 0 (0 redos)  use_count 0  failed 0  done 0  fail_count 0  login_ptr user  pass_ptr user
[DEBUG] Task 0 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Tasks 1 inactive  0 active
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 24075
[DEBUG] head_no 0 has pid 24075
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 0, redo_state 0, pass_state 0. loop_mode 0, curlogin (null), curpass (null), tlogin user, tpass user, logincnt 0/1, passcnt 0/1, loop_cnt 1
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin user, cpass user, tlogin -p, tpass user, redo 0
[ATTEMPT] target xx.xxx.xxx.xx - login "user" - pass "user" - 1 of 1 [child 0] (0/0)
DEBUG_CONNECT_OK
[DEBUG] SEND [pid:24075] (55 bytes):
0000:  4445 5343 5249 4245 2072 7473 703a 2f2f    [ DESCRIBE rtsp:// ]
0010:  reda cted 0000 0000 0000 0000 0000 3535    [ xx.xxx.xxx.xx:55 ]
0020:  3420 5254 5350 2f31 2e30 0d0a 4353 6571    [ 4 RTSP/1.0..CSeq ]
0030:  3a20 320d 0a0d 0a                          [ : 2....          ]
[DEBUG] hydra_receive_line: waittime: 32, conwait: 0, socket: 5, pid: 24075
[DEBUG] RECV [pid:24075] (169 bytes):
0000:  5254 5350 2f31 2e30 2034 3031 2055 6e61    [ RTSP/1.0 401 Una ]
0010:  7574 686f 7269 7a65 640d 0a43 5365 713a    [ uthorized..CSeq: ]
0020:  2032 0d0a 5365 7276 6572 3a20 4869 7063    [  2..Server: Hipc ]
0030:  616d 2052 6561 6c53 6572 7665 722f 5631    [ am RealServer/V1 ]
0040:  2e30 0d0a 5757 572d 4175 7468 656e 7469    [ .0..WWW-Authenti ]
0050:  6361 7465 3a20 4469 6765 7374 2072 6561    [ cate: Digest rea ]
0060:  6c6d 3d22 4869 7063 616d 2052 6561 6c53    [ lm="Hipcam RealS ]
0070:  6572 7665 722f 5631 2e30 222c 206e 6f6e    [ erver/V1.0", non ]
0080:  6365 3d22 6332 3338 3162 3863 3533 6462    [ ce="c2381b8c53db ]
0090:  6266 6230 6338 3364 6462 3766 3833 6137    [ bfb0c83ddb7f83a7 ]
00a0:  6331 6638 220d 0a0d 0a                     [ c1f8"....        ]
[ERROR] children crashed! (0)
[DEBUG] head_no[0] read E
[ATTEMPT-ERROR] target xx.xxx.xxx.xx - login "user" - pass "user" - child 0 - 1 of 1
[DEBUG] hydra_increase_fail_count: 1 >= 0 => disable
[DEBUG] - will be retried at the end: ip xx.xxx.xxx.xx - login user - pass user - child 0
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 24076
[DEBUG] head_no 0 has pid 24076
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 1, redo_state 0, pass_state 0. loop_mode 0, curlogin , curpass , tlogin -p, tpass user, logincnt 1/1, passcnt 0/1, loop_cnt 1
[COMPLETED] target xx.xxx.xxx.xx - login "" - pass "" - child 0 - 1 of 2
[DEBUG] send_next_pair_mid done 0, pass_state 0, clogin , cpass , tlogin -p, tpass user, redo 1
[DEBUG] Entering redo_state
[DEBUG] send_next_pair_init target 0, head 0, redo 1, redo_state 1, pass_state 0. loop_mode 0, curlogin , curpass , tlogin -p, tpass user, logincnt 1/1, passcnt 0/1, loop_cnt 2
[COMPLETED] target xx.xxx.xxx.xx - login "" - pass "" - child 0 - 1 of 2
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin user, cpass user, tlogin -p, tpass user, redo 1
[REDO-ATTEMPT] target xx.xxx.xxx.xx - login "user" - pass "user" - 2 of 2 [child 0] (1/1)
DEBUG_CONNECT_OK
[DEBUG] SEND [pid:24076] (55 bytes):
0000:  4445 5343 5249 4245 2072 7473 703a 2f2f    [ DESCRIBE rtsp:// ]
0010:  reda cted 0000 0000 0000 0000 0000 3535    [ xx.xxx.xxx.xx:55 ]
0020:  3420 5254 5350 2f31 2e30 0d0a 4353 6571    [ 4 RTSP/1.0..CSeq ]
0030:  3a20 320d 0a0d 0a                          [ : 2....          ]
[DEBUG] hydra_receive_line: waittime: 32, conwait: 0, socket: 5, pid: 24076
[DEBUG] RECV [pid:24076] (169 bytes):
0000:  5254 5350 2f31 2e30 2034 3031 2055 6e61    [ RTSP/1.0 401 Una ]
0010:  7574 686f 7269 7a65 640d 0a43 5365 713a    [ uthorized..CSeq: ]
0020:  2032 0d0a 5365 7276 6572 3a20 4869 7063    [  2..Server: Hipc ]
0030:  616d 2052 6561 6c53 6572 7665 722f 5631    [ am RealServer/V1 ]
0040:  2e30 0d0a 5757 572d 4175 7468 656e 7469    [ .0..WWW-Authenti ]
0050:  6361 7465 3a20 4469 6765 7374 2072 6561    [ cate: Digest rea ]
0060:  6c6d 3d22 4869 7063 616d 2052 6561 6c53    [ lm="Hipcam RealS ]
0070:  6572 7665 722f 5631 2e30 222c 206e 6f6e    [ erver/V1.0", non ]
0080:  6365 3d22 6131 3963 6432 3433 3631 6230    [ ce="a19cd24361b0 ]
0090:  3532 3237 3430 3238 3332 6434 3639 6234    [ 5227402832d469b4 ]
00a0:  6265 6565 220d 0a0d 0a                     [ beee"....        ]
[ERROR] children crashed! (0)
[DEBUG] head_no[0] read E
[ATTEMPT-ERROR] target xx.xxx.xxx.xx - login "user" - pass "user" - child 0 - 2 of 1
[DEBUG] hydra_increase_fail_count: 2 >= 0 => disable
[DEBUG] - will be retried at the end: ip xx.xxx.xxx.xx - login user - pass user - child 0
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 24077
[DEBUG] head_no 0 has pid 24077
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 2, redo_state 2, pass_state 0. loop_mode 0, curlogin , curpass , tlogin -p, tpass user, logincnt 1/1, passcnt 0/1, loop_cnt 1
[COMPLETED] target xx.xxx.xxx.xx - login "" - pass "" - child 0 - 2 of 3
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin user, cpass user, tlogin -p, tpass user, redo 2
[REDO-ATTEMPT] target xx.xxx.xxx.xx - login "user" - pass "user" - 3 of 3 [child 0] (2/2)
DEBUG_CONNECT_OK
[DEBUG] SEND [pid:24077] (55 bytes):
0000:  4445 5343 5249 4245 2072 7473 703a 2f2f    [ DESCRIBE rtsp:// ]
0010:  reda cted 0000 0000 0000 0000 0000 3535    [ xx.xxx.xxx.xx:55 ]
0020:  3420 5254 5350 2f31 2e30 0d0a 4353 6571    [ 4 RTSP/1.0..CSeq ]
0030:  3a20 320d 0a0d 0a                          [ : 2....          ]
[DEBUG] hydra_receive_line: waittime: 32, conwait: 0, socket: 5, pid: 24077
[DEBUG] RECV [pid:24077] (169 bytes):
0000:  5254 5350 2f31 2e30 2034 3031 2055 6e61    [ RTSP/1.0 401 Una ]
0010:  7574 686f 7269 7a65 640d 0a43 5365 713a    [ uthorized..CSeq: ]
0020:  2032 0d0a 5365 7276 6572 3a20 4869 7063    [  2..Server: Hipc ]
0030:  616d 2052 6561 6c53 6572 7665 722f 5631    [ am RealServer/V1 ]
0040:  2e30 0d0a 5757 572d 4175 7468 656e 7469    [ .0..WWW-Authenti ]
0050:  6361 7465 3a20 4469 6765 7374 2072 6561    [ cate: Digest rea ]
0060:  6c6d 3d22 4869 7063 616d 2052 6561 6c53    [ lm="Hipcam RealS ]
0070:  6572 7665 722f 5631 2e30 222c 206e 6f6e    [ erver/V1.0", non ]
0080:  6365 3d22 6562 3762 6238 3634 3139 6162    [ ce="eb7bb86419ab ]
0090:  3933 3764 6237 3830 6461 3337 3363 3635    [ 937db780da373c65 ]
00a0:  6264 6261 220d 0a0d 0a                     [ bdba"....        ]
[ERROR] children crashed! (0)
[DEBUG] head_no[0] read E
[ATTEMPT-ERROR] target xx.xxx.xxx.xx - login "user" - pass "user" - child 0 - 3 of 1
[DEBUG] hydra_increase_fail_count: 3 >= 0 => disable
[DEBUG] - will be retried at the end: ip xx.xxx.xxx.xx - login user - pass user - child 0
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 24078
[DEBUG] head_no 0 has pid 24078
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 3, redo_state 3, pass_state 0. loop_mode 0, curlogin , curpass , tlogin -p, tpass user, logincnt 1/1, passcnt 0/1, loop_cnt 1
[COMPLETED] target xx.xxx.xxx.xx - login "" - pass "" - child 0 - 3 of 4
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin user, cpass user, tlogin -p, tpass user, redo 3
[REDO-ATTEMPT] target xx.xxx.xxx.xx - login "user" - pass "user" - 4 of 4 [child 0] (3/3)
DEBUG_CONNECT_OK
[DEBUG] SEND [pid:24078] (55 bytes):
0000:  4445 5343 5249 4245 2072 7473 703a 2f2f    [ DESCRIBE rtsp:// ]
0010:  reda cted 0000 0000 0000 0000 0000 3535    [ xx.xxx.xxx.xx:55 ]
0020:  3420 5254 5350 2f31 2e30 0d0a 4353 6571    [ 4 RTSP/1.0..CSeq ]
0030:  3a20 320d 0a0d 0a                          [ : 2....          ]
[DEBUG] hydra_receive_line: waittime: 32, conwait: 0, socket: 5, pid: 24078
[DEBUG] RECV [pid:24078] (169 bytes):
0000:  5254 5350 2f31 2e30 2034 3031 2055 6e61    [ RTSP/1.0 401 Una ]
0010:  7574 686f 7269 7a65 640d 0a43 5365 713a    [ uthorized..CSeq: ]
0020:  2032 0d0a 5365 7276 6572 3a20 4869 7063    [  2..Server: Hipc ]
0030:  616d 2052 6561 6c53 6572 7665 722f 5631    [ am RealServer/V1 ]
0040:  2e30 0d0a 5757 572d 4175 7468 656e 7469    [ .0..WWW-Authenti ]
0050:  6361 7465 3a20 4469 6765 7374 2072 6561    [ cate: Digest rea ]
0060:  6c6d 3d22 4869 7063 616d 2052 6561 6c53    [ lm="Hipcam RealS ]
0070:  6572 7665 722f 5631 2e30 222c 206e 6f6e    [ erver/V1.0", non ]
0080:  6365 3d22 3239 6434 6634 6631 3735 3931    [ ce="29d4f4f17591 ]
0090:  3632 3662 6536 3336 6538 3338 6535 3930    [ 626be636e838e590 ]
00a0:  3364 3461 220d 0a0d 0a                     [ 3d4a"....        ]
[ERROR] children crashed! (0)
[DEBUG] head_no[0] read E
[ATTEMPT-ERROR] target xx.xxx.xxx.xx - login "user" - pass "user" - child 0 - 4 of 1
[DEBUG] hydra_increase_fail_count: 4 >= 0 => disable
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 24079
[DEBUG] head_no 0 has pid 24079
[DEBUG] head_no[0] read n
[STATUS] attack finished for xx.xxx.xxx.xx (waiting for children to complete tests)
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] all targets done and all heads finished
[DEBUG] while loop left with 1
1 of 1 target completed, 0 valid password found
[DEBUG] killing all remaining children now that might be stuck
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2019-12-10 20:33:46

System is Ubuntu 18.04.2 LTS (bionic). Hydra was compiled with -g. These services were not compiled in: afp ncp oracle sapr3. A core file (frustratingly) is not created. 

I understand it doesn't crah on your system; what can I do to help?

**Comment by amdorj** [comment]
After using some rudimentary debug tactics (shove printf statements everywhere), it reaches the `#ifdef` LIBOPENSSL` on line 137 and apparently crashes on function ` sasl_digest_md5`.

**Comment by amdorj** [comment]
sasl.c crashes during function `sasl_digest_md5` at [Line 529:](https://github.com/vanhauser-thc/thc-hydra/blob/d0c9d7ca3f84c7eaeda64bba6309fe713ee3202b/sasl.c#L529) `snprintf(result, 500, "username=\"%s\", realm=\"%s\", nonce=\"%s\", uri=\"%s://%s:%i\", response=\"%s\"\r\n", preplogin, realm, nonce, type, webtarget, port, buffer);`

I don't really know C that well so I hope this information helps. I see nothing wrong with the syntax, so I'm not sure what's happening.

**Comment by amdorj** [comment]
Changing [line 130](https://github.com/vanhauser-thc/thc-hydra/blob/d0c9d7ca3f84c7eaeda64bba6309fe713ee3202b/hydra-rtsp.c#L130) `char *dbuf = NULL;` to `char *dbuf = malloc(500);` seems to make everything work.

**Comment by vanhauser-thc** [comment]
That is correct.
your fix works, however the bug is deeper and needs quite some fixing.
thanks for reporting and sorry for the late handling!
please report back when the fix is in.

**Comment by vanhauser-thc** [comment]
OK this fix is in, if you still can - please test

**Comment by francisuk1989** [comment]
No idea if i can help @vanhauser-thc since @amdorj may or may not have the device.

I have a old genbolt thats runs the same as the above hipcam rtsp info and was having the children crashed error however now everything seems fine but dos not get the right login/password and keep hanging trying to guess.
