### ISSUE TITLE
pw-inspector tool keeps token with length = minlen - 1

### ISSUE THREAD

**Issue by gersona** [vanhauser-thc/thc-hydra#479]
I'm using the 9.0 version on a linux mint machine
i'm trying to reduce a password list, only keeping those with at least *minlen*  characters, but the result would also include some with *minlen - 1*  characters
for instance, using `cat list.txt | pw-inspector -m 5 > new_list.txt`, i would get some passwords with 4 characters 

same if i use other optional args like -c or -n

**Comment by vanhauser-thc** [comment]
From the code this looks impossible. could it be that there were carriage returns in there (\r)? thats the only thing possible. Just added a fix to remove these.

If this still happens please send the input file and the command line where this occurs.

**Comment by gersona** [comment]
oh yes, that's right, the CR was in fault in my lists
thanks
