### ISSUE TITLE
./configure issue

### ISSUE THREAD

**Issue by demokia** [vanhauser-thc/thc-hydra#480]
[thc-hydra.pdf](https://github.com/vanhauser-thc/thc-hydra/files/3974221/thc-hydra.pdf)

When I try to configure I run into this issue.

**Comment by vanhauser-thc** [comment]
very old gcc. install a newer one. this one is ancient

**Comment by demokia** [comment]
I am using rhel 6 and it is saying we are on the latest version of gcc Package
gcc-4.8.5-39.el7.x86_64 already installed and latest version
is there a specific version that is required? so i can enable new repos

**Comment by vanhauser-thc** [comment]
I think anything from 5.x onwards. current is version 9.x btw :)
