### ISSUE TITLE
Hydra not finding passwords

### ISSUE THREAD

**Issue by dac2020** [vanhauser-thc/thc-hydra#481]
I looked around the net and in the issues before posting this. I'm not sure if this is a known problem or something I'm doing wrong. Since I cannot find an answer, I thought I should post here.

I created a test password file with the password contained then run hydra and it doesn't find the password. The username and password on the device are both admin, admin. As you can see in the word list, the password exists buy hydra keeps going after trying it.

Centos 7.6. New server, minimal build, not much on it yet.

This is how I ran the command.
hydra -l admin -P testwords 192.168.1.41 -t 4 -V ssh

% hydra -l admin -P testwords 192.168.1.41 -t 4 -V ssh
Hydra v8.2-dev (c) 2016 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

`Hydra (http://www.thc.org/thc-hydra) starting at 2019-12-20 08:58:18
[DATA] max 4 tasks per 1 server, overall 64 tasks, 27 login tries (l:1/p:27), ~0 tries per task
[DATA] attacking service ssh on port 22
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "kingshit" - 1 of 27 [child 0]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "monkey" - 2 of 27 [child 1]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "admin" - 3 of 27 [child 2]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "abc123" - 4 of 27 [child 3]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "nicole" - 5 of 27 [child 1]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "daniel" - 6 of 27 [child 0]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "babygirl" - 7 of 27 [child 2]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "monkey" - 8 of 27 [child 3]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "lovely" - 9 of 27 [child 1]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "jessica" - 10 of 27 [child 0]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "654321" - 11 of 27 [child 2]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "michael" - 12 of 27 [child 3]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "ashley" - 13 of 27 [child 1]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "qwerty" - 14 of 27 [child 0]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "111111" - 15 of 27 [child 2]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "iloveu" - 16 of 27 [child 3]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "000000" - 17 of 27 [child 1]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "michelle" - 18 of 27 [child 0]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "tigger" - 19 of 27 [child 2]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "sunshine" - 20 of 27 [child 3]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "chocolate" - 21 of 27 [child 1]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "password1" - 22 of 27 [child 0]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "soccer" - 23 of 27 [child 2]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "anthony" - 24 of 27 [child 3]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "friends" - 25 of 27 [child 2]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "administrator" - 26 of 27 [child 3]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "" - 27 of 27 [child 0]
1 of 1 target completed, 0 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2019-12-20 08:58:50
`

**Comment by vanhauser-thc** [comment]
ancient hydra version. update

**Comment by dac2020** [comment]
Freshly installed on Centos 7.6. Would it not be current to that OS at least?

**Comment by vanhauser-thc** [comment]
current is 9.0 or 9.1-dev ... ;)
when distros update their version is their thing. and older distro == dont update the version

**Comment by dac2020** [comment]
Fair enough. Moving to centos-8 now but not finding any information what so ever on installing it on that. Thanks for the info and glad it was not a bug.

**Comment by vanhauser-thc** [comment]
just install compiler, libraries etc. and build it from this github repository

**Comment by dac2020** [comment]
Thanks, yes, I went ahead and downloaded source and working through the problems now. 
I'm still trying on Centos-7 however.

bfg.c:196:3: note: use option -std=c99 or -std=gnu99 to compile your code

No such options so working through it :).

**Comment by dac2020** [comment]
So I installed the full kali distro which hyrad 9.0 on it. I ran the exact same command and again, it doesn't stop when finding the password. I used the user admin and put the 'admin' password as the second line in the password file yet hydra does not result with a found password. 

I am missing something and if I am, it means non technical people are for sure missing it too :)

**Comment by vanhauser-thc** [comment]
does it work now for you?

**Comment by dac2020** [comment]
Yes, 'I'm all set' meant it's working fine now. Thank you for checking.
