### ISSUE TITLE
Help needed.

### ISSUE THREAD

**Issue by happyhacck** [vanhauser-thc/thc-hydra#483]
I have installed the thc-hydra-9.0.zip and it's extracted to my desktop.
When I open cmd, I typed:
1. cd desktop
2. cd thc-hydra-9.0
When I type:
hydra.exe as final setup, it shows:
is not recognized as an internal or external command,

Solution needed. Thank you.

**Comment by vanhauser-thc** [comment]
you have not compiled it. its source code. not an executable.

**Comment by happyhacck** [comment]
Hi. By how exactly am I going to do with this situation? I am new. Thx.
