### ISSUE TITLE
Use hydra with a API

### ISSUE THREAD

**Issue by carloshm91** [vanhauser-thc/thc-hydra#484]
I am trying to use hydra with a API, this is the command that I using

$ hydra site.com http-post-form -m "/api/Users/authenticate:Email=^USER^&Password=^PASS^:F=**error**" -L listOfUsers.txt -P listOfPasswords.txt -t 10 -w 30 -vV -f -o out.log

But in my case, **error** is a json string, how I can put it there?

Example of **error**:

{"message":"User and password wrong.","status":"error"}

Thanks in advance, Merry Christmas!!

**Comment by vanhauser-thc** [comment]
just exchange ```error``` in the command line with ```User and password wrong```
