### ISSUE TITLE
problem with -x function

### ISSUE THREAD

**Issue by stefan1318** [vanhauser-thc/thc-hydra#488]
https://photos.google.com/share/AF1QipPSbnxVlfd3yTDZ9arQZOwI7mSMv28GI_vno7WdEm15w1GAjfC3xxW2v5wWZX__sA/photo/AF1QipMGyRM7jEMw3wXFfqfTntBcs0g42vyMzWxnrek6?key=S2cxdTBTQUJsSmJaLVJHSHAwYlRLQmRuR0RITF93
I have a problem with hydra function that generate a password. it send me this error and can't start

**Comment by vanhauser-thc** [comment]
this means that you are trying to generate too many passwords. It would take many years to complete. makes no sense.
