### ISSUE TITLE
9.0 hydra-mod.c will not compile

### ISSUE THREAD

**Issue by fossildoc** [vanhauser-thc/thc-hydra#493]
On line 466 of this file, there is a statement ok = BN_zero(n). This is a macro which resolves to a function which returns a void. The compiler complains that it cannot assign a void to the variable ok.

All versions from 8.5 and later have this statement, and all those versions will not compile. This must be my fault, but I can't find it.

**Comment by vanhauser-thc** [comment]
I dont have much time so this is not a good fix, but it should compile now for you - please use the github state (git clone ...) and test

**Comment by jackma520** [comment]
I hit this error when I am compiling.
Below is the error screenshot.
![image](https://user-images.githubusercontent.com/38458623/73588095-c4f59700-44ff-11ea-903c-a1883cf34326.png)

**Comment by jackma520** [comment]
BTW, the 9.0 version is fine running on Centos7.x OS. It has been compiled.

**Comment by vanhauser-thc** [comment]
that other compile error is because the compiler is very, very, very old.
but fixed it.
