### ISSUE TITLE
Non existing password from the password list found (weird chars)

### ISSUE THREAD

**Issue by erkanaksoy** [vanhauser-thc/thc-hydra#494]
EDIT: Tried the same with another tool and result was same, so there is nothing wrong with hydra. Sorry for that.

Hi,
I was bruteforcing a web login form and hydra found a password which doesn't exists in the password list I used. The command is below (redacted the IP address)

hydra -l root -P /usr/share/seclists/Passwords/darkweb2017-top1000.txt example.com http-post-form "/webmail/src/redirect.php:login_username=^USER^&secretkey=^PASS^&js_autodetect_results=1&just_logged_in=1:Unknown user or password incorrect" -I -t 30

[80][http-post-form] host: example.com   login: root   password: пїЅпїЅпїЅпїЅпїЅпїЅ

According to google translate,  those characters are Kazakh language.

![image](https://user-images.githubusercontent.com/10220856/73616691-baceb800-4627-11ea-86b5-aad28d199bb7.png)

**Comment by vanhauser-thc** [comment]
could be false positive (e.g. when the web server terminates the connection hence the FAIL string is not seen). the password can either be a memory bug or that the characters are printed different on the screen then in a text editor if they are special characters.
what version are you using? current github state? if not please use that
