### ISSUE TITLE
 hydra freezes after completing one task

### ISSUE THREAD

**Issue by Anton19780301** [vanhauser-thc/thc-hydra#495]
Good afternoon.
You must find all the empty passwords of local administrators on the network.
I’m doing this as a test.

hydra -l Аdministrator -p MyPass0rd -t 1 192.168.56.1/24 smb

This is my local administrator login password, just to check the functionality.
But after the first selection, Hydra does nothing (does not write - 
I waited an hour), although I know for sure that the password/login pair is correct. That is, after the first attempt, the selection stops.
If you do so, then the password shows immediately

hydra -l Аdministrator -p MyPass0rd -t 1 192.168.56.1 smb

Does Hydra not support the IP range? Or did I type the command incorrectly?

**Comment by vanhauser-thc** [comment]
are you using the current version? or is it outdated?
/24 does work
also - if you use the github state (so you compile it yourself) you can use smb2 which might work better for you

**Comment by vanhauser-thc** [comment]
@Anton19780301 please react or I close the issue

**Comment by Anton19780301** [comment]
I react - the version is new, and it does not work if I do as I described. I have already used another tool. Hydra works correctly with only one purpose. Close if you want.

**Comment by vanhauser-thc** [comment]
@Anton19780301  did you compile from github? if not what is the version?

because it is working fine for me - with your command line.

**Comment by Anton19780301** [comment]
I used the version in the latest release of kali linux
maybe it does not work correctly. Hydra v9.0 (c) 2019.

**Comment by vanhauser-thc** [comment]
that code part was not touched ... can you please paste the full screen output?

**Comment by be4r** [comment]
Im experiencing the same problem. Pulled the repo today, 28.07.2021, built a Docker image and this happens:
```
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).                              

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2021-07-29 00:17:25                                                                                                                                                           
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task                                                                                                                                                       
[DATA] attacking http-post-form://172.17.0.2:80/wp-login.php:log=^USER^&pwd=^PASS^&testcookie=1&redirect_to=/wp-admin/:Welcome to WordPress!:H=Cookie: wordpress_test_cookie=WP%20Cookie%20check                                             

[ATTEMPT] target 172.17.0.2 - login "user" - pass "password" - 1 of 1 [child 0] (0/0)
[STATUS] 1.00 tries/min, 1 tries in 00:01h, 1 to do in 00:01h, 1 active                                                                                                                                                                      
[STATUS] 0.50 tries/min, 1 tries in 00:02h, 1 to do in 00:01h, 1 active
```
Stays like this and continues to load CPU to full even thou it should've just exited.

**Comment by vanhauser-thc** [comment]
@be4r  well no you didnt :) current github repo state is v9.3-dev. your output shows 9.1 .... :)

**Comment by be4r** [comment]
Yeah, thanks for pointing out my obvious mistake, cloned wrong repo :/ On 9.3-dev all seems to work as expected!
