### ISSUE TITLE
Please drop usage restriction for military/secret services and illegal purposes

### ISSUE THREAD

**Issue by rhertzog** [vanhauser-thc/thc-hydra#497]
Hello @vanhauser-thc,

the README states:
> Please do not use in military or secret service organizations, or for illegal purposes.

This restriction make hydra non-free for Debian. Among the criteria of the Debian Free Software Guidelines, there's « No Discrimination Against Fields of Endeavor » and forbidding usage in military/secret services clearly goes against that. See https://www.debian.org/social_contract.en.html#guidelines

Also, such a rule serves no real purpose. The persons who are already doing illegal activities have no problem in not respecting your license, thus breaking one more law. And secret/military services are already commonly breaking laws in the name of some greater cause... sometimes with the blessing of decision-makers.

Thus I would like to invite you to drop this requirement. It would avoid work for us because we have been informed of this problematic license in https://bugs.debian.org/951120 and it would make sure that hydra continues to be widely available by default (the non-free section of Debian is not enabled by default).

Thank you.

**Comment by vanhauser-thc** [comment]
@rhertzog I do not see an issue. It clearly states: "*PLEASE* do not"

its nice asking something and not making it a requirement, so RFC speak-wise it is a SHOULD not a MUST.

so why does that violate (A)GPL?

**Comment by rhertzog** [comment]
It's not at all clear that it's not a requirement but a wish. You're the author and the one who can define the license, the fact that you use "please" does not turn it into something that is not a requirement. A boss also gives orders by starting with "please" because it's nicer for everybody, it's still something that's a requirement from the point of view of the employee.

I still question the usefulness of such a wish given that those that would be impacted are unlikely to make any effort to follow your desire... and in the mean time it creates confusion on the license since such an additional requirement makes it non-free (it does not violate the AGPL, but the combined result is not compliant with the Debian Free Software Guidelines).

If you want to keep that statement, can you make it clear that it's not part of the license binding the user and the author ?

Maybe something like this:

> Please do not use in military or secret service organizations, or for illegal purposes. (This statement is not part of the license, it's just a wish that I invite you to follow)

**Comment by rhertzog** [comment]
If you decide to entirely remove the statement, I want to point out that it is also in the output of "hydra -h".

**Comment by vanhauser-thc** [comment]
I put more text in, I guess its fine now? 90bbde1

**Comment by rhertzog** [comment]
Yes, thank you.
