### ISSUE TITLE
Tool viability

### ISSUE THREAD

**Issue by cfcc2020** [vanhauser-thc/thc-hydra#499]
I have read some of your closed issues regarding:
[ERROR] definition for password bruteforce (-x) generates more than 4 billion passwords

Does this mean that this tool cannot do a -x 8:8:Aa1 brute force? Because that is the error I am getting and I already know that the pass I am trying to retrieve is 8 characters with upper/lower and numbers.
It's an old/previous router from my ISP who will not give me the admin pass and yes, I already tried the factory reset bit, but they have a custom firmware, so that does nothing for this case.
Respectfully

**Comment by vanhauser-thc** [comment]
you would not believe how many messages I get for that. I changed the error message to:

```
[ERROR] definition for password bruteforce (-x) generates more than 4 billion passwords - this is not a bug in the program, it is just not feasible to try so many attempts. Try a calculator how long that would take. duh.
```

;)
