### ISSUE TITLE
Configuration issues (iphoneos-arm)

### ISSUE THREAD

**Issue by The-SamminAter** [vanhauser-thc/thc-hydra#502]
This is on iOS 13.2.3

The following aren’t found when running `configure`:

• libssh.h, which is present in /usr/include/libssh/

• libafpclient.la is present in /use/lib/, and libafpclient.so doesn’t exist. I do not know if this is a problem with afpfs-ng or not

• MySQL is installed. I do not know if math.h is present, or where it would be. libmysqlclient.so is found

• PostgreSQL is installed, libpq-fe.h is present in /usr/local/pgsql/include/, I don’t know if libpq.so is present, or where it would be

I am searching for these files now

**Comment by vanhauser-thc** [comment]
... and the issue is?
And what is the output?
anything?
If you dont know if a file exists - the should be a "find" command.

Please give me enough information so I can see what the issue is, what is wrong and then have the information needed to fix it.

**Comment by The-SamminAter** [comment]
Edited

**Comment by The-SamminAter** [comment]
I edited the issue

**Comment by vanhauser-thc** [comment]
you mean in the other issue with the march=native? then close this one please

**Comment by The-SamminAter** [comment]
These are two separate issues. This one is about configure not finding libssh, and possibly some other files, and the other issue is about bot being able to build hydra after it’s been built

**Comment by The-SamminAter** [comment]
I'm closing this issue. Sorry for forgetting about this until now, and for wasting your time on this.
