### ISSUE TITLE
hydra on gmail smtp is fake

### ISSUE THREAD

**Issue by alfeardo** [vanhauser-thc/thc-hydra#505]
after running the brute on my account placing the password ..

claiming the password is validated but its fake ...

is this error for me only or for all ? how i can fix it ..
thanks

**Comment by Anonymous11C** [comment]
Actually Brute force nor Dictionary attack will work on gmail account because it uses mechanism to prevent these attacks.

    - Captcha : those strange looking letters that not even humans can read need to be submitted after every try after the first 4 wrong attempts.

    - Login form has hidden values that change every time you submit the form.


None of this can be solved with Hydra or any other known software.

**Comment by vanhauser-thc** [comment]
@Anonymous11C there are not captchas on smtp, only on web
@alfeardo if you read hydra output: `[WARNING] Google Mail and others have bruteforce and hydra detection and sends false positives. You are not doing anything illegal right?!`

**Comment by goyonas** [comment]
so how can i do it ? if any one know how to hack gmail with hydra please tell me ! "its for educational purpose only"
