### ISSUE TITLE
Skip GET request

### ISSUE THREAD

**Issue by GitAntoinee** [vanhauser-thc/thc-hydra#506]
Hello,
I am using hydra, but I can see that a GET request is made before the expected request. Is there a way to skip this GET request, if necessary: in some servers there is no cookies needed. And sending this GET request reduce the performances.

I hope you understand my English!

**Comment by vanhauser-thc** [comment]
This is very rare that this is not needed.
I understand you request though. I have not time to do that, but if you send a pull request that adds an option (miscptr option like C=, H= etc.) then I will accept that into the repository

**Comment by GitAntoinee** [comment]
Hello, thanks for the reply.
Note that the miscptr option (named in this case `G`) do not need arguments, it can be used like `/login:body:S=valid:G`

**Comment by vanhauser-thc** [comment]
or it could be an empty C= option, i don't care. somebody has to write the code though and add it to the help output of the module :)

**Comment by GitAntoinee** [comment]
Hello, I created a pull request : #509

**Comment by GitAntoinee** [comment]
The pull request is merged.
