### ISSUE TITLE
I entered my own email and password for yahoo account

### ISSUE THREAD

**Issue by sandnima** [vanhauser-thc/thc-hydra#507]
It seems like HYDRA in not correctly working for yahoo smtp attemp. I've tested with proxy too.
I use this part of command and I put my own password in pass file, but hydra says 0 valid passwords found
`hydra -l [user]@yahoo.com -P C:\Downloads\cupp\pass.txt -e ns -s 465 -S -v -V smtp.mail.yahoo.com smtp HYDRA_PROXY_HTTP=proxy.txt`
plese help!
 (It worked for gmail)

**Comment by vanhauser-thc** [comment]
it helps if you can read hydra output: `[WARNING] Google Mail and others have bruteforce and hydra detection and sends false positives. You are not doing anything illegal right?!`
