### ISSUE TITLE
RDP module disabled in cygwin

### ISSUE THREAD

**Issue by Robin6464** [vanhauser-thc/thc-hydra#508]
When compiling, it says that I do not have freerdp2 installed. I have all rdp packages installed in cygwin. How to solve the problem?

Checking for Freerdp2 (libfreerdp2.so, freerdp/.h, libwinpr2.so, winpr/.h) ...
... NOT found, module rdp disabled

https://imgur.com/a/QOk5p1S

**Comment by Robin6464** [comment]
I was able to solve the problem in an unusual way. In cygwin64\usr\local\lib there were already rdp files from cygwin after installing all rdp packages. I made copies of libfreerdp2.dll.a and libwinpr2.dll.a in this location and changed their names to libfreerdp2.so and libwinpr2.so. After compiling thc-hydra, the freerdp2 module was now available. I made a dictionary RDP butal attack on Windows 8.1 PROx64 and the password was found correctly.

**Comment by vanhauser-thc** [comment]
good to hear that. weird that this solved your problem though :)

**Comment by Robin6464** [comment]
Right now I didn't have access to rdp on the virtual machine, but it shows that it works :)

https://imgur.com/a/1n11lsl


admin@Komputer ~
$ cd hydra

admin@Komputer ~/hydra
$ ./configure

Starting hydra auto configuration ...

Checking for zlib (libz.so, zlib.h) ...
                                        ... found
Checking for openssl (libssl, libcrypto, ssl.h, sha.h) ...
                                                       ... found
Checking for gcrypt (libgcrypt.so, gpg-error.h) ...
                                        ... found
Checking for idn (libidn.so) ...
                             ... found
Checking for curses (libcurses.so / term.h) ...
                                            ... found, color output enabled
Checking for pcre (libpcre.so, pcre.h) ...
                                       ... found
Checking for Postgres (libpq.so, libpq-fe.h) ...
                                             ... found
Checking for SVN (libsvn_client-1 libapr-1.so libaprutil-1.so) ...
                                                               ... NOT found, module svn disabled
Checking for firebird (libfbclient.so) ...
                                       ... NOT found, module firebird disabled
Checking for MYSQL client (libmysqlclient.so, math.h) ...
                                                      ... found
Checking for AFP (libafpclient.so) ...
                                   ... NOT found, module Apple Filing Protocol disabled - Apple sucks anyway
Checking for NCP (libncp.so / nwcalls.h) ...
                                         ... NOT found, module NCP disabled
Checking for SAP/R3 (librfc/saprfc.h) ...
                                      ... NOT found, module sapr3 disabled
Get it from http://www.sap.com/solutions/netweaver/linux/eval/index.asp
Checking for libssh (libssh/libssh.h) ...
                                      ... found
Checking for Oracle (libocci.so libclntsh.so / oci.h and libaio.so) ...
                                                                    ... NOT found, module Oracle disabled
Get basic and sdk package from http://www.oracle.com/technetwork/database/features/instant-client/index.html
Checking for Memcached (libmemcached.so, memcached.h) ...
                                             ... NOT found, module memcached disabled
Checking for Freerdp2 (libfreerdp2.so, freerdp/*.h, libwinpr2.so, winpr/*.h) ...
                                             ... found
Checking for Mongodb (libmongoc-1.0.so, mongoc.h, libbson-1.0.so, bson.h) ...
                                             ... NOT found, module mongodb disabled
Checking for smbclient (libsmbclient.so, libsmbclient.h) ...
                                             ... NOT found, module smb2 disabled
Checking for GUI req's (pkg-config, gtk+-2.0) ...
                                              ... found
Checking for Android specialities ...
                                  ... strrchr() found
                                  ... RSA_generate_key() found
Checking for secure compile option support in gcc ...
                                                  Compiling... yes
                                                  Linking... no

Hydra will be installed into .../bin of: /usr/local
  (change this by running ./configure --prefix=path)

Writing Makefile.in ...

Cygwin detected, if compilation fails just update your installation.

Windres found, will attach icons to hydra cygwin executables

now type "make"

admin@Komputer ~/hydra
