### ISSUE TITLE
Error running with proxychains

### ISSUE THREAD

**Issue by Loloman2** [vanhauser-thc/thc-hydra#513]
Im running this:
sudo proxychains hydra -l MrAlex9 -P testing.txt www.ideletedomainforprivacy.com https-post-form "/login:dopost=1&timezone=120&hasjs=y&username=^USER^&password=^PASS^&.submit=Entrar:incorrecto.:H=Cookie: scrollPos=ATLIXGBXVG; over18=1; af_locale=es"  -V

When I run without proxychains it runs well and it detects the password aswell, however, once i run with proxychains I get this:

Hydra (http://www.thc.org/thc-hydra) starting at 2020-04-12 00:58:39
[DATA] max 4 tasks per 1 server, overall 4 tasks, 4 login tries (l:1/p:4), ~1 try per task
[DATA] attacking http-post-forms://www.domain.com:443//login:dopost=1&timezone=120&hasjs=y&username=^USER^&password=^PASS^&.submit=Entrar:incorrecto.:H=Cookie: scrollPos=ATLIXGBXVG; over18=1; af_locale=es
|DNS-request| www.domain.com
|D-chain|-<>-127.0.0.1:9050-<><>-4.2.2.2:53-<><>-OK

PS: I deleted real domain ye, but im actually not running it in an domain without permission, using mine for learn to use this.

**Comment by vanhauser-thc** [comment]
if it works without proxychains but not with proxychains - what makes you think it is a problem with hydra? ;)
also - you can use HYDRA_PROXY/HYDRA_PROXY_HTTP if you only want one proxy in between
