### ISSUE TITLE
Hydra not decoding ^USER^ and ^PASS^ when passed as HTTP Headers

### ISSUE THREAD

**Issue by jhertz** [vanhauser-thc/thc-hydra#514]
Hi All,

So I'm trying to use hydra to bruteforce a login on a system that uses custom http headers to receive the username and password.  Hydra does not seem to be doing substitution of ^USER^ and ^PASS^ when used as HTTP headers. If I issue issuing a call to hydra like this:

`hydra "http-post://0.0.0.0:8000/:H=username\:^USER^:H=password\:^PASS^"  -l admin -p admin`

I see the following result in my nc session:

```
POST / HTTP/1.1
Host: 0.0.0.0
Connection: close
Authorization: Basic YWRtaW46YWRtaW4=
User-Agent: Mozilla/4.0 (Hydra)
username: ^USER^
password: ^PASS^
Content-Length: 0
```

Am I invoking hydra incorrectly or is this a bug?

(I am on the latest build from git-master).

**Comment by jhertz** [comment]
I just confirmed this issue is also present on the v9.0 release.

**Comment by jhertz** [comment]
Just to make sure it wasn't the module, I confirmed the 'http-form-post' module (which has the code to do this conversion) exhibits this bug. Very strange.

**Comment by cygonz0** [comment]
The substitution code seems to be buggy. 

When I run:

```
hydra -v -V -L "user.txt" -P "pass.txt" -s 8080 192.168.2.111 http-get-form "/bea_wls_deployment_internal/DeploymentService:user=^USER^&password=^PASS^:h=username\:^USER^:h=password\:^PASS^"
```

I get:

```
GET /bea_wls_deployment_internal/DeploymentService?user=admin2&password=password123 HTTP/1.0
password: password123
Host: 192.168.2.111
User-Agent: Mozilla/5.0 (Hydra)
Cookie: 
Connection: close
```

But if I "overload" the `:h` parameters like (e.g. defining the custom username header twice):
```
hydra -v -V -L "user.txt" -P "pass.txt" -s 8080 192.168.2.111 http-get-form "/bea_wls_deployment_internal/DeploymentService::h=username\:^USER^:h=password\:^PASS^:h=username\:^USER^"
```

I get:

```
GET /bea_wls_deployment_internal/DeploymentService? HTTP/1.0
password: password123
username: admin1
Host: 192.168.2.111
User-Agent: Mozilla/5.0 (Hydra)
Cookie: 
Connection: close
```
Funky!

**Comment by cygonz0** [comment]
The substitution code seems to be buggy. 

When I run:

```
hydra -v -V -L "user.txt" -P "pass.txt" -s 8080 192.168.2.111 http-get-form "/xxx:user=^USER^&password=^PASS^:h=username\:^USER^:h=password\:^PASS^"
```

I get:

```
GET /xxx?user=admin2&password=password123 HTTP/1.0
password: password123
Host: 192.168.2.111
User-Agent: Mozilla/5.0 (Hydra)
Cookie: 
Connection: close
```

But if I "overload" the `:h` parameters like (e.g. defining the custom username header twice):
```
hydra -v -V -L "user.txt" -P "pass.txt" -s 8080 192.168.2.111 http-get-form "/xxx:h=username\:^USER^:h=password\:^PASS^:h=username\:^USER^"
```

I get:

```
GET /xxx? HTTP/1.0
password: password123
username: admin1
Host: 192.168.2.111
User-Agent: Mozilla/5.0 (Hydra)
Cookie: 
Connection: close
```
Funky!

**Comment by cygonz0** [comment]
The substitution code seems to be buggy. 

When I run:

```
hydra -v -V -L "user.txt" -P "pass.txt" -s 8080 192.168.2.111 http-get-form "/xxx:user=^USER^&password=^PASS^:h=username\:^USER^:h=password\:^PASS^"
```

I get:

```
GET /xxx?user=admin1&password=password123 HTTP/1.0
password: password123
Host: 192.168.2.111
User-Agent: Mozilla/5.0 (Hydra)
Cookie: 
Connection: close
```

But if I "overload" the `:h` parameters like (e.g. defining the custom username header twice):
```
hydra -v -V -L "user.txt" -P "pass.txt" -s 8080 192.168.2.111 http-get-form "/xxx:h=username\:^USER^:h=password\:^PASS^:h=username\:^USER^"
```

I get:

```
GET /xxx? HTTP/1.0
password: password123
username: admin1
Host: 192.168.2.111
User-Agent: Mozilla/5.0 (Hydra)
Cookie: 
Connection: close
```

Also doing:
```
hydra -v -V -L "user.txt" -P "pass.txt" -s 8080 192.168.2.111 http-get-form "/xxx::a:h=username\:^USER^:h=password\:^PASS^"

```

Returns:

```
GET /xxx? HTTP/1.0
username: admin1
password: password123
Host: 192.168.2.111
User-Agent: Mozilla/5.0 (Hydra)
Cookie: 
Connection: close
```

Looks like the parsing of the parameter indexes is buggy.

**Comment by vanhauser-thc** [comment]
Hi,
this is not really a bug - ^user^/^pass^ replacement in the header option is simply not supported. never before someone wanted/needed that.
should be very easy to add though. but I dont have time for that at the moment, but feel free to send a pull request.

**Comment by jhertz** [comment]
Hi Vanhauser,

Thanks for responding so quickly. So code to perform this substitution is present in the codebase: https://github.com/vanhauser-thc/thc-hydra/blob/master/hydra-http-form.c#L744

But due to buggy parsing of command line parameters, it only sometimes get activated correctly. I am not sure why this is, and unfortunately don't have time right now to track down the underlying issue.

**Comment by Hafiz11732482** [comment]
في ماذا استفيد من عدار

**Comment by gitak9** [comment]
**hi**

**Comment by vanhauser-thc** [comment]
the need to duplicate the header seems fixed, works fine for me, eg.
`hydra -d -l user -p pass 127.0.0.1 http-get-form "/test.txt::S=test:h=username\: ^USER^:h=password\: ^PASS^"`
->
```
GET /test.txt? HTTP/1.0
username: user
password: pass
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (Hydra)
Cookie: 
```
the very first connect has ^USER^/^PASS^ instead because that is just an initial empty request to get cookies ...
