### ISSUE TITLE
Hydra does not find password even though it's correct. 

### ISSUE THREAD

**Issue by twinkette** [vanhauser-thc/thc-hydra#515]
I am attempting on my own Outlook account. 

The syntax is:

`hydra -l name@outlook.com -p my_password -s 465 -S -v -V smtp.office365.com smtp`

Hydra resolves the address but then:

`[ATTEMPT] target smtp.office365.com - login "name@outlook.com" - pass "my_password" - 1 of 1 [child 0] (0/0)
`

Yet my password is my_password. What am I doing wrong? Thanks. 
`

**Comment by vanhauser-thc** [comment]
add -d option to see the messages being sent that might help
