### ISSUE TITLE
Hydra: 0 valid passwords found even is my password

### ISSUE THREAD

**Issue by Manuelucki** [vanhauser-thc/thc-hydra#517]
_I am attemping on my own account of "hobba.tv"
I'm using a test username and password that I just created.

The syntax is:_ 

`hydra -l mamatoton -p lolmen12 -vV -s 80 -f www.hobba.tv http-post-form "/index.php:login-account=^USER^&login-password=^PASS^&button=Login:Entrar"`

When i start with that command it appears this:
**Hydra (http://www.thc.org/thc-hydra) starting at 2020-04-22 12:08:55
[DATA] max 1 task per 1 server, overall 64 tasks, 1 login try (l:1/p:1), ~0 tries per task
[DATA] attacking service http-post-form on port 80
[VERBOSE] Resolving addresses ... done
[ATTEMPT] target www.hobba.tv - login "mamatoton" - pass "lolmen12" - 1 of 1 [child 0]
[VERBOSE] Page redirected to http://www.hobba.tv/index.ph
[VERBOSE] Page redirected to http://www.hobba.tv/index.p
[VERBOSE] Page redirected to http://www.hobba.tv/index.
[VERBOSE] Page redirected to http://www.hobba.tv/index
[VERBOSE] Page redirected to http://www.hobba.tv/inde
[VERBOSE] Page redirected to http://www.hobba.tv/ind
[VERBOSE] Page redirected to http://www.hobba.tv/in
[VERBOSE] Page redirected to http://www.hobba.tv/i
[STATUS] attack finished for www.hobba.tv (waiting for children to complete tests)
1 of 1 target completed, 0 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2020-04-22 12:08:56**

As you can see, the link is http://www.hobba.tv, so if you guys can check If I have an error (looking the view source of the page) it would help me a lot :/

**Comment by Manuelucki** [comment]
BTW, I just started using hydra today, so If I get an answer, ppllllleeeease try to explain something that I could understand xD

**Comment by vanhauser-thc** [comment]
it helps to a) add the -d option to see the request and response. and b) use a web proxy software to see how a) differs to what your web browser sends.

**Comment by Manuelucki** [comment]
Just recieved this: 
https://pastebin.com/M8u9PU4B

**Comment by Manuelucki** [comment]
> it helps to a) add the -d option to see the request and response. and b) use a web proxy software to see how a) differs to what your web browser sends.

Recieved this:
https://pastebin.com/M8u9PU4B
