### ISSUE TITLE
libfreerdp2.a and libwinpr2.a do not exist on Cygwin

### ISSUE THREAD

**Issue by maaaaz** [vanhauser-thc/thc-hydra#519]
Hello @vanhauser-thc,

By default on Cygwin :
* `libfreerdp2` is named `libfreerdp2.dll.a`, not [`libfreerdp2.a`](https://github.com/vanhauser-thc/thc-hydra/blob/master/configure#L1028).
* `libwinpr2` is named `libwinpr2.dll.a`, not [`libwinpr2.a`](https://github.com/vanhauser-thc/thc-hydra/blob/master/configure#L1054) or [`winpr.dll`](https://github.com/vanhauser-thc/thc-hydra/blob/master/configure#L1059).

Cheers.

**Comment by vanhauser-thc** [comment]
here too: feel free to send in a patch (pull request).

**Comment by maaaaz** [comment]
https://github.com/vanhauser-thc/thc-hydra/pull/522
