### ISSUE TITLE
Recurrent no password found

### ISSUE THREAD

**Issue by Blbl** [vanhauser-thc/thc-hydra#521]
Hello,

I'm now trying hydra on Mac OS X. I'm trying to log in to my own reddit account, just to see how it works.

But it doesn't stop sending back to me "no password found", but of course this is my account so I'm sure the password is correct. 

Here is my line : `hydra -l ScroH -p mypass -Vv -f -t 5 reddit.com http-form-post "/login:username=^USER^&password=^PASS^:Incorrect password"`

You can have a look to HTML code of reddit.com/login, all informations are right.
I've been trying to solve this for a while now...

If someone could indicate me something to do, it would be great!
Thanks in advance

**Comment by Blbl** [comment]
I ran hydra with -d option, if someone is interested...
https://pastebin.com/rZZKjfqx

Thanks!

**Comment by Manuelucki** [comment]
Have the same problem... and still looking for an answer from somebody expert in the program.. :/

**Comment by vanhauser-thc** [comment]
use a proxy like zapproxy and see what the browser is sending and receiving and then use the -d option in hydra and massage until you have setup the request correctly
