### ISSUE TITLE
thc-hydra

### ISSUE THREAD

**Issue by Ghost-hashempire** [vanhauser-thc/thc-hydra#524]
Hi @ vanhauser

I’m having this issue with thc-hydra in my Kali and blackarch Linux 

[Error] freerdp: The connection fail to establish. 

Pls what’s the solution?

**Comment by vanhauser-thc** [comment]
how should I know? how does your issue explain anything of the setup, the target, the command line options used?

**Comment by Ghost-hashempire** [comment]
It was a network issue then but there another issue when and it’s only when to cracker RDP the response is that (Freerdp2) is not compiled with Thc-hydra and I have install it.
