### ISSUE TITLE
Doesn't detect ^USER and ^PASS strings

### ISSUE THREAD

**Issue by theamazingwaffle** [vanhauser-thc/thc-hydra#525]
here's the error message:  
```
Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2020-04-28 13:02:25
[ERROR] the variables argument needs at least the strings ^USER^, ^PASS^, ^USER64^ or ^PASS64^: username=^USER&password=^PASS&queryParams=%7B%7D&optIntoOneTap=false
```

As you can see, i put ^USER and ^PASS there.  
Here's the command (domain name, ip and username modified)  
```bash
./hydra -l someusername -P common_passwords.txt someIpAddress http-post-form "/www.somewebsite.com/accounts/login/ajax:username=^USER&password=^PASS&queryParams=%7B%7D&optIntoOneTap=false:Sorry, your password was incorrect. Please double-check your password."
```

**Comment by vanhauser-thc** [comment]
it is `^USER^` not `^USER`

**Comment by theamazingwaffle** [comment]
@vanhauser-thc i'm so sorry for my stupid mistake...

**Comment by OnlineHacKing** [comment]
┌──(root💀OnlineHacking)-[~]
└─# hydra 147.139.6.113:8090 http-post-form "/username=^USER^&password=^PASS^verifyLoginCredentials()=Submit:Could Not Login, Error message: Administrator matching query does not exist. " -L /root/Desktop/user.txt -P /root/Desktop/pass.txt -V -f
Hydra v9.3 (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).



Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-05-09 03:21:29
[ERROR] the variables argument needs at least the strings ^USER^, ^PASS^, ^USER64^ or ^PASS64^: Could Not Login, Error message
