### ISSUE TITLE
[ERROR] freerdp init failed

### ISSUE THREAD

**Issue by Golden-Security** [vanhauser-thc/thc-hydra#528]
i have a problem [ERROR] freerdp init failed
when i work on ssh is work good but when i shell_exec i get this error 
![Screenshot_16](https://user-images.githubusercontent.com/37330496/81489903-5e5ce380-927b-11ea-9c24-d3e06fa1c8ba.png)
 
but in ssh is work good 

![Screenshot_17](https://user-images.githubusercontent.com/37330496/81489926-982dea00-927b-11ea-832e-fa5fccffc0fe.png)

**Comment by Kbishou** [comment]
have you solved the problem？ I got the same issue^-^

**Comment by kxjhcs** [comment]
have you solved the problem?
