### ISSUE TITLE
Problems when working with proxies

### ISSUE THREAD

**Issue by knivets** [vanhauser-thc/thc-hydra#537]
Here's the command that I use:

`HYDRA_PROXY="connect://login:pwd@exampleproxy.com:10000"
hydra  -I -l admin -P passwords.txt example.com https-post-form "/login:username=^USER^&password=^PASS^:Invalid password"`

I have also tried this one:

`HYDRA_PROXY_HTTP="http://login:pwd@exampleproxy.com:10000"
hydra  -I -l admin -P passwords.txt example.com https-post-form "/login:username=^USER^&password=^PASS^:Invalid password"`

The problem I have is that when using those commands Hydra always returns the following errors:

```
[ERROR] Child with pid 73777 terminating, cannot connect
```

If I remove the proxy variable, it works. What should I do?

**Comment by vanhauser-thc** [comment]
my guess is the problem is the proxy.

you can add the -d flag and see all output sent and received.
