### ISSUE TITLE
Problem with mongodb

### ISSUE THREAD

**Issue by yangT1112** [vanhauser-thc/thc-hydra#539]
[INFO] Using default database "admin"
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 0, redo_state 0, pass_state 0. loop_mode 0, curlogin (null), curpass (null), tlogin test, tpass test, logincnt 0/1, passcnt 0/1, loop_cnt 1
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin test, cpass test, tlogin -p, tpass test, redo 0
[ATTEMPT] target 10.0.13.112 - login "test" - pass "test" - 1 of 1 [child 0] (0/0)
*** Error in `./hydra': free(): invalid next size (fast): 0x00005583213c4fe0 ***
*** Error in `./hydra': malloc(): memory corruption: 0x00005583213c50a0 ***
[STATUS] 1.00 tries/min, 1 tries in 00:01h, 1 to do in 00:01h, 1 active

when guessing mongodb,the program has these errors and not exit, and i don't know where are the error? can you give me some advise?

**Comment by vanhauser-thc** [comment]
which version are you using?

**Comment by yangT1112** [comment]
the version is 4.0.7,and the version of 3.6.18 also has these problems ,I find that in 
hydra-mongodb.c ,it start at about 80 lines:
collection = mongoc_client_get_collection(client, miscptr, "test");
cursor = mongoc_collection_find_with_opts(collection, &q, NULL, NULL);
r = mongoc_cursor_next(cursor, &doc);
the function of mongoc_cursor_next reports these error,is it because the table content is empty?

**Comment by vanhauser-thc** [comment]
I mean the version of hydra :)

**Comment by yangT1112** [comment]
9.0

**Comment by vanhauser-thc** [comment]
can you please checkout the current git state here?
then build it and use this one.
then: "ulimit -c unlimited"
then run the hydra command. it might crash again, if so a core file is generated.
use gdb: "gdb ./hydra core.<number>", on the console type "backtrace" and send the whole output.
I do not have a mongodb so cant check

**Comment by yangT1112** [comment]
I have fount  out  that the reason is my some linux library version is not support the mongodb，so the 
the function of mongoc_cursor_next reports these errors.change the platform and install hydra and no error
