### ISSUE TITLE
redis弱口令爆破，ip能ping通，但是端口不通，hydra会阻塞，一直等待

### ISSUE THREAD

**Issue by HelloDoria** [vanhauser-thc/thc-hydra#543]
测试过程中，有个远程主机，IP是通的，端口号 6379 访问不通，用 hydra 进行若口令爆破，程序一直运行，跑了7天还没结束，hydra是不是没有这种连通性测试啊，如果不通的话，直接跳过吧应该

**Comment by vanhauser-thc** [comment]
write english ... neither me not many other people understand chinese. sorry
