### ISSUE TITLE
It's working on http-post-form; it isn't working on https-post-form (same web app)

### ISSUE THREAD

**Issue by o-alquimista** [vanhauser-thc/thc-hydra#544]
The commands I'm using for HTTPS and HTTP, respectively _(only the Hydra module and the `<domain>` changes)_:
```
hydra -l <user> -P <password_file> -F "https-post-form://<domain>/<page>:username=^USER^&password=^PASS^&_csrf_token=<token>:S=<text_on_success>:H=Cookie\: <session_cookie_name>=<cookie_value>"
hydra -l <user> -P <password_file> -F "http-post-form://<domain>/<page>:username=^USER^&password=^PASS^&_csrf_token=<token>:S=<text_on_success>:H=Cookie\: <session_cookie_name>=<cookie_value>"
```

### The target hosts and the web application
The HTTP target is my computer, on localhost. The HTTPS target is hosted on a remote server.

The same web application is used on both targets. It contains a POST login form with CSRF protection. The session ID will be regenerated upon a successful login. The application on the remote server is configured with a Let's Encrypt certificate and can only be accessed with HTTPS.

### The module options
To retrieve the CSRF token and session ID I'm using the browser inspector to copy and paste each of them onto the command, while making sure they are not consumed - as I said, the session ID changes when you successfully login, which invalidates the CSRF token.

The success text `S=` is the same I used for the HTTP target. It should work for HTTPS too.

### The problem
The requests made to the HTTP target consistently return the correct password. The requests made to the HTTPS target do not return any, even though they are reaching the server and even triggering a regeneration of the session ID. If I remove the correct password from the password list, the session ID remains unchanged.

In either case, the result from the HTTPS attack is always `1 of 1 target completed, 0 valid passwords found`. There are no errors. Due to the session ID becoming invalid after running Hydra, I believe it is actually performing a successful login, but it's not recognizing the success `S=` condition and therefore the correct password is never found.

### Logs?
I have collected a verbose/debug log of one of these HTTPS attempts. But as the file contains a lot of potentially sensitive info, I'd rather not upload it unless it's really needed for us to figure out the problem.

My description of the problem alone could be enough. However, if you need access to my target website and the text I used to detect a successful login, I'll update this issue with that.

**Comment by vanhauser-thc** [comment]
my guess is simply - it is not the same data that is returned ;) there is no difference in the http module if it is https or http.

check the data that is sent and received by adding the -d switch. (and test with only one login and password at a time)

**Comment by o-alquimista** [comment]
I have created two logs with the -d switch, one for HTTP and another for HTTPS.

### HTTP:
At a certain point after the POST is sent, a redirect starts from the login page `/entrar` to the home page `/`, as expected when you successfully authenticates:
```
[VERBOSE] Page redirected to http://kabum.develop/
```

My success text is in this log, so Hydra successfully identifies the correct password.

### HTTPS:
Something isn't right about the HTTPS request:
```
[VERBOSE] Page redirected to http://:443/entrar
```
See? It's missing the domain. Also, it's redirecting to the login page `/entrar` instead of the home page `/`.

Hydra then receives a `400 Bad Request` error page. This makes the HTTPS log file much smaller than the HTTP log. It doesn't contain the success text I defined.

Do you think it could it be a problem with Hydra?

**Comment by vanhauser-thc** [comment]
it could be a problem but I doubt it - as I said - same code.
maybe the redirect from the target is wrong. check the logs what is different, especially where in your local setup the reply contains kabum.develop and what is at the same part of the reply from the real target

**Comment by o-alquimista** [comment]
I think you're right. There seems to be something wrong with the redirection response the server gives us after the POST. I see no problems accessing it through the browser, though. I'll investigate this in the coming days and update this issue if I find a solution.

**Comment by vanhauser-thc** [comment]
any update? what is the difference? (add the -d option and compare)

**Comment by o-alquimista** [comment]
I haven't had much time to look into this, but I do have some new information.

The https response is pretty similar to the one received through http until the part where it sets cookies. That is where it gets interesting. A cookie named `sf_redirect` is being set when you attack the server through http, but is missing from the https response!

The `sf_redirect` cookie is part of the "Security" component of the Symfony PHP framework. This component is in charge of user authentication.

I can't do it right now, but this weekend I'll experiment with the relevant code. The interesting portion of it is the one below. It decides what happens after a successful login.
```php
public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey): RedirectResponse
{
    /*
     * When you attempt to access a page that requires you to be logged in,
     * it redirects you to the login form. The code below ensures that you
     * are redirected back to the page you were trying to access, after
     * the login process is completed.
     */
    if ($targetPath = $this->getTargetPath($request->getSession(), $providerKey)) {
        return new RedirectResponse($targetPath);
    }

    return new RedirectResponse($this->urlGenerator->generate('main_page'));
}
```

**Comment by vanhauser-thc** [comment]
then you could match on the contents of the header

**Comment by o-alquimista** [comment]
But the POST request header that Hydra sends is identical in both http and https. I'm sure of this. I compared them carefully. I'm thinking it must be something Symfony does. I might also setup a non-Symfony project on the server and see how it goes.

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 31 de jul de 2020 06:17, van Hauser escreveu:

**Comment by vanhauser-thc** [comment]
any update? :)

**Comment by o-alquimista** [comment]
I haven't had the time to continue testing yet. Maybe next weekend. I'll put a plain PHP web app on the remote server and try Hydra on it through https to see what happens.

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 31 de ago de 2020 15:20, van Hauser escreveu:

**Comment by o-alquimista** [comment]
I have found the problem and was able to fix it by modifying the DNS configuration for the domain. I'll explain.

My web app is accessible at a subdomain (e.g. subdomain.domain.com). Its certificate was configured for both "subdomain.domain.com" and "www.subdomain.domain.com"; and while I had a CNAME entry that prepends the www alias to the domain.com, the subdomains were missing their corresponding CNAME entries. That means trying to access the subdomains with "www" would result in an error - the Bad Request error I was receiving through https!

It works now :)
