### ISSUE TITLE
1 of 1 target completed, 0 valid password found

### ISSUE THREAD

**Issue by Chmuurkaa** [vanhauser-thc/thc-hydra#545]
I think I've read every post about this problem, and none of them seem to help

I'm new in hydra but this is a second time me giving it a try after 2 years, and after 2 years I still have the same error. Hydra never worked for me, and I tried on many VMs and machines
I'm using a Kali and this is the command I use

sudo hydra -t 1 -V -f -l [Correct Username] -p [Correct Password] pokewars.pl http-post-form "/auth.html:login=^USER&pass=^PASS^&zaloguj=Zaloguj:F=Trailers" -vV -f

Does anyone see what am I doing wrong?

**Comment by vanhauser-thc** [comment]
a) it does not need sudo
b) sure that "Trailers" is in the website in a failed attempt?  use -d and look at the debug output

**Comment by Chmuurkaa** [comment]
![image](https://user-images.githubusercontent.com/68754678/88456668-b7521600-ce7f-11ea-9c77-7f3d83b06cb6.png)
That was a problem ;D
