### ISSUE TITLE
Hydra taking forever to "brute force" [STATUS] 1.00 tries/min (etc)

### ISSUE THREAD

**Issue by Chmuurkaa** [vanhauser-thc/thc-hydra#546]
![image](https://user-images.githubusercontent.com/68754678/88456447-1ca50780-ce7e-11ea-95d0-c78578d190b2.png)

Hi
I'm trying to brute force an http website, but I'm getting this kind of messages as seen in the picture above

This is my command
`sudo hydra -V -l [CorrectUsername]-p [CorrectPassword] [HTML Website] http-post-form "/auth.html:login=^USER^&pass=^PASS^&zaloguj=Zaloguj:S=Trailer" -v -I`

I've seen from other issue that this is a brute force protection. But I'm not really "bruteforcing" using any dictionaries. I'm just giving my username and my password to this website, and something like this happens anyway

![image](https://user-images.githubusercontent.com/68754678/88456593-fdf34080-ce7e-11ea-98d1-8726b469e756.png)

**EDIT:**

After 2 hours I decided to try this again. I copy pasted the command from this post (to be sure I'm using the same thing)
And now I'm getting this message

![image](https://user-images.githubusercontent.com/68754678/88458578-529eb780-ce8f-11ea-9260-943f5218dc4f.png)

here's the -d output
https://pastebin.com/tKeYLk1t

**Comment by vanhauser-thc** [comment]
add the -d switch so you can see what hydra is sending and receiving

**Comment by enigm4s** [comment]
welp, I'm not even done yet with standard hydra, look like I should switch to this version of hydra :D

tried rockyou on android termux, estimated time : 27 hrs, lets try again :D

**Comment by wuryo** [comment]
I really don't know , how work hydra on android

**Comment by enigm4s** [comment]
> I really don't know , how work hydra on android

basically, nothing much different, except these little keyboard, small screen, and slow network if you use it on mobile not wifi.

hydra 9.0
don't mind this pict, I use dark color font on purpose :) 
it just a help page.

![Screenshot_20200806-124538](https://user-images.githubusercontent.com/68355570/89495938-8bba1e80-d7e3-11ea-8bd8-0872ddd761d2.png)
