### ISSUE TITLE
Hydra does not stop when it uses the -P and -F options and it finds a match

### ISSUE THREAD

**Issue by jrobertsz66** [vanhauser-thc/thc-hydra#55]
Why does Hydra 8.1 not stop when it finds a password?

I am using the -P option with a file that has over 5 Million passwords in it and the correct SSH password is located at approx. line 2100, but Hydra v 8.1 goes past that password and keeps going, ant it looks like it is trying to process the entire file.

I have tried both, the -F and the -f option, which per the documentation, indicate that Hydra should stop when it finds a match. 

Here is the command I am using:

hydra -f -V -t 10 -l admin -P ../../all ubuntu14vm ssh

If I actually use the following command with -p option instead, the command finds the password right away.  

hydra -f -V -t 10 -l admin -p admin ubuntu14vm ssh

Only when I use the -P command with a file that contains the password, it seems that Hydra tries that password and keeps going and attempts to process the entire file.

**Comment by vanhauser-thc** [comment]
does it report the correct password?
if not, its no wonder it keeps on.
when you try the correct one, can you please do that while the other hydra cracking task is running?

If it does report, yes, then there would be an -f issue.

so - more data.
always, please always send in full logs.

**Comment by jrobertsz66** [comment]
I hope this helps you figure it out.  Unfortunately, I do not have time 
to test this further right now as I am under the gun to produce an 
assessment report at work.

Here is the result when it works with -p without any other tests running:

Hydra (http://www.thc.org/thc-hydra) starting at 2015-04-13 16:05:37
[WARNING] Many SSH configurations limit the number of parallel tasks, it 
is recommended to reduce the tasks: use -t 4
[DATA] max 1 task per 1 server, overall 64 tasks, 1 login try (l:1/p:1), 
~0 tries per task
[DATA] attacking service ssh on port 22
[ATTEMPT] target ubuntu14vm - login "admin" - pass "admin" - 1 of 1 
[child 0]
[22][ssh] host: ubuntu14vm   login: admin   password: admin
[STATUS] attack finished for ubuntu14vm (valid pair found)
*1 of 1 target successfully completed, 1 valid password found*
Hydra (http://www.thc.org/thc-hydra) finished at 2015-04-13 16:05:38


I then run the following command:

hydra -f -V -t 50 -l admin -P all ubuntu14vm ssh

And Hydra kept going past the valid "admin" password again.  The valid 
admin password is in the file named "all" at line 2823:

~/dev/security$ grep -wn admin all
*2823:admin*
31331:admin!
57926:admin.
60882:admin?
3696295:admin's
3696296:admin-mtv
3696297:admin/arc
3696298:admin/nasa
3696299:admin/staff
3699226:auto-admin
3700284:bbn-admin
3734576:mail/admin
3753232:sccs-admin
3753246:sccs/admin
3759132:sys-admin
3759143:sys/admin


But Hydra kept on going and processing past line number 9996 - when I 
used ctrl+c to stop it.  Here is some of the final output right before I 
stopped it:

[ATTEMPT] target ubuntu14vm - login "admin" - pass "pepsi1" - 9984 of 
5014898 [child 1]
[ATTEMPT] target ubuntu14vm - login "admin" - pass "petunia1" - 9985 of 
5014898 [child 3]
[ATTEMPT] target ubuntu14vm - login "admin" - pass "philip1" - 9986 of 
5014898 [child 10]
[ATTEMPT] target ubuntu14vm - login "admin" - pass "photo1" - 9987 of 
5014898 [child 2]
[ATTEMPT] target ubuntu14vm - login "admin" - pass "pickle1" - 9988 of 
5014898 [child 8]
[ATTEMPT] target ubuntu14vm - login "admin" - pass "player1" - 9989 of 
5014898 [child 11]
[ATTEMPT] target ubuntu14vm - login "admin" - pass "poiuyt1" - 9990 of 
5014898 [child 16]
[ATTEMPT] target ubuntu14vm - login "admin" - pass "porsche1" - 9991 of 
5014898 [child 17]
[ATTEMPT] target ubuntu14vm - login "admin" - pass "porter1" - 9992 of 
5014898 [child 0]
[ATTEMPT] target ubuntu14vm - login "admin" - pass "puppy1" - 9993 of 
5014898 [child 9]
[ATTEMPT] target ubuntu14vm - login "admin" - pass "python1" - 9994 of 
5014898 [child 12]
[ATTEMPT] target ubuntu14vm - login "admin" - pass "quality1" - 9995 of 
5014898 [child 13]
[ATTEMPT] target ubuntu14vm - login "admin" - pass "raquel1" - 9996 of 
5014898 [child 18]

Before I stopped it, and while it was still processing the "all" file, I 
run the hydra command with the -p admin option from another terminal and 
it still worked.  Here is the output:

~$ hydra -f -V -t 10 -l admin -p admin ubuntu14vm ssh
Hydra v8.1 (c) 2014 by van Hauser/THC - Please do not use in military or 
secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2015-04-13 16:45:41
[WARNING] Many SSH configurations limit the number of parallel tasks, it 
is recommended to reduce the tasks: use -t 4
[DATA] max 1 task per 1 server, overall 64 tasks, 1 login try (l:1/p:1), 
~0 tries per task
[DATA] attacking service ssh on port 22
[ATTEMPT] target ubuntu14vm - login "admin" - pass "admin" - 1 of 1 
[child 0]
[22][ssh] host: ubuntu14vm   login: admin   password: admin
[STATUS] attack finished for ubuntu14vm (valid pair found)
*1 of 1 target successfully completed, 1 valid password found*
Hydra (http://www.thc.org/thc-hydra) finished at 2015-04-13 16:45:42

So, to me, it appears that the -f option isn't working.

The hydra.restore file is 54 MB in size so I am unable to send it via email.

Regards,

Joe

**Comment by jrobertsz66** [comment]
And just FYI, I am running version 8.1 of Hydra downloaded last week and 
my OS is as follows:

ProductName:    Mac OS X
ProductVersion:    10.9.5
BuildVersion:    13F1077

**Comment by vanhauser-thc** [comment]
hmm this is either a libssh issue or the ssh daemon on the server side always reports failed attempt after X tries in a session.
All occasions where you say it continues it is because the password was NOT found. so it is eiher the libssh library or the server.
idea?
