### ISSUE TITLE
Help in providing failed login string in http-post-form

### ISSUE THREAD

**Issue by mvineza** [vanhauser-thc/thc-hydra#550]
I'm testing hydra on a webapp which returns `Login failed for user $USER` on failed login. For example if you enter wrong credentials such as:

```
usernme: admin
password: admin
```

The page will return:

```
Login failed for user admin
```

Aside from the message above, it will also return "400 Bad Request".

The following commands seems not working because they return multiple matches even though the password is wrong.

```
hydra webapp -V -s 80 -L users.txt -P passwors.txt http-post-form "/login:username=^USER^&password=^PASS^:F=Login failed for user.*"
hydra webapp -V -s 80 -L users.txt -P passwors.txt http-post-form "/login:username=^USER^&password=^PASS^:F=Login failed for user ^USER^"
```

Kindly shed some light. Thank you.

**Comment by vanhauser-thc** [comment]
just use "...:F=Login failed for user"

also - that message might be rendered in the browser and not really what the server is sending. add -d to see the data being exchanged.
