### ISSUE TITLE
Enhancement - Gauth - 2FA Response Detection SSH

### ISSUE THREAD

**Issue by uBadRequest** [vanhauser-thc/thc-hydra#551]
I forgot the SSH password to a server I haven't used in a long time, and I can't find the ssh key, but I know I had used a really easy password because I added 2FA to SSH. I would have though I would have been able to crack it by now, but I have a feeling Hydra may not have the ability to detect a successful login with 2FA enabled.

I'm using the 'Google Authenticator PAM module'

https://ubuntu.com/tutorials/configure-ssh-2fa#2-installing-and-configuring-required-packages

**Comment by vanhauser-thc** [comment]
there is no special code that is able to detect that AFAIK.
why do you think you would be able to crack it? you would need to type in your 2FA pin to succeed and as this cannot happen in hydra it is not possible to work.
dunno what 2FA mechanism you are using, but if it can be given somehow to hydra you could add a patch that support 2FA and sends the second authentication value.
I dont even know if libssh supports 2fa.

**Comment by vanhauser-thc** [comment]
however detecting 2fa and aborting would be the correct step at this point.
a PR for that would be nice :)
