### ISSUE TITLE
help for fiddler debug

### ISSUE THREAD

**Issue by pstandard** [vanhauser-thc/thc-hydra#555]
Hello ,

  I want to use fiddler to debug hacking process, by setting HYDAR_PROXY_HTTP=http://127.0.0.1:8888/ , it dosn't work. 
  
  Check neststat in Windows CMD, it show bellow line:
   TCP    192.168.3.106:8875     1.0.0.0:8888           SYN_SENT        22248 
  
  22248 PID is hydra.exe

  can any one help me? thanks in advance.

  My environment:
  Windows 10 with Cygwin64 Terminal;

  $ hydra -C /home/chenren/usepass.txt -I -t 1 -vV 127.0.0.1 http-post-form "/book/service/login.asp:userName=^USER^&password=^PASS^":F=login.asp
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2020-08-26 19:14:29
[INFO] Using HTTP Proxy: http://127.0.0.1:8888/
[WARNING] Restorefile (ignored ...) from a previous session found, to prevent overwriting, ./hydra.restore
[DATA] max 1 task per 1 server, overall 1 task, 7 login tries, ~7 tries per task
[DATA] attacking http-post-form://127.0.0.1:80/book/service/login.asp:userName=^USER^&password=^PASS^:F=login.asp
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[ATTEMPT] target 127.0.0.1 - login "fitterer" - pass "aaaaaa" - 1 of 7 [child 0] (0/0)
Process 2060: Can not connect [unreachable], retrying (1 of 1 retries)

**Comment by vanhauser-thc** [comment]
this shows that the env var is correctly set:
```
[INFO] Using HTTP Proxy: http://127.0.0.1:8888/
```

But the connection is being made to 1.0.0.0
```
TCP 192.168.3.106:8875 1.0.0.0:8888 SYN_SENT 22248
```

The issue is though that I am unable to reproduce it:
```
HYDRA_PROXY_HTTP=http://127.0.0.1:8888/ hydra -l test -p test -s 1111 google.com http-get
```
correctly connects to the localhost port 8888 for me...
```
$ nc -lvnp 8888
listening on [any] 8888 ...
connect to [127.0.0.1] from (UNKNOWN) [127.0.0.1] 45174
GET http://google.com:80/ HTTP/1.1
Host: google.com
Connection: close
Authorization: Basic dGVzdDp0ZXN0
User-Agent: Mozilla/4.0 (Hydra)
```

**Comment by pstandard** [comment]
Hello Vanhauser-thc, 

 Thanks you for information. 
By -l and -p, it works. but don't work for -C

Bellow are my debug result:

$ hydra -l test -p test -I google.com http-get
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2020-08-26 19:54:57
[WARNING] You must supply the web page as an additional option or via -m, default path set to /
[INFO] Using HTTP Proxy: http://127.0.0.1:8888/
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking http-get://google.com:80/
[80][http-get] host: google.com   login: test   password: test
1 of 1 target successfully completed, 1 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2020-08-26 19:54:59


$ hydra -C /home/chenren/usepass.txt -I google.com http-get
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2020-08-26 19:55:22
[WARNING] You must supply the web page as an additional option or via -m, default path set to /
[INFO] Using HTTP Proxy: http://127.0.0.1:8888/
[DATA] max 7 tasks per 1 server, overall 7 tasks, 7 login tries, ~1 try per task
[DATA] attacking http-get://google.com:80/
[ERROR] Child with pid 2113 terminating, can not connect
[ERROR] Child with pid [ERROR] Child with pid [ERROR] Child with pid [ERROR] Child with pid 2112211621142110 terminating, can not connect
 terminating, can not connect
 terminating, can not connect
[ERROR] Child with pid [ERROR] Child with pid  terminating, can not connect
21152111 terminating, can not connect
 terminating, can not connect
[STATUS] 14.00 tries/min, 14 tries in 00:01h, 1 to do in 00:01h, 7 active
The session file ./hydra.restore was written. Type "hydra -R" to resume session.

**Comment by vanhauser-thc** [comment]
hm I retried with -C and same result for me, it works.
Can you share your -C file? maybe it triggers a bug. just zip and attach here.

**Comment by pstandard** [comment]
Here is the file, I created it by EditPlus.
[usepass.zip](https://github.com/vanhauser-thc/thc-hydra/files/5130473/usepass.zip)

**Comment by vanhauser-thc** [comment]
thats what I feared.
works fine for me.
But I am on Linux and I dont have Windows with Cygwin ....

**Comment by WdehFsociety** [comment]
Dude,

Got the same issue... [WARNING] Restorefile (ignored ...) from a previous session found, to prevent overwriting, ./hydra.restore
                                   ERROR] could not connect to ssh://10.150.150.27:22 - Timeout connecting to 10.150.150.27
Using Oracle VM.

└─# hydra -L /usr/share/seclists/Passwords/Common-Credentials/best1050.txt -p /usr/share/seclists/Passwords/Common-Credentials/Best1050.txt ssh://10.150.150.27:22 -t 4 -I
Hydra v9.3-dev (c) 2021 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2021-07-17 20:52:45
[WARNING] Restorefile (ignored ...) from a previous session found, to prevent overwriting, ./hydra.restore
[DATA] max 4 tasks per 1 server, overall 4 tasks, 1049 login tries (l:1049/p:1), ~263 tries per task
[DATA] attacking ssh://10.150.150.27:22/
[ERROR] could not connect to ssh://10.150.150.27:22 - Timeout connecting to 10.150.150.27
