### ISSUE TITLE
Hydra works with -p and correct password but does not work with -P and correct password in a file.

### ISSUE THREAD

**Issue by twinkette** [vanhauser-thc/thc-hydra#556]
Hello,

If I pass the correct password to the smtp server using the -p option, Hydra detects that the password is correct. For example:

hydra -l email@domain.com -p this_is_my_password -s 587 -m TLS -v -V smtp.domain.com smtp -f 

However, if I do the exact same thing but place the correct password on the first line of a text file and use -P, then Hydra does not detect the correct password. For example:

hydra -l email@domain.com -P my_password_file -s 587 -m TLS -v -V smtp.office365.com smtp -f 

The my_password_file is just a series of passwords on each line. For example:

aaa
bbb
ccc
ddd

Am I doing something wrong? All help appreciated! Thanks.

**Comment by vanhauser-thc** [comment]
with -P parallel connections are made and likely microsoft detects that and fails them then. try adding -t 1

**Comment by donowhattosay** [comment]
even if i use this command : 

hydra -l email@domain.com -p this_is_my_password -s 587 -m TLS -v -V smtp.domain.com smtp -f

its still doesnt work, what happen?

**Comment by limaniscrow** [comment]
should we add a new proxy before each request ? it should be much longer but with more probability of not being detected ?

**Comment by vanhauser-thc** [comment]
didnt you see this?
```
[INFO] several providers have implemented cracking protection, check with a small wordlist first - and stay legal!
```
hydra announces itself so it can be blocked. auth type might be wrong, e.g. account might require oauth etc.

**Comment by GibonPe123** [comment]
Who fixed the problem?
