### ISSUE TITLE
Limitation of password dictionary

### ISSUE THREAD

**Issue by 404notfoundhard** [vanhauser-thc/thc-hydra#56]
Hi, How I can bypass limit in 50kk passwords??

**Comment by vanhauser-thc** [comment]
lets do a little math.
you can do 16 attempts in parallel (which is already rare to work) and you can do all the attempts in 1 second. How long will the 50.000 password attempts take for one account?

**Comment by 404notfoundhard** [comment]
I apologize for the stupid question
