### ISSUE TITLE
Hydra hangs with user provided HTTP header

### ISSUE THREAD

**Issue by yelsanya** [vanhauser-thc/thc-hydra#563]
![image](https://user-images.githubusercontent.com/56681837/93487794-a0ee9680-f8d3-11ea-93b8-04ba2cbedda1.png)

**Comment by vanhauser-thc** [comment]
and if you run it without proxychains?

**Comment by vanhauser-thc** [comment]
if you use a non 127.0.0.1 proxy then of course this proxychain cannot connect succesfully to your 127.0.0.1 host ...

**Comment by yelsanya** [comment]
Just to show that neither proxychains and 127.0.0.1 are issue here
![image](https://user-images.githubusercontent.com/56681837/93489094-1a3ab900-f8d5-11ea-8b37-06bb08b0f5ae.png)
As you can see it works without header
