### ISSUE TITLE
Hydra not able to find password/FTP

### ISSUE THREAD

**Issue by eflick323** [vanhauser-thc/thc-hydra#565]
I’m currently taking a network vulnerability class. In the lab I’m required to do I’m having problems using hydra to crack a password from rockyou list. 

I’m running a Kali VM and a Server 2008 VM on VirtualBox. On Server 08 I added a role in server manager Web Server with basic authentication and FTP server. Then I added a FTP site pointed it at c:\inetpub\ftproot, allowed ssl, selected both basic and anonymous authentication. I created a new user FTPUser with password !!caMERON23 (which is on the rockyou list; teacher had us tail the last 10,000 and create a new word list called rockyou10000.txt). Then on FTP site I did allow rule and added FTPUser with read/write permissions. 

Ok. I boot up Kali. Both VMs are on the same network and NAT is giving both VMs ip 10.02.15. My hydra command is:
sudo hydra -l FTPUser -P rockyou10000.txt ftp://10.0.2.15

The output is this:
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway)

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2020-09-21 16:27:42
[DATA] max 16 tasks per 1 server, overall 16 tasks, 10000 login tries (l:1/p:10000), ~625 tries per task
[DATA] attacking ftp://10.0.2.15:21/
[STATUS] 318.00 tries/min, 318 tries in 00:01h, 9715 to do in 00:31h, 16 active
[STATUS] 314.00 tries/min, 942 tries in 00:03h, 9091 to do in 00:29h, 16 active
[STATUS] 313.57 tries/min, 2195 tries in 00:07h, 7838 to do in 00:25h, 16 active
[STATUS] 312.13 tries/min, 4682 tries in 00:15h, 5351 to do in 00:18h, 16 active
[STATUS] 313.15 tries/min, 6263 tries in 00:20h, 3770 to do in 00:13h, 16 active
[STATUS] 314.12 tries/min, 7853 tries in 00:25h, 2180 to do in 00:07h, 16 active
[STATUS] 314.97 tries/min, 9449 tries in 00:30h, 584 to do in 00:02h, 16 active
[STATUS] 315.06 tries/min, 9767 tries in 00:31h, 266 to do in 00:01h, 16 active
1 of 1 target completed, 0 valid password found
[WARNING] Writing restore file because 14 final worker threads did not complete until end.
[ERROR] 14 targets did not resolve or could not be connected
[ERROR] 0 target did not complete
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2020-09-21 16:59:32.

I have searched the web, I have read the post on here and if my answer is there I didn’t realize it. I’m fairly new to this stuff. I’ve tried things that I have found. I made sure every thing was up-to-date, I even deleted my Kali VM and started over bc I thought maybe there was something wrong with it. I followed along with the teacher and did exactly as he did. He got results. I have reached out to him but no response yet.  I don’t know how to fix it.  What am I doing wrong?

**Comment by vanhauser-thc** [comment]
did you try if you can actually log in?
if yes, add the -d switch (plus maybe -t 1) to see what is going on

**Comment by eflick323** [comment]
I was able to login on the server as FTPUser with p: !!caMERON23

so i ran the command with -d and -t 1. This the output for the correct password

[ATTEMPT] target 10.0.2.15 - login "FTPUser" - pass "!!caMERON23" - 9131 of 10003 [child 0] (0/3)
Process 33786: Can not connect [unreachable], retrying (1 of 1 retries)
Process 33786: Can not connect [unreachable]
DEBUG_CONNECT_UNREACHABLE
[ERROR] Child with pid 33786 terminating, can not connect
[DEBUG] pid 33786 called child_exit with code 1
[DEBUG] head_no[0] read C
[ATTEMPT-ERROR] target 10.0.2.15 - login "FTPUser" - pass "!!caMERON23" - child 0 - 9131 of 10000
[DEBUG] hydra_increase_fail_count: 9131 >= 0 => disable
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 33787
[DEBUG] head_no 0 has pid 33787
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 3, redo_state 0, pass_state 3. loop_mode 0, curlogin FTPUser, curpass !!caMERON23, tlogin FTPUser, tpass !!bumbo, logincnt 0/1, passcnt 9131/10000, loop_cnt 1
[COMPLETED] target 10.0.2.15 - login "FTPUser" - pass "!!caMERON23" - child 0 - 9131 of 10003

**Comment by vanhauser-thc** [comment]
and there you see the problem:

```
Process 33786: Can not connect [unreachable], retrying (1 of 1 retries)
Process 33786: Can not connect [unreachable]
DEBUG_CONNECT_UNREACHABLE
```

could be brute force protection in the ftp server or fail2ban being active or ... simple connection problems.
