### ISSUE TITLE
What should I do in this case?

### ISSUE THREAD

**Issue by Manuelucki** [vanhauser-thc/thc-hydra#566]
Hey!

Im using hydra and I don't know what I should do in this case.

My trial is this website: www.projecthabbo.x10.bz/index.php

If you see the view-source of the page, we can see this:

```
<form method="post" action="logar.php">
  | <fieldset id="painel01"><legend>Entrar en Siaro Project</legend>
  | <input type="text" id="husuario" name="husuario" size="30" placeholder="Usuario"/>
  | <input type="password" id="hsenha" name="hsenha" size="30" placeholder="Contraseña">
  | <input type="submit" value="Entrar">
```

This is my command: 
hydra -l coins -P PASSS.txt -vV -s 80 -f www.projecthabbo.x10.bz http-post-form "/index.php:husuario=^USER^&hsenha=^PASS^&Login=button:Entrar"

My question is, after "hsenha=^PASS^&" what should I put? I'm asking because the button for login at the page, doesn't have a "name" and basically I don't know how to submit the button at the hydra..

**Comment by Manuelucki** [comment]
I only want to know how to put correctly the command because I'm new using this and I just looking for a simple answer :/

**Comment by Manuelucki** [comment]
hey

**Comment by BMPE2** [comment]
I'm new to all this. Wish I had an answer for you but I don't.

**Comment by vanhauser-thc** [comment]
Sorry but this is for reporting bugs, not a help forum. There are a lot of forums, stack exchange, etc. to ask questions and get help.

**Comment by Manuelucki** [comment]
answer that would took you literally 2 minutes but thanks for the help!! 👍
