### ISSUE TITLE
Queueing up multiple .txt files?

### ISSUE THREAD

**Issue by quamisido** [vanhauser-thc/thc-hydra#567]
I've got a 39 GB wordlist that I can't narrow down in order to crack a Gmail password I made for myself. The only solution I can think of as of yet to go around the file limit is to break it into 94 different text files and run each one manually, but I wanted to check here and see if there was a better solution.

**Comment by vanhauser-thc** [comment]
I think you dont know what you are doing.
a) it is not allowed what you are doing - if it would be your own account
b) gmail (and others) have brueforce protection which - after several attempts - can report success for a wrong password, and failure for the correct password, making bruteforcing pointless
