### ISSUE TITLE
Не могу установить Github взломщик паролей

### ISSUE THREAD

**Issue by oleg975** [vanhauser-thc/thc-hydra#568]
Здравствуйте!Хочу воспользоваться "взломщиком паролей" у Github.Ваша инструкция требует ввести соответствующий скрипт в командную строку.У меня Вин 19 Про,64 бита.Моя командная строка отказывает в обработке этого скрипта.В чём может быть ошибка?Подскажите,пожалуйста. Олег

**Comment by vanhauser-thc** [comment]
english

**Comment by oleg975** [comment]
Gentleman,  My question to you is very simple I've as OS Win 10 Pro,64 bit.It seems to me that your Github operate only with Linux.Am I right or it's possible operate with me OS?      Best regards,           Oleg 27.09.2020, 20:40, "van Hauser" <notifications@github.com>: english—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by vanhauser-thc** [comment]
you can compile and run it with cygwin -> www.cygwin.com

**Comment by oleg975** [comment]
Thanks a lot.I'll try 28.09.2020, 15:56, "van Hauser" <notifications@github.com>: you can compile and run it with cygwin -> www.cygwin.com—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
