### ISSUE TITLE
Hydra on cygwin error when installing - "make: command not found"

### ISSUE THREAD

**Issue by Tim15** [vanhauser-thc/thc-hydra#57]
I am trying to install hydra on a windows computer with cygwin. I extract the tarball and run ./configure, but when I type in "make", I get an error that the command is not found.
![hydra bug](https://cloud.githubusercontent.com/assets/11166947/7333745/8c9900d8-eb48-11e4-8fd3-55e041455035.PNG)

**Comment by green-big-frog** [comment]
You have to install make

**Comment by vanhauser-thc** [comment]
and most likely gcc etc. too

**Comment by Tim15** [comment]
Thanks! I reinstalled cygwin and installed make, but when I open hydra.exe
I get an error that I cannot open the application.

**Comment by vanhauser-thc** [comment]
you have to use the command line to start hydra.

this is a bug tracking system for BUGS. not a help system.

**Comment by Tim15** [comment]
It's just a simple question, and Jonathan was happy to help. I understand
this though, so I'll figure out the next one on my own.
Sorry,
Tim

**Comment by iyanfarid** [comment]
Hello brother...  U cant help.me to hack games software..?

http://myaccount.dropsend.com/file/ae95222f75f6e9b8

This is software of games.. Im lossee big money for this games.. I need ur
help

**Comment by stefadsh** [comment]
I have the same problem , but I can't solve it , it's so annoying, please help meeeee!!!!

**Comment by 4skinSkywalker** [comment]
Same problem here, anyone on how to solve this?
