### ISSUE TITLE
SSH attack with diffie-hellman-group1-sha1

### ISSUE THREAD

**Issue by chppppp** [vanhauser-thc/thc-hydra#570]
I amt trying to test an older server that is only accepting diffie-hellman-group1-sha1 and i cannot seem to figure out how to get hydra/libssh to accept this. libssh docs says to support it but it doesnt seem to do so out of the box. any suggestions? 

thanks so much

**Comment by vanhauser-thc** [comment]
Not a clue to be honest. 
https://www.libssh.org/?s=diffie-hellman-group1-sha1 shows it should be supported.
maybe deinstall the potentially outdated installed libssh and compile + install the newest version from hand?

**Comment by rocketscientist911** [comment]
@chppppp have you had any luck? I am in the same boat.
