### ISSUE TITLE
[WARNING] you want to access SMTP/POP3/IMAP with SSL. Are you sure you want to use direct SSL (-S) instead of STARTTLS (-m TLS)?

### ISSUE THREAD

**Issue by kareemyoussef22** [vanhauser-thc/thc-hydra#573]
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2020-10-18 17:34:11
[WARNING] you want to access SMTP/POP3/IMAP with SSL. Are you sure you want to use direct SSL (-S) instead of STARTTLS (-m TLS)?
[INFO] several providers have implemented cracking protection, check with a small wordlist first - and stay legal!
[WARNING] Google Mail and others have bruteforce and hydra detection and send false positives. You are not doing anything illegal right?!
[WARNING] !read the above!
[DATA] max 16 tasks per 1 server, overall 16 tasks, 28 login tries (l:1/p:28), ~2 tries per task
[DATA] attacking smtps://smtp.mail.yahoo.com:587/
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "01001002326" - 1 of 28 [child 0] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "01001135044" - 2 of 28 [child 1] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "0101002326" - 3 of 28 [child 2] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "kaza01001002326" - 4 of 28 [child 3] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "karim01001002326" - 5 of 28 [child 4] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "k01001002326" - 6 of 28 [child 5] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "kaza01001135044" - 7 of 28 [child 6] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "karim01001135044" - 8 of 28 [child 7] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "k01001135044" - 9 of 28 [child 8] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "karim0101002326" - 10 of 28 [child 9] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "kaza0101002326" - 11 of 28 [child 10] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "k0101002326" - 12 of 28 [child 11] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "virusteam" - 13 of 28 [child 12] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "virusteam22" - 14 of 28 [child 13] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "vv" - 15 of 28 [child 14] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "vsadv" - 16 of 28 [child 15] (0/0)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "asdvasd" - 17 of 31 [child 5] (0/3)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "VirusTeam$$$3" - 18 of 31 [child 3] (0/3)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass " sd " - 19 of 31 [child 0] (0/3)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass " sdf sa" - 20 of 35 [child 1] (0/7)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass " df " - 21 of 35 [child 4] (0/7)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass " asdf" - 22 of 35 [child 6] (0/7)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "  sad" - 23 of 37 [child 10] (0/9)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "  f" - 24 of 37 [child 8] (0/9)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "  asd" - 25 of 38 [child 7] (0/10)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "  f " - 26 of 39 [child 13] (0/11)
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9608 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9606 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9603 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9607 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9609 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9604 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9613 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9611 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9610 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9616 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9617 terminating, can not connect
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "  sad" - 27 of 39 [child 14] (0/11)
[ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "" - 28 of 41 [child 3] (0/13)
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9620 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9621 terminating, can not connect
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "k01001002326" - 29 of 41 [child 0] (1/13)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "kaza01001002326" - 30 of 43 [child 6] (2/15)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "01001002326" - 31 of 43 [child 8] (3/15)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "01001135044" - 32 of 46 [child 13] (4/18)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "karim01001002326" - 33 of 46 [child 14] (5/18)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "kaza01001135044" - 34 of 46 [child 15] (6/18)
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9624 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9626 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9628 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9629 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9618 terminating, can not connect
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "kaza0101002326" - 35 of 48 [child 3] (7/20)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "k01001135044" - 36 of 48 [child 0] (8/20)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "karim01001135044" - 37 of 50 [child 6] (9/22)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "virusteam22" - 38 of 50 [child 8] (10/22)
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9630 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9631 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9632 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9633 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9634 terminating, can not connect
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "vv" - 39 of 52 [child 13] (11/24)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "VirusTeam$$$3" - 40 of 52 [child 15] (12/24)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass " sd " - 41 of 54 [child 3] (13/26)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass " asdf" - 42 of 54 [child 0] (14/26)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "  f" - 43 of 56 [child 6] (15/28)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "  f " - 44 of 56 [child 8] (16/28)
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9636 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9637 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9638 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9639 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9640 terminating, can not connect
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "  sad" - 45 of 58 [child 13] (17/30)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "vsadv" - 46 of 58 [child 15] (18/30)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "" - 47 of 60 [child 3] (19/32)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "k01001002326" - 48 of 60 [child 0] (20/32)
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9641 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9642 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9643 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9644 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9645 terminating, can not connect
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "kaza01001002326" - 49 of 61 [child 6] (21/33)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "01001002326" - 50 of 61 [child 8] (22/33)
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9646 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9647 terminating, can not connect
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "01001135044" - 51 of 61 [child 13] (23/33)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "kaza01001135044" - 52 of 61 [child 3] (24/33)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "kaza0101002326" - 53 of 61 [child 0] (25/33)
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9649 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9650 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9651 terminating, can not connect
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "k01001135044" - 54 of 61 [child 6] (26/33)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "karim01001135044" - 55 of 61 [child 3] (27/33)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "virusteam22" - 56 of 61 [child 13] (28/33)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "vv" - 57 of 61 [child 0] (29/33)
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9654 terminating, can not connect
[ERROR] Child with pid 9653 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9655 terminating, can not connect
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "VirusTeam$$$3" - 58 of 61 [child 6] (30/33)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass " sd " - 59 of 61 [child 13] (31/33)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass " asdf" - 60 of 61 [child 3] (32/33)
[REDO-ATTEMPT] target smtp.mail.yahoo.com - login "kareemyoussef.id@yahoo.com " - pass "  f" - 61 of 61 [child 0] (33/33)
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9656 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9658 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9657 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9659 terminating, can not connect
[STATUS] attack finished for smtp.mail.yahoo.com (waiting for children to complete tests)
[VERBOSE] Disabled child 3 because of too many errors
[VERBOSE] Disabled child 0 because of too many errors
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9660 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9661 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9662 terminating, can not connect
[VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[ERROR] Child with pid 9663 terminating, can not connect

**Comment by kareemyoussef22** [comment]
any one help me

**Comment by vanhauser-thc** [comment]
works for me. maybe your openssl installation is outdated?

**Comment by kareemyoussef22** [comment]
how to config openssl installation

**Comment by kareemyoussef22** [comment]
its was working bu stooped in all emails yahoo gmail and live
