### ISSUE TITLE
[ERROR] invalid restore file (end)

### ISSUE THREAD

**Issue by RussiaVk** [vanhauser-thc/thc-hydra#575]
`[DEBUG] run_debug 1, orig_debug 0
[DEBUG] reading restore file: Step 3 complete
[DEBUG] reading restore file: Step 4 complete
[DEBUG] reading restore file: Step 5 complete
[DEBUG] reading restore file: Step 6 complete
[DEBUG] reading restore file: Step 7 complete
[DEBUG] reading restore file: Step 8 complete
[DEBUG] reading restore file: Step 9 complete
[DEBUG] reading restore file: Step 10 complete
[DEBUG] target 0 redo 61
[DEBUG] reading restore file: Step 11 complete
[DEBUG] head 0 redo
[DEBUG] TEMP head 0: pass == zhujingqin, login == zhujingqin
[DEBUG] redo: 0 zhujingqin/zhujingqin
[DEBUG] head 1 redo
[DEBUG] TEMP head 1: pass == zhujingliu, login == zhujingliu
[DEBUG] redo: 1 zhujingliu/zhujingliu
[DEBUG] head 2 redo
[DEBUG] TEMP head 2: pass == zhujingpu, login == zhujingpu
[DEBUG] redo: 2 zhujingpu/zhujingpu
[DEBUG] head 3 redo
[DEBUG] TEMP head 3: pass == zhujinglan, login == zhujinglan
[DEBUG] redo: 3 zhujinglan/zhujinglan
[DEBUG] head 4 redo
[DEBUG] TEMP head 4: pass == zhujingmei, login == zhujingmei
[DEBUG] redo: 4 zhujingmei/zhujingmei
[DEBUG] head 5 redo
[DEBUG] TEMP head 5: pass == zhujingrao, login == zhujingrao
[DEBUG] redo: 5 zhujingrao/zhujingrao
[DEBUG] head 6 redo
[DEBUG] TEMP head 6: pass == zhujingle, login == zhujingle
[DEBUG] redo: 6 zhujingle/zhujingle
[DEBUG] head 7 redo
[DEBUG] TEMP head 7: pass == zhujiongda, login == zhujiongda
[DEBUG] redo: 7 zhujiongda/zhujiongda
[DEBUG] head 8 redo
[DEBUG] TEMP head 8: pass == zhujingqi, login == zhujingqi
[DEBUG] redo: 8 zhujingqi/zhujingqi
[DEBUG] head 9 redo
[DEBUG] TEMP head 9: pass == zhujingmu, login == zhujingmu
[DEBUG] redo: 9 zhujingmu/zhujingmu
[DEBUG] head 10 redo
[DEBUG] TEMP head 10: pass == zhujingru, login == zhujingru
[DEBUG] redo: 10 zhujingru/zhujingru
[DEBUG] head 11 redo
[DEBUG] TEMP head 11: pass == zhujingluo, login == zhujingluo
[DEBUG] redo: 11 zhujingluo/zhujingluo
[DEBUG] head 12 redo
[DEBUG] TEMP head 12: pass == zhujinzi, login == zhujinzi
[DEBUG] redo: 12 zhujinzi/zhujinzi
[DEBUG] head 13 redo
[DEBUG] TEMP head 13: pass == zhujingbei, login == zhujingbei
[DEBUG] redo: 13 zhujingbei/zhujingbei
[DEBUG] head 14 redo
[DEBUG] TEMP head 14: pass == zhujinzhu, login == zhujinzhu
[DEBUG] redo: 14 zhujinzhu/zhujinzhu
[DEBUG] head 15 redo
[DEBUG] TEMP head 15: pass == zhujingmi, login == zhujingmi
[DEBUG] redo: 15 zhujingmi/zhujingmi
[DEBUG] head 16 redo
[DEBUG] TEMP head 16: pass == zhujingqun, login == zhujingqun
[DEBUG] redo: 16 zhujingqun/zhujingqun
[DEBUG] head 17 redo
[DEBUG] TEMP head 17: pass == zhujingke, login == zhujingke
[DEBUG] redo: 17 zhujingke/zhujingke
[DEBUG] head 18 redo
[DEBUG] TEMP head 18: pass == zhujingqiu, login == zhujingqiu
[DEBUG] redo: 18 zhujingqiu/zhujingqiu
[DEBUG] head 19 redo
[DEBUG] TEMP head 19: pass == zhujingkui, login == zhujingkui
[DEBUG] redo: 19 zhujingkui/zhujingkui
[DEBUG] head 20 redo
[DEBUG] TEMP head 20: pass == zhujingkou, login == zhujingkou
[DEBUG] redo: 20 zhujingkou/zhujingkou
[DEBUG] reading restore file: Step 12 complete
[ERROR] invalid restore file (end)
`

**Comment by JediYarosh** [comment]
I have encountered the same issue. It was on a Kali in VirutalBox after a run (started from xHydra) which somehow stopped during the night - output window (in verbose mode) was very long but mostly empty. Then I run the restore from bash and it worked until the end of the run. Without restarting anything I wanted to run another session from xHydra and it works giving output. When I stop it manually, after it says that the restore file was written (it actually is) it gives '[ERROR] Received signal 15, going down'. When I try to restore from command line it gives the a/m error.

**Comment by JediYarosh** [comment]
I just installed Kali to disk, updated everything to the newest version and run XHydra again. I let it run for a while and stopped. Then Rebooted the system and tried to run _hydra -R_ - same error message appears: "[ERROR] invalid restore file (end)"

**Comment by vanhauser-thc** [comment]
can you zip and upload the restore file?

**Comment by JediYarosh** [comment]
Of course. Here you go.
[restore_file.zip](https://github.com/vanhauser-thc/thc-hydra/files/6316581/restore_file.zip)

**Comment by vanhauser-thc** [comment]
dunno why but the value for number of logins is huge in the restore file which results that hydra tries to allocate a huge amount of memory which fails.
I fixed it so that hydra does not segfault anymore but exits with an error message.
I am unable to create such a buggy restore file here.

**Comment by jpcy2** [comment]
I came here looking for some clues. But it wasn't to be. I get plenty of corrupted restore files, if you would like me to collect some and pass them forward for diagnosis?

Just a few questions - please forgive my ignorance.

How /can/ Hydra create a bad restore file? What kind of things does it write to the file?

Could this be linked to hydra eating up all my RAM and borking for no reason?

Please could you give us an overview or point us to a descriptive overview of the operational functionality of hydra, please?

I have this problem at least 50% of the time I try to use it. It makes the whole experience take an unacceptable amount of time.

TBF, I will try another version, again, but if it just keeps on breaking itself, it's unfortunately looking like hydra is just not as useful as I had originally hoped. :(

My recent attempt's restore file is here:
[hydra.restore.tar.gz](https://github.com/vanhauser-thc/thc-hydra/files/8356052/hydra.restore.tar.gz)

Does my borked restore file show the same symptoms as the OPs - Bad/illegal values?

The restore file seems to contain lots of unrelated data such as shared library names (including "/usr/lib/x86_64-linux-gnu/sasl2", "libcrammd5.so" and "/usr/lib/x86_64-linux-gnu/sasl2/libntlm.so"), GMT/DST time zones, a malformed IP address, hydra's list of protocol names, etc...  I am really confused as to how hydra is purported to function with these breakages and writing extraneous or corrupt data to the restore file.  I gather it's storing far more than the requisite command line options and progress counter?

Re. the 'fix'...  Isn't checking availability of memory before requesting an allocation (or trapping an allocation failure) a standard practice. O_o (I must be a terribly bad programmer.)

I am just so confused as to why hydra is so problematic in use when it should be quite simple.  There's not much insight in the above responses.

**Comment by francescocmazza** [comment]
Hello, Sometimes running hydra on kali VM it crashes my vm after a few days of operation. I'm forced to force-power-off the VM and all restore files are corrupted. is there any way to repair the corrupted the hydra.restore?

**Comment by vanhauser-thc** [comment]
@francescocmazza well without a working crystal ball or an example file it is impossible to say what is wrong in your restore file. could have been the filesystem full and the write is incomplete? then it would not be possible to be repaired.
what service were you using? maybe there is a memory leak in that module which causes out of memory aborts
