### ISSUE TITLE
MySQL brute force cracking does not work properly

### ISSUE THREAD

**Issue by xuchaoa** [vanhauser-thc/thc-hydra#581]
hydra version: v9.1

I built a MySQL weak password container with docker locally. I believe the information is as follows
![image](https://user-images.githubusercontent.com/34988066/100694085-3aa0ec80-33c9-11eb-9a0b-c185ff11f278.png)

I can log in normally using the command line
![image](https://user-images.githubusercontent.com/34988066/100694131-56a48e00-33c9-11eb-8081-b9fb9c4c69ee.png)

but hydra returns `0 valid password found` 
![image](https://user-images.githubusercontent.com/34988066/100694521-3c1ee480-33ca-11eb-8bf6-5a991b8e368a.png)

i also try hydra v8.6 with mysql5.6 , the result is the same as above.

I'm not using it correctly ? or there is a bug in the program ?

Thanks

**Comment by vanhauser-thc** [comment]
the reason is that mysql will not make a tcp connection and use a socket - ignoring the -h and -P option, unless you also specify --protocol=tcp 

My guess - if you add this option your login with mysql will fail too.

**Comment by xuchaoa** [comment]
I use hydra v8.6 in dokcer container (without mysql installed) It return `0 valid password found` too.

![image](https://user-images.githubusercontent.com/34988066/100744152-567faf00-3418-11eb-92a8-3a5b3cb3b938.png)

Emmm..

**Comment by vanhauser-thc** [comment]
did you read and understand my reply?

**Comment by xuchaoa** [comment]
> did you read and understand my reply?



> the reason is that mysql will not make a tcp connection and use a local socket instead - ignoring the -h and -P option, unless you also specify --protocol=tcp
> 
> My guess - if you add this option your login with mysql will fail too.


Can you elaborate a little bit? I feel like I misunderstood your meaning
sorry, i'm poor at english

**Comment by vanhauser-thc** [comment]
your mysql command does not use a TCP connection.

this one does: `mysql -P 3306 -h localhost --protocol=tcp -u root -p`
It will likely also result in that you cannot login.
this is a problem with your mysql installation, not hydra.

**Comment by xuchaoa** [comment]
> your mysql command does not use a TCP connection.
> 
> this one does: `mysql -P 3306 -h localhost --protocol=tcp -u root -p`
> It will likely also result in that you cannot login.
> this is a problem with your mysql installation, not hydra.

Thank you for your reply， but it login successfully with the option `--protocol=tcp`

![image](https://user-images.githubusercontent.com/34988066/100820350-f6752100-3488-11eb-8124-ddfb913b5502.png)

**Comment by vanhauser-thc** [comment]
it works fine for me:
```
# hydra -l root -p test localhost mysql
Hydra v9.2-dev (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2020-12-02 10:13:34
[INFO] Reduced number of tasks to 4 (mysql does not like many parallel connections)
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking mysql://localhost:3306/
[3306][mysql] host: localhost   login: root   password: test
1 of 1 target successfully completed, 1 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2020-12-02 10:13:34
``` 
but I am using mariadb 10.3

can you please do a wireshark capture of the hydra traffic and the mysql traffic, zip it and attach it here? thanks

**Comment by xuchaoa** [comment]
> it works fine for me:
> 
> ```
> # hydra -l root -p test localhost mysql
> Hydra v9.2-dev (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).
> 
> Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2020-12-02 10:13:34
> [INFO] Reduced number of tasks to 4 (mysql does not like many parallel connections)
> [DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
> [DATA] attacking mysql://localhost:3306/
> [3306][mysql] host: localhost   login: root   password: test
> 1 of 1 target successfully completed, 1 valid password found
> Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2020-12-02 10:13:34
> ```
> 
> but I am using mariadb 10.3
> 
> can you please do a wireshark capture of the hydra traffic and the mysql traffic, zip it and attach it here? thanks

[cap.pcapng.gz](https://github.com/vanhauser-thc/thc-hydra/files/5628366/cap.pcapng.gz)

hydra v9.1 and mysql 5.6

excute once

thx very much

**Comment by vanhauser-thc** [comment]
I need also the mysql command capture, not only hydra.

**Comment by vanhauser-thc** [comment]
@xuchaoa  I need also the mysql command capture in a pcap, not only hydra.

**Comment by xuchaoa** [comment]
> @xuchaoa I need also the mysql command capture in a pcap, not only hydra.

I'm sorry to reply late. I didn't change anything. All of a sudden, I could scan out the weak password (in v8.6 on the server), but the local attempt still failed. I was very confused.

when i try on local pc , mysql command log nothing(there is no err in hydra's stdout), this makes me confused

I'm trying to find the problem, and I'll comment when I find the problem

Thanks

**Comment by vanhauser-thc** [comment]
just open this issue again if you can again into this problem
