### ISSUE TITLE
Error: network size may only be between /16 and /31: 192.168.100.20/dvwa/login.php

### ISSUE THREAD

**Issue by khalidalwalid** [vanhauser-thc/thc-hydra#583]
I run this command : 

hydra -l admin -P /usr/share/seclists/Passwords/xato-net-10-million-passwords.txt 192.168.100.20/dvwa/login.php http-post-form "/:username=^USER^&password=^PASS^:F=Login failed" -V

and it said : 

Error: network size may only be between /16 and /31: 192.168.100.20/dvwa/login.php

![error-login-httppost-hydra](https://user-images.githubusercontent.com/33023197/102434376-a34fb200-3fe2-11eb-96ce-273790f1a9b6.png)

Some advices please and thank you!

**Comment by vanhauser-thc** [comment]
you are not using the right syntax ...

**Comment by Azmorus** [comment]
> you are not using the right syntax ...

You tend to respond with this without actually telling people the right syntax.
Great job bud.

**Comment by R-Rothrock** [comment]
I’m a third party, but it seems like that’s the point. There are manuals and things online, but this is a place for build errors and bugs, not user error.
