### ISSUE TITLE
Hydra cannot be compiled in Termux

### ISSUE THREAD

**Issue by 26chk** [vanhauser-thc/thc-hydra#587]
Error message：

hydra.c:1109:25: note: include the header <strings.h> or explicitly provide a declaration for 'index'
1 warning generated.
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/hydra-339d88.o: in function `fill_mem':
/data/data/com.termux/files/home/thc-hydra/hydra.c:1109: undefined reference to `index'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/hydra-339d88.o: in function `hydra_increase_fail_count':
/data/data/com.termux/files/home/thc-hydra/hydra.c:1472: undefined reference to `index'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/thc-hydra/hydra.c:1472: undefined reference to `index'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/hydra-339d88.o: in function `process_proxy_line':
/data/data/com.termux/files/home/thc-hydra/hydra.c:2025: undefined reference to `index'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/home/thc-hydra/hydra.c:2029: undefined reference to `index'
/data/data/com.termux/files/usr/bin/ld: /data/data/com.termux/files/usr/tmp/hydra-339d88.o:/data/data/com.termux/files/home/thc-hydra/hydra.c:2037: more undefined references to `index' follow
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:66: hydra] Error 1

**Comment by vanhauser-thc** [comment]
termux is some Android thing right? I dont have it, so you will have t fix it yourself and send a pull request.
weird that it seems to have not the index function.

**Comment by 26chk** [comment]
> termux是Android的某些功能吗？我没有它，所以您将无法自己修复并发送请求请求。
> 很奇怪，它似乎没有索引功能。

How can I compile it?

**Comment by 26chk** [comment]
> termux是Android的某些功能吗？我没有它，所以您将无法自己修复并发送请求请求。
> 很奇怪，它似乎没有索引功能。
I don't understand how Termux compiles

https://github.com/termux/termux-packages/blob/37375312b93aecee93d86392b8db6b9ab3359c84/packages/hydra/build.sh#L14
