### ISSUE TITLE
Multiple target servers option

### ISSUE THREAD

**Issue by MMquant** [vanhauser-thc/thc-hydra#588]
This is the enhancement proposal.
It would be nice if hydra could accept a list of target servers in the following form

```
111.222.121.212:322
112.223.122.213:422
...
```

It would be very useful when for example fuzzing SSH service which is often doable just with 1 thread. That way we could fuzz 10 ssh servers each with 1 thread.

**Comment by vanhauser-thc** [comment]
that is supported since many years ... is that not working?

**Comment by MMquant** [comment]
I missed that `-M` flag in the docs :). All good!
