### ISSUE TITLE
makefile generated with ./configure but not working

### ISSUE THREAD

**Issue by Shreya-Stuy21** [vanhauser-thc/thc-hydra#592]
I have git and cygwin. After I ran ./configure in cygwin, I ran make, but it did not work. Instead, I got  the following error message. So I tried in make in git bash (where I know for a fact that make works), but it still didn't work. I think the problem is in my makefile.

$ make
cc -I. -O3 -g -fcommon  -g   -o pw-inspector pw-inspector-logo.o pw-inspector.c
process_begin: CreateProcess(NULL, cc -I. -O3 -g -fcommon -g -o pw-inspector pw-inspector-logo.o pw-inspector.c, ...) failed.
make (e=2): The system cannot find the file specified.
make: [Makefile:75: pw-inspector] Error 2 (ignored)
cc -I. -O3 -g -fcommon  -g  -c hydra-vnc.c -DHAVE_PCRE -DNO_STRRCHR -DHAVE_ZLIB -DHAVE_MATH_H -DHAVE_SYS_PARAM_H -I/usr/include
process_begin: CreateProcess(NULL, cc -I. -O3 -g -fcommon -g -c hydra-vnc.c -DHAVE_PCRE -DNO_STRRCHR -DHAVE_ZLIB -DHAVE_MATH_H -DHAVE_SYS_PARAM_H -I/usr/include, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:78: hydra-vnc.o] Error 2

**Comment by vanhauser-thc** [comment]
try `export CC=gcc` before make
