### ISSUE TITLE
[ERROR] Child with pid 4370 terminating, cannot connect

### ISSUE THREAD

**Issue by Kalifjord** [vanhauser-thc/thc-hydra#594]
Hi there, trying to test my wordpress site for problems. But i continuing having this problem.

sudo hydra -l admin -P /usr/share/wordlists/fasttrack.txt the ip of the website https-post-form '/wp-login.php:log=admin&pwd=^PASS^&wp-submit=Log In&testcookie=1:Ukendt brugernavn. Kontroller igen eller prøv med din mailadresse.'

output is:
[ERROR] Child with pid 4382 terminating, cannot connect
[ERROR] Child with pid 4385 terminating, cannot connect
[ERROR] Child with pid 4384 terminating, cannot connect
[ERROR] Child with pid 4391 terminating, cannot connect
[ERROR] Child with pid 4393 terminating, cannot connect
[ERROR] Child with pid 4390 terminating, cannot connect
[ERROR] Child with pid 4395 terminating, cannot connect
[ERROR] Child with pid 4399 terminating, cannot connect

trying to -d flag it

giving this information:

[ATTEMPT-ERROR] target **"the ip"** - login "admin" - pass "Winter2016" - child 8 - 255 of 222
[DEBUG] hydra_increase_fail_count: 1 >= 0 => disable
[DEBUG] head_no 8, kill 1, fail 2
[VERBOSE] Disabled child 8 because of too many errors
[VERBOSE] Could not create an SSL session: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
[VERBOSE] Could not create an SSL session: error:14094410:SSL routines:ssl3_read_bytes:sslv3 al

Someone know how to fix this+

**Comment by vanhauser-thc** [comment]
this is the issue:
```
[VERBOSE] Could not create an SSL session: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```
your ssl library seem to be ancient. update to a new version and recompile hydra

**Comment by Kalifjord** [comment]
Thanks for respond, do you mean like this? "sudo apt-get install libssl-dev libssh-dev" ?

**Comment by vanhauser-thc** [comment]
yes.

**Comment by Kalifjord** [comment]
Not working unfortunately - just trying with a whole new wordpress installation, without any security plugins, without any luck. Really hope someone know a solution...

**Comment by vanhauser-thc** [comment]
what linux distribution are you using? is it that old?

**Comment by Kalifjord** [comment]
Hmm...
Virtual machine is Oracel VM -v 6.1.18 
Kali linux -v 2020.4 
Debian 64 bit

**Comment by vanhauser-thc** [comment]
can you try this:
`hydra -l admin -p admin https-get://www.google.com`
if this succeeds then there is an issue with your target. if this fails too you have a problematic ssl lib. I am on Kali Linux too and things work fine for me

**Comment by Kalifjord** [comment]
Here is the output
-
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2021-01-31 09:38:22
[WARNING] You must supply the web page as an additional option or via -m, default path set to /
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking http-gets://www.google.com:443/
[443][http-get] host: www.google.com   login: admin   password: admin
1 of 1 target successfully completed, 1 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2021-01-31 09:38:22

**Comment by vanhauser-thc** [comment]
try to: make clean, make, make install. and remove hydra kali hydra package.

**Comment by whitediamondys5** [comment]
please i need your help concerning this post, i got this but my hydra is 2023

*Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2021-01-31 09:38:22
[WARNING] You must supply the web page as an additional option or via -m, default path set to /
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking http-gets://www.google.com:443/
[443][http-get] host: [www.google.com](http://www.google.com/) login: admin password: admin
1 of 1 target successfully completed, 1 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2021-01-31 09:38:22*

**Comment by whitediamondys5** [comment]
![Image](https://github.com/user-attachments/assets/63b406bd-90f3-4508-abb5-df20e0d3007c)

please where do i do next to solve this
