### ISSUE TITLE
[VERBOSE] Could not create an SSL session: error:00000000:lib(0):func(0):reason(0) 

### ISSUE THREAD

**Issue by gitfirewall** [vanhauser-thc/thc-hydra#596]
When the process is started, i have this error, many times:

[VERBOSE] Could not create an SSL session: error:00000000:lib(0):func(0):reason(0) 

Then these too:

[ERROR] Child with pid 3497 terminating, can not connect  

[ERROR] Child with pid 3496 terminating, can not connect 

[ERROR] Child with pid 3504 terminating, can not connect    

and so on..... 

after 3 or 4 minutes the process is killed in this way:

^C[ERROR] Received signal 2, going down ...
The session file ./hydra.restore was written. Type "hydra -R" to resume session.

Can you help me? I can't resolve it alone. Thanks.

**Comment by vanhauser-thc** [comment]
either your target is too old and does not support current SSL/TLS settings or your openssl is too old. try updating to a newer libssl-dev
