### ISSUE TITLE
Find the inital letter ONLY. Possible?

### ISSUE THREAD

**Issue by gitfirewall** [vanhauser-thc/thc-hydra#598]
With the brute force, i want to find only the initial 3-4 letter of the password, then rebuild it myself with the social engineering.

Is this possible? Example: The password has 15 characters, but i want to know only the first 4. 

Can hydra show me a thing like that:

frado***********

If, for example, i set hydra to search a maximum of 4 characters, can i know if those 4 characters are the initial letters of my password?

Thanks.

**Comment by vanhauser-thc** [comment]
no
