### ISSUE TITLE
 burst mysql fail

### ISSUE THREAD

**Issue by dubao123** [vanhauser-thc/thc-hydra#599]
the latest version Hydra v9.1 i installed by source code. burst mysql  fail.
the version Hydra v8.2-dev  i installed by yum is success. pls help.thks!

![1](https://user-images.githubusercontent.com/31361186/106376436-482a2100-63d0-11eb-9785-be2ef00a41b5.png)
![2](https://user-images.githubusercontent.com/31361186/106376442-5ed07800-63d0-11eb-9d64-2c05aa266e39.png)

**Comment by vanhauser-thc** [comment]
weird. is hydra run on the same system?
