### ISSUE TITLE
ClaymoreMiner API password

### ISSUE THREAD

**Issue by PvtSec** [vanhauser-thc/thc-hydra#600]
The API uses this following json as a raw tcp request:
```{"id":0,"jsonrpc":"2.0","method":"miner_controlgpu", "psw":"sample_password"}```
The brute was possible with python multithreading.
The mining software can have multiple ports available with different rigs using the same password. So parallel connection to each port can immensely reduce the time required to check all passwords without dos-ing the miner service.

**Comment by vanhauser-thc** [comment]
1. you pose no question or request
2. what you are doing looks pretty illegal ... so closing this.

**Comment by PvtSec** [comment]
May be the specific question turned up as illegal, but handling a raw json request like this one would be helpful in testing apps during development.

**Comment by vanhauser-thc** [comment]
well have a valid and legal problem and you will get an answer :)
