### ISSUE TITLE
Managing Hydra for HTTP-POST-FORM

### ISSUE THREAD

**Issue by PvtSec** [vanhauser-thc/thc-hydra#601]
Hydra returns an error for setting http-post-form
```
[ERROR] the target is using HTTP auth, not a web form, received HTTP error code 401. Use module "http-get" instead.
```
Already the page uses HTTP POST to authorize. But by receiving a response of 401 triggers Hydra to throw the errors.

**Comment by vanhauser-thc** [comment]
that is an unusual setup.
you can either patch that out of hydra and recompile - or if you think that is a useful feature make it a parameter in the miscptr, similar to H=, etc.

**Comment by HarrisonKeeling** [comment]
Would be nice to see official support around this... saw this config in recent cPanel versions

**Comment by vanhauser-thc** [comment]
@HarrisonKeeling patches are welcome :)
