### ISSUE TITLE
Error trying to read server list with -M when it contains IPs instead of URLs

### ISSUE THREAD

**Issue by BustedSec** [vanhauser-thc/thc-hydra#602]
example command: hydra -l username -p password -s 9999 -M iplist.txt http-get
example output: [ERROR] could not resolve address: x.x.x.x (<-whatever IPs are in the list, over and over)

**Comment by BustedSec** [comment]
I tried formatting the input file in a bunch of different ways. I tried prepending http:// to each IP. I tried using actual hostnames instead IPs, I tried http://hostname. No matter what I try, I get hit with the "[ERROR] could not resolve address:" for each host it iterates through in the loop. I thought - maybe it's DNS - so I manually set my DNS servers in resolv.conf. No difference. Been at this hours now, I think there is some kind of parsing error going on when it's reading the input file via the -M parameter.

**Comment by vanhauser-thc** [comment]
do you think it would help if you paste an example from your file? ;)
format is:

```
1.2.3.4
1.2.6.7:1234
foo.bar.domain
```

**Comment by BustedSec** [comment]
I think this turned out to be some kind of weird DNS issue due to my local setup because it worked fine when I sshed into a VPS then do the same thing. I think it has something to do with the way Windows does NATIng on WSL and Linux vms that are NAT instead of bridge networking. I run a OpenVPN tunnel on the windows box.... The stewnge

**Comment by BustedSec** [comment]
Example would be like 
1.2.3.4
2.3.4.5
4.5.6.7
