### ISSUE TITLE
SMB2 module not working?

### ISSUE THREAD

**Issue by RuiNatario** [vanhauser-thc/thc-hydra#603]
When trying to use the brand new SMB2 module, I get an error stating the app was compiled without the proper library:

```
hydra -L /usr/share/wordlists/csa_users.txt -P /usr/share/wordlists/csa_passwords.txt 172.16.1.10 smb2                               255 ⨯
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2021-02-13 19:44:50
[ERROR] Compiled without LIBSMBCLIENT support, module not available!
```

**Comment by vanhauser-thc** [comment]
you have to install the library, checkout the repo, ./configure;make;sudo make install .... the usual stuff :)

**Comment by RuiNatario** [comment]
In the changelog there is a line:

`new module: smb2 which also supports smb3 (uses libsmbclient-dev) (thanks to Karim Kanso for the module!)`

I assumed the release file had already been compiled with this lib in order to enable the new module.

My bad, sorry :-)

**Comment by vanhauser-thc** [comment]
that is the responsibility of the package maintainer of the linux distro you are using... :)

**Comment by RuiNatario** [comment]
Got it, I'm using the latest Kali ;-)

**Comment by gioguanuo** [comment]
Hello everybodies also with Kali 2022.4 doesn't work
