### ISSUE TITLE
If add a http-header option(h|H=), hydra doesn't send packets.

### ISSUE THREAD

**Issue by bbakbbak2** [vanhauser-thc/thc-hydra#605]
OS: Linux kali 5.8.0-kali2-amd64 #1 SMP Debian 5.8.10-1kali1 (2020-09-22) x86_64 GNU/Linux
version: hydra version 9.1

1. Turn on my web server to see packets.
python3 -m http.server 80

2. Start hydra
hydra -l admin -P /tools/pwd/rockyou.txt 127.0.0.1 -s 80 http-post-form "/test:username=^USER^&password=^PASS^:F=fail:h=foo" -v -V

Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2021-02-16 06:52:26
[WARNING] Restorefile (you have 10 seconds to abort... (use option -I to skip waiting)) from a previous session found, to prevent overwriting, ./hydra.restore
[DATA] max 16 tasks per 1 server, overall 16 tasks, 14344399 login tries (l:1/p:14344399), ~896525 tries per task
[DATA] attacking http-post-form://127.0.0.1:80/test:username=^USER^&password=^PASS^:F=fail:h=foo
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "123456" - 1 of 14344399 [child 0] (0/0)
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "12345" - 2 of 14344399 [child 1] (0/0)
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "123456789" - 3 of 14344399 [child 2] (0/0)
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "password" - 4 of 14344399 [child 3] (0/0)
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "iloveyou" - 5 of 14344399 [child 4] (0/0)
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "princess" - 6 of 14344399 [child 5] (0/0

It seems to be work well but my server doesn't receive anything.
If I remove the http-header option then it will work well.

**Comment by vanhauser-thc** [comment]
it needs to be "...:h=foo\: bar"

**Comment by bbakbbak2** [comment]
> it needs to be "...:h=foo: bar"

I tested yours but it showed still error
I saw other people found same issue when they add http-header with http-post-form on Hydra 9.1.
This issue was not being resolved.
