### ISSUE TITLE
Not working on smtp yahoo server

### ISSUE THREAD

**Issue by mariembenali** [vanhauser-thc/thc-hydra#606]
**IMPORTANT**
This is just for reporting *BUGS* not help on how to hack, how to use hydra, command line options or how to get it compiled. Please search for help via search engines. Issues asking for this here will be closed.

**Describe the bug**
Hydra is not working on yahoo smtp server.

**To Reproduce**

hydra -S -C file.txt  -V -s 465 smtp.mail.yahoo.com smtp

**Expected behavior**
using a correct user/password. Expected behavior is password found. 

**Results**

1 of 1 target completed, 0 valid password found

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - hydra version 9.1

**Additional context**
NONE

**Comment by vanhauser-thc** [comment]
did you notice the banner?
```
[INFO] several providers have implemented cracking protection, check with a small wordlist first - and stay legal!
```
most likely they either detect hydra (it reports itself so it can be detected) or the auth type is different what you selected (e.g. needs NTLM or OAUTH etc.)
