### ISSUE TITLE
Support cross pkg-config when configuring

### ISSUE THREAD

**Issue by jscott0** [vanhauser-thc/thc-hydra#607]
Hi,

I'm working on getting the Debian package to cross-build but there's a coded assumption in configure that's making this difficult: it tries to use pkg-config under the name `pkg-config`, with no way to override, which belongs to the build system, not the host. It's here around line 1306:
````
if [ "X" = "X$XHYDRA_SUPPORT" ]; then
    echo "Checking for GUI req's (pkg-config/gtk+-2.0) ..."
  XHYDRA_SUPPORT=`pkg-config --help > /dev/null 2>&1 || echo disabled`
  if [ "X" = "X$XHYDRA_SUPPORT" ]; then
     XHYDRA_SUPPORT=`pkg-config --modversion gtk+-2.0 2> /dev/null`
  else
     XHYDRA_SUPPORT=""
  fi
  if [ "X" = "X$XHYDRA_SUPPORT" ]; then
    echo "                                             ... NOT found, optional anyway"
  else
    echo "                                             ... found"
  fi
fi
````

This could be solved a variety of ways. You could support the --host argument to configure, so that `--host=aarch64-linux-gnu` would make it try `aarch64-linux-gnu-pkg-config`. Hydra could also support a `PKG_CONFIG` environment variable, like for `CC`, of what it would use.

For xhydra to build, the same GNU-style arguments that are given to the top-level configure script should be passed along to the xhydra configure script.

**Comment by vanhauser-thc** [comment]
I added PKG_CONFIG support, hope this helps.
