### ISSUE TITLE
Hydra build failed

### ISSUE THREAD

**Issue by 26chk** [vanhauser-thc/thc-hydra#608]
I tried to compile Hydra in Termux, but it gave me errors

CFLAGS=" -Dindex=strchr -Drindex=strrchr -DLIBOPENSSL -DNO_RINDEX -DHAVE_MATH_H -DHAVE_PCRE -DLIBSSH"

export MANDIR=/share/man/man1

export XLIBS="-lcrypto -lssl -lpcre -lssh"

cat Makefile.am | sed 's/^install:.*/install: all/' >> Makefile && make install

![Screenshot_20210221_111540](https://user-images.githubusercontent.com/61009000/108614522-37e8ed00-7436-11eb-825f-cb50f9392258.jpg)

**Comment by vanhauser-thc** [comment]
how about you do a correct fix that does and ifdef which then selects index or strchr, etc.?
then this will work.
