### ISSUE TITLE
Not working when "./configure"

### ISSUE THREAD

**Issue by WheatThin12** [vanhauser-thc/thc-hydra#609]
I am running it on Windows 10 home

Just added a cmd prompt to the file so it has a compiler and when I went to set it up with typing "./configure" I get this message: "DNS server not authoritative for zone." I have no clue what this means, I am running it as an admin and it still wont run,

**Comment by vanhauser-thc** [comment]
you need to install cygwin from www.cygin.com and install there. it is quite complex.

**Comment by WheatThin12** [comment]
![Capture](https://user-images.githubusercontent.com/79823164/109578410-be4ba180-7abc-11eb-8ef2-0bef3979802b.JPG)
Which site would I download it from, there is no option for the current site

**Comment by WheatThin12** [comment]
![Capture](https://user-images.githubusercontent.com/79823164/109578544-f94dd500-7abc-11eb-9248-94f12e480f52.PNG)
Which site do I pick? It doesn't have a option for the current cite.

**Comment by WheatThin12** [comment]
What packages do I need to download in cygwin?
