### ISSUE TITLE
database patator has no effect

### ISSUE THREAD

**Issue by jienhui9407** [vanhauser-thc/thc-hydra#611]
**IMPORTANT**
There is something wrong in the newest version. When I use hydra to patator the database like mysql. There is no effect with hydra. But the old version can.

**Comment by vanhauser-thc** [comment]
what is "patator"? and what database are you talking about? be specfic, if you put no effort in the issue then there is nothing I can fix

**Comment by jienhui9407** [comment]
> 
> 
> what is "patator"? and what database are you talking about? be specfic, if you put no effort in the issue then there is nothing I can fix

Sorry, I didn't specify it in detail. When I use the newest hydra to do like this <hydra -l root -p root 192.168.20.41 mysql -s 3306>, there is no result. However, when I use the old version the result is correct.

**Comment by vanhauser-thc** [comment]
@jienhui9407 
that is still zero information I can work with.
which version works for you? against the same target? what is the error output? ... etc.
If you do not invest the necessary time to give a comprehensive issue report I can actually work with then please close it.
