### ISSUE TITLE
CPU Utilization on Xenon

### ISSUE THREAD

**Issue by koiakoia** [vanhauser-thc/thc-hydra#614]
**IMPORTANT**
This is just for reporting *BUGS* not help on how to hack, how to use hydra, command line options or how to get it compiled. Please search for help via search engines. Issues asking for this here will be closed.

**Describe the bug**
When using Hydra on Xenon Silver 4215 hydra runs 1 attempt per minute per task assigned by option.  ie. -t 64 = 64 attempts per minute.  Changing -t to 16 runs 12 per minute.  Maybe not a bug maybe because of lower clock speed? 2.5 GHZ

**To Reproduce**
Current version
run it on xenon proc

1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**
Note that all messages must be in *English*, not in Chinese, Russian, etc.
<img width="394" alt="hydra" src="https://user-images.githubusercontent.com/60405354/110870177-f2337d80-8299-11eb-9ec2-223299e6abd4.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - hydra version [e.g. current github state]

**Additional context**

**Comment by vanhauser-thc** [comment]
the -t is not "attempts per minute" it is "spawned heads for performing tests".
1 head = 1 connection to the target.

the CPU impact of hydra is actually little, so if you have a xeon with 64 cores or an i3 with 4 does not have that much of a difference. 

the difference you see is not on your side, but rather that when fewer heads attack then the server has less overhead so can reply faster. for that reason a high -t value is often problematic - for the server side or because a server does only accept a max amount of connections from one IP.

**Comment by koiakoia** [comment]
Yes. I understand -t is not supposed to be that. But it does in fact operate that way on this bare metal deployment of Kali. I'm not sure why and was assuming it was related to the xenon chip architecture. Whatever I set -t top is how many attempts a minute I will see outputted on the first cycle.

**Comment by vanhauser-thc** [comment]
1. it depends on the protocol and responsiveness of the server. 1 sttempt per minutes is super slow.
2. it is juts a rought calculation, ot gets more precise after 15+ minutes

**Comment by koiakoia** [comment]
Okay. I'll do some continued exploration see if I can find a cause or if it improves over time. Just was shocked my vm instance was doing like 8000 per minute and the bare metal server with much better hardware was so slow. Appreciate your responses and was very helpful. Anything else I can provide or do to help let me know.

**Comment by koiakoia** [comment]
For whatever reason it is just very very slow on this machine.  Not sure why but probably not a hydra issue probably a linux issue.

Thanks
