### ISSUE TITLE
Hydra cant crack gmail passwords 

### ISSUE THREAD

**Issue by ImKool-Gitch** [vanhauser-thc/thc-hydra#618]
i started a brute force attack against a gmail that i created and i put the password in a wordlist and and i ran than wordlist against the gmail and the password was clearly in it but hydra said 0 passwords

**Comment by vanhauser-thc** [comment]
https://github.com/vanhauser-thc/thc-hydra/issues/613

**Comment by maoad950-cmd** [comment]
https://github.com/vanhauser-thc/thc-hydra/issues/618

**Comment by ns3508192-prog** [comment]
https://github.com/vanhauser-thc/thc-hydra/issues/618
