### ISSUE TITLE
Missing GET parameters and Hydra never ends

### ISSUE THREAD

**Issue by andreafortunato** [vanhauser-thc/thc-hydra#619]
Hello there,

I'm trying to learn the basics of brute force, using DVWA.
I don't know if I'm missing something but I think I have a problem with _:H_ option...

First of all (maybe it can help): `uname -a  ==>  Linux kali 5.10.0-kali4-amd64 #1 SMP Debian 5.10.19-1kali1 (2021-03-03) x86_64 GNU/Linux`

The command I am using is very simple and it is the following (taken from #612):
`hydra -l admin -p password 'http-get-form://192.168.32.129/vulnerabilities/brute/:username=^USER^&password=^PASS^&Login=Login:S=Welcome:H=Cookie\: PHPSESSID=59oimk975a2200fu3a0v63apo6; security=low' -vV`
But the output is:
![Hydra1](https://user-images.githubusercontent.com/7126728/111178237-39c44d00-85ab-11eb-81db-c63d2a321f1d.png)

The line `[INFO] Using HTTP Proxy: http://127.0.0.1:8080` is there because not understanding what was happening, I tried to investigate using BurpSuite (I used `export HYDRA_PROXY_HTTP="http://127.0.0.1:8080"`) and I encountered 2 major problems:
1) Using the _H_ option, BurpSuite does not intercept any traffic and Hydra never ends;
2) Without the _H_ option (`hydra -l admin -p password 'http-get-form://192.168.32.129/vulnerabilities/brute/:username=^USER^&password=^PASS^&Login=Login:S=Welcome' -vV`), BurpSuite shows GET parameters are missing!
![Burp1](https://user-images.githubusercontent.com/7126728/111180424-52356700-85ad-11eb-9c05-f21eb3f4aaf5.png)
Hit _Forward_ and:
![Burp2](https://user-images.githubusercontent.com/7126728/111180485-5eb9bf80-85ad-11eb-84ed-0ecd15af9e3f.png)
Hit _Forward_ and:
![Burp3](https://user-images.githubusercontent.com/7126728/111180505-62e5dd00-85ad-11eb-9a33-6af75cdffa04.png)
and Hydra output
![Hydra2](https://user-images.githubusercontent.com/7126728/111179705-9d9b4580-85ac-11eb-8005-81e10e448251.png)

I've tried to change the command in so many different ways but the result doesn't change...
Am I doing something wrong? I would really like to understand and learn but unfortunately I'm stuck here and can't go on.

Thank you in advance and I apologize if I wrote something wrong or silly.

**Comment by vanhauser-thc** [comment]
did you see https://github.com/vanhauser-thc/thc-hydra/issues/612 ?

**Comment by andreafortunato** [comment]
Thanks for the quick reply!
Yes. As I wrote, I used the exact same command in #612 (I just added _-vV_ and changed _PHPSESSID=*PLACE_YOUR_SESSION_ID_HERE*;_ to _PHPSESSID=59oimk975a2200fu3a0v63apo6;_.

**Comment by vanhauser-thc** [comment]
No this is the problem:
```
Process 5613: Can not connect [unreachable]
```
the target ip/port cannot be connected

**Comment by andreafortunato** [comment]
Yes, this was just a test with a wrong ip (on purpose, to see Hydra's output using the _H:_ parameter as well).
It just seems to get stuck when I add H: to pass Cookies, whether the ip is right or not.

**Comment by vanhauser-thc** [comment]
have you tried a checkout and compilation of this github state? could be that your distro has a broken binary

**Comment by andreafortunato** [comment]
I can confirm that now it works! (Hydra v9.2-dev)

> 1. git clone https://github.com/vanhauser-thc/thc-hydra
> 2. ./configure
> 3. make
> 4. make install

So I'll purge the pre-installed Hydra version (9.1) on Kali (I also tried to reinstall it but it doesn't work anyway).

Thanks so much for the help!
