### ISSUE TITLE
 Out of memory in 8.2-dev

### ISSUE THREAD

**Issue by bonaff** [vanhauser-thc/thc-hydra#62]
Hi, i have this behaviour when trying to perform a dictionary attack against a https login page. When i launch the attack i get this output:
$./hydra -L ../../user.txt -P ../../pass.txt www.hackthis.co.uk https-form-post "/levels/extras/real/4/planetbid/login.php:user=^USER^&password=^PASS^:Incorect:h=Cookie\: PHPSESSID=gpso9vnXXXXXXXXXXXXvu675h2"
[443][http-post-form] host: www.hackthis.co.uk   login: John   password: (name)
[443][http-post-form] host: www.hackthis.co.uk   login: John   password: qwerty
[..]
[ERROR] Out of memory[ERROR] Out of memory[ERROR] Out of memory[ERROR] Out of memory[ERROR] Out of memory[ERROR] Out of memory[ERROR] Out of memory[ERROR] Out of memory[ERROR] Out of memory[ERROR] Out of memory[ERROR] Out of memory[ERROR] Out of memory[ERROR] Out of memory[ERROR] Out of memory[ERROR] Out of memory[ERROR] Out of memory[443][http-post-form] host: www.hackthis.co.uk   login: Revoked.Mayhem   password: pass
[..]
[443][http-post-form] host: www.hackthis.co.uk   login: Revoked.Mayhem   password: (name)
[443][http-post-form] host: www.hackthis.co.uk   login: Gizmo   password: letmein
[ERROR] Out of memory[ERROR] Out of memory1 of 1 target successfully completed, 32 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2015-05-14 18:11:09

(the target it's a game, so no worry)

**Comment by vanhauser-thc** [comment]
hydra tries to get necessary memory but does not get it.
can you please retry the command line, add the -d switch and post everything here (command line and all output)? 
and besides it looks like you did not set up hydra correctly as you have false positives.

**Comment by vanhauser-thc** [comment]
please submit the debug data if you want it fixed, otherwise I will close the issue

**Comment by vanhauser-thc** [comment]
with was a weird bug, I think I found and fixed it. please checkout the current version and retest.
