### ISSUE TITLE
hydra 9.2 doesn't build on mac osx

### ISSUE THREAD

**Issue by Moisan** [vanhauser-thc/thc-hydra#622]
**Describe the bug**
When trying to build hydra 9.2 on mac osx I get the following error:
```
ld: unknown option: --allow-multiple-definition
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**To Reproduce**

1. `./configure`
2. `make all`

**Desktop:**
 - OS: OSX 11.2.3
 - hydra version 9.2

Homebrew CI has also tested 10.15 and 10.14 on which the build has failed. See https://github.com/Homebrew/homebrew-core/pull/73232

**Comment by vanhauser-thc** [comment]
the linker you are using is the crippled apple one.
just remove `-Wl,--allow-multiple-definition` from the generated Makefile and pray it works ;)

**Comment by Moisan** [comment]
It does work. 👍  Would it be possible modify `configure` to remove this option on mac?

**Comment by cconcannon** [comment]
had the same issue on OS 10.15.7

per the suggestion, changing this line: 
`OPTS=-I. -O3 $(CFLAGS) -fcommon -Wl,--allow-multiple-definition` 
to
`OPTS=-I. -O3 $(CFLAGS) -fcommon`
allowed `make` and `make install` to proceed without error

Thanks

**Comment by vanhauser-thc** [comment]
will add a check for that in the future

**Comment by NextAbyss** [comment]
@vanhauser-thc I pass make stage with freerdp,but i can't "make install" it;
eg:
λ ~/Desktop/thc-hydra/ master* sudo make install
Password:

Now type make install
strip hydra pw-inspector
echo OK > /dev/null && test -x xhydra && strip xhydra || echo OK > /dev/null
mkdir -p /usr/local/bin
cp -f hydra-wizard.sh hydra pw-inspector /usr/local/bin && cd /usr/local/bin && chmod 755 hydra-wizard.sh hydra pw-inspector
echo OK > /dev/null && test -x xhydra && cp xhydra /usr/local/bin && cd /usr/local/bin && chmod 755 xhydra || echo OK > /dev/null
sed -e "s|^INSTALLDIR=.*|INSTALLDIR="/usr/local"|" dpl4hydra.sh | sed -e "s|^LOCATION=.*|LOCATION="/etc"|" > /usr/local/bin/dpl4hydra.sh
chmod 755 /usr/local/bin/dpl4hydra.sh
mkdir -p /usr/local/etc
cp -f *.csv /usr/local/etc
mkdir -p /usr/local/man/man1/
cp -f hydra.1 xhydra.1 pw-inspector.1 /usr/local/man/man1/
mkdir -p /usr/local/share/pixmaps
cp -f xhydra.png /usr/local/share/pixmaps/
mkdir -p /usr/local/share/applications
desktop-file-install --dir /usr/local/share/applications xhydra.desktop
make: desktop-file-install: No such file or directory
make: [install] Error 1 (ignored)

**Comment by vanhauser-thc** [comment]
it installed fine, you just dont have a linux to have the desktop icon.

**Comment by lakshmias** [comment]
> the linker you are using is the crippled apple one.
> just remove `-Wl,--allow-multiple-definition` from the generated Makefile and pray it works ;)

that worked for me on Mac
