### ISSUE TITLE
Output HTTP Response code for each Attempt of an HTTPS-POST-FORM

### ISSUE THREAD

**Issue by renegadeandy** [vanhauser-thc/thc-hydra#624]
Hi all,

I am not sure if this is possible, and cannot find an alternative place to ask the question! Is it possible with Hydra to check, and / or output the HTTP response code for a set of HTTPS-POST-FORM calls?

Many thanks

**Comment by vanhauser-thc** [comment]
`-d` option

**Comment by renegadeandy** [comment]
@vanhauser-thc -d gives me debug - which is very hard to quickly determine for each request what the HTTP return code was especially when SSL is on.

I am literally looking for : ATTEMPT <existing details> HTTP RC:403
