### ISSUE TITLE
How do you override the debug flag continuing a restored run?

### ISSUE THREAD

**Issue by renegadeandy** [vanhauser-thc/thc-hydra#625]
I was doing a run. I stopped it using Ctrl+C.

This made a restore file :)

I then wanted to try the "-d" flag as per issue https://github.com/vanhauser-thc/thc-hydra/issues/624 which showed me debug info after restarting the run.

However now it seems like debug info is locked into the run - Each time I restart I cannot get it to turn 'off' debug? How can I do this?

**Comment by vanhauser-thc** [comment]
It should work like this: "hydra -R -d" if you switch -d and -R it is gone :)

**Comment by renegadeandy** [comment]
To clarify @vanhauser-thc its not clear what you mean by 'If you switch -d and -R it is gone' so I did a couple of things :

I run "hydra -R -d" and it does debug.

I cancel.

I run "hydra -R" and it does debug.

I cancel.

I run "hydra -d -R" and it does debug.

**Comment by vanhauser-thc** [comment]
I closed it because you asked something and I answered it.
anything else? its debugging now ...

**Comment by renegadeandy** [comment]
I guess I am looking for something that the software doesn't do in that case. I'll need to find something else.

**Comment by renegadeandy** [comment]
Sorry @vanhauser-thc this issue is not closed! I still see debug output all the time when resuming a run:

https://github.com/vanhauser-thc/thc-hydra/issues/625#issuecomment-807174103

**Comment by vanhauser-thc** [comment]
ah, now I get it. I thought you WANT debug output.  but you have it enabled and DO NOT want it anymore :)
sorry bad luck for your, this can not be reversed.
look at the state (what is the password tried) and remove anything until this point from the password list, restart.
