### ISSUE TITLE
Makefile:67: ошибка выполнения рецепта для цели «hydra-smb.o»

### ISSUE THREAD

**Issue by 230v** [vanhauser-thc/thc-hydra#63]
gcc -I. -O3 -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wl,-z,now -Wl,-z,relro   -c hydra-smb.c -DLIBOPENSSL -DLIBNCURSES -DHAVE_PCRE -DLIBSSH -DHAVE_MATH_H -I/usr/include -I/usr/include
hydra-smb.c: В функции «MakeKey»:
hydra-smb.c:179:23: ошибка: «des_cblock» undeclared (first use in this function)
   des_set_odd_parity((des_cblock *) des_key);
                       ^
hydra-smb.c:179:23: замечание: each undeclared identifier is reported only once for each function it appears in
hydra-smb.c:179:35: ошибка: expected expression before «)» token
   des_set_odd_parity((des_cblock *) des_key);
                                   ^
hydra-smb.c: В функции «DesEncrypt»:
hydra-smb.c:184:3: ошибка: unknown type name «des_cblock»
   des_cblock des_key;
   ^
hydra-smb.c:185:3: ошибка: unknown type name «des_key_schedule»
   des_key_schedule key_schedule;
   ^
hydra-smb.c:187:16: предупреждение: при передаче аргумента 2 «MakeKey» целое преобразуется в указатель без приведения типа
   MakeKey(key, des_key);
                ^
hydra-smb.c:169:13: замечание: expected «unsigned char *» but argument is of type «int»
 static void MakeKey(unsigned char *key, unsigned char *des_key) {
             ^
hydra-smb.c:189:20: ошибка: «des_cblock» undeclared (first use in this function)
   des_ecb_encrypt((des_cblock *) clear, (des_cblock *) cipher, key_schedule, 1);
                    ^
hydra-smb.c:189:32: ошибка: expected expression before «)» token
   des_ecb_encrypt((des_cblock *) clear, (des_cblock *) cipher, key_schedule, 1);
                                ^
Makefile:67: ошибка выполнения рецепта для цели «hydra-smb.o»
make: *** [hydra-smb.o] Ошибка 1

**Comment by vanhauser-thc** [comment]
as you might guess, russian error messages do not help if you try to communicate with someone who doesnt know russian :)
I think I can guess the issue, but it will take a week until I have time for this

**Comment by vanhauser-thc** [comment]
what openssl version are you using?

**Comment by vanhauser-thc** [comment]
and please send the output of:
grep -ri des_cblock /usr/include

**Comment by vanhauser-thc** [comment]
please send in the data, or I will close the issue

**Comment by 0xc0decafe** [comment]
Hi, running across the same problem using libressl-2.5.1.

>grep -ri des_cblock /usr/include/openssl
>/usr/include/openssl/des.h:typedef unsigned char DES_cblock[8];
>/usr/include/openssl/des.h:typedef /* const */ unsigned char const_DES_cblock[8];
>/usr/include/openssl/des.h:/* With "const", gcc 2.8.1 on Solaris thinks that DES_cblock *
>/usr/include/openssl/des.h: * and const_DES_cblock * are incompatible pointer types. */
>/usr/include/openssl/des.h:	DES_cblock cblock;
>/usr/include/openssl/des.h:#define DES_KEY_SZ 	(sizeof(DES_cblock))
>/usr/include/openssl/des.h:void DES_ecb3_encrypt(const_DES_cblock *input, DES_cblock *output,
>/usr/include/openssl/des.h:DES_LONG DES_cbc_cksum(const unsigned char *input,DES_cblock *output,
>/usr/include/openssl/des.h:		       const_DES_cblock *ivec);
>/usr/include/openssl/des.h:		     long length,DES_key_schedule *schedule,DES_cblock *ivec,
>/usr/include/openssl/des.h:		      long length,DES_key_schedule *schedule,DES_cblock *ivec,
>/usr/include/openssl/des.h:		      long length,DES_key_schedule *schedule,DES_cblock *ivec,
>/usr/include/openssl/des.h:		      const_DES_cblock *inw,const_DES_cblock *outw,int enc);
>/usr/include/openssl/des.h:		     long length,DES_key_schedule *schedule,DES_cblock *ivec,
>/usr/include/openssl/des.h:void DES_ecb_encrypt(const_DES_cblock *input,DES_cblock *output,
>/usr/include/openssl/des.h:			  DES_key_schedule *ks3,DES_cblock *ivec,int enc);
>/usr/include/openssl/des.h:			   DES_cblock *ivec1,DES_cblock *ivec2,
>/usr/include/openssl/des.h:			    DES_cblock *ivec,int *num,int enc);
>/usr/include/openssl/des.h:			  DES_cblock *ivec,int enc);
>/usr/include/openssl/des.h:			    DES_cblock *ivec,int *num);
>/usr/include/openssl/des.h:		 DES_cblock *iv);
>/usr/include/openssl/des.h:		  DES_cblock *iv);
>/usr/include/openssl/des.h:		     long length,DES_key_schedule *schedule,DES_cblock *ivec);
>/usr/include/openssl/des.h:		      long length,DES_key_schedule *schedule,DES_cblock *ivec,
>/usr/include/openssl/des.h:DES_LONG DES_quad_cksum(const unsigned char *input,DES_cblock output[],
>/usr/include/openssl/des.h:			long length,int out_count,DES_cblock *seed);
>/usr/include/openssl/des.h:int DES_random_key(DES_cblock *ret);
>/usr/include/openssl/des.h:void DES_set_odd_parity(DES_cblock *key);
>/usr/include/openssl/des.h:int DES_check_key_parity(const_DES_cblock *key);
>/usr/include/openssl/des.h:int DES_is_weak_key(const_DES_cblock *key);
>/usr/include/openssl/des.h:int DES_set_key(const_DES_cblock *key,DES_key_schedule *schedule);
>/usr/include/openssl/des.h:int DES_key_sched(const_DES_cblock *key,DES_key_schedule *schedule);
>/usr/include/openssl/des.h:int DES_set_key_checked(const_DES_cblock *key,DES_key_schedule *schedule);
>/usr/include/openssl/des.h:void DES_set_key_unchecked(const_DES_cblock *key,DES_key_schedule *schedule);
>/usr/include/openssl/des.h:void DES_string_to_key(const char *str,DES_cblock *key);
>/usr/include/openssl/des.h:void DES_string_to_2keys(const char *str,DES_cblock *key1,DES_cblock *key2);
>/usr/include/openssl/des.h:		       DES_key_schedule *schedule,DES_cblock *ivec,int *num,
>/usr/include/openssl/des.h:		       DES_key_schedule *schedule,DES_cblock *ivec,int *num);

**Comment by 0xc0decafe** [comment]
Also, to anti russian:

hydra-smb.c: In function 'MakeKey':
hydra-smb.c:179:23: error: 'des_cblock' undeclared (first use in this function)
   des_set_odd_parity((des_cblock *) des_key);
                       ^
hydra-smb.c:179:23: note: each undeclared identifier is reported only once for each function it appears in
hydra-smb.c:179:35: error: expected expression before ')' token
   des_set_odd_parity((des_cblock *) des_key);
                                   ^
hydra-smb.c: In function 'DesEncrypt':
hydra-smb.c:184:3: error: unknown type name 'des_cblock'
   des_cblock des_key;
   ^
hydra-smb.c:185:3: error: unknown type name 'des_key_schedule'
   des_key_schedule key_schedule;
   ^
hydra-smb.c:187:16: warning: passing argument 2 of 'MakeKey' makes pointer from integer without a cast
   MakeKey(key, des_key);
                ^
hydra-smb.c:169:13: note: expected 'unsigned char *' but argument is of type 'int'
 static void MakeKey(unsigned char *key, unsigned char *des_key) {
             ^
hydra-smb.c:189:20: error: 'des_cblock' undeclared (first use in this function)
   des_ecb_encrypt((des_cblock *) clear, (des_cblock *) cipher, key_schedule, 1);
                    ^
hydra-smb.c:189:32: error: expected expression before ')' token
   des_ecb_encrypt((des_cblock *) clear, (des_cblock *) cipher, key_schedule, 1);

**Comment by vanhauser-thc** [comment]
@0xc0decafe are you using the current version of this github repository? looks rather like an old hydra tar.gz

**Comment by 0xc0decafe** [comment]
Hi,

yes, was using the 8.1 release. git version builds. any plans for a new release?
THX!

**Comment by vanhauser-thc** [comment]
the current release is 8.4 and has the fix .... ... ... ...

**Comment by vitold54** [comment]
> the current release is 8.4 and has the fix .... ... ... ...

I used version 9.2, the error is the sameю

output comman grep -ri des_cblock /usr/include

`/usr/include/openssl/des.h:typedef unsigned char DES_cblock[8];
/usr/include/openssl/des.h:typedef /* const */ unsigned char const_DES_cblock[8];
/usr/include/openssl/des.h: * With "const", gcc 2.8.1 on Solaris thinks that DES_cblock * and
/usr/include/openssl/des.h: * const_DES_cblock * are incompatible pointer types.
/usr/include/openssl/des.h:        DES_cblock cblock;
/usr/include/openssl/des.h:# define DES_KEY_SZ      (sizeof(DES_cblock))
/usr/include/openssl/des.h:void DES_ecb3_encrypt(const_DES_cblock *input, DES_cblock *output,
/usr/include/openssl/des.h:DES_LONG DES_cbc_cksum(const unsigned char *input, DES_cblock *output,
/usr/include/openssl/des.h:                       const_DES_cblock *ivec);
/usr/include/openssl/des.h:                     DES_cblock *ivec, int enc);
/usr/include/openssl/des.h:                      DES_cblock *ivec, int enc);
/usr/include/openssl/des.h:                      DES_cblock *ivec, const_DES_cblock *inw,
/usr/include/openssl/des.h:                      const_DES_cblock *outw, int enc);
/usr/include/openssl/des.h:                     DES_cblock *ivec, int enc);
/usr/include/openssl/des.h:void DES_ecb_encrypt(const_DES_cblock *input, DES_cblock *output,
/usr/include/openssl/des.h:                          DES_key_schedule *ks3, DES_cblock *ivec, int enc);
/usr/include/openssl/des.h:                           DES_cblock *ivec1, DES_cblock *ivec2, int enc);
/usr/include/openssl/des.h:                            DES_cblock *ivec, int *num, int enc);
/usr/include/openssl/des.h:                          DES_cblock *ivec, int enc);
/usr/include/openssl/des.h:                            DES_cblock *ivec, int *num);
/usr/include/openssl/des.h:void DES_xwhite_in2out(const_DES_cblock *DES_key, const_DES_cblock *in_white,
/usr/include/openssl/des.h:                       DES_cblock *out_white);
/usr/include/openssl/des.h:                 DES_cblock *iv);
/usr/include/openssl/des.h:                  DES_cblock *iv);
/usr/include/openssl/des.h:                     DES_cblock *ivec);
/usr/include/openssl/des.h:                      DES_cblock *ivec, int enc);
/usr/include/openssl/des.h:DES_LONG DES_quad_cksum(const unsigned char *input, DES_cblock output[],
/usr/include/openssl/des.h:                        long length, int out_count, DES_cblock *seed);
/usr/include/openssl/des.h:int DES_random_key(DES_cblock *ret);
/usr/include/openssl/des.h:void DES_set_odd_parity(DES_cblock *key);
/usr/include/openssl/des.h:int DES_check_key_parity(const_DES_cblock *key);
/usr/include/openssl/des.h:int DES_is_weak_key(const_DES_cblock *key);
/usr/include/openssl/des.h:int DES_set_key(const_DES_cblock *key, DES_key_schedule *schedule);
/usr/include/openssl/des.h:int DES_key_sched(const_DES_cblock *key, DES_key_schedule *schedule);
/usr/include/openssl/des.h:int DES_set_key_checked(const_DES_cblock *key, DES_key_schedule *schedule);
/usr/include/openssl/des.h:void DES_set_key_unchecked(const_DES_cblock *key, DES_key_schedule *schedule);
/usr/include/openssl/des.h:void private_DES_set_key_unchecked(const_DES_cblock *key,
/usr/include/openssl/des.h:void DES_string_to_key(const char *str, DES_cblock *key);
/usr/include/openssl/des.h:void DES_string_to_2keys(const char *str, DES_cblock *key1, DES_cblock *key2);
/usr/include/openssl/des.h:                       DES_cblock *ivec, int *num, int enc);
/usr/include/openssl/des.h:                       DES_cblock *ivec, int *num);
/usr/include/openssl/des.h:int DES_read_password(DES_cblock *key, const char *prompt, int verify);
/usr/include/openssl/des.h:int DES_read_2passwords(DES_cblock *key1, DES_cblock *key2,
/usr/include/openssl/des_old.h:typedef unsigned char _ossl_old_des_cblock[8];
/usr/include/openssl/des_old.h:        _ossl_old_des_cblock _;
/usr/include/openssl/des_old.h:#  define des_cblock DES_cblock
/usr/include/openssl/des_old.h:#  define const_des_cblock const_DES_cblock
/usr/include/openssl/des_old.h:#  define des_cblock _ossl_old_des_cblock
/usr/include/openssl/des_old.h:void _ossl_old_des_ecb3_encrypt(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *output,
/usr/include/openssl/des_old.h:DES_LONG _ossl_old_des_cbc_cksum(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                                 _ossl_old_des_cblock *output, long length,
/usr/include/openssl/des_old.h:                                 _ossl_old_des_cblock *ivec);
/usr/include/openssl/des_old.h:void _ossl_old_des_cbc_encrypt(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                               _ossl_old_des_cblock *output, long length,
/usr/include/openssl/des_old.h:                               _ossl_old_des_cblock *ivec, int enc);
/usr/include/openssl/des_old.h:void _ossl_old_des_ncbc_encrypt(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *output, long length,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *ivec, int enc);
/usr/include/openssl/des_old.h:void _ossl_old_des_xcbc_encrypt(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *output, long length,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *ivec,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *inw,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *outw, int enc);
/usr/include/openssl/des_old.h:                               _ossl_old_des_cblock *ivec, int enc);
/usr/include/openssl/des_old.h:void _ossl_old_des_ecb_encrypt(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                               _ossl_old_des_cblock *output,
/usr/include/openssl/des_old.h:void _ossl_old_des_ede3_cbc_encrypt(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                                    _ossl_old_des_cblock *output, long length,
/usr/include/openssl/des_old.h:                                    _ossl_old_des_cblock *ivec, int enc);
/usr/include/openssl/des_old.h:                                      _ossl_old_des_cblock *ivec, int *num,
/usr/include/openssl/des_old.h:                                      _ossl_old_des_cblock *ivec, int *num);
/usr/include/openssl/des_old.h:void _ossl_old_des_xwhite_in2out(_ossl_old_des_cblock (*des_key),
/usr/include/openssl/des_old.h:                                 _ossl_old_des_cblock (*in_white),
/usr/include/openssl/des_old.h:                                 _ossl_old_des_cblock (*out_white));
/usr/include/openssl/des_old.h:                           _ossl_old_des_cblock *iv);
/usr/include/openssl/des_old.h:                            _ossl_old_des_cblock *iv);
/usr/include/openssl/des_old.h:                               _ossl_old_des_cblock *ivec);
/usr/include/openssl/des_old.h:void _ossl_old_des_pcbc_encrypt(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *output, long length,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *ivec, int enc);
/usr/include/openssl/des_old.h:DES_LONG _ossl_old_des_quad_cksum(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                                  _ossl_old_des_cblock *output, long length,
/usr/include/openssl/des_old.h:                                  int out_count, _ossl_old_des_cblock *seed);
/usr/include/openssl/des_old.h:void _ossl_old_des_random_seed(_ossl_old_des_cblock key);
/usr/include/openssl/des_old.h:void _ossl_old_des_random_key(_ossl_old_des_cblock ret);
/usr/include/openssl/des_old.h:int _ossl_old_des_read_password(_ossl_old_des_cblock *key, const char *prompt,
/usr/include/openssl/des_old.h:int _ossl_old_des_read_2passwords(_ossl_old_des_cblock *key1,
/usr/include/openssl/des_old.h:                                  _ossl_old_des_cblock *key2,
/usr/include/openssl/des_old.h:void _ossl_old_des_set_odd_parity(_ossl_old_des_cblock *key);
/usr/include/openssl/des_old.h:int _ossl_old_des_is_weak_key(_ossl_old_des_cblock *key);
/usr/include/openssl/des_old.h:int _ossl_old_des_set_key(_ossl_old_des_cblock *key,
/usr/include/openssl/des_old.h:int _ossl_old_des_key_sched(_ossl_old_des_cblock *key,
/usr/include/openssl/des_old.h:void _ossl_old_des_string_to_key(char *str, _ossl_old_des_cblock *key);
/usr/include/openssl/des_old.h:void _ossl_old_des_string_to_2keys(char *str, _ossl_old_des_cblock *key1,
/usr/include/openssl/des_old.h:                                   _ossl_old_des_cblock *key2);
/usr/include/openssl/des_old.h:                                 _ossl_old_des_cblock *ivec, int *num,
/usr/include/openssl/des_old.h:                                 _ossl_old_des_cblock *ivec, int *num);
/usr/include/openssl/des_old.h:void _ossl_096_des_random_seed(des_cblock *key);
/usr/include/openssl/des_old.h:#  define C_Block des_cblock
root@vitaliy-N68S3:~# grep -ri des_cblock /usr/include/openssl
/usr/include/openssl/des.h:typedef unsigned char DES_cblock[8];
/usr/include/openssl/des.h:typedef /* const */ unsigned char const_DES_cblock[8];
/usr/include/openssl/des.h: * With "const", gcc 2.8.1 on Solaris thinks that DES_cblock * and
/usr/include/openssl/des.h: * const_DES_cblock * are incompatible pointer types.
/usr/include/openssl/des.h:        DES_cblock cblock;
/usr/include/openssl/des.h:# define DES_KEY_SZ      (sizeof(DES_cblock))
/usr/include/openssl/des.h:void DES_ecb3_encrypt(const_DES_cblock *input, DES_cblock *output,
/usr/include/openssl/des.h:DES_LONG DES_cbc_cksum(const unsigned char *input, DES_cblock *output,
/usr/include/openssl/des.h:                       const_DES_cblock *ivec);
/usr/include/openssl/des.h:                     DES_cblock *ivec, int enc);
/usr/include/openssl/des.h:                      DES_cblock *ivec, int enc);
/usr/include/openssl/des.h:                      DES_cblock *ivec, const_DES_cblock *inw,
/usr/include/openssl/des.h:                      const_DES_cblock *outw, int enc);
/usr/include/openssl/des.h:                     DES_cblock *ivec, int enc);
/usr/include/openssl/des.h:void DES_ecb_encrypt(const_DES_cblock *input, DES_cblock *output,
/usr/include/openssl/des.h:                          DES_key_schedule *ks3, DES_cblock *ivec, int enc);
/usr/include/openssl/des.h:                           DES_cblock *ivec1, DES_cblock *ivec2, int enc);
/usr/include/openssl/des.h:                            DES_cblock *ivec, int *num, int enc);
/usr/include/openssl/des.h:                          DES_cblock *ivec, int enc);
/usr/include/openssl/des.h:                            DES_cblock *ivec, int *num);
/usr/include/openssl/des.h:void DES_xwhite_in2out(const_DES_cblock *DES_key, const_DES_cblock *in_white,
/usr/include/openssl/des.h:                       DES_cblock *out_white);
/usr/include/openssl/des.h:                 DES_cblock *iv);
/usr/include/openssl/des.h:                  DES_cblock *iv);
/usr/include/openssl/des.h:                     DES_cblock *ivec);
/usr/include/openssl/des.h:                      DES_cblock *ivec, int enc);
/usr/include/openssl/des.h:DES_LONG DES_quad_cksum(const unsigned char *input, DES_cblock output[],
/usr/include/openssl/des.h:                        long length, int out_count, DES_cblock *seed);
/usr/include/openssl/des.h:int DES_random_key(DES_cblock *ret);
/usr/include/openssl/des.h:void DES_set_odd_parity(DES_cblock *key);
/usr/include/openssl/des.h:int DES_check_key_parity(const_DES_cblock *key);
/usr/include/openssl/des.h:int DES_is_weak_key(const_DES_cblock *key);
/usr/include/openssl/des.h:int DES_set_key(const_DES_cblock *key, DES_key_schedule *schedule);
/usr/include/openssl/des.h:int DES_key_sched(const_DES_cblock *key, DES_key_schedule *schedule);
/usr/include/openssl/des.h:int DES_set_key_checked(const_DES_cblock *key, DES_key_schedule *schedule);
/usr/include/openssl/des.h:void DES_set_key_unchecked(const_DES_cblock *key, DES_key_schedule *schedule);
/usr/include/openssl/des.h:void private_DES_set_key_unchecked(const_DES_cblock *key,
/usr/include/openssl/des.h:void DES_string_to_key(const char *str, DES_cblock *key);
/usr/include/openssl/des.h:void DES_string_to_2keys(const char *str, DES_cblock *key1, DES_cblock *key2);
/usr/include/openssl/des.h:                       DES_cblock *ivec, int *num, int enc);
/usr/include/openssl/des.h:                       DES_cblock *ivec, int *num);
/usr/include/openssl/des.h:int DES_read_password(DES_cblock *key, const char *prompt, int verify);
/usr/include/openssl/des.h:int DES_read_2passwords(DES_cblock *key1, DES_cblock *key2,
/usr/include/openssl/des_old.h:typedef unsigned char _ossl_old_des_cblock[8];
/usr/include/openssl/des_old.h:        _ossl_old_des_cblock _;
/usr/include/openssl/des_old.h:#  define des_cblock DES_cblock
/usr/include/openssl/des_old.h:#  define const_des_cblock const_DES_cblock
/usr/include/openssl/des_old.h:#  define des_cblock _ossl_old_des_cblock
/usr/include/openssl/des_old.h:void _ossl_old_des_ecb3_encrypt(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *output,
/usr/include/openssl/des_old.h:DES_LONG _ossl_old_des_cbc_cksum(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                                 _ossl_old_des_cblock *output, long length,
/usr/include/openssl/des_old.h:                                 _ossl_old_des_cblock *ivec);
/usr/include/openssl/des_old.h:void _ossl_old_des_cbc_encrypt(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                               _ossl_old_des_cblock *output, long length,
/usr/include/openssl/des_old.h:                               _ossl_old_des_cblock *ivec, int enc);
/usr/include/openssl/des_old.h:void _ossl_old_des_ncbc_encrypt(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *output, long length,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *ivec, int enc);
/usr/include/openssl/des_old.h:void _ossl_old_des_xcbc_encrypt(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *output, long length,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *ivec,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *inw,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *outw, int enc);
/usr/include/openssl/des_old.h:                               _ossl_old_des_cblock *ivec, int enc);
/usr/include/openssl/des_old.h:void _ossl_old_des_ecb_encrypt(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                               _ossl_old_des_cblock *output,
/usr/include/openssl/des_old.h:void _ossl_old_des_ede3_cbc_encrypt(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                                    _ossl_old_des_cblock *output, long length,
/usr/include/openssl/des_old.h:                                    _ossl_old_des_cblock *ivec, int enc);
/usr/include/openssl/des_old.h:                                      _ossl_old_des_cblock *ivec, int *num,
/usr/include/openssl/des_old.h:                                      _ossl_old_des_cblock *ivec, int *num);
/usr/include/openssl/des_old.h:void _ossl_old_des_xwhite_in2out(_ossl_old_des_cblock (*des_key),
/usr/include/openssl/des_old.h:                                 _ossl_old_des_cblock (*in_white),
/usr/include/openssl/des_old.h:                                 _ossl_old_des_cblock (*out_white));
/usr/include/openssl/des_old.h:                           _ossl_old_des_cblock *iv);
/usr/include/openssl/des_old.h:                            _ossl_old_des_cblock *iv);
/usr/include/openssl/des_old.h:                               _ossl_old_des_cblock *ivec);
/usr/include/openssl/des_old.h:void _ossl_old_des_pcbc_encrypt(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *output, long length,
/usr/include/openssl/des_old.h:                                _ossl_old_des_cblock *ivec, int enc);
/usr/include/openssl/des_old.h:DES_LONG _ossl_old_des_quad_cksum(_ossl_old_des_cblock *input,
/usr/include/openssl/des_old.h:                                  _ossl_old_des_cblock *output, long length,
/usr/include/openssl/des_old.h:                                  int out_count, _ossl_old_des_cblock *seed);
/usr/include/openssl/des_old.h:void _ossl_old_des_random_seed(_ossl_old_des_cblock key);
/usr/include/openssl/des_old.h:void _ossl_old_des_random_key(_ossl_old_des_cblock ret);
/usr/include/openssl/des_old.h:int _ossl_old_des_read_password(_ossl_old_des_cblock *key, const char *prompt,
/usr/include/openssl/des_old.h:int _ossl_old_des_read_2passwords(_ossl_old_des_cblock *key1,
/usr/include/openssl/des_old.h:                                  _ossl_old_des_cblock *key2,
/usr/include/openssl/des_old.h:void _ossl_old_des_set_odd_parity(_ossl_old_des_cblock *key);
/usr/include/openssl/des_old.h:int _ossl_old_des_is_weak_key(_ossl_old_des_cblock *key);
/usr/include/openssl/des_old.h:int _ossl_old_des_set_key(_ossl_old_des_cblock *key,
/usr/include/openssl/des_old.h:int _ossl_old_des_key_sched(_ossl_old_des_cblock *key,
/usr/include/openssl/des_old.h:void _ossl_old_des_string_to_key(char *str, _ossl_old_des_cblock *key);
/usr/include/openssl/des_old.h:void _ossl_old_des_string_to_2keys(char *str, _ossl_old_des_cblock *key1,
/usr/include/openssl/des_old.h:                                   _ossl_old_des_cblock *key2);
/usr/include/openssl/des_old.h:                                 _ossl_old_des_cblock *ivec, int *num,
/usr/include/openssl/des_old.h:                                 _ossl_old_des_cblock *ivec, int *num);
/usr/include/openssl/des_old.h:void _ossl_096_des_random_seed(des_cblock *key);
/usr/include/openssl/des_old.h:#  define C_Block des_cblock
`

I would like to get help. Thank you
