### ISSUE TITLE
Hydra cannot find any valid passwords

### ISSUE THREAD

**Issue by latarnik1** [vanhauser-thc/thc-hydra#631]
Hi,
I have a problem with Hydra. I wanted to try a brute force attack on DVWA using Hydra, but the program cannot find the correct password. I tried to look for solutions on the internet, but none of them helped. I don't know where I have the error in the code, because the same code worked for others. Full command below.

`hydra_ -l admin -P Desktop/passwords.txt 127.0.0.1 http-get-form "/DVWA/vulnerabilities/brute/:username=^USER^&password=^PASS^&Login=Login:F=Username and/or password incorrect.:H=Cookie\: security=low; PHPSESSID=d1jdiq8r4uc8e5klk967qo64f0" -V
`

Here is the screenshot of an output

![hydra_issue](https://user-images.githubusercontent.com/82617706/114946979-8a4df500-9e4c-11eb-90c2-4eaa67ec4645.png)

If the bug is obvious then sorry but I just started using Hydra.
Thank you in advance for your help.

**Comment by vanhauser-thc** [comment]
#612

**Comment by sunilkumarupp437-cmyk** [comment]
### hydra

**Comment by sunilkumarupp437-cmyk** [comment]
Hydra

**Comment by sunilkumarupp437-cmyk** [comment]
Hydra

**Comment by sunilkumarupp437-cmyk** [comment]
Password insta

**Comment by sunilkumarupp437-cmyk** [comment]
### hydra

**Comment by sunilkumarupp437-cmyk** [comment]
**91067 36092**

**Comment by sunilkumarupp437-cmyk** [comment]
Deepa.akraj1476
