### ISSUE TITLE
Hydra Compile failed with freerdp(from brew) on macos

### ISSUE THREAD

**Issue by NextAbyss** [vanhauser-thc/thc-hydra#632]
If without freerdp(uninstalled freerdp),it will compile successlly, once i installed freerdp, i will "make" it fail.

eg:

In file included from /usr/local/include/winpr2/winpr/platform.h:25:
/usr/local/include/winpr2/winpr/wtypes.h:168:21: error: typedef redefinition with different types
      ('signed char' vs 'int32_t' (aka 'int'))
typedef signed char BOOL;
                    ^
./hydra-mod.h:70:17: note: previous definition is here
typedef int32_t BOOL;
                ^
1 error generated.
make: *** [hydra-rdp.o] Error 1

**Comment by vanhauser-thc** [comment]
thanks, fixed.
