### ISSUE TITLE
Issue with Installing

### ISSUE THREAD

**Issue by dt021501** [vanhauser-thc/thc-hydra#634]
Hello
I'm new to this and had never problems till nowm
After typing in make it says error.

Can someone help me pls.
![Screenshot_20210421-092209_Termux](https://user-images.githubusercontent.com/82475547/115513191-157f1e80-a283-11eb-8e50-c099703484bd.jpg)

**Comment by vanhauser-thc** [comment]
are you compiling for android?

**Comment by victorolayemi** [comment]
The same error on macos

**Comment by vanhauser-thc** [comment]
I dont have a Mac either.
it complains that strings.h is not included but it is in line 14 of hydra.c - but this is just an indicator that index is actually not present in the libc that is linked.
you can try to replace index() with strchr().

**Comment by Dark01010** [comment]
Thc hydra is install you have just type this command to start your hydra tool in your termux. command ./hydra -h

**Comment by vanhauser-thc** [comment]
the issue is fixed in hydra for some months now
