### ISSUE TITLE
What string test conditions to use to bruteforce the Outlook Web App?

### ISSUE THREAD

**Issue by andizaa** [vanhauser-thc/thc-hydra#635]
I put The OWA (outlook web app) on Burpsuite proxy, it seems there are 4 or 5 redirects after the submit button. What should be the string/text in the test condition? 
I tried to put S=text (true conditions) with string/text in body response from each first, second, third, fourth, and fifth redirect page, but none of the works.
I tried to put error message (F=error) but it doesnt work because the error string text is loaded from Javascript.

Thank you @vanhauser-thc

**Comment by hoangkm13** [comment]
Sorry but did you solve it ?
