### ISSUE TITLE
Command dpl4hydra.sh all generate a invalid pair

### ISSUE THREAD

**Issue by iago-silva** [vanhauser-thc/thc-hydra#636]
**Describe the bug**

Invalid pair at line 17:

```(first 7 letters of student's last name + first seven letters of first name + middle initial -- no spaces or punctuation):(First letter of first name Capitalized + First letter of last name in lowercase + day of birth {01-31} + birth year {2 digits} + last 4 digits of student ID)```

**To Reproduce**

- run `dpl4hydra.sh all`
- run `hydra -C dpl4hydra_all.txt 127.0.0.1 http-get`

**Expected behavior**

This raises: `[ERROR] invalid line in colon file (-C), missing colon in line: t 4 digits of student ID)`

**Desktop:**
 - OS: Linux Mint 20
 - hydra version: v0.9.9

**Comment by vanhauser-thc** [comment]
thanks, fixed
