### ISSUE TITLE
Google reports thc-hydra page as harmful

### ISSUE THREAD

**Issue by maaaaz** [vanhauser-thc/thc-hydra#64]
Hello,

I just have seen that Google reports the thc-hydra page as harmful, showing [that kind of message](https://support.google.com/websearch/answer/45449?hl=en&rd=1).
However the full thc.org website is not reported as harmful.

Cheers.

**Comment by vanhauser-thc** [comment]
yeah we know.
google sucks.
and we will not go through the hassle to get the page unlocked (creating an evil google account etc. etc.)
