### ISSUE TITLE
How can I build or install hydra for Termux app that give  Linux environment also?

### ISSUE THREAD

**Issue by Vuacheslav1234590** [vanhauser-thc/thc-hydra#640]
Termux is app giving some Linux environment. How can I install hydra on termux app? The termux has libssh and other libs, "bash" shell and other shells. But I can not complile hydra.

**Comment by vanhauser-thc** [comment]
I have no clue what that is, so cant help you, sorry

**Comment by Vuacheslav1234590** [comment]
U can know more about what is termux in:
https://wiki.termux.com/wiki/Main_Page

вт, 27 апр. 2021 г., 20:46 van Hauser ***@***.***>:

**Comment by vanhauser-thc** [comment]
duplicate #647
