### ISSUE TITLE
[ERROR] the variables argument needs at least the strings ^USER^, ^PASS^, ^USER64^ or ^PASS64^

### ISSUE THREAD

**Issue by Rzrfin8** [vanhauser-thc/thc-hydra#643]
**Describe the bug**
Please excuse me if this is not a bug. I am new to this tool however it appears as this is a bug. Attempting to complete a room on THM where I need to crack a web login using a POST response.  The response body from the POST request does not appear to be a standard format.  Attempting to use the response body given, I receive an error.

 Response body for login is as such:
`{"email":"user_inputted_text","password":"user_inputted_text"`

However, this returns error:
`[ERROR] the variables argument needs at least the strings ^USER^, ^PASS^, ^USER64^ or ^PASS64^`

Full code is as follows:
`sudo hydra -l admin@juice-sh.op -P /usr/share/seclists/Passwords/Common-Credentials/best1050.txt 10.10.142.186 http-post-form "/#/login:{"email":^USER^,"password":^PASS^}:F=Invalid"`

Error return:
`[ERROR] the variables argument needs at least the strings ^USER^, ^PASS^, ^USER64^ or ^PASS64^: {email`

**To Reproduce**

Use response body not matching to:
`username=username&password=password`

**Expected behavior**
Command to run without errors.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Kernel: 5.10.32-1-MANJARO
 - hydra version: current github state (downloaded about 2 hours before post)

**Comment by vanhauser-thc** [comment]
sorry for the super late reply, this issue somehow didnt show for me.
the post information was set wrong, correct would have been:
`hydra -l admin@juice-sh.op -P /usr/share/seclists/Passwords/Common-Credentials/best1050.txt 10.10.142.186 http-post-form '/#/login:{"email"\:^USER^,"password"\:^PASS^}:F=Invalid'`
