### ISSUE TITLE
Compile and installation error in cygwin64

### ISSUE THREAD

**Issue by furqan-ops** [vanhauser-thc/thc-hydra#644]
Please Help i cannot install hydra password cracker using cygwin64 
Below are pics
![2](https://user-images.githubusercontent.com/60847168/116785669-3d0c8d00-aab4-11eb-880b-fe66f765e011.JPG)
[
![1](https://user-images.githubusercontent.com/60847168/116785702-5dd4e280-aab4-11eb-9c2a-0d528aa1996f.JPG)
![3](https://user-images.githubusercontent.com/60847168/116785939-a04aef00-aab5-11eb-935d-be94134a8930.JPG)

**Comment by vanhauser-thc** [comment]
you have no compiler installed

**Comment by furqan-ops** [comment]
So how i can solve this problem
