### ISSUE TITLE
Macos [ERROR] The -M FILE option can not be used together with a host on the commandline

### ISSUE THREAD

**Issue by nelly2340** [vanhauser-thc/thc-hydra#645]
✘  ~  hydra -L logins.txt -P pass.txt  -M 22port.txt ssh -e n -o ssh.txt
Hydra v9.2 (c) 2021 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2021-05-03 21:28:58
[ERROR] The -M FILE option can not be used together with a host on the commandline

I tried many times, is there a problem with my grammar? I can't find where the error is.

**Comment by vanhauser-thc** [comment]
works for me, although it should rather be
`hydra -L logins.txt -P pass.txt -M 22port.txt -e n -o ssh.txt ssh`

**Comment by nelly2340** [comment]
> 为我工作，尽管它应该是
> `hydra -L logins.txt -P pass.txt -M 22port.txt -e n -o ssh.txt ssh`


Strange, I can run in Kali, the same file. But I usually use Mac os, what should I do, I don’t know where the problem is?
