### ISSUE TITLE
error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by MohdAltaf01** [vanhauser-thc/thc-hydra#646]
When i command to make this happens and i am not getting
Solution of this
error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:68: hydra] Error 1
What happening to this hydra is also not available in packages
I updated and upgraded many times i can't use brute force with out him

**Comment by vanhauser-thc** [comment]
1. paste full error.
2. try a translation site so your english can be better understood by me
