### ISSUE TITLE
Module VNC doesn't skip the target if password is found.

### ISSUE THREAD

**Issue by safranalulu** [vanhauser-thc/thc-hydra#653]
If "VNC server does not require authentication" or the target accepts any password for login, the target is found and is not skipped,and the app checks the same target with every password in the list over and over like a loop even if the targets are unique. 

./hydra -P passfile -M targets -o resultsfile vnc

[5900][vnc] host: 192.168.0.1   password: 1234
[5900][vnc] host: 192.168.0.2   password: 1234
VNC server does not require authentication.
VNC server does not require authentication.
[5900][vnc] host: 192.168.0.1   password: 12345...
[5900][vnc] host: 192.168.0.2   password: !!??3323
[5900][vnc] host: 192.168.0.1   password: !!!???

With Hydra v9.2 (c) 2021 and 9.1 on  Linux kali 5.10.0-kali3-cloud-amd64 #1 SMP Debian 5.10.13-1kali1 (2021-02-08) x86_64 GNU/Linux,Kali GNU/Linux Rolling.

**Expected behavior**

if target is found the app should not check again the same target,sometimes the target is found but the results are false positive.

**Comment by yoke88** [comment]
try -f or -F switch ?

**Comment by vanhauser-thc** [comment]
@safranalulu 
I just pushed a fix, can you please test?
