### ISSUE TITLE
What kind of proxy application you recommend and/or prefer for the Hydra app?

### ISSUE THREAD

**Issue by feruenzerujkun** [vanhauser-thc/thc-hydra#659]
Sorry to intrude for a moment as a use saying "hi/(and)hello" to you, @vanhauser-thc.
I'm mentally afraid to interrupt to be here for a moment unless longer and shorter things be needed also.
I am about to be (re)installing the cygwin and Hydra (your stuff) via the use of Windscribe the VPN I am using, might to redownload to start all over again by the 9th of June instead of now in my own opinion.

Do you recommend and/or prefer a proxy for that + HTTPS, I am kinda needing one under or over VPN instead of LAN or a regular net.

I was thinking of OWASP ZAP or other since you started mentioning it to other people on the repository.
Some screenshots (of my own) could be useful to give me/us feedback and ideas unless I'm getting confused over that and the settings along needing anything also.

![vanhauser_htc_owasp_zap_hydra (1)](https://user-images.githubusercontent.com/40934370/120600488-5ba9cf00-c438-11eb-9da6-ace0f69300af.png)

![vanhauser_htc_owasp_zap_hydra (2)](https://user-images.githubusercontent.com/40934370/120600536-68c6be00-c438-11eb-90d7-3862ee555f72.png)

![vanhauser_htc_owasp_zap_hydra (3)](https://user-images.githubusercontent.com/40934370/120600541-6b291800-c438-11eb-8b05-88c43b1220d1.png)

![vanhauser_htc_owasp_zap_hydra (4)](https://user-images.githubusercontent.com/40934370/120600549-6d8b7200-c438-11eb-841c-c3c111931579.png)

![vanhauser_htc_owasp_zap_hydra (5)](https://user-images.githubusercontent.com/40934370/120600564-72502600-c438-11eb-90c6-a024398d4070.png)

![vanhauser_htc_owasp_zap_hydra (6)](https://user-images.githubusercontent.com/40934370/120600575-74b28000-c438-11eb-8556-6a57ae7ffa83.png)

![vanhauser_htc_owasp_zap_hydra (7)](https://user-images.githubusercontent.com/40934370/120600592-77ad7080-c438-11eb-89bf-c3c9765e567e.png)

sidenote;
I do not think that OWASP ZAP, or BURP-Suite or anything similar to those two can or could work on sites containing HTTPS+Cloudflare (or other) with Cloudflare and/or other DNS installed by bypassing it/them,
it can also 403 error responses before starting it completely.

**Comment by vanhauser-thc** [comment]
you only use a proxy if you need a proxy to be able to connect to the target. using burp, zap etc. in between is usually pointless and just slows things down.
