### ISSUE TITLE
How to start the Hydra SSH module in Alpine OS

### ISSUE THREAD

**Issue by lonelyPoker** [vanhauser-thc/thc-hydra#661]
expect the author to upgrade the libssh library version to 0.9.5. alpine OS .

compile  libssh v0.4.8:
![image](https://user-images.githubusercontent.com/37132457/121119933-285bab80-c84f-11eb-962a-e625a906396a.png)

**Comment by vanhauser-thc** [comment]
that is an issue in libssh, why are you posting here?
