### ISSUE TITLE
If i opt-out with ctrl+C can i still see the results?

### ISSUE THREAD

**Issue by Amalsarr** [vanhauser-thc/thc-hydra#663]
I’ve had my machine up for 24 hours by now and apparently i still got about another 24h tp finish all the remaining attempts to brute-force an ssh protocol, if i opt-out rn using ssh would i still get to see at least half the results? I’ve forgot to verbose the results so I can’t really tell if hydra managed to found any valid correct credentials and im scared leaving my machine up for that long is gonna ruin it for me.

**Comment by vanhauser-thc** [comment]
finds are written directly on the screen (or -o output file). so you have no findings so far.
you can press control-c, and continue at another time with hydra -R
