### ISSUE TITLE
Requests from http-*-form modules sent as TCP in Mac OSX

### ISSUE THREAD

**Issue by erwanlr** [vanhauser-thc/thc-hydra#67]
Using the http-get-form and http-post-form modules, it turns out that the requests are done with the TCP rather than the HTTP protocol in MacOSX. As a result the attacks never find a correct password. Behaviour was confirmed using wireshark to check the traffic as the web server was not receiving anything.

The https version of these modules might also be affected (as well as other ones which would normally use HTTP), however they were not tested.

OSX v10.10.3
Xcode v6.3.2 (6D2105)
Hydra 8.1 installed via brew (and w/o the libssh)

Command ran: hydra -t 2 -l admin -p admin -V 192.168.1.103 http-form-get "/test.php:log=^USER^&pwd=^PASS^&testcookie=1:incorrect"

In Kali linux, the requests are correctly sent via HTTP. 

Let me know if you need more info.

**Comment by vanhauser-thc** [comment]
This explanation does not really make sense. HTTP is sent over TCP ...
please attach the wireshark pcap from both platforms, I will try to figure out what the problem is.

**Comment by erwanlr** [comment]
Once downloaded, remove the .png extension ;)

MacOSX.pcap.png
![mac-osx.pcap.png](https://cloud.githubusercontent.com/assets/1668843/8393309/75f39140-1d02-11e5-9ac1-220ba339c5c5.png)

Kali.pcap.png
![kali.pcap.png](https://cloud.githubusercontent.com/assets/1668843/8393347/eb5063b8-1d03-11e5-88d5-5416be5d4f83.png)

**Comment by vanhauser-thc** [comment]
so, the issue is that on OS/X no data is sent whatsoever.
can you please send the full output of the following command:

hydra -dvv -t 2 -l admin -p admin -V 192.168.1.103 http-form-get "/test.php:log=^USER^&pwd=^PASS^&testcookie=1:incorrect"

**Comment by erwanlr** [comment]
There you go https://gist.github.com/erwanlr/8235e7d0f27ef79a841f

**Comment by vanhauser-thc** [comment]
damn, the debug output tells nothing what goes wrong.
please checkout the the repository here, compile it and try again.

**Comment by erwanlr** [comment]
Already tried to compile it yesterday, got the last issue mentioned at https://github.com/vanhauser-thc/thc-hydra/issues/50

```
4 warnings generated.
ld: warning: directory not found for option '-L/lib'
Undefined symbols for architecture x86_64:
  "_TLSv1_2_client_method", referenced from:
      _internal__hydra_connect_to_ssl in hydra-mod.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [hydra] Error 1
```

**Comment by vanhauser-thc** [comment]
it looks like your openssl installation is totally outdated ...

can you please send in the output of "./configure --debug" ?
and then do a make and please paste all output.

**Comment by erwanlr** [comment]
```
$ openssl version
OpenSSL 1.0.2c 12 Jun 2015
```

https://gist.github.com/erwanlr/57ac4cc4c6d1565b1c19

**Comment by erwanlr** [comment]
Looks like the issue is the same than https://github.com/vanhauser-thc/thc-hydra/issues/28 which was not fixed but closed.

**Comment by vanhauser-thc** [comment]
is this still an issue?

my problem is that I dont have OS X and can not reproduce it.

please update all software, get the newest repository here too, recompile and retry.

**Comment by TylerRockwell** [comment]
I ran into this issue today.

This command works in Kali Linux (also running Hydra 8.1), but not in OSX
```
hydra -l 'aaa' -p 'password' -v -s 3000 192.168.56.102 http-form-post "/account/login:user_login=^USER^&user_password=^PASS^:S=redirected"
```
Hydra 8.1 installed via Homebrew.
OSX 10.11.5
openssl 1.02h

In OSX:
Using `http-get` works fine.
Using `http-*-form` sends SYN and ACK messages, but never sends an HTTP request.

**Comment by vanhauser-thc** [comment]
@TylerRockwell that sucks.

sadly I can not do anything about this. I do not have an OS X (thank god :) ) and it works on all my platforms.

so it needs someone with debugging know.how on OS X to analyze the issue.

If you do - can you do an strace+ltrace (or something similar on OS X) and send the output? plus the output of the hydra command with an added -d option.

A patch of course would be even better.

and finally - it needs to be tested with the current github version here. not an outdated one.

**Comment by dmaciejak** [comment]
Just removed some compilation warning like
ld: warning: directory not found for option '-L/lib' and
clang: warning: argument unused during compilation: '-pie'
