### ISSUE TITLE
smtp-enum should quit on Error: command not recognized

### ISSUE THREAD

**Issue by stloewen** [vanhauser-thc/thc-hydra#674]
When smtp-enum encounters an
`Error: command not recognized` (which often happens when using EXPN) it should quit.

There is some uncommented code mentioning this error alread:
https://github.com/vanhauser-thc/thc-hydra/blob/b375bbc33264f3cedd0b75096a663c36c88b3770/hydra-smtp-enum.c#L122

However, I tried uncommenting this and adding
```c
free(buf);
return 3;
```

Which only led to hydra terminating the current thread and retrying with another thread. Instead the enumeration should stop completely. If you could tell me how to signal the parent process to exit I'd gladly prepare a PR.

**Comment by vanhauser-thc** [comment]
can you recompiled from github and try the change? I cant find a mail server that supports it :)

**Comment by stloewen** [comment]
I only have a mailserver available that has EXPN disabled. And with that it works as expected:

```
$ ./hydra smtp-enum://10.1.1.1/expn -L /usr/share/seclists/Usernames/xato-net-10-million-usernames.txt -I 
Hydra v9.3-dev (c) 2021 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2021-08-01 14:04:41
[WARNING] Restorefile (ignored ...) from a previous session found, to prevent overwriting, ./hydra.restore
[DATA] max 16 tasks per 1 server, overall 16 tasks, 8295455 login tries (l:8295455/p:1), ~518466 tries per task
[DATA] attacking smtp-enum://10.1.1.1:25/expn
[ERROR] command is disabled on the server (choose different method): 502 5.5.2 Error: command not recognized
[ERROR] command is disabled on the server (choose different method): 502 5.5.2 Error: command not recognized
1 of 1 target completed, 0 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2021-08-01 14:04:53

```

Thank you very much!
