### ISSUE TITLE
How do I uninstall Hydra?

### ISSUE THREAD

**Issue by dipanshparmar** [vanhauser-thc/thc-hydra#676]
I installed Hydra in Linux with the steps mentioned in the README. But now how do I uninstall it? There are no steps mentioned for uninstalling it, and there is also no rule in the makefile to uninstall it.

**Comment by engRaed** [comment]
sudo apt remove hydra

**Comment by vanhauser-thc** [comment]
if you update to the newest git you can do "make uninstall" after a ./configure
