### ISSUE TITLE
rdp false positive

### ISSUE THREAD

**Issue by coneycalifornia** [vanhauser-thc/thc-hydra#678]
1 of 1 target successfully completed, 1 valid password found                                                                                               
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2021-08-15 15:56:13     
password dont match.

**Comment by vanhauser-thc** [comment]
how can anyone expect to get help when giving no information?
how is it clear that the password is wrong? maybe the account is locked or the password has expired. if the password is really different then where is the debug output that shows what exactly the server sends etc.

**Comment by ShyftXero** [comment]
Unfortunately, that machine was taken offline to mitigate some other findings during the pentest so I can't fully reproduce / validate that the creds aren't working. 

I'm sure it's meaningless because there's no actual exchange of auth material at this point but I went ahead and did as you asked in case it was still up... fresh git clone and -dvv

```
hydra -l 'redacted_user' -p redacted_pass  rdp://xxx.xxx.xxx.xxx -dvv
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

[DEBUG] Output color flag is 1
Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2021-10-15 02:16:07
[DEBUG] cmdline: hydra -l redacted_user -p redacted_pass -dvv rdp://xxx.xxx.xxx.xxx 
[DEBUG] opt:6 argc:7 mod:rdp tgt:xxx.xxx.xxx.xxx port:0 misc:(null)
[WARNING] rdp servers often don't like many connections, use -t 1 or -t 4 to reduce the number of parallel connections and -W 1 or -W 3 to wait between connection to allow the server to recover
[INFO] Reduced number of tasks to 4 (rdp does not like many parallel connections)
[WARNING] the rdp module is experimental. Please test, report - and if possible, fix.
[WARNING] Restorefile (you have 10 seconds to abort... (use option -I to skip waiting)) from a previous session found, to prevent overwriting, ./hydra.restore
[VERBOSE] More tasks defined than login/pass pairs exist. Tasks reduced to 1
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking rdp://xxx.xxx.xxx.xxx:3389/
[VERBOSE] Resolving addresses ... 
[DEBUG] resolving xxx.xxx.xxx.xxx
[VERBOSE] resolving done
[DEBUG] Code: attack   Time: 1634278577
[DEBUG] Options: mode 0  ssl 0  restore 0  showAttempt 0  tasks 1  max_use 1 tnp 0  tpsal 0  tprl 0  exit_found 0  miscptr (null)  service rdp
[DEBUG] Brains: active 0  targets 1  finished 0  todo_all 1  todo 1  sent 0  found 0  countlogin 1  sizelogin 26  countpass 1  sizepass 6
[DEBUG] Target 0 - target xxx.xxx.xxx.xxx  ip xxx.xxx.xxx.xxx  login_no 0  pass_no 0  sent 0  pass_state 0  redo_state 0 (0 redos)  use_count 0  failed 0  done 0  fail_count 0  login_ptr redacted_user  pass_ptr redacted_pass
[DEBUG] Task 0 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Tasks 1 inactive  0 active
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 23271
[DEBUG] head_no 0 has pid 23271
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 0, redo_state 0, pass_state 0. loop_mode 0, curlogin (null), curpass (null), tlogin redacted_user, tpass redacted_pass, logincnt 0/1, passcnt 0/1, loop_cnt 1
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin redacted_user, cpass redacted_pass, tlogin -p, tpass redacted_pass, redo 0
[ATTEMPT] target xxx.xxx.xxx.xxx - login "redacted_user" - pass "redacted_pass" - 1 of 1 [child 0] (0/0)
[ERROR] freerdp: The connection failed to establish.
[DEBUG] pid 23271 called child_exit with code 1
[DEBUG] head_no[0] read C
[ATTEMPT-ERROR] target xxx.xxx.xxx.xxx - login "redacted_user" - pass "redacted_pass" - child 0 - 1 of 1
[DEBUG] hydra_increase_fail_count: 1 >= 0 => disable
[DEBUG] - will be retried at the end: ip xxx.xxx.xxx.xxx - login redacted_user - pass redacted_pass - child 0
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 23280
[DEBUG] head_no 0 has pid 23280
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 1, redo_state 0, pass_state 0. loop_mode 0, curlogin , curpass , tlogin -p, tpass redacted_pass, logincnt 1/1, passcnt 0/1, loop_cnt 1
[COMPLETED] target xxx.xxx.xxx.xxx - login "" - pass "" - child 0 - 1 of 2
[DEBUG] send_next_pair_mid done 0, pass_state 0, clogin , cpass , tlogin -p, tpass redacted_pass, redo 1
[DEBUG] Entering redo_state
[DEBUG] send_next_pair_init target 0, head 0, redo 1, redo_state 1, pass_state 0. loop_mode 0, curlogin , curpass , tlogin -p, tpass redacted_pass, logincnt 1/1, passcnt 0/1, loop_cnt 2
[COMPLETED] target xxx.xxx.xxx.xxx - login "" - pass "" - child 0 - 1 of 2
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin redacted_user, cpass redacted_pass, tlogin -p, tpass redacted_pass, redo 1
[REDO-ATTEMPT] target xxx.xxx.xxx.xxx - login "redacted_user" - pass "redacted_pass" - 2 of 2 [child 0] (1/1)
[ERROR] freerdp: The connection failed to establish.
[DEBUG] pid 23280 called child_exit with code 1
[DEBUG] head_no[0] read C
[ATTEMPT-ERROR] target xxx.xxx.xxx.xxx - login "redacted_user" - pass "redacted_pass" - child 0 - 2 of 1
[DEBUG] hydra_increase_fail_count: 2 >= 0 => disable
[DEBUG] - will be retried at the end: ip xxx.xxx.xxx.xxx - login redacted_user - pass redacted_pass - child 0
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 23290
[DEBUG] head_no 0 has pid 23290
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 2, redo_state 2, pass_state 0. loop_mode 0, curlogin , curpass , tlogin -p, tpass redacted_pass, logincnt 1/1, passcnt 0/1, loop_cnt 1
[COMPLETED] target xxx.xxx.xxx.xxx - login "" - pass "" - child 0 - 2 of 3
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin redacted_user, cpass redacted_pass, tlogin -p, tpass redacted_pass, redo 2
[REDO-ATTEMPT] target xxx.xxx.xxx.xxx - login "redacted_user" - pass "redacted_pass" - 3 of 3 [child 0] (2/2)
[ERROR] freerdp: The connection failed to establish.
[DEBUG] pid 23290 called child_exit with code 1
[DEBUG] head_no[0] read C
[ATTEMPT-ERROR] target xxx.xxx.xxx.xxx - login "redacted_user" - pass "redacted_pass" - child 0 - 3 of 1
[DEBUG] hydra_increase_fail_count: 3 >= 0 => disable
[DEBUG] - will be retried at the end: ip xxx.xxx.xxx.xxx - login redacted_user - pass redacted_pass - child 0
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 23303
[DEBUG] head_no 0 has pid 23303
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 3, redo_state 3, pass_state 0. loop_mode 0, curlogin , curpass , tlogin -p, tpass redacted_pass, logincnt 1/1, passcnt 0/1, loop_cnt 1
[COMPLETED] target xxx.xxx.xxx.xxx - login "" - pass "" - child 0 - 3 of 4
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin redacted_user, cpass redacted_pass, tlogin -p, tpass redacted_pass, redo 3
[REDO-ATTEMPT] target xxx.xxx.xxx.xxx - login "redacted_user" - pass "redacted_pass" - 4 of 4 [child 0] (3/3)
[STATUS] 4.00 tries/min, 4 tries in 00:01h, 1 to do in 00:01h, 1 active
[DEBUG] Code: STATUS   Time: 1634278637
[DEBUG] Options: mode 0  ssl 0  restore 0  showAttempt 0  tasks 1  max_use 1 tnp 0  tpsal 0  tprl 0  exit_found 0  miscptr (null)  service rdp
[DEBUG] Brains: active 1  targets 1  finished 0  todo_all 4  todo 1  sent 4  found 0  countlogin 1  sizelogin 26  countpass 1  sizepass 6
[DEBUG] Target 0 - target xxx.xxx.xxx.xxx  ip xxx.xxx.xxx.xxx  login_no 1  pass_no 0  sent 4  pass_state 0  redo_state 4 (3 redos)  use_count 1  failed 0  done 0  fail_count 3  login_ptr -p  pass_ptr redacted_pass
[DEBUG] Task 0 - pid 23303  active 1  redo 0  current_login_ptr redacted_user  current_pass_ptr redacted_pass
[DEBUG] Tasks 0 inactive  1 active
[ERROR] freerdp: The connection failed to establish.
[DEBUG] pid 23303 called child_exit with code 1
[DEBUG] head_no[0] read C
[ATTEMPT-ERROR] target xxx.xxx.xxx.xxx - login "redacted_user" - pass "redacted_pass" - child 0 - 4 of 1
[DEBUG] hydra_increase_fail_count: 4 >= 0 => disable
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 23315
[DEBUG] head_no 0 has pid 23315
[DEBUG] head_no[0] read n
[STATUS] attack finished for xxx.xxx.xxx.xxx (waiting for children to complete tests)
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] all targets done and all heads finished
[DEBUG] while loop left with 1
1 of 1 target completed, 0 valid password found
[DEBUG] killing all remaining children now that might be stuck
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2021-10-15 02:17:19
```

Like I said, the machine is INOP so impossible to reproduce... Sorry for the hassle.

**Comment by ShyftXero** [comment]
I did try it at a later time with the `ecorp\\jsmith` just in case but I think the machine was already offline at that point.

**Comment by ShyftXero** [comment]
idk man. computers. the `\\` was to escape the backslash. `/` was doing something weird too. Maybe the same?  I don't recall as it was a long time ago now.

**Comment by wadethrillson** [comment]
i have the same issue. was trying to brute rdp with hydra in my home lab. 

it gave me false positive: the password for admin account was password1234 and it gives something else; hence false positive.

tried another tool (crowbar) it gives the same false positive as well. might be related to rdp idk. 


`hydra -t 1 -dvv -f -l administrator -P /opt/rockyou.txt rdp://192.168.44.124 -s 3389 
Hydra v9.5 (c) 2023 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

[DEBUG] Output color flag is 1
Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2023-08-24 15:23:26
[DEBUG] cmdline: hydra -t 1 -dvv -f -l administrator -P /opt/rockyou.txt -s 3389 rdp://192.168.44.124 
[DEBUG] opt:11 argc:12 mod:rdp tgt:192.168.44.124 port:3389 misc:(null)
[WARNING] the rdp module is experimental. Please test, report - and if possible, fix.
[WARNING] Restorefile (you have 10 seconds to abort... (use option -I to skip waiting)) from a previous session found, to prevent overwriting, ./hydra.restore
[DATA] max 1 task per 1 server, overall 1 task, 14344126 login tries (l:1/p:14344126), ~14344126 tries per task
[DATA] attacking rdp://192.168.44.124:3389/
[VERBOSE] Resolving addresses ... 
[DEBUG] resolving 192.168.44.124
[VERBOSE] resolving done
[DEBUG] Code: attack   Time: 1692879817
[DEBUG] Options: mode 1  ssl 0  restore 0  showAttempt 0  tasks 1  max_use 1 tnp 0  tpsal 0  tprl 0  exit_found 1  miscptr (null)  service rdp
[DEBUG] Brains: active 0  targets 1  finished 0  todo_all 14344126  todo 14344126  sent 0  found 0  countlogin 1  sizelogin 14  countpass 14344126  sizepass 139901242
[DEBUG] Target 0 - target 192.168.44.124  ip 192.168.44.124  login_no 0  pass_no 0  sent 0  pass_state 0  redo_state 0 (0 redos)  use_count 0  failed 0  done 0  fail_count 0  login_ptr administrator  pass_ptr 123hfjdk147
[DEBUG] Task 0 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Tasks 1 inactive  0 active
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 176478
[DEBUG] head_no 0 has pid 176478
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 0, redo_state 0, pass_state 0. loop_mode 0, curlogin (null), curpass (null), tlogin administrator, tpass 123hfjdk147, logincnt 0/1, passcnt 0/14344126, loop_cnt 1
[DEBUG] send_next_pair_mid done 1, pass_state 3, clogin administrator, cpass 123hfjdk147, tlogin administrator, tpass 1464688081, redo 0
[ATTEMPT] target 192.168.44.124 - login "administrator" - pass "123hfjdk147" - 1 of 14344126 [child 0] (0/0)
[DEBUG] rdp reported 00000000
[DEBUG] head_no[0] read F
[3389][rdp] host: 192.168.44.124   login: administrator   password: 123hfjdk147
[STATUS] attack finished for 192.168.44.124 (valid pair found)
[DEBUG] head_no 0, kill 1, fail 2
[DEBUG] all targets done and all heads finished
[DEBUG] while loop left with 1
1 of 1 target successfully completed, 1 valid password found
[DEBUG] killing all remaining children now that might be stuck
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2023-08-24 15:23:38
`

**Comment by wadethrillson** [comment]
as i stated earlier; i checked the hydra_rdp.c file and it states it works on

win 7, 10. so this could be the issue here for MY CASE.

my lab machine is windows xp.

checked the crowbar source code it also initiates the xfreerdp +auth-only option where hydra also uses freerdp library and also checks

```
  if (password[0] == 0)
    instance->settings->AuthenticationOnly = FALSE;
  else
    instance->settings->AuthenticationOnly = TRUE;
```

when i try to login with terminal using xfreerdp to my xp machine with the given parameters ( +auth-only and /cert:ignore) it gives the same result with a false password.

both debug output is exactly same. will try on win7 later.

xp is already lost its vendor support. imo using ncrack with slow mode will solve our problems here.
