### ISSUE TITLE
Postgres - Default DB is set to 'template1'.  There is no flag to specify otherwise.

### ISSUE THREAD

**Issue by Pusher91** [vanhauser-thc/thc-hydra#682]
When brute forcing postgres it uses dbname = 'template1' as part of the login attempt.  I do not see any way to disable specifying a database name or changing the database name

`
└─$ hydra -C /usr/share/seclists/Passwords/Default-Credentials/postgres-betterdefaultpasslist.txt postgres://192.168.159.47 -Vvv -I -s 5437                      255 ⨯
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2021-08-21 14:28:51
[WARNING] Restorefile (ignored ...) from a previous session found, to prevent overwriting, ./hydra.restore
[DATA] max 8 tasks per 1 server, overall 8 tasks, 8 login tries, ~1 try per task
[DATA] attacking postgres://192.168.159.47:5437/
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[ATTEMPT] target 192.168.159.47 - login "dcmadmin" - pass "passw0rd" - 1 of 8 [child 0] (0/0)
[ATTEMPT] target 192.168.159.47 - login "postgres" - pass "amber" - 2 of 8 [child 1] (0/0)
[ATTEMPT] target 192.168.159.47 - login "postgres" - pass "postgres" - 3 of 8 [child 2] (0/0)
[ATTEMPT] target 192.168.159.47 - login "postgres" - pass "password" - 4 of 8 [child 3] (0/0)
[ATTEMPT] target 192.168.159.47 - login "postgres" - pass "admin" - 5 of 8 [child 4] (0/0)
[ATTEMPT] target 192.168.159.47 - login "admin" - pass "admin" - 6 of 8 [child 5] (0/0)
[ATTEMPT] target 192.168.159.47 - login "admin" - pass "password" - 7 of 8 [child 6] (0/0)
[ATTEMPT] target 192.168.159.47 - login "postgres" - pass "123" - 8 of 8 [child 7] (0/0)
connection string: host = '192.168.159.47' dbname = 'template1' user = 'dcmadmin' password = 'passw0rd' 
connection string: host = '192.168.159.47' dbname = 'template1' user = 'postgres' password = 'postgres' 
connection string: host = '192.168.159.47' dbname = 'template1' user = 'postgres' password = 'amber' 
connection string: host = '192.168.159.47' dbname = 'template1' user = 'postgres' password = 'admin' 
connection string: host = '192.168.159.47' dbname = 'template1' user = 'admin' password = 'admin' 
connection string: host = '192.168.159.47' dbname = 'template1' user = 'postgres' password = 'password' 
connection string: host = '192.168.159.47' dbname = 'template1' user = 'postgres' password = '123' 
connection string: host = '192.168.159.47' dbname = 'template1' user = 'admin' password = 'password' `

**Comment by vanhauser-thc** [comment]
```
$ hydra -U postgres
Hydra v9.3-dev (c) 2021 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2021-08-23 12:27:36

Help for module postgres:
============================================================================
Module postgres is optionally taking the database to attack, default is "template1"
```
