### ISSUE TITLE
-r (rain) command removed in Hydra + Truth and/or Explanation on the removal and/or how it functions like a random/shuffling option

### ISSUE THREAD

**Issue by feruenzerujkun** [vanhauser-thc/thc-hydra#683]
" Warning: the option -r has been removed. " - during a test

hydra -x -h ⬇⬇⬇⬇⬇
" Hydra bruteforce password generation option usage:

  -x MIN:MAX:CHARSET

     MIN     is the minimum number of characters in the password
     MAX     is the maximum number of characters in the password
     CHARSET is a specification of the characters to use in the generation
             valid CHARSET values are: 'a' for lowercase letters,
             'A' for uppercase letters, '1' for numbers, and for all others,
             just add their real representation.
  -y         disable the use of the above letters as placeholders
  -r         use a shuffling method called 'rain' to try to break
             the linearity of the bruteforce (REMOVED BEFORE/AFTER TRYING OUT)
Examples:
   -x 3:5:a  generate passwords from length 3 to 5 with all lowercase letters
   -x 5:8:A1 generate passwords from length 5 to 8 with uppercase and numbers (tried, also gives user a responsive error message)
   -x 1:3:/  generate passwords from length 1 to 3 containing only slashes
   -x 5:5:/%,.-  generate passwords with length 5 which consists only of /%,.-
   -x 3:5:aA1 -y generate passwords from length 3 to 5 with a, A and 1 only

The bruteforce mode was made by Jan Dlabal, http://houbysoft.com/bfg/ "
⬆⬆⬆⬆⬆

Has anyone on this Github repository (vanhauser-htc / thc-hydra) have any idea on how "-r" (the rain) command for -x command works or what it functions.

Therefore it can function like a shuffling/randomization option rather? :-\

**Comment by vanhauser-thc** [comment]
that feature was removed, that text was forgotten to be removed as well :)
you can do it yourself by creating your own wordlist e.g. with tools that generate the passwords you want and another tool to shuffle that.
