### ISSUE TITLE
Unable to brute force the ssh service in batches

### ISSUE THREAD

**Issue by Vulner-6** [vanhauser-thc/thc-hydra#688]
**IMPORTANT**
This is just for reporting *BUGS* not help on how to hack, how to use hydra, command line options or how to get it compiled. Please search for help via search engines. Issues asking for this here will be closed.

**Describe the bug**
I get an error message when I brute force the ssh service in batches
![image](https://user-images.githubusercontent.com/56946543/138556555-ee4ba06b-185a-4aea-bb40-9283bbaca33e.png)
The command I used is `hydra -L /home/kali/Desktop/BruteForce/ssh/ssh_user_25.txt -P /home/kali/Desktop/BruteForce/ssh/ssh_pwd_205.txt  -f -V -M /home/kali/Desktop/BruteForce/test.txt ssh
`
When I brute force these ips that cannot be brute-forced, I can brute-force them separately.
![image](https://user-images.githubusercontent.com/56946543/138556736-e849a3c9-50ec-4281-ace1-fa54644a7d8c.png)

So, is this a bug？

**Comment by vanhauser-thc** [comment]
@Vulner-6 I just tried with with 10 entries in the -M file and as well as in the -L and -P files. I cannot reproduce the issue. which libssh version are you using?

**Comment by Vulner-6** [comment]
@vanhauser-thc hello! Thank you for your reply! I use 2021.3_Kali's own hydra
![image](https://user-images.githubusercontent.com/56946543/140704400-1970c37a-b375-437c-9941-441788f5f565.png)

the hydra version is v9.1. but  i don't know the libssh version in Kali . I only know the version of Kali . the version of  kali is 2021.3 

you can test these ip addresses in 2021.3_Kali linux :
103.231.252.170:22
45.43.55.188:22
156.255.240.171:22
202.146.216.245:22
18.163.29.69:22
103.148.202.69:22
18.166.252.49:22
18.166.252.57:22
154.210.211.140:22
45.43.55.192:22
154.210.157.36:22
119.28.66.80:22
23.99.121.214:22
156.255.248.130:22
154.210.211.139:22
103.149.26.112:22
156.255.248.60:22
103.195.7.172:22
18.167.102.132:22
182.153.115.145:22
156.234.126.113:22
202.146.216.220:22
156.255.247.179:22
202.146.216.250:22
18.163.233.111:22
18.163.134.244:22
42.2.118.203:22
103.94.103.29:22
154.204.190.120:22
210.6.86.102:22
45.120.76.127:22
183.179.185.14:22
156.255.248.64:22
156.255.248.143:22
154.91.197.47:22
18.167.102.196:22
154.206.100.124:22
156.255.248.113:22
18.166.252.59:22
156.234.75.251:22
154.210.211.2:22
156.255.248.43:22
156.255.240.240:22
103.16.229.111:22
156.225.168.206:22
156.255.247.190:22
156.255.240.236:22
13.94.25.145:22
154.206.93.126:22
156.234.75.213:22
103.149.163.1:22
207.46.150.205:22
119.28.66.43:22
103.231.252.11:22

**Comment by vanhauser-thc** [comment]
you are not using a current version of hydra and what you are doing is illegal

**Comment by alvosec** [comment]
Go:

`sudo apt show libssh-dev`

in my case it is: Version: 0.9.5-1+deb11u1
