### ISSUE TITLE
IpV6 Error

### ISSUE THREAD

**Issue by MajorRaccoon** [vanhauser-thc/thc-hydra#690]
When starting the hydra with command: ```hydra -l root -p root -6 -M finalaa.txt ssh``` it starts saying something like: ```[ERROR] could not resolve address: 2a03```
finalaa.txt contains ipv6 address in [] brackets each.
1. Create text file with ipv6 addresses inside in brackets every.
2. Start hydra with ```hydra -l root -p root -6 -M finalaa.txt ssh```

**Expected behavior**
Hydra should start bruting ip address from list.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-88-generic x86_64)
 - hydra version: Last from apt.

**Comment by MajorRaccoon** [comment]
![Screenshot_2021-10-31-16-08-05-848_com sonelli juicessh](https://user-images.githubusercontent.com/68560081/139585168-29b2c5ba-4278-48f7-9341-ec5562fb90ca.jpg)

**Comment by vanhauser-thc** [comment]
thanks, confirmed and fixed it!

**Comment by MajorRaccoon** [comment]
Yeah it starts now, but prints ```[ERROR] could not connect to ssh://[2a01:a700:48af::1:9]:22 - No route to host`` for all hosts, maybe that's because it is running from wrong interface?
Masscan, nmap, even python script do work with ipv6 on my system, so i believe smth is wrong in hydra?

**Comment by vanhauser-thc** [comment]
I tried it and it worked fine for me. try to switch from ssh to http to see if it is maybe your libssh.

**Comment by MajorRaccoon** [comment]
got it

**Comment by MajorRaccoon** [comment]
Oh, there was my fault, works perfect, thanks!

**Comment by Mrship12138** [comment]
sorry i still cant solve it

**Comment by Mrship12138** [comment]
hydra -6 -L Ussh -P Pssh [fe80::20c:29ff:fedf:6991] ssh 
is it wrong?

**Comment by vanhauser-thc** [comment]
> hydra -6 -L Ussh -P Pssh [fe80::20c:29ff:fedf:6991] ssh is it wrong?

not for fe80:: addresses. there you must specify also the interface, e.g.
`hydra -6 -l user -p pass 'ssh://[fe80::20c:29ff:fedf:6991]%wlan0'`
