### ISSUE TITLE
Why is the 404 returned by the get request considered as a successful guess?

### ISSUE THREAD

**Issue by leimingyong** [vanhauser-thc/thc-hydra#692]
Around line 300 of the file hydra-http.c, 404 and 403 are recognized as successful password guessing When judging the return value of ptr.
![1636625625(1)](https://user-images.githubusercontent.com/32924093/141280349-472301a7-f0d6-47a3-9c3f-a8e1b2acf2d5.png)

This will cause false report when cracking a URL that does not exist.
I don’t quite understand, can anyone answer my doubts?Thanks.

**Comment by vanhauser-thc** [comment]
well if you crack an URL that does not exist - that is the mistake. you know you have the correct url if you get a 401.

**Comment by leimingyong** [comment]
Thank you for the reply!
So is there a case where the guess is correct but a 404 is returned? Does the logic here need to be modified?

**Comment by vanhauser-thc** [comment]
nope the logic is fine, because if there is an auth but no directory the 404 still tells you the credentials are correct
