### ISSUE TITLE
Hydra Termux

### ISSUE THREAD

**Issue by JyanJohn** [vanhauser-thc/thc-hydra#694]
Hello, make install is not working in Termux

**Comment by vanhauser-thc** [comment]
according to my crystal ball you were not wearing the correct number of rings on your left hand, that is why I could not work ... ;)

care to make a useful issue report?

**Comment by JyanJohn** [comment]
okok

**Comment by JyanJohn** [comment]
I fixed make install by installing missing stuff. And another problem surfaces, it works but I cant attack ssh ftp and smb there are a lot of errors.

**Comment by JyanJohn** [comment]
im using Hydra for [this](https://github.com/JyanJohn/PisoWifi-BruteForce)

**Comment by vanhauser-thc** [comment]
and still this is far away from being a good issue description.
what is the output of ./configure?
and how is it that ftp is not working? (this is basically impossible)

**Comment by JyanJohn** [comment]
![Screenshot_20211126_173310](https://user-images.githubusercontent.com/86553521/143559155-1a2e355b-ea2e-4a4e-a463-44a9fd23fe54.jpg)

that is the error....

**Comment by JyanJohn** [comment]
Hold on... let me install a compiler

**Comment by GitHubNeko** [comment]
> 您好，在 Termux 中 make install 不起作用

It is not recommended that you run hydra in Termux because it does not have enough dependencies. I suggest you run hydra in proot or chroot

**Comment by JyanJohn** [comment]
![Screenshot_20211212_150454](https://user-images.githubusercontent.com/86553521/145703677-4023199f-f2fe-4cf7-a20e-ca2949e9ac11.jpg)

It shows this error
