### ISSUE TITLE
[ERROR] Compiled without LIBMONGODB support, module not available!

### ISSUE THREAD

**Issue by mehrdad-khojastefar** [vanhauser-thc/thc-hydra#697]
**Describe the bug**
The problem is even though I installed libmongoc and recompiled the hydra it can't connect to my local mongodb server and throwing this error

1. Installed libmongoc using `apt-get install libmongoc-1.0-0`
2. Recompiled the hydra `./configure && make && make install`
3. ./hydra -l root -p root mongodb://localhost:27017

**Expected behavior**
Connect to my database and check the username and password I have provided

**Screenshots**
![image](https://user-images.githubusercontent.com/74628421/145074650-a70bea33-5a69-468a-ae95-99efcd8d9c8c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS 
 - hydra v9.2 [latest]

**Comment by vanhauser-thc** [comment]
you need to install the -dev variant of the package (same with all libs you want to build with a program you compile)
