### ISSUE TITLE
Colon in "S" or "F" statement - 100% CPU or ERROR

### ISSUE THREAD

**Issue by Green360** [vanhauser-thc/thc-hydra#700]
I am trying to brute force a login with the http-post-form option. In case of failure the response content is empty and the server sends me back to the login site. The response header looks like this:

```
HTTP/1.1 302 Moved Temporarily
Server: nginx (Ubuntu)
Date: Wed, 15 Dec 2021 19:37:00 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Location: login.php
Content-Length: 0
```
As far as I am aware, I cannot filter for content on the target of the redirection. There it would show "Wrong username/password".
Therefore, I attempt to filter for "Location: login.php" as I was hoping that it might differ in a successful attempt.
My command looks like this:

`hydra-9.1 -l admin -P /usr/share/wordlists/rockyou.txt www.example.com http-post-form "/login.php:username=^USER^&password=^PASS^:F=Location\: login.php" -V`

Unfortunately, whenever I use an escaped colon in the "S" or "F" statement it just causes the CPU to go up to 100% and Hydra hangs. The output is the following:
```
...
[INFORMATION] escape sequence \: detected in module option, no parameter verification is performed.
[DATA] max 16 tasks per 1 server, overall 16 tasks, 14344399 login tries (l:1/p:14344399), ~896525 tries per task
[DATA] attacking http-post-form://www.example.com:80/login.php:username=^USER^&password=^PASS^:F=Location\: login.php
[ATTEMPT] target www.example.com - login "admin" - pass "123456" - 1 of 14344399 [child 0] (0/0)
...
[ATTEMPT] target www.example.com - login "admin" - pass "jessica" - 16 of 14344399 [child 15] (0/0)
```
I then downloaded the latest version 9.2 and tried it again:

`hydra-9.2 -l admin -P /usr/share/wordlists/rockyou.txt www.example.com http-post-form "/login.php:username=^USER^&password=^PASS^:F=Location\: login.php" -V`
```
[INFORMATION] escape sequence \: detected in module option, no parameter verification is performed.
[WARNING] Restorefile (you have 10 seconds to abort... (use option -I to skip waiting)) from a previous session found, to prevent overwriting, ./hydra.restore
[DATA] max 16 tasks per 1 server, overall 16 tasks, 14344399 login tries (l:1/p:14344399), ~896525 tries per task
[DATA] attacking http-post-form://www.example.com:80/login.php:username=^USER^&password=^PASS^:F=Location\: login.php
[ERROR] optional parameters must have the format X=value:  login.php
```
What am I missing? 
Is it possible to filter for response headers in "S" and "F"?
If so, how do I treat the colon?

**Comment by vanhauser-thc** [comment]
the latest is the repo state - not 9.2

as far as I remember colons cant be in the detection string.
you could match on "302 Moved Temporarily" if successful auth will not do a 302. or better, you match on a success criteria (if you know how that looks), which will also result in less false positives. you can match on " login.php" otherwise.

**Comment by Green360** [comment]
Thanks for the fast response! I thought that I saw people using the colon but then I was wrong. Good to know that it is not possible. This means I can stop trying to make it work. In certain cases it would still be nice to have I guess.
