### ISSUE TITLE
is thereany support for windows onhow to build it

### ISSUE THREAD

**Issue by nityanand86876** [vanhauser-thc/thc-hydra#706]
**IMPORTANT**
Please note that hydra is still maintained however not actively developed. If you would like to see specific feature here it it recommended implement it yourself and send a pull request - or look for someone to do that for you :-)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vanhauser-thc** [comment]
you have to install cygwin (www.cygin.com)
