### ISSUE TITLE
Unable to make install with Hydra

### ISSUE THREAD

**Issue by jeremygithub** [vanhauser-thc/thc-hydra#71]
I have successfully installed Cygwin in Windows 7. And when I try to install Hyrda, I got this:

```
Jeremy@CodeName ~
$ cd c:\hydra

Jeremy@CodeName /cygdrive/c/hydra
$ ./configure
./configure: line 5: $'\r': command not found
./configure: line 130: syntax error near unexpected token `$'do\r''
'/configure: line 130: `for i in $INCDIRS; do

Jeremy@CodeName /cygdrive/c/hydra
$
```

What should I do?

**Comment by jeremygithub** [comment]
I figure it out. I should not use the git repo files, but the compiled one.
Now I got this error:

```
now type "make"

Jeremy@CodeName /cygdrive/c/hydra
$ make && make install
-bash: make: command not found
```

I have installed all files listed on the Cygwin, what did I missed?

**Comment by vanhauser-thc** [comment]
you did not install make (and very likely other stuff. installed gcc?, etc.)
