### ISSUE TITLE
[BUG] Proxy + Destination Port => Duplicated port in HTTP GET Request

### ISSUE THREAD

**Issue by kai2s** [vanhauser-thc/thc-hydra#710]
Hello,

**Bug Description**
The generated HTTP GET request contains the value of the destination port twice in it when using HYDRA_PROXY_HTTP. This works without a problem when the proxy is not used.

**How To Reproduce**
`$ HYDRA_PROXY_HTTP=http://127.0.0.1:8080 hydra -C /usr/share/seclists/Passwords/Default-Credentials/tomcat-betterdefaultpasslist.txt http-get://10.129.1.110:8080/manager/html`

![image](https://user-images.githubusercontent.com/46607614/148845984-fc3b7fcf-3130-4345-a630-ea61bea7592b.png)

**Expected Behavior**
 Without the proxy enabled, the GET request is formed correctly:

`$ hydra -C /usr/share/seclists/Passwords/Default-Credentials/tomcat-betterdefaultpasslist.txt http-get://10.129.1.110:8080/manager/html`

![image](https://user-images.githubusercontent.com/46607614/148845648-03efffda-b9c8-486a-944e-9b59221d675a.png)

When removing the port from the destination service, the request is also well formed:

`$ HYDRA_PROXY_HTTP=http://127.0.0.1:8080 hydra -C /usr/share/seclists/Passwords/Default-Credentials/tomcat-betterdefaultpasslist.txt http-get://10.129.1.110/manager/html`

![image](https://user-images.githubusercontent.com/46607614/148846621-05ed7112-aa2c-4607-9827-4ab6b78ea454.png)

**System Info**
 - OS: Kali 2021.4
 - hydra version: 9.12

I tried to find out if I was using Hydra in a wrong way but I could not find anything about this situation so I prefer to open an issue and let you guys know in case it is a real bug.

Thanks for developing this tool!

**Comment by vanhauser-thc** [comment]
thank you for this good issue description. I pushed a fix, please test.

**Comment by kai2s** [comment]
My pleasure!

It seems that the original problem is fixed now, so that is great.

However I think there is a new bug. Even though I did not specify the `-f` option for exiting after a login/pass pair was found, it seems to exit anyways:

![image](https://user-images.githubusercontent.com/46607614/149010621-965f10d8-7fd2-4fb6-8200-58c751b8924b.png)

As you can see here, it did a bunch of attempts, but far from the total number of login/password combinations in the file:

![image](https://user-images.githubusercontent.com/46607614/149011016-13dc3ff9-dbfd-4bd5-b538-9aee62141c2e.png)

![image](https://user-images.githubusercontent.com/46607614/149011144-bb629e09-da82-49d6-9925-d4c596ad1cd2.png)

Thanks again!

**Comment by vanhauser-thc** [comment]
wow, that bug has been in there since ... 10 years maybe? :)
thank you, fixed.

**Comment by kai2s** [comment]
Hehehe, glad I could help you get rid of it! I tested it and all works fine for me. :)

Thanks and great work!

**Comment by vanhauser-thc** [comment]
thank you for reporting :)
