### ISSUE TITLE
http-form-post always sends a Cookie header

### ISSUE THREAD

**Issue by gblomqvist** [vanhauser-thc/thc-hydra#713]
The `http-form-post` module appears to always send a Cookie header, even when the pre-request doesn't set any cookie and regardless of whether the (g|G) option is used. I suspect this is a bug since it, at least for me, seems unintuitive. If you specify a cookie header using the "h" option, two cookie headers will be sent.

As a side issue, the "h" option is said to "add the user-defined header at the end regardless it's already being sent by Hydra or not", but in my case it's not added to the end (unless the header order is opposite to what I believe). Or does "end" perhaps refer to the end of the user-defined headers?

**To Reproduce**
`hydra -l user -p pass  "http-form-post://localhost/:^USER^, ^PASS^:test:g=1:h=Cookie\: mycookie=val"`

Request made:
```
POST http://localhost:80/ HTTP/1.0
Cookie: mycookie=val
Host: localhost
User-Agent: Mozilla/5.0 (Hydra Proxy)
Content-Length: 10
Content-Type: application/x-www-form-urlencoded
Cookie: 

user, pass
```

**Expected behavior**
Only _one_ cookie header at the _end_ of all headers, i.e:
```
POST http://localhost:80/ HTTP/1.0
Host: localhost
User-Agent: Mozilla/5.0 (Hydra Proxy)
Content-Length: 10
Content-Type: application/x-www-form-urlencoded
Cookie: mycookie=val

user, pass
```

**Desktop:**
 - Hydra v9.3-dev (current GitHub state)

**Comment by vanhauser-thc** [comment]
thanks.
fixed, please test.
note that if there are cookies set from the server there will be 2 cookie headers, this is how it should be. the bug is though that there should not be an empty header.

**Comment by gblomqvist** [comment]
It seems to work, thanks!

Note however that it's still possible to send an empty header name and/or value by specifying the name and/or value as whitespace. E.g., running:
```sh
hydra -l user -p pass "http-form-post://localhost/:^USER^, ^PASS^:test:g=1:h= \: "
```
yields the request:
```http
POST http://localhost:80/ HTTP/1.0
: 
Host: localhost
User-Agent: Mozilla/5.0 (Hydra Proxy)
Content-Length: 10
Content-Type: application/x-www-form-urlencoded
```

Since the user is doing something wrong in this case, it's perhaps not an issue.

**Comment by vanhauser-thc** [comment]
that is fine. if a user wants such a broken request then this is what happens :)
