### ISSUE TITLE
Hydra ssh multiple targets in file not works - Library not initilized

### ISSUE THREAD

**Issue by fernando535** [vanhauser-thc/thc-hydra#714]
Define file targets3.txt:

192.168.0.20:22
1.1.1.1:22
2.2.2.2:22
3.3.3.3:22
4.4.4.4:22

hydra -l root -M targets3.txt -P test.txt -o pass.txt -f -K -t 4 ssh
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-01-16 00:32:34
[DATA] max 4 tasks per 5 servers, overall 20 tasks, 4 login tries (l:1/p:4), ~1 try per task
[DATA] attacking ssh://(5 targets):22/
[ERROR] could not connect to ssh://1.1.1.1:22 - Library not initialized.
[ERROR] could not connect to ssh://2.2.2.2:22 - Library not initialized.
[ERROR] could not connect to ssh://3.3.3.3:22 - Library not initialized.
[ERROR] could not connect to ssh://4.4.4.4:22 - Library not initialized.
1 of 5 targets completed, 0 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2022-01-16 00:32:36

**Comment by vanhauser-thc** [comment]
try the current version from github (compile!) and if the issue persists reopen the issue. tx
