### ISSUE TITLE
hydra no stop when server or port is down

### ISSUE THREAD

**Issue by fernando535** [vanhauser-thc/thc-hydra#715]
Hi, before anything, congratulations for hydra, it works very well.

I've tested ssh brute force with passfile, and when target server is down or  the port is unreachable, hydra not stop, continue probe with the follow words of the passfile.

This makes it forward with the words in the password file and therefore it is trying words and forward when the server/port is down.

Do you have any solution?

**Comment by vanhauser-thc** [comment]
you should see something like this:
```
[ERROR] could not connect to ssh://1.1.1.1:22 - Timeout connecting to 1.1.1.1
```
compile from the repository and try again

**Comment by fernando535** [comment]
The ip 1.1.1.1 is a example.

ok, I try with compile from source.

**Comment by fernando535** [comment]
I've install hydra from source code. The version is Hydra v9.3-dev

The problem persist. With this command for testing brute force ssh in vm vagrant with ubuntu 20.04:

hydra -I localhost -s 22 -l root -P /home/vagrant/rockyou.txt -f ssh -t 5 -V

Stop ssh, and hydra continue try password when service ssh is down...

**Comment by vanhauser-thc** [comment]
hmm yes there seem to be a bug. I pushed a fix.

**Comment by fernando535** [comment]
ok, many thanks.


it is already corrected? for trying again by pulling the code and recompiling it. Thanks again

**Comment by vanhauser-thc** [comment]
yes, please test

**Comment by fernando535** [comment]
ok, test it:

[RE-ATTEMPT] target localhost - login "root" - pass "sunshine" - 30 of 14344402 [child 1] (0/3)
[ERROR] all children were disabled due too many connection errors
0 of 1 target completed, 0 valid password found
[INFO] Writing restore file because 2 server scans could not be completed
[ERROR] 1 target was disabled because of too many errors
[ERROR] 1 targets did not complete
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2022-01-19 19:39:16


Now, works well because not continue test password when service (ssh at now in my example) is down.

Now there is another problem, when the service is stopped (ssh in my test) and hydra stops, it does not leave a hydra.restore file to be able to continue testing for the password of the file where it was going and you have to start the passwords from the beginning, in my case ([RE-ATTEMPT] target localhost - login "root" - pass "sunshine" - 30 of 14344402 [child 1] (0/3)) ...

root@vagrant:/home/vagrant# hydra -R localhost -s 22 -l root -P /home/vagrant/rockyou.txt -f ssh -t 5 -V
Hydra v9.3-dev (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

[INFORMATION] reading restore file ./hydra.restore
[ERROR] restore file (./hydra.restore) not found - No such file or directory

**Comment by Jentility3051** [comment]
Please can I get an hydra virus python link to recover my hacked Gmail please

**Comment by vanhauser-thc** [comment]
ah damn. no time to fix this the next 2 weeks though

**Comment by vanhauser-thc** [comment]
pushed a fix. thanks for reporting.
