### ISSUE TITLE
crunch + hydra pipeline -P

### ISSUE THREAD

**Issue by fernando535** [vanhauser-thc/thc-hydra#716]
Hi! Is possible use crunch in realtime + hydra passed password generate on the air?

I try this:

hydra IP -s 22 -l root -P<(crunch 1 6 123456 --stdout) -f -t 5 ssh -V
crunch 1 4 123456 | hydra IP -s 22 -l root -f -t 5 ssh -V

But not generate pass.

Thanks in advanced.

**Comment by vanhauser-thc** [comment]
not possible. you have to create a file and supply the filename

**Comment by fernando535** [comment]
ok, many thanks for your work!!
