### ISSUE TITLE
Hydra script not running

### ISSUE THREAD

**Issue by Daveinator01** [vanhauser-thc/thc-hydra#717]
When i try and run this script, it doesn’t run and just responds with (without quotation marks)

"Hydra v9.2 (c) 2021 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-01-23 20:59:08
Syntax: hydra [[[-l LOGIN|-L FILE] [-p PASS|-P FILE]] | [-C FILE]] [-e nsr] [-o FILE] [-t TASKS] [-M FILE [-T TASKS]] [-w TIME] [-W TIME] [-f] [-s PORT] [-x MIN:MAX:CHARSET] [-c TIME] [-ISOuvVd46] [-m MODULE_OPT] [service://server[:PORT][/OPT]]

Options:
  -l LOGIN or -L FILE  login with LOGIN name, or load several logins from FILE
  -p PASS  or -P FILE  try password PASS, or load several passwords from FILE
  -C FILE   colon separated "login:pass" format, instead of -L/-P options
  -M FILE   list of servers to attack, one entry per line, ':' to specify port
  -t TASKS  run TASKS number of connects in parallel per target (default: 16)
  -U        service module usage details
  -m OPT    options specific for a module, see -U output for information
  -h        more command line options (COMPLETE HELP)
  server    the target: DNS, IP or 192.168.0.0/24 (this OR the -M option)
  service   the service to crack (see below for supported protocols)
  OPT       some service modules support additional input (-U for module help)

Supported services: adam6500 asterisk cisco cisco-enable cvs ftp[s] http[s]-{head|get|post} http[s]-{get|post}-form http-proxy http-proxy-urlenum icq imap[s] irc ldap2[s] ldap3[-{cram|digest}md5][s] mssql mysql nntp oracle-listener oracle-sid pcanywhere pcnfs pop3[s] redis rexec rlogin rpcap rsh rtsp s7-300 sip smb smtp[s] smtp-enum snmp socks5 ssh sshkey teamspeak telnet[s] vmauthd vnc xmpp

Hydra is a tool to guess/crack valid login/password pairs.
Licensed under AGPL v3.0. The newest version is always available at;
https://github.com/vanhauser-thc/thc-hydra
Please don't use in military or secret service organizations, or for illegal
purposes. (This is a wish and non-binding - most such people do not care about
laws and ethics anyway - and tell themselves they are one of the good ones.)

Example:  hydra -l user -P passlist.txt ftp://192.168.0.1"

Which is strange as is the same thing I would get if I type in 'hydra' in my terminal.
I have tried using someones else's script with my own wordlist 
https://securitytutorials.co.uk/brute-forcing-passwords-with-thc-hydra/     (it's around the halfway point under webpage login)
And still comes up with the same message. I used BREW to install Hydra if that helps. It's not a bug with my terminal app as I can run SQLmap just fine.

Im running MacOS Big Sur 11.6
And I'm running Hydra 9.2_1

If you suggest I reinstall Hydra, let me know!
<img width="1440" alt="Bug" src="https://user-images.githubusercontent.com/98257745/150674157-80d69ee0-b658-4b6c-a86e-d6bb60ac694b.png">

**Comment by vanhauser-thc** [comment]
simply look at what hydra expect and what you write. you fuck up the order of parameters. last is target service etc. and before that options.
