### ISSUE TITLE
Openssl version test probably wrong

### ISSUE THREAD

**Issue by e2002e** [vanhauser-thc/thc-hydra#724]
HI, linker cannot find
'TLS_client_method'
'SSL_CTX_set_options'
'OPENSSL_init_ssl'
'OPENSSL_init_ssl'
'TLS_client_method'

This was tried with openssl 1.1.1l
I successfully compiled and linked with 1.0.1e 11 Feb 2013
Using The Android.mk with ndk-build.

**Comment by vanhauser-thc** [comment]
I am on 1.1.1m and dont have that issue. could a problem with android or something.

**Comment by e2002e** [comment]
Probably, I'm working coarsly and with an ndk from 2014.
Aufviedersehen

**Comment by e2002e** [comment]
I have a question: Do we not need libmysql anymore ? I see it's enabled by default (c file is present) but there is no linkage.
Also there is LIBMYSQLCLIENT pragma but even without it and without the lib it compiles without issues.
