### ISSUE TITLE
hydra use obsolete pcre3 library

### ISSUE THREAD

**Issue by epsilon77** [vanhauser-thc/thc-hydra#729]
Hello Van!

In Debian Hydra depends on the old PCRE3 library (libpcre3-dev). This has been end of life and it will be removed of Debian Archive soon. Could you check if is possible use the newer PCRE2 library in Hydra?

Please see this bug for more info: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000116

Really thank you very much!

**Comment by vanhauser-thc** [comment]
thanks for the heads up! I am very busy at the moment but should be able to take care of this somewhere between the next two weeks.

**Comment by vanhauser-thc** [comment]
can you please have a look?
c82e5d51c5595374e6b7801bfc84c26a497d8989

**Comment by epsilon77** [comment]
It works like a charm.. thanks! :)

**Comment by vanhauser-thc** [comment]
do you need me to make a new release?

**Comment by epsilon77** [comment]
Hi van!

not really. I just made a new revision with your patch.

Thanks!
