### ISSUE TITLE
can‘t find the password with hydra

### ISSUE THREAD

**Issue by qwerty64315** [vanhauser-thc/thc-hydra#736]
Hello,
I am a new Hydra user
I have an error each time I try to run it. I am trying to find the password of an ethernet connected router I have bought with the default password  disabled, and can't be reset with a factory reset.

For example ：
hydra -l root -P '/root/桌面/FastPwds.txt' ssh://183.129.189.61
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-03-21 16:04:03
[WARNING] Many SSH configurations limit the number of parallel tasks, it is recommended to reduce the tasks: use -t 4
[DATA] max 14 tasks per 1 server, overall 14 tasks, 14 login tries (l:1/p:14), ~1 try per task
[DATA] attacking ssh://183.129.189.61:22/
1 of 1 target completed, 0 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2022-03-21 16:04:06

Am I doing something obviously wrong?
Thanks

**Comment by vanhauser-thc** [comment]
there is no error. you specify a password file with 14 entries and none of them is correct, thats all

**Comment by qwerty64315** [comment]
thank you.
How can I modify it
