### ISSUE TITLE
Hydra password  not found

### ISSUE THREAD

**Issue by qwerty64315** [vanhauser-thc/thc-hydra#738]
Hello,
I am a new Hydra user
I entered the correct password into the dictionary, but I couldn't find it

For example ：
hydra -l root -P '/root/桌面/FastPwds.txt' ssh://183.129.189.61
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-03-21 16:04:03
[WARNING] Many SSH configurations limit the number of parallel tasks, it is recommended to reduce the tasks: use -t 4
[DATA] max 14 tasks per 1 server, overall 14 tasks, 14 login tries (l:1/p:14), ~1 try per task
[DATA] attacking ssh://183.129.189.61:22/
1 of 1 target completed, 0 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2022-03-21 16:04:06

What should I do to find the password

Thanks

**Comment by vanhauser-thc** [comment]
first you should update the newest version.
second with that little information there is nothing I can work with.
