### ISSUE TITLE
every password valid

### ISSUE THREAD

**Issue by extor656** [vanhauser-thc/thc-hydra#739]
Hello,
Just a simple hydra command
hydra -l admin -p admin http-get://195xxxxxxx:80
even for wrong password I am getting success password
[80][http-get] host: 19x.xxx.xx.xx5   login: admin2   password: admin2
1 of 1 target successfully completed, 1 valid password found

correct password in admin and admin. why i am getting valid password if it is not valid.

Please this is a question to many. Help will be really appreciated.
Thanks

**Comment by vanhauser-thc** [comment]
well likely that web page displays a form so you are using the wrong module ... http-form-post would be the right one then
