### ISSUE TITLE
google blocked hydra ?? 

### ISSUE THREAD

**Issue by th0m1** [vanhauser-thc/thc-hydra#74]
root@kali:~# hydra smtp.live.com smtp -l monemail@hotmail.com -s 587 -S -P wordlist.txt -v -V
...
[ATTEMPT] target smtp.live.com - login "monemail@hotmail.com" - pass "mypassword" - 1 of 1 [child 0]
Process 3555: Can not connect [unreachable], retrying (1 of 1 retries)
Process 3555: Can not connect [unreachable]
[ERROR] Child with pid 3555 terminating, can not connect
[VERBOSE] Retrying connection for child 0
...
[ERROR] Child with pid 3558 terminating, can not connect
[STATUS] attack finished for smtp.live.com (waiting for children to finish) ...
1 of 1 target completed, 0 valid passwords found

it's my password so i don't understand why i can't bruteforce my email . maybe google blocked hydra ? how can i fix this?

**Comment by harrim4n** [comment]
First of all, what you are doing is **illegal**. It *may* be your email-address, but those aren't your servers. Secondly, hotmail is owned by microsoft, not google.
Also, this is IMHO not a bug in hydra, just you being blocked by hotmail for trying to break into their services.

**Comment by vanhauser-thc** [comment]
all mayor webmail provder have anti login hacking mechanisms in place. as it should be.
