### ISSUE TITLE
cant use emails as logins

### ISSUE THREAD

**Issue by wigiglenekit** [vanhauser-thc/thc-hydra#740]
hydra-http-form.c
cant use emails as logins
@ from emails dont properly encodes into "%40" witch leads to incorrect processing by the server
also character escaping dosent work, harcoded "\%40" converts into "%2540"

please add in hydra-http-form.c on line 590

if (strchr(ret, '@') != NULL)
	ret = hydra_strrep(ret, "@", "%40");

**Comment by wigiglenekit** [comment]
Or im just stupid and there is no difference(

**Comment by vanhauser-thc** [comment]
why would a server require @ to be encoded? never seen this

**Comment by wigiglenekit** [comment]
Most likely I really made a mistake, I will do various tests and report back.

**Comment by wigiglenekit** [comment]
That was my mistake and I'm sorry for the time I wasted
