### ISSUE TITLE
I had a little trouble using Hydra for the first time

### ISSUE THREAD

**Issue by Salamanderss** [vanhauser-thc/thc-hydra#742]
**I'm trying to crack my router login password, which is ten digits,  I use the command:** C:\Users\HaNg\Downloads\thc-hydra-master>hydra -l admin -x 10:10:1 -f -v -o 456.txt 192.168.1.1 http-get /
**However, the results show that:**
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).
than I use the command:
hydra -l admin -x 4:5:1a. -f -v -o 456.txt 192.168.1.1 http-get /
**the results show that:**
C:\Users\HaNg\Downloads\thc-hydra-master>hydra -l admin -x 4:5:1a. -f -v -o 456.txt 192.168.1.1 http-get /
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-04-10 01:33:03
[DATA] max 16 tasks per 1 server, overall 16 tasks, 71218118 login tries (l:1/p:71218118), ~4451133 tries per task
[DATA] attacking http-get://192.168.1.1:80/
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[80][http-get] host: 192.168.1.1   login: admin   password: 0002**(this is wrong password)**
[STATUS] attack finished for 192.168.1.1 (valid pair found)
1 of 1 target successfully completed, 1 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2022-04-10 01:33:03

Running these commands, Hydra doesn't seem to crack, but reports an error or displays the wrong cracking results

**Comment by Salamanderss** [comment]
> **I'm trying to crack my router login password, which is ten digits, I use the command:** C:\Users\HaNg\Downloads\thc-hydra-master>hydra -l admin -x 10:10:1 -f -v -o 456.txt 192.168.1.1 http-get / **However, the results show that:** [ERROR] definition for password bruteforce (-x) generates more than 4 billion passwords - this is not a bug in the program, it is just not feasible to try so many attempts. Try a calculator how long that would take. duh.. than I use the command: hydra -l admin -x 4:5:1a. -f -v -o 456.txt 192.168.1.1 http-get / **the results show that:** C:\Users\HaNg\Downloads\thc-hydra-master>hydra -l admin -x 4:5:1a. -f -v -o 456.txt 192.168.1.1 http-get / Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).
> 
> Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-04-10 01:33:03 [DATA] max 16 tasks per 1 server, overall 16 tasks, 71218118 login tries (l:1/p:71218118), ~4451133 tries per task [DATA] attacking http-get://192.168.1.1:80/ [VERBOSE] Resolving addresses ... [VERBOSE] resolving done [80][http-get] host: 192.168.1.1 login: admin password: 0002**(this is wrong password)** [STATUS] attack finished for 192.168.1.1 (valid pair found) 1 of 1 target successfully completed, 1 valid password found Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2022-04-10 01:33:03
> 
> Running these commands, Hydra doesn't seem to crack, but reports an error or displays the wrong cracking results

**Comment by Salamanderss** [comment]
The error of the first command prompt is:[ERROR] definition for password bruteforce (-x) generates more than 4 billion passwords - this is not a bug in the program, it is just not feasible to try so many attempts. Try a calculator how long that would take. duh.

**Comment by vanhauser-thc** [comment]
well do you understand the error message?
