### ISSUE TITLE
[ERROR] all children were disabled due too many connection errors

### ISSUE THREAD

**Issue by LouisElPerk** [vanhauser-thc/thc-hydra#747]
i use 
sudo hydra -l kalilouis -P pass3.txt ftp://IP

and

Hydra v9.3 (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-04-18 01:04:44
[DATA] max 16 tasks per 1 server, overall 16 tasks, 330000 login tries (l:1/p:330000), ~20625 tries per task
[DATA] attacking ftp://IP:21/
[ERROR] all children were disabled due too many connection errors
0 of 1 target completed, 0 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2022-04-18 01:04:47

**Comment by vanhauser-thc** [comment]
and your question is?

**Comment by LouisElPerk** [comment]
I created a file with crunch and there is the key.
then try to use that file together with Hydra to attack my own Kalilunux machine and I get that error.
I have searched for this error on web pages and I can't find it.
I was wondering if anyone here knew what I'm doing wrong?

**Comment by LouisElPerk** [comment]
I'm sorry, I just saw that this is just to report failures and bugs. I'll try to find the solution to the error elsewhere.

**Comment by ryanckulp** [comment]
hi @LouisElPerk , i also installed today (v9.3) and had the same issue. adding the `-S` flag fixed it for me.

during my initial debugging i added `-vV` flags as well, by the way, to determine exactly when it was failing (after 32 attempts if i included `-t 32`, after 16 attempts if i included `-t 16`, and so on).

with the `-S` flag it keeps flying through my password list; in my case i'm using the popular `rockyou.txt` library.

**Comment by LouisElPerk** [comment]
hi @ryanckulp thanks for the support, can you send me an example? i'm trying but it doesn't work

**Comment by Joyfernandas** [comment]
i also have the same problem to solve this error ([ERROR] all children were disabled due too many connection errors
)

**Comment by Lostcath** [comment]
> hi @LouisElPerk , i also installed today (v9.3) and had the same issue. adding the `-S` flag fixed it for me.
> 
> during my initial debugging i added `-vV` flags as well, by the way, to determine exactly when it was failing (after 32 attempts if i included `-t 32`, after 16 attempts if i included `-t 16`, and so on).
> 
> with the `-S` flag it keeps flying through my password list; in my case i'm using the popular `rockyou.txt` library.

Where to add that -s?

**Comment by waall** [comment]
Are you sure the host has port 21 open?
As you are doing in the FTP protocol, the default port is set to 21, do an NMAP to confirm.
For those who have this problem, do the same but with the respective protocol/port

**Comment by wjy00044996** [comment]
I have the seam problem during against rdp, anyone solved it ?

**Comment by Godsagar** [comment]
I have some error :- all children were disabled due too many connection errors

**Comment by Muntazir0** [comment]
sudo hydra - l kalilouis - P pass3.txt ftp: // IP                                 
Hydra v9.3 (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

**Comment by weeseng95** [comment]
For whoever facing this issues. This is what I've done:

1. Terminal: Ping ip.addr
2. if no response = your IP is Blocked

3. Connect to VPN.

4. Hydra

**Comment by Softwaresman** [comment]
[ERROR] all children were disabled due too many connection errors 
Please give any solution

**Comment by V4mp1reeee** [comment]
i dont see any solutions here please someone (omg hydra is so stressful and annoying) by the way im running kali linux on wsl2, does it have any effect on hydra?

**Comment by waqarahmad403** [comment]
Hey man! are you got the solution of this ?????
if yes, please share with me ...
Thanks

**Comment by waqarahmad403** [comment]
@LouisElPerk 
Hey man! are you got the solution of this ?????
if yes, please share with me ...
Thanks

**Comment by s1a2u3r4a5b6h7** [comment]
> and your question is?
 What is solution for this error??

**Comment by Joyfernandas** [comment]
yeah

**Comment by Acayuuu** [comment]
Same erroe

**Comment by LakerMoon** [comment]
I met the same question:

**Comment by Ondjultomte** [comment]
ERROR] all children were disabled due too many connection errors


also get this error against port 21 ftp . the port is open, verified with nmap prior.

**Comment by pedrosoandre** [comment]
hydra -l <alvo> -p arquivo.txt ftp://IP


Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2024-02-20 22:13:18
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking ftp://31.13.85.174:21/
**### [STATUS] 2.00 tries/min, 2 tries in 00:01h, 1 to do in 00:01h, 1 active**
[ERROR] all children were disabled due too many connection errors
0 of 1 target completed, 0 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2024-02-20 22:14:54

**Comment by Ariagnd** [comment]
> i use sudo hydra -l kalilouis -P pass3.txt ftp://IP
> 
> and
> 
> Hydra v9.3 (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).
> 
> Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-04-18 01:04:44 [DATA] max 16 tasks per 1 server, overall 16 tasks, 330000 login tries (l:1/p:330000), ~20625 tries per task [DATA] attacking ftp://IP:21/ [ERROR] all children were disabled due too many connection errors 0 of 1 target completed, 0 valid password found Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2022-04-18 01:04:47

Dude you have to check your network again please check DNS and PING of internet then tell me (may you using a Kali in a VM so may you have some problem with that )

**Comment by Abdullah-hello** [comment]
I have also installed Kali Linux and now facing the same problem.

**Comment by Logan0112** [comment]
Tenta usar só Linux

Em dom., 6 de out. de 2024 14:09, Abdullah-hello ***@***.***>
escreveu:

**Comment by iamprim0rdial** [comment]
Well, I had the same issue, so I used the { -t 4 -w 5 -S } flag ( -t: reduce the number of tasks from 16 to 4, -w: wait time with a 5-second delay, -S: use SSL encryption for the connection). It will resolve your problem. Thanks! :)
