### ISSUE TITLE
why i got this.

### ISSUE THREAD

**Issue by XM1N21KR1** [vanhauser-thc/thc-hydra#748]
https://drive.google.com/file/d/1Lft3oiRwnU0NaCjb0UICgdoSLnh_5Id8/view?usp=sharing

someone please me, I'm a newbie

There should be only one correct answer, but why does he say that all the passwords in the txt file are correct/valid

**Comment by vanhauser-thc** [comment]
text to detect false password is likely wrong. add -d switch and look at the output sent from the server and choose correct text
