### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by lilnecati** [vanhauser-thc/thc-hydra#749]
I wonder why it doesn't work even though I have real password among them? 

<img width="1298" alt="Ekran Resmi 2022-04-21 22 49 45" src="https://user-images.githubusercontent.com/67555847/164541514-b789d735-d082-4b23-9b3f-8c2af1305623.png">

**Comment by pssvbz14** [comment]
I have the same issue too.

**Comment by lilnecati** [comment]
did you find a solution

**Comment by vanhauser-thc** [comment]
https://github.com/vanhauser-thc/thc-hydra/issues/613
