### ISSUE TITLE
[ERROR] Child with pid ... terminating, can not connect

### ISSUE THREAD

**Issue by irontits** [vanhauser-thc/thc-hydra#75]
hi
sometimes i get this message:
[ERROR] Child with pid ... terminating, can not connect.
repeat hydra the password or it is lose(wrong password)?

greets

**Comment by vanhauser-thc** [comment]
it will repeat those lost attempts at the end.
see with -V

**Comment by domprehsamuel** [comment]
[ERROR] Child with pid ... terminating, can not connect
i also get this error with hydra
can i get help please?
