### ISSUE TITLE
Hydra error

### ISSUE THREAD

**Issue by sub123d** [vanhauser-thc/thc-hydra#759]
i am using hydra on my practice lab but i'm getting this error constantly. no matter what i do, can anyone help me fix it here is the error message i'm getting.
hydra -l molly -w /usr/share/wordlists/rockyou.txt http://10.10.239.22 http-post-form "/:username=^USER^&password=^PASS^:F=incorrect" -V -t 5      
Hydra v9.3 (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

[ERROR] waittime must be larger than 0

**Comment by vanhauser-thc** [comment]
fix your command line options
