### ISSUE TITLE
thc.org blocked by google

### ISSUE THREAD

**Issue by dkorzhevin** [vanhauser-thc/thc-hydra#76]
http://www.google.com/safebrowsing/diagnostic?site=https://www.thc.org/thc-hydra/&hl=en

**Comment by dkorzhevin** [comment]
https://www.stopbadware.org/my-site-has-badware
https://www.stopbadware.org/common-hacks

**Comment by vanhauser-thc** [comment]
Google sucks. please complain to them. a lot.
