### ISSUE TITLE
imaps error

### ISSUE THREAD

**Issue by mabangde** [vanhauser-thc/thc-hydra#760]
**Screenshots**
![image](https://user-images.githubusercontent.com/6219246/170465232-2b37d1c3-8781-46b6-985c-b10fdfe0393b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 
![image](https://user-images.githubusercontent.com/6219246/170465397-a7d55ab0-3335-4c0c-8c9b-ab3bf99520f3.png)

**Comment by vanhauser-thc** [comment]
maybe only kerberos is allowed for authentication?
