### ISSUE TITLE
Custom User-Agent Header Field Broken for http-get

### ISSUE THREAD

**Issue by jboomgaarden** [vanhauser-thc/thc-hydra#763]
**Description**
When attempting to perform a brute force attack against a website protected with Basic HTTP Authentication (e.g., base64 encoded username and password), I've noticed that attempting to modify/replace the User-Agent header field results in adding an additional User-Agent header field and value, rather than actually replacing the default header field. I only see this behavior with the http-get module, and not with http-get-form or http-post-form.

1. Setup something to capture and inspect the traffic (tcpdump, wireshark, or nc -nvlp, etc.)
2. Use the following command
`hydra -C /path/to/wordlist 127.0.0.1 -f -s 8080 http-get "/:H=User-Agent\\:CUSTOM_USER_AGENT_STRING"`

**Expected behavior**
Replacement of default Hydra header field for user agent string with CUSTOM_USER_AGENT_STRING

GET / HTTP/1.1
Host: 127.0.0.1:8081
Connection: close
Authorization: Basic YWRtaW46MTIzNDU2
User-Agent: CUSTOM_USER_AGENT_STRING

**Actual Behavior**
Includes two User-Agent header fields in packets sent:

GET / HTTP/1.1
Host: 127.0.0.1:8081
Connection: close
Authorization: Basic YWRtaW46MTIzNDU2
User-Agent: Mozilla/4.0 (Hydra)
User-Agent: CUSTOM_USER_AGENT_STRING

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Kali GNU/Linux v2022.2
 - hydra version 9.3

**Additional context**
n/a

**Comment by vanhauser-thc** [comment]
let me have a look at this, will take several days though.
I might have coded this specifically so it cannot be overriden (so IDS/IPS can filter unauthorized attempts by n00bs :) )

**Comment by vanhauser-thc** [comment]
yes I hardcoded this for http-get and http-proxy :) 
it is not in http-form because I did not code that module :)

**Comment by jboomgaarden** [comment]
That seems disparate functionality across modules, but hey not my project and totally understand your decision and reasons for doing so! Happy to close this if you don't think it should be changed. Thanks for taking the time to look this up and all the hard work you put into this project!
