### ISSUE TITLE
SMB scann failing

### ISSUE THREAD

**Issue by edlovesiraq** [vanhauser-thc/thc-hydra#765]
**IMPORTANT**
This is just for reporting *BUGS* not help on how to hack, how to use hydra, command line options or how to get it compiled. Please search for help via search engines. Issues asking for this here will be closed.

**Describe the bug**
Running SMB brute force and getting 
[ERROR] Compiled without LIBSMBCLIENT support, module not available!
I have purged hydra, installed libsmbclient and reinstalled hydra and I get the same answer. Purged and installed from github, same result. 
**To Reproduce**
─$ uname -a
Linux kali 5.15.0-kali3-amd64 #1 SMP Debian 5.15.15-2kali1 (2022-01-31) x86_64 GNU/Linux
hydra -l name -P passwords.txt X.X.X.X smb2

**Comment by vanhauser-thc** [comment]
install the module
