### ISSUE TITLE
Hydra docker image

### ISSUE THREAD

**Issue by tarampampam** [vanhauser-thc/thc-hydra#766]
**Is your feature request related to a problem? Please describe.**
Since Docker is a de facto standard, how would you feel about hydra distributing using a docker image?

**Describe the solution you'd like**
Run docker-image with a Hydra using something like a `docker run vanhauser/hydra ...`

**Describe alternatives you've considered**
I have made a repo with it [here](https://github.com/tarampampam/hydra-docker), but I think the better way is to build a docker image in your repo using GitHub Actions, for example (it's free and easy to use).

**Additional context**
You can mention a link to my repository in the readme or I can make a PR with docker image building in yours. What do you think?

**Comment by vanhauser-thc** [comment]
yes, that might be good.
it is fine for me if you put a PR, I can create a github action script to build and push it automatically.
set the ARG to download the wordlists to true though :)

**Comment by tarampampam** [comment]
Are you sure about enabling ARG `INCLUDE_SECLISTS` by default?

![image](https://user-images.githubusercontent.com/7326800/173372941-5b834c5d-79f1-43ac-8946-d227121b5a96.png)

**Comment by tarampampam** [comment]
That's why I have made two tags on one release - `X.Y.Z` with a hydra only, and `X.Y.Z-ext` with those lists. What do you think about it?

**Comment by vanhauser-thc** [comment]
people wont be aware that there is another one. what would be the reason that people would not want such lists? even if people have their own, have extra lists is good.

**Comment by tarampampam** [comment]
Ok ok, as you wish 👍🏼

**Comment by vanhauser-thc** [comment]
weird the image is not available although the CI says it was pushed:
https://hub.docker.com/repository/docker/vanhauser/hydra/general

**Comment by tarampampam** [comment]
The `latest` tag is available, but I suppose the image should be published only on the release creation (this is the default workflow for most cases).

You can revert your CI changes and re-publish the latest tag, as I told you previously

**Comment by vanhauser-thc** [comment]
yeah I got it fixed, publish was set to false, my credentials were in the wrong vault, etc. :)

**Comment by vanhauser-thc** [comment]
I dont want a release creation, I want the github state, releases are only 1-2 times a year, but a fix should be available asap in the container. it is now like it should be. thanks for your effort!
