### ISSUE TITLE
issue with ssh module if server used ssh key

### ISSUE THREAD

**Issue by Oldusercustom** [vanhauser-thc/thc-hydra#768]
**IMPORTANT**
This is just for reporting *BUGS* not help on how to hack, how to use hydra, command line options or how to get it compiled. Please search for help via search engines. Issues asking for this here will be closed.

hydra -L login.txt -P passwords.txt -M list_ip.txt -o result_22port.txt -W 5 -I -t 4 -s 22 ssh

**Describe the bug**

I detected logs about correct access in log hydra

**To Reproduce**
  * Ensure that you have tested the bug to be present in the current github code. You might be using an outdated version that comes with your Linux distribution!
  * You must provide full command line options.

1. ...
2. ...
3. ...

**Expected behavior**

**Screenshots**
Note that all messages must be in *English*, not in Chinese, Russian, etc.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04] - Ubuntu 20.04
 - hydra version [e.g. current github state]   Hydra v9.4-dev (c) 2022

**Additional context**

I detected  in logs

[22][ssh] host: X.X.X.X   login: test1   password: test1
[22][ssh] host: X.X.X.X   login: test2   password: test2
[22][ssh] host: X.X.X.X   login: test3   password: test3
[22][ssh] host: X.X.X.X   login: test4   password: test4

if check via terminal, access broken

ssh test1@X.X.X.X
Unable to negotiate with X.X.X.X port 22: no matching key exchange method found. 
Their offer: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1

sh admin@X.X.X.X -oKexAlgorithms=diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
Unable to negotiate with X.X.X.X port 22: no matching host key type found. Their offer: ssh-dss

I think ssh server used access via ssh key.

Please check.
Thank you!

**Comment by vanhauser-thc** [comment]
your ssh client configuration disabled crypto algorithms the server needs
