### ISSUE TITLE
[RELEASE] Download thc-hydra v9.3 for Windows x64 pre-compiled here

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [vanhauser-thc/thc-hydra#770]
This isn't an actual issue. It's just that compiling stuff is a hastle, so I'd like to share my pre-compiled binaries:
https://mega.nz/file/tspyBbxS#QkHw0tnzRSWJcK1XEmA0ziv2E8NRMSgDTVL_5ij-QYE

Just download the zip, extract it, and run `hydra.exe`.

ZLIB: enabled
SSL: enabled
radmin2 module: disabled
color output: enabled
postgres: enabled
svn: disabled
firebird: disabled
Apple Filing Protocol: disabled - Apple sucks anyway
NCP: disabled
sapr3: disabled
ssh: enabled
Oracle: disabled
memcached: disabled
rdp: enabled
mongodb: disabled
smb2: disabled

**Comment by winezer0** [comment]
Could you provide the windows compiler of hydra 9.5
