### ISSUE TITLE
correct username and password not working

### ISSUE THREAD

**Issue by Testing554** [vanhauser-thc/thc-hydra#773]
**Describe the bug**
I am using hydra -l admin -p admin -e ns -f -V xx.xx.xx.xx http-get /
i am getting below output
Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-07-15 01:08:11
[DATA] max 3 tasks per 1 server, overall 3 tasks, 3 login tries (l:1/p:3), ~1 try per task
[DATA] attacking http-get:// xx.xx.xx.xx:80/
[ATTEMPT] target xx.xx.xx.xx - login "admin" - pass "admin" - 1 of 3 [child 0] (0/0)
[ATTEMPT] target xx.xx.xx.xx - login "admin" - pass "" - 2 of 3 [child 1] (0/0)
[ERROR] Child with pid 83383 terminating, can not connect
[ERROR] Child with pid 83382 terminating, can not connect
1 of 1 target completed, 0 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2022-07-15 01:08:21

the ip is of ip camera. I can connect to camera through smartPss
![image](https://user-images.githubusercontent.com/109334404/179162081-56fb17e3-90f3-4333-9a41-2e572af9b04d.png)

**Expected behavior**
it should give a valid password

**Comment by vanhauser-thc** [comment]
"can not connect" tells you all ...

**Comment by Testing554** [comment]
but i can login with same username and password in smartpss software. Is there something i am missing here that hydra cannot find right password, although i know pass and username is right

**Comment by Testing554** [comment]
if needed i can provide more details

**Comment by Testing554** [comment]
of issue
