### ISSUE TITLE
Make

### ISSUE THREAD

**Issue by job-hacker** [vanhauser-thc/thc-hydra#774]
make
cc -I. -O3 -g -fcommon -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wl,-z,now -Wl,-z,relro -Wl,--allow-multiple-definition -lm -g   -o hydra  hydra.c hydra-vnc.o hydra-pcnfs.o hydra-rexec.o hydra-nntp.o hydra-socks5.o hydra-telnet.o hydra-cisco.o hydra-http.o hydra-ftp.o hydra-imap.o hydra-pop3.o hydra-smb.o hydra-icq.o hydra-cisco-enable.o hydra-ldap.o hydra-memcached.o hydra-mongodb.o hydra-mysql.o hydra-mssql.o hydra-cobaltstrike.o hydra-xmpp.o hydra-http-proxy-urlenum.o hydra-snmp.o hydra-cvs.o hydra-smtp.o hydra-smtp-enum.o hydra-sapr3.o hydra-ssh.o hydra-sshkey.o hydra-teamspeak.o hydra-postgres.o hydra-rsh.o hydra-rlogin.o hydra-oracle-listener.o hydra-svn.o hydra-pcanywhere.o hydra-sip.o hydra-oracle-sid.o hydra-oracle.o hydra-vmauthd.o hydra-asterisk.o hydra-firebird.o hydra-afp.o hydra-ncp.o hydra-http-proxy.o hydra-http-form.o hydra-irc.o hydra-redis.o hydra-rdp.o hydra-s7-300.c hydra-adam6500.o hydra-rtsp.o hydra-rpcap.o hydra-radmin2.o crc32.o d3des.o bfg.o ntlm.o sasl.o hmacmd5.o hydra-mod.o hydra-time.o hydra-smb2.o -lm
hydra.c:1029:9: warning: implicit declaration of function 'wait3' is invalid in C99 [-Wimplicit-function-declaration]
  pid = wait3(NULL, WNOHANG, NULL);                                       ^
hydra.c:1450:9: warning: implicit declaration of function 'wait3' is invalid in C99 [-Wimplicit-function-declaration]
  (void)wait3(NULL, WNOHANG, NULL);
        ^
hydra.c:4254:11: warning: implicit declaration of function 'wait3' is invalid in C99 [-Wimplicit-function-declaration]
    (void)wait3(NULL, WNOHANG, NULL);
          ^
hydra.c:4357:9: warning: implicit declaration of function 'wait3' is invalid in C99 [-Wimplicit-function-declaration]
  (void)wait3(NULL, WNOHANG, NULL);
        ^
4 warnings generated.
ld.lld: error: undefined symbol: wait3
>>> referenced by hydra.c:1029
>>>               /data/data/com.termux/files/usr/tmp/hydra-19a2ac.o:(killed_childs)
>>> referenced by hydra.c:1450
>>>               /data/data/com.termux/files/usr/tmp/hydra-19a2ac.o:(hydra_kill_head)
>>> referenced by hydra.c:4254
>>>               /data/data/com.termux/files/usr/tmp/hydra-19a2ac.o:(main)
>>> referenced 1 more times
>>> did you mean: wait4
>>> defined in: /system/lib64/libc.so
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:68: hydra] Error 1

make install
cc -I. -O3 -g -fcommon -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wl,-z,now -Wl,-z,relro -Wl,--allow-multiple-definition -lm -g   -o hydra  hydra.c hydra-vnc.o hydra-pcnfs.o hydra-rexec.o hydra-nntp.o hydra-socks5.o hydra-telnet.o hydra-cisco.o hydra-http.o hydra-ftp.o hydra-imap.o hydra-pop3.o hydra-smb.o hydra-icq.o hydra-cisco-enable.o hydra-ldap.o hydra-memcached.o hydra-mongodb.o hydra-mysql.o hydra-mssql.o hydra-cobaltstrike.o hydra-xmpp.o hydra-http-proxy-urlenum.o hydra-snmp.o hydra-cvs.o hydra-smtp.o hydra-smtp-enum.o hydra-sapr3.o hydra-ssh.o hydra-sshkey.o hydra-teamspeak.o hydra-postgres.o hydra-rsh.o hydra-rlogin.o hydra-oracle-listener.o hydra-svn.o hydra-pcanywhere.o hydra-sip.o hydra-oracle-sid.o hydra-oracle.o hydra-vmauthd.o hydra-asterisk.o hydra-firebird.o hydra-afp.o hydra-ncp.o hydra-http-proxy.o hydra-http-form.o hydra-irc.o hydra-redis.o hydra-rdp.o hydra-s7-300.c hydra-adam6500.o hydra-rtsp.o hydra-rpcap.o hydra-radmin2.o crc32.o d3des.o bfg.o ntlm.o sasl.o hmacmd5.o hydra-mod.o hydra-time.o hydra-smb2.o -lm
hydra.c:1029:9: warning: implicit declaration of function 'wait3' is invalid in C99 [-Wimplicit-function-declaration]
  pid = wait3(NULL, WNOHANG, NULL);
        ^
hydra.c:1450:9: warning: implicit declaration of function 'wait3' is invalid in C99 [-Wimplicit-function-declaration]
  (void)wait3(NULL, WNOHANG, NULL);
        ^
hydra.c:4254:11: warning: implicit declaration of function 'wait3' is invalid in C99 [-Wimplicit-function-declaration]
    (void)wait3(NULL, WNOHANG, NULL);
          ^
hydra.c:4357:9: warning: implicit declaration of function 'wait3' is invalid in C99 [-Wimplicit-function-declaration]
  (void)wait3(NULL, WNOHANG, NULL);
        ^
4 warnings generated.
ld.lld: error: undefined symbol: wait3
>>> referenced by hydra.c:1029
>>>               /data/data/com.termux/files/usr/tmp/hydra-d6d0e3.o:(killed_childs)
>>> referenced by hydra.c:1450
>>>               /data/data/com.termux/files/usr/tmp/hydra-d6d0e3.o:(hydra_kill_head)
>>> referenced by hydra.c:4254
>>>               /data/data/com.termux/files/usr/tmp/hydra-d6d0e3.o:(main)
>>> referenced 1 more times
>>> did you mean: wait4
>>> defined in: /system/lib64/libc.so
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:68: hydra] Error 1

😨 make
4 warnings generated.
ld.lld: error: undefined symbol: wait3
>>> referenced by hydra.c:1029
>>>               /data/data/com.termux/files/usr/tmp/hydra-d6d0e3.o:(killed_childs)
>>> referenced by hydra.c:1450
>>>               /data/data/com.termux/files/usr/tmp/hydra-d6d0e3.o:(hydra_kill_head)
>>> referenced by hydra.c:4254
>>>               /data/data/com.termux/files/usr/tmp/hydra-d6d0e3.o:(main)
>>> referenced 1 more times
>>> did you mean: wait4
>>> defined in: /system/lib64/libc.so
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:68: hydra] Error 1

😨 make install 
4 warnings generated.
ld.lld: error: undefined symbol: wait3
>>> referenced by hydra.c:1029
>>>               /data/data/com.termux/files/usr/tmp/hydra-d6d0e3.o:(killed_childs)
>>> referenced by hydra.c:1450
>>>               /data/data/com.termux/files/usr/tmp/hydra-d6d0e3.o:(hydra_kill_head)
>>> referenced by hydra.c:4254
>>>               /data/data/com.termux/files/usr/tmp/hydra-d6d0e3.o:(main)
>>> referenced 1 more times
>>> did you mean: wait4
>>> defined in: /system/lib64/libc.so
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:68: hydra] Error 1

help I'm a newbie, I tried to solve it myself, I can't find a solution, maybe it's jumping in my face, but I don't understand much!  Few, days of studies ⌛️

**Comment by Vaddagrewal21** [comment]
I also facing same

**Comment by vanhauser-thc** [comment]
can you please check out the new github state and retry?
