### ISSUE TITLE
[ERROR] all children were disabled due too many connection errors

### ISSUE THREAD

**Issue by Hafzan-250601** [vanhauser-thc/thc-hydra#776]
![image](https://user-images.githubusercontent.com/54774679/180010474-5cadee41-3898-487c-990e-f359d2dedb9a.png)
Hi why is this error keep showing I m trying to use it for HackerOneCTF challenge.
I use the 9.3v on Kali Linux please help. I have been trying this for days.

**Comment by vanhauser-thc** [comment]
most likely it is an SSL Service, so you need to add -S?

**Comment by Zlatanius** [comment]
I have the same problem also for the Hacker101 CTF. Are they blocking hydra. It wouldent make sense if they were since they recomend the tool.

**Comment by Godsagar** [comment]
ERROR] all children were disabled due too many connection errors
How to fix this problem

**Comment by V4mp1reeee** [comment]
> most likely it is an SSL Service, so you need to add -S? I dont know where to add it
