### ISSUE TITLE
Hydra SMTP module continues login attempts after failure & output with -K

### ISSUE THREAD

**Issue by sschoenith** [vanhauser-thc/thc-hydra#779]
**Describe the bug**
When attempting to use the Hydra SMTP module, if Hydra encounters an error for SMTP Login Auth stating auth is disabled / or not using authentication, Hydra will continue sending authentication requests to the target until complete. This behavior continues with -K flag enabled. This behavior also continues outputting error messages even with -q.

**To Reproduce**

1. Setup / locate an SMTP server with password authentication not enabled
2. ensure seclists installed / provide any password list
3. run the following command (replace target IP):
`hydra -l admin -P /usr/share/seclists/Passwords/darkweb2017-top10.txt {targetip} -e ns -t 4 -T 4 -K -q smtp -V`

**Expected behavior**
- Expected that -K flag will see this as a connection error / failed attempt and thus stop sending requests.
- Expected that -q flag will see this as a connection error and thus stop printing messages about the connection errors
```
  -K        do not redo failed attempts (good for -M mass scanning)
  -q        do not print messages about connection errors
```

**Screenshots**
Example output:
```
[ERROR] SMTP LOGIN AUTH, either this auth is disabled or server is not using auth: 503 5.5.1 Error: authentication not enabled
[ATTEMPT] target {targetip} - login "admin" - pass "password1" - 10 of 12 [child 2] (0/0)
[ERROR] SMTP LOGIN AUTH, either this auth is disabled or server is not using auth: 503 5.5.1 Error: authentication not enabled
[ATTEMPT] target {targetip} - login "admin" - pass "1234567" - 11 of 12 [child 3] (0/0)
[ATTEMPT] target {targetip} - login "admin" - pass "123123" - 12 of 12 [child 1] (0/0)
[ERROR] SMTP LOGIN AUTH, either this auth is disabled or server is not using auth: 503 5.5.1 Error: authentication not enabled
[ATTEMPT] target {targetip} - login "azureuser" - pass "1234567" - 203 of 204 [child 2] (0/0)
[ATTEMPT] target {targetip} - login "azureuser" - pass "123123" - 204 of 204 [child 3] (0/0)
[ERROR] SMTP LOGIN AUTH, either this auth is disabled or server is not using auth: 503 5.5.1 Error: authentication not enabled
[ERROR] SMTP LOGIN AUTH, either this auth is disabled or server is not using auth: 503 5.5.1 Error: authentication not enabled
[ERROR] SMTP LOGIN AUTH, either this auth is disabled or server is not using auth: 503 5.5.1 Error: authentication not enabled
1 of 1 target completed, 0 valid password found
[WARNING] Writing restore file because 1 final worker threads did not complete until end.
[ERROR] 1 target did not resolve or could not be connected
[ERROR] 0 target did not complete
```

**Desktop (please complete the following information):**
 - OS: Kali Linux 2022.1 rolling
 - Linux kernel: 5.16.0-kali3-amd64
 - hydra -v = Hydra v9.3 (c) 2022

**Additional context**
N/A

**Comment by vanhauser-thc** [comment]
somehow I didnt see any notifcation about this issue, sorry.
fixed in feaab90b1fe29c9f059e4b548540f00b6df79ff1
