### ISSUE TITLE
SSLv3 Problem With Yahoo

### ISSUE THREAD

**Issue by Merujan99** [vanhauser-thc/thc-hydra#78]
input: ./hydra -C ~/Desktop/wordlistYahoo.txt smtp://smtp.mail.yahoo.com:587 -S -v -V
output: [VERBOSE] Could not create an SSL session: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number

Can't Create SSL Session, so please fix it

**Comment by vanhauser-thc** [comment]
works fine if you care to update to the newest versoin instead of reporting

**Comment by Merujan99** [comment]
I cloned and compiled it yesterday, but didn't work

**Comment by gsi-edel** [comment]
I have a similar problem and i resolved using ssl instead sslv3.
