### ISSUE TITLE
The same syntax command can be recognized normally on kali, but an error is prompted on macos

### ISSUE THREAD

**Issue by yjn140** [vanhauser-thc/thc-hydra#780]
**Describe the bug**

When I use the following code to run in kali and macos terminal, kali works fine. Format error message on macOS
`hydra -L user.txt -P passwd.txt 192.168.2.82 -s 55007 pop3`

**Screenshots**
macOS-12.5 hydra v9.3 （`brew install hydra`）
<img width="1240" alt="1111" src="https://user-images.githubusercontent.com/30982195/184531634-3bf0e4f6-b2e1-4ebb-bbf4-44693c8cc83a.png">

kali-2020 hydra v9.1
<img width="629" alt="Snipaste_2022-08-14_17-28-51" src="https://user-images.githubusercontent.com/30982195/184531439-e31de877-23c6-4911-9354-53bf6a74a014.png">

**Comment by vanhauser-thc** [comment]
simply learn how to pass command line options correctly.

hydra -L user.txt -P passwd.txt -s 55007 192.168.2.82 pop3
