### ISSUE TITLE
[ERROR] all children were disabled due too many connection errors

### ISSUE THREAD

**Issue by xyplex** [vanhauser-thc/thc-hydra#781]
I am running the following command over a proxychains

**proxychains -q hydra -L "usernames.txt" -P "passwords.txt" -e nsr -s 3389  rdp://10.1.1.248** 

I get following  ERROR message

**[ERROR] all children were disabled due too many connection errors**

I am using an SSH Dynamic tunnel 

![image](https://user-images.githubusercontent.com/45394257/185356624-863ca668-0663-4f96-be57-1e64390b53db.png)

Can you help me to fix this issue?

**Comment by nickxsc** [comment]
i think this problen is because of the server's protect , not hydra

**Comment by vanhauser-thc** [comment]
it might be that rdp cannot be tunneled? check with tcpdump/wireshark if it uses the tunnel or if it tried to connect directly
