### ISSUE TITLE
[ERROR] Compiled without LIBSSH v0.4.x support, module is not available!

### ISSUE THREAD

**Issue by aaryankotharii** [vanhauser-thc/thc-hydra#782]
downloaded hydra on macOS 12.0 via home-brew

aaryankotharii@Aaryans-MacBook-Air ~ % hydra -l aaryankotharii -P /Users/aaryankotharii/Desktop/passwords.txt ssh://172.20.10.4
Hydra v9.4-dev (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-08-24 18:52:55
[WARNING] Many SSH configurations limit the number of parallel tasks, it is recommended to reduce the tasks: use -t 4
[ERROR] Compiled without LIBSSH v0.4.x support, module is not available!

**Comment by vanhauser-thc** [comment]
you have to install libssh-dev
