### ISSUE TITLE
Invalid condition string is considered as optional part

### ISSUE THREAD

**Issue by MASTREX** [vanhauser-thc/thc-hydra#783]
Whenever I use optional parameter in hydra like C= or H= I get this error for invalid condition string

> Command used
```
installed/bin/hydra  -l login -p pass -o found.txt -c 1 -IvVd server.com https-post-form "/checkuser.php:&typefunc=&userid=^USER^&pass_word=^PASS^&uotpid=:Invalid:C=/corecampus/index.php"
```

```
 [ERROR] optional parameters must have the format X=value: Invalid
```

Hydra v9.4-dev (c) 2022

**Comment by varens** [comment]
Can confirm on v9.5-dev:
`/endpoint:cookie=null&user=^USER^&pass=^PASS^:failed:g=` results in `[ERROR] optional parameters must have the format X=value: failed`

**Comment by vanhauser-thc** [comment]
What is wrong is the help output in hydra, just fixed that.
the condition match statement - ":failed" here - must always be the LAST statement, not the third.

**Comment by jakard** [comment]
what happens when you have literally ":" within the condition match statement? (after the : which is separating the last term)

**Comment by MASTREX** [comment]
Escape any : with \ that are not used as seperator

**Comment by MAH69IK** [comment]
> What is wrong is the help output in hydra, just fixed that. the condition match statement - ":failed" here - must always be the LAST statement, not the third.

Sorry, could you release the version with the corrected help? Still, this is probably not the rarest module and it seems to me that new users (like me) will take a long time to understand why they get an error although they do everything according to the documentation.
