### ISSUE TITLE
Install fail macos 12.5.1 (21G83)

### ISSUE THREAD

**Issue by mbierman** [vanhauser-thc/thc-hydra#785]
**Describe the bug**

Doesn't seem to install on macOS 

**To Reproduce**
  * Ensure that you have tested the bug to be present in the current github code. You might be using an outdated version that comes with your Linux distribution!
  * You must provide full command line options.

.```
/configure
$ make
cc -I. -O3 -g -fcommon  -g  -c hydra-http-form.c -DHAVE_ZLIB -DHAVE_MATH_H -DHAVE_SYS_PARAM_H 
In file included from hydra-http-form.c:53:
In file included from ./hydra-http.h:4:
./hydra-mod.h:74:6: warning: 'TARGET_OS_IPHONE' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
#if (TARGET_OS_IPHONE && __LP64__) || TARGET_OS_WATCH
     ^
./hydra-mod.h:74:39: warning: 'TARGET_OS_WATCH' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
#if (TARGET_OS_IPHONE && __LP64__) || TARGET_OS_WATCH
                                      ^
hydra-http-form.c:262:5: error: non-void function 'add_header' should return a value [-Wreturn-type]
    return;
    ^
2 warnings and 1 error generated.
make: *** [hydra-http-form.o] Error 1
```

**Expected behavior**
installation completes

**Screenshots**


**Desktop (please complete the following information):**
 - OS: macOS 12.5.1 (21G83)
 - hydra version 9.3

**Additional context**
Add any other context about the problem here.

**Comment by vanhauser-thc** [comment]
use github state

**Comment by mbierman** [comment]
@vanhauser-thc what does that mean? 

I will note that brew install did work.

**Comment by vanhauser-thc** [comment]
I mean compile it from source, brew version is outdated

**Comment by mbierman** [comment]
Is that not what the make process does? 

It failed. 

Brew worked and says 9.3 which is current, is it not?

**Comment by vanhauser-thc** [comment]
it is the last release but there have been fixes since. you have to install a compiler, make etc. with brew
