### ISSUE TITLE
Version 9.4 brute force with http-form BUG

### ISSUE THREAD

**Issue by Esgarothh** [vanhauser-thc/thc-hydra#787]
First time posting a bug ever!
The version 9.4 wont allows to use an bruteforce attack with the F parameters as the following code:
![image](https://user-images.githubusercontent.com/83790801/189459792-ab97acd3-c5e8-4c4f-ae81-00e305043b5d.png)

but in the 9.3 version it works!
![image](https://user-images.githubusercontent.com/83790801/189459841-81de6051-ba19-49e0-8ec7-2d35aa28c320.png)

might be an error in the "hydra-http-form.c"

**Comment by vanhauser-thc** [comment]
F/S should be the last parameter, not in the middle

**Comment by Esgarothh** [comment]
Thanks! not it works for the last version
