### ISSUE TITLE
[ERROR] the variables argument needs at least the strings ^USER^, ^PASS^, ^USER64^ or ^PASS64^

### ISSUE THREAD

**Issue by imjustcaden** [vanhauser-thc/thc-hydra#789]
**Describe the bug**
Not sure if this is a bug, I am new to this tool, please excuse me. I am attempting to crack a web form login using http-post-get. The response body doesn't seem to be normal, receiving an error.

**To Reproduce**
Full code as follows:
`sudo hydra -L user.txt -P pass.txt -t 16 -f [address concealed] https-post-form "/loginService:7|0|9|https://[address concealed]|A65D154816CB27F28877B9D2D4D68A25|com.edgear.client.security.loginService|staffLogin|java.lang.String/2004016611|^USER^|^PASS^|Live|010|1|2|3|4|4|5|5|5|5|6|7|8|9|:Invalid Login"`

Gave the error:
`[ERROR] the variables argument needs at least the strings ^USER^, ^PASS^, ^USER64^ or ^PASS64^: 7|0|9|https`

**Expected behavior**
Command to run without errors.

**Desktop (please complete the following information):**
 - OS: Kali
 - hydra version: current realese

**Comment by vanhauser-thc** [comment]
I kinda doubt your target wants pipe symbols in their data

**Comment by imjustcaden** [comment]
> I kinda doubt your target wants pipe symbols in their data

well thats what the request payload is

**Comment by vanhauser-thc** [comment]
ah you have to escape the colon in `|https://[address concealed]|`with the `\\` sign
