### ISSUE TITLE
Need help with form post synax

### ISSUE THREAD

**Issue by tsoernes** [vanhauser-thc/thc-hydra#79]
`hydra -l testuser -P "rockyou.txt" -s 5001 129.xxx.106.153 http-post-form "/login:user=^USER^&pass=^PASS^&submit=Log in:Incorrect"`
URL: `http://example.org:5001/login`
Login:
```
<form action="" method="POST">
<label>Username: </label>
<input type="text" name="user" required title="Please fill in a username." /> <br />
<label>Password: </label>
<input type="password" name="pass" required title="Please fill in a password." /> <br />
<input type="submit" name="submit" value="Log in">
</form>
```
Invalid:
```
<h2>Login</h2>
Incorrect user/pass combination. <br />
```
I get false positives. It tests the 11 first passwords and says that all are correct. Do you know why?

Also: If I use http://129.xxx.xxx.153 instead of 129.xxx.xxx.153 I get the error message: `network size may only be between /16 and /31`

**Comment by vanhauser-thc** [comment]
maybe it requires a cookie?

but add the switches "-d -t 1" and take a look at the ouput why hydra reports false positives.
