### ISSUE TITLE
Not working properly for this request body

### ISSUE THREAD

**Issue by xiyang203** [vanhauser-thc/thc-hydra#790]
**IMPORTANT**
This is just for reporting *BUGS* not help on how to hack, how to use hydra, command line options or how to get it compiled. Please search for help via search engines. Issues asking for this here will be closed.
√I get it.

**Describe the bug**

The request body of a website(http://10.10.10.1:60020) is as follows:
__VIEWSTATE=%2FwEPDwUKMTE3NTYyOTE3Ng9kFgICAQ9kFgICBw8PFgIeBFRleHQFlgE8YSBocmVmPSJodHRwOi8vd3d3LmxhbnpoZXIuY29tLyIgdGFyZ2V0PSJfYmxhbmsiPueJiOadg%2BaJgOacie%2B8muWMl%2BS6rOa1quaZuuenkeaKgOaciemZkOWFrOWPuCAg54mI5pys5Y%2B377yaVjIuMTExICDmioDmnK%2FmlK%2FmjIHvvJo0MDAtNjExLTQwODkgIDwvYT5kZGSiOqTtqMXxOJUBitRJHCvRrICU6qypdQoOg4rBc2cX%2FA%3D%3D&__EVENTVALIDATION=%2FwEdAASE4sxq6a102Xm1q65o9iaEKhoCyVdJtLIis5AgYZ%2FRYe4sciJO3Hoc68xTFtZGQEjN%2BDvxnwFeFeJ9MIBWR693USBs6H5AWDnWxZpn0p15R2a18IFK6zm6ltxJI1LiCVk%3D&username=sam&password=test&Button1=%E7%99%BB++++%E5%BD%95

My syntax like this：
hydra -l admin -P C:\Users\Administrator\Downloads\Documents\pass\Blasting_dictionary\1000.txt -t 1 -o out.txt -s 60020 10.10.10.1 http-post-form "/:__VIEWSTATE=%2FwEPDwUKMTE3NTYyOTE3Ng9kFgICAQ9kFgICBw8PFgIeBFRleHQFlgE8YSBocmVmPSJodHRwOi8vd3d3LmxhbnpoZXIuY29tLyIgdGFyZ2V0PSJfYmxhbmsiPueJiOadg%2BaJgOacie%2B8muWMl%2BS6rOa1quaZuuenkeaKgOaciemZkOWFrOWPuCAg54mI5pys5Y%2B377yaVjIuMTExICDmioDmnK%2FmlK%2FmjIHvvJo0MDAtNjExLTQwODkgIDwvYT5kZGSiOqTtqMXxOJUBitRJHCvRrICU6qypdQoOg4rBc2cX%2FA%3D%3D&__EVENTVALIDATION=%2FwEdAASE4sxq6a102Xm1q65o9iaEKhoCyVdJtLIis5AgYZ%2FRYe4sciJO3Hoc68xTFtZGQEjN%2BDvxnwFeFeJ9MIBWR693USBs6H5AWDnWxZpn0p15R2a18IFK6zm6ltxJI1LiCVk%3D&username=^USER^&password=^PASS^&Button1=%E7%99%BB++++%E5%BD%95:F=Invalid username"

It gives me wrong results. And each change of dictionary will give different results. If I adjust the threads to two it gives me two wrong results, if I adjust to three it gives me three wrong results, and so on.

**To Reproduce**
  * Ensure that you have tested the bug to be present in the current github code. You might be using an outdated version that comes with your Linux distribution!
  * You must provide full command line options.

1. ...
2. ...
3. ...

**Expected behavior**
I would like to know why this error occurs. How should it be fixed?

**Screenshots**
Note that all messages must be in *English*, not in Chinese, Russian, etc.
![image](https://user-images.githubusercontent.com/41546806/190847037-e45c296c-c8ad-4857-bbe2-6986d5f2f293.png)
![image](https://user-images.githubusercontent.com/41546806/190847076-476b497c-fbbd-4278-ac37-11507b408266.png)
![image](https://user-images.githubusercontent.com/41546806/190847105-f15b24f0-3f4a-474e-bec5-178c3e0eb0f6.png)
![image](https://user-images.githubusercontent.com/41546806/190847479-c1b98e2b-5d3b-4d77-b4bb-355603134027.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - hydra version: thc-hydra-windows-v9.1

**Additional context**

**Comment by vanhauser-thc** [comment]
your string to identify failed logins is not correct
