### ISSUE TITLE
SMB2 Module not working possibly because of current library

### ISSUE THREAD

**Issue by mehftersh0ck** [vanhauser-thc/thc-hydra#791]
hydra -l someuser -p _valid_password_ smb2://Windows_2019_DC
This is working on a kali VM before upgrading but after upgrading returns "[Error] Success (0)" multiple times and never finds valid password. The same was repeated on a fresh install of the latest kali and when compiling the latest hydra manually. Copying the compiled binary from the old kali to the new kali fails as well. Perhaps an issue with libsmbclient? Is there an easy fix and I'm being dumb? Thanks

Works with libsmbclient 2:4.13.14+dfsg-1+b2
Fails with libsmbclient 2:4.16.5+dfsg-1

Example of run with -dvvv and the correct credentials: 
Hydra v9.5-dev (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

[DEBUG] Output color flag is 0
Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-09-22 15:17:41
[DEBUG] cmdline: ./hydra -l someuser -p Pa$$w0rd -dvvv smb2://192.168.30.200 
[DEBUG] opt:6 argc:7 mod:smb2 tgt:192.168.30.200 port:0 misc:(null)
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking smb2://192.168.30.200:445/
[VERBOSE] Resolving addresses ... 
[DEBUG] resolving 192.168.30.200
[VERBOSE] resolving done
[DEBUG] Code: attack   Time: 1663874261
[DEBUG] Options: mode 0  ssl 0  restore 0  showAttempt 0  tasks 1  max_use 1 tnp 0  tpsal 0  tprl 0  exit_found 0  miscptr (null)  service smb2
[DEBUG] Brains: active 0  targets 1  finished 0  todo_all 1  todo 1  sent 0  found 0  countlogin 1  sizelogin 9  countpass 1  sizepass 9
[DEBUG] Target 0 - target 192.168.30.200  ip 192.168.30.200  login_no 0  pass_no 0  sent 0  pass_state 0  redo_state 0 (0 redos)  use_count 0  failed 0  done 0  fail_count 0  login_ptr someuser  pass_ptr Pa$$w0rd
[DEBUG] Task 0 - pid 0  active 0  redo 0  current_login_ptr (null)  current_pass_ptr (null)
[DEBUG] Tasks 1 inactive  0 active
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 23018
[DEBUG] head_no 0 has pid 23018
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 0, redo_state 0, pass_state 0. loop_mode 0, curlogin (null), curpass (null), tlogin someuser, tpass Pa$$w0rd, logincnt 0/1, passcnt 0/1, loop_cnt 1
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin someuser, cpass Pa$$w0rd, tlogin -p, tpass Pa$$w0rd, redo 0
[ATTEMPT] target 192.168.30.200 - login "someuser" - pass "Pa$$w0rd" - 1 of 1 [child 0] (0/0)
INFO: Current debug levels:
  all: 7
  tdb: 7
  printdrivers: 7
  lanman: 7
  smb: 7
  rpc_parse: 7
  rpc_srv: 7
  rpc_cli: 7
  passdb: 7
  sam: 7
  auth: 7
  winbind: 7
  vfs: 7
  idmap: 7
  quota: 7
  acls: 7
  locking: 7
  msdfs: 7
  dmapi: 7
  registry: 7
  scavenger: 7
  dns: 7
  ldb: 7
  tevent: 7
  auth_audit: 7
  auth_json_audit: 7
  kerberos: 7
  drs_repl: 7
  smb2: 7
  smb2_credits: 7
  dsdb_audit: 7
  dsdb_json_audit: 7
  dsdb_password_audit: 7
  dsdb_password_json_audit: 7
  dsdb_transaction_audit: 7
  dsdb_transaction_json_audit: 7
  dsdb_group_audit: 7
  dsdb_group_json_audit: 7
[INFO] Connecting to: smb://192.168.30.200/IPC$ with WORKGROUP\someuser%Pa$$w0rd
[DEBUG] pid 23018 called child_exit with code 2
[DEBUG] head_no[0] read E
[ATTEMPT-ERROR] target 192.168.30.200 - login "someuser" - pass "Pa$$w0rd" - child 0 - 1 of 1
[DEBUG] hydra_increase_fail_count: 1 >= 0 => disable
[DEBUG] - will be retried at the end: ip 192.168.30.200 - login someuser - pass Pa$$w0rd - child 0
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 23019
[DEBUG] head_no 0 has pid 23019
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 1, redo_state 0, pass_state 0. loop_mode 0, curlogin , curpass , tlogin -p, tpass Pa$$w0rd, logincnt 1/1, passcnt 0/1, loop_cnt 1
[COMPLETED] target 192.168.30.200 - login "" - pass "" - child 0 - 1 of 2
[DEBUG] send_next_pair_mid done 0, pass_state 0, clogin , cpass , tlogin -p, tpass Pa$$w0rd, redo 1
[DEBUG] Entering redo_state
[DEBUG] send_next_pair_init target 0, head 0, redo 1, redo_state 1, pass_state 0. loop_mode 0, curlogin , curpass , tlogin -p, tpass Pa$$w0rd, logincnt 1/1, passcnt 0/1, loop_cnt 2
[COMPLETED] target 192.168.30.200 - login "" - pass "" - child 0 - 1 of 2
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin someuser, cpass Pa$$w0rd, tlogin -p, tpass Pa$$w0rd, redo 1
[REDO-ATTEMPT] target 192.168.30.200 - login "someuser" - pass "Pa$$w0rd" - 2 of 2 [child 0] (1/1)
INFO: Current debug levels:
  all: 7
  tdb: 7
  printdrivers: 7
  lanman: 7
  smb: 7
  rpc_parse: 7
  rpc_srv: 7
  rpc_cli: 7
  passdb: 7
  sam: 7
  auth: 7
  winbind: 7
  vfs: 7
  idmap: 7
  quota: 7
  acls: 7
  locking: 7
  msdfs: 7
  dmapi: 7
  registry: 7
  scavenger: 7
  dns: 7
  ldb: 7
  tevent: 7
  auth_audit: 7
  auth_json_audit: 7
  kerberos: 7
  drs_repl: 7
  smb2: 7
  smb2_credits: 7
  dsdb_audit: 7
  dsdb_json_audit: 7
  dsdb_password_audit: 7
  dsdb_password_json_audit: 7
  dsdb_transaction_audit: 7
  dsdb_transaction_json_audit: 7
  dsdb_group_audit: 7
  dsdb_group_json_audit: 7
[INFO] Connecting to: smb://192.168.30.200/IPC$ with WORKGROUP\someuser%Pa$$w0rd
[DEBUG] pid 23019 called child_exit with code 2
[DEBUG] head_no[0] read E
[ATTEMPT-ERROR] target 192.168.30.200 - login "someuser" - pass "Pa$$w0rd" - child 0 - 2 of 1
[DEBUG] hydra_increase_fail_count: 2 >= 0 => disable
[DEBUG] - will be retried at the end: ip 192.168.30.200 - login someuser - pass Pa$$w0rd - child 0
[DEBUG] head_no 0, kill 1, fail 0
[DEBUG] child 0 got target 0 selected
[DEBUG] child 0 spawned for target 0 with pid 23020
[DEBUG] head_no 0 has pid 23020
[DEBUG] head_no[0] read n
[DEBUG] send_next_pair_init target 0, head 0, redo 2, redo_state 2, pass_state 0. loop_mode 0, curlogin , curpass , tlogin -p, tpass Pa$$w0rd, logincnt 1/1, passcnt 0/1, loop_cnt 1
[COMPLETED] target 192.168.30.200 - login "" - pass "" - child 0 - 2 of 3
[DEBUG] send_next_pair_mid done 1, pass_state 0, clogin someuser, cpass Pa$$w0rd, tlogin -p, tpass Pa$$w0rd, redo 2
[REDO-ATTEMPT] target 192.168.30.200 - login "someuser" - pass "Pa$$w0rd" - 3 of 3 [child 0] (2/2)
INFO: Current debug levels:
  all: 7
  tdb: 7
  printdrivers: 7
  lanman: 7
  smb: 7
  rpc_parse: 7
  rpc_srv: 7
  rpc_cli: 7
  passdb: 7
  sam: 7
  auth: 7
  winbind: 7
  vfs: 7
  idmap: 7
  quota: 7
  acls: 7
  locking: 7
  msdfs: 7
  dmapi: 7
  registry: 7
  scavenger: 7
  dns: 7
  ldb: 7
  tevent: 7
  auth_audit: 7
  auth_json_audit: 7
  kerberos: 7
  drs_repl: 7
  smb2: 7
  smb2_credits: 7
  dsdb_audit: 7
  dsdb_json_audit: 7
  dsdb_password_audit: 7
  dsdb_password_json_audit: 7
  dsdb_transaction_audit: 7
  dsdb_transaction_json_audit: 7
  dsdb_group_audit: 7
  dsdb_group_json_audit: 7
[INFO] Connecting to: smb://192.168.30.200/IPC$ with WORKGROUP\someuser%Pa$$w0rd
[DEBUG] pid 23020 called child_exit with code 2
[DEBUG] head_no[0] read E
[ATTEMPT-ERROR] target 192.168.30.200 - login "someuser" - pass "Pa$$w0rd" - child 0 - 3 of 1
[DEBUG] hydra_increase_fail_count: 3 >= 0 => disable
[DEBUG] - will be retried at the end: ip 192.168.30.200 - login someuser - pass Pa$$w0rd - child 0
[DEBUG] head_no 0, kill 1, fail 2
[DEBUG] while loop left with -1
0 of 1 target completed, 0 valid password found
[DEBUG] killing all remaining children now that might be stuck
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2022-09-22 15:17:41

**Comment by vanhauser-thc** [comment]
I just tried this and upgraded to 2.4.16.5 and for me it still works ...
what I can see in your output that the client is unable to connect to the target (port or protocol issue):
```
[DEBUG] pid 23018 called child_exit with code 2
[DEBUG] head_no[0] read E
[ATTEMPT-ERROR] target 192.168.30.200 - login "someuser" - pass "Pa$$w0rd" - child 0 - 1 of 1
```

**Comment by mehftersh0ck** [comment]
Thanks, but then I’m confused on why since I can connect via smb(2) directly. This issue only appears with hydra. Is there something else I can post?

**Comment by vanhauser-thc** [comment]
try and have a look with wireshark what is happening?

**Comment by mehftersh0ck** [comment]
Wireshark shows the transactions on VM1 (libsmbclient/libsmbclient-dev held back) and the transactions on VM2 (up to date) as the same. Both VMs are from the same image and attacking copies of the same virtual environment. The transactions include all the regular activity - session setup/negotiation, tree connect, NTLMSSP_*, etc. and a bunch of failed logins. The only notable differences are on VM2:
The account is never successfully cracked.
On failed logins (assumed), hydra displays [Error] Success (0) <- This displays repeatedly. Using just the single correct password instead of a list there are 3 of those errors.
(On VM1, failed logins are not shown in terminal as normal)

VM3 – Fresh install of kali – behaves like VM2
Do you think it is a Hyper-V issue?
Thanks

**Comment by vanhauser-thc** [comment]
as I cannot reproduce this here, can you somehow make the smb target available to me? I do not need a valid account I think

**Comment by mehftersh0ck** [comment]
What is an offline method to communicate? If you have time I can get you access into the environment.

**Comment by vanhauser-thc** [comment]
pgp key is at https://www.mh-sec.de/downloads/mh_at_mh-sec_de.asc and email address is mh(at)mh-sec.de
I might have time on thursday to have a look.

**Comment by vanhauser-thc** [comment]
fixed
