### ISSUE TITLE
Dockerfile Error. Cannot build hydra from dockerfile

### ISSUE THREAD

**Issue by hoangkm13** [vanhauser-thc/thc-hydra#797]
I have implemented your docker file example https://github.com/vanhauser-thc/thc-hydra/blob/master/Dockerfile and get this error :

Step 1/14 : FROM debian:buster-slim
 ---> 96297d782f0a
Step 2/14 : ARG HYDRA_VERSION="github"
 ---> Using cache
 ---> 31c6dbe520ac
Step 3/14 : LABEL     org.opencontainers.image.url="https://github.com/vanhauser-thc/thc-hydra"     org.opencontainers.image.source="https://github.com/vanhauser-thc/thc-hydra"     org.opencontainers.image.version="$HYDRA_VERSION"     org.opencontainers.image.vendor="vanhauser-thc"     org.opencontainers.image.title="hydra"     org.opencontainers.image.licenses="GNU AFFERO GENERAL PUBLIC LICENSE"
 ---> Using cache
 ---> 8efc088d8ce6
Step 4/14 : COPY . /src
 ---> 82ed638f1654
Step 5/14 : RUN set -x     && apt-get update     && apt-get -y install         default-libmysqlclient-dev         libgpg-error-dev         libgcrypt-dev         libpcre3-dev         libidn11-dev         libssh-dev         libssl-dev         make         curl         gcc         1>/dev/null     && c_rehash     && cd /src         && ./configure 1>/dev/null         && make 1>/dev/null         && make install     && apt-get purge -y make gcc libgpg-error-dev libgcrypt-dev     && apt-get autoremove -y     && rm -rf /var/lib/apt/lists/*     && hydra -h || error_code=$?     && if [ ! "${error_code}" -eq 255 ]; then echo "Wrong exit code for 'hydra help' command"; exit 1; fi     && echo 'hydra:x:10001:10001::/tmp:/sbin/nologin' > /etc/passwd     && echo 'hydra:x:10001:' > /etc/group
 ---> Running in 1dc45c5b01f2
+ apt-get update
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://deb.debian.org/debian-security buster/updates InRelease [34.8 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 Packages [7909 kB]
Get:5 http://deb.debian.org/debian-security buster/updates/main amd64 Packages [369 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [8788 B]
Fetched 8500 kB in 3s (3128 kB/s)
Reading package lists...
+ apt-get -y install default-libmysqlclient-dev libgpg-error-dev libgcrypt-dev libpcre3-dev libidn11-dev libssh-dev libssl-dev make curl gcc
debconf: delaying package configuration, since apt-utils is not installed
+ c_rehash
Doing /usr/lib/ssl/certs
WARNING: Skipping duplicate certificate ca-certificates.crt
WARNING: Skipping duplicate certificate ca-certificates.crt
+ cd /src
+ ./configure
/bin/sh: 1: ./configure: not found
+ error_code=127
+ [ ! 127 -eq 255 ]
+ echo Wrong exit code for 'hydra help' command
Wrong exit code for 'hydra help' command
+ exit 1
The command '/bin/sh -c set -x     && apt-get update     && apt-get -y install         default-libmysqlclient-dev         libgpg-error-dev         libgcrypt-dev         libpcre3-dev         libidn11-dev         libssh-dev         libssl-dev         make         curl         gcc         1>/dev/null     && c_rehash     && cd /src         && ./configure 1>/dev/null         && make 1>/dev/null         && make install     && apt-get purge -y make gcc libgpg-error-dev libgcrypt-dev     && apt-get autoremove -y     && rm -rf /var/lib/apt/lists/*     && hydra -h || error_code=$?     && if [ ! "${error_code}" -eq 255 ]; then echo "Wrong exit code for 'hydra help' command"; exit 1; fi     && echo 'hydra:x:10001:10001::/tmp:/sbin/nologin' > /etc/passwd     && echo 'hydra:x:10001:' > /etc/group' returned a non-zero code: 1

I want to pre-install hydra in docker container. Please help

**Comment by vanhauser-thc** [comment]
the docker file was broken, please try again with the updated repo here

**Comment by hoangkm13** [comment]
> the docker file was broken, please try again with the updated repo here

I have updated my dockerfile with your latest fix and get this error

FROM debian:buster-slim

ARG HYDRA_VERSION="github"

LABEL \
    org.opencontainers.image.url="https://github.com/vanhauser-thc/thc-hydra" \
    org.opencontainers.image.source="https://github.com/vanhauser-thc/thc-hydra" \
    org.opencontainers.image.version="$HYDRA_VERSION" \
    org.opencontainers.image.vendor="vanhauser-thc" \
    org.opencontainers.image.title="hydra" \
    org.opencontainers.image.licenses="GNU AFFERO GENERAL PUBLIC LICENSE"

COPY . /src

RUN set -x \
    && apt-get update \
    && apt-get -y install \
        #libmysqlclient-dev \
        default-libmysqlclient-dev \
        libgpg-error-dev \
        #libmemcached-dev \
        #libgcrypt11-dev \
        libgcrypt-dev \
        #libgcrypt20-dev \
        #libgtk2.0-dev \
        libpcre3-dev \
        #firebird-dev \
        libidn11-dev \
        libssh-dev \
        #libsvn-dev \
        libssl-dev \
        #libpq-dev \
        make \
        curl \
        gcc \
        1>/dev/null \
    # The next line fixes the curl "SSL certificate problem: unable to get local issuer certificate" for linux/arm
    && c_rehash

# Get hydra sources and compile
RUN cd /src \
        && make clean \
        && ./configure \
        && make \
        && make install

# Make clean
RUN apt-get purge -y make gcc \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /src

# Verify hydra installation
RUN hydra -h || error_code=$? \
    && if [ ! "${error_code}" -eq 255 ]; then echo "Wrong exit code for 'hydra help' command"; exit 1; fi \
    # Unprivileged user creation
    && echo 'hydra:x:10001:10001::/tmp:/sbin/nologin' > /etc/passwd \
    && echo 'hydra:x:10001:' > /etc/group

ARG INCLUDE_SECLISTS="true"

RUN set -x \
    && if [ "${INCLUDE_SECLISTS}" = "true" ]; then \
        mkdir /tmp/seclists \
        && curl -SL "https://api.github.com/repos/danielmiessler/SecLists/tarball" -o /tmp/seclists/src.tar.gz \
        && tar xzf /tmp/seclists/src.tar.gz -C /tmp/seclists \
        && mv /tmp/seclists/*SecLists*/Passwords /opt/passwords \
        && mv /tmp/seclists/*SecLists*/Usernames /opt/usernames \
        && chmod -R u+r /opt/passwords /opt/usernames \
        && rm -Rf /tmp/seclists \
        && ls -la /opt/passwords /opt/usernames \
    ;fi

# Use an unprivileged user
USER 10001:10001

ENTRYPOINT ["hydra"]

**Comment by hoangkm13** [comment]
@vanhauser-thc  can u continue checking this issue

**Comment by vanhauser-thc** [comment]
maybe recone the repository, because it is a problem on your system

**Comment by hoangkm13** [comment]
> maybe reclone the repository, because it is a problem on your system

I thought in DockerFile you have cloned Hydra repository and build, so what does the reclone really mean ? 

From DockerFile:

LABEL \
    org.opencontainers.image.url="https://github.com/vanhauser-thc/thc-hydra" \
    org.opencontainers.image.source="https://github.com/vanhauser-thc/thc-hydra" \

**Comment by vanhauser-thc** [comment]
reclone:

rm -rf thc-hydra
git clone ...
cd thc-hydra
docker build -t thc-hydra .
