### ISSUE TITLE
Issue during install

### ISSUE THREAD

**Issue by dumitruds** [vanhauser-thc/thc-hydra#798]
make
cc -I. -O3 -g -fcommon  -g -D_GNU_SOURCE  -o pw-inspector  pw-inspector.c
make: cc: No such file or directory
make: [Makefile:78: pw-inspector] Error 127 (ignored)
cc -I. -O3 -g -fcommon  -g -D_GNU_SOURCE -c hydra-vnc.c -DNO_STRRCHR
make: cc: No such file or directory
make: *** [Makefile:81: hydra-vnc.o] Error 127

**Comment by vanhauser-thc** [comment]
make CC=gcc
if this does not work you havent installed a compiler
