### ISSUE TITLE
Allow stdin for password files

### ISSUE THREAD

**Issue by FalcoGer** [vanhauser-thc/thc-hydra#800]
**Is your feature request related to a problem? Please describe.**
I would like to use a generator for passwords, for example hashcat or some python script. This is currently impossible.

**Describe the solution you'd like**
Using a special option or using `-` or "STDIN" as the file name should read passwords or possibly logins from STDIN.

**Describe alternatives you've considered**
```bash
mkfifo /tmp/pipe
./passwordGenerator > /tmp/pipe & hydra -l "admin" -P /tmp/pipe service://host:port
```
This doesn't work though as all the passwords are then read to be empty.

**Comment by vanhauser-thc** [comment]
you could do that now already with `./passwordGenerator > pass.txt`  and then use that file with `-P`.

to implement reading from pipes or stdin would require a large rewrite of hydra, as first hydra reads in all logins and passwords into memory and performs some calculations. and I don't have the time to do that nor do I think it is a useful feature (network cracking is slow hence if it would be a huge password list it would take years to succeed ...).
