### ISSUE TITLE
Paradox (typo) in pw-inspector man page

### ISSUE THREAD

**Issue by FalcoGer** [vanhauser-thc/thc-hydra#801]
**Describe the bug**
The password inspector man page describes the `-p` tag as

> -p     printable characters (which are not -l/-n/-p, e.g. $,!,/,(,*, etc.)

This seems to be a typo. A set of things, which it itself doesn't contain is a paradox.

**To Reproduce**

1. `man pw-inspector`
2. ???
3. no profit

**Expected behavior**
It probably means `-l/-n/-u`

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - hydra version: 9.5-dev

**Additional context**
None

**Comment by vanhauser-thc** [comment]
true, fixed
