### ISSUE TITLE
Typo in pw-inspector man page

### ISSUE THREAD

**Issue by FalcoGer** [vanhauser-thc/thc-hydra#802]
https://github.com/vanhauser-thc/thc-hydra/blob/972039b3ae2122a2aa8e9322a6f1b36fd5ef3966/pw-inspector.1#L45

`which are not \-l/\-n/\-p` should be `which are not \-l/\-u/\-n`

**Comment by vanhauser-thc** [comment]
this was fixed a day before you posted this :)

**Comment by FalcoGer** [comment]
it was fixed in the program help output, not the manual page.

**Comment by vanhauser-thc** [comment]
oh I didnt read correctly, sorry. fixed
