### ISSUE TITLE
Library not initialized.

### ISSUE THREAD

**Issue by 1949hacker** [vanhauser-thc/thc-hydra#803]
[ERROR] could not connect to ssh://*.*.*.*:22 - Library not initialized.

I encountered this problem when using it. I don't know whether it is a problem with the hydra or the target server.

**Comment by vanhauser-thc** [comment]
are you using the most current version? your linux distribution might ship an old one. better compile yourself

**Comment by 1949hacker** [comment]
I use apt install,I'll try compile,thanks for your help!
