### ISSUE TITLE
Writing Makefile.in ... now type "make"

### ISSUE THREAD

**Issue by SNA288** [vanhauser-thc/thc-hydra#804]
hi sir after enter ./configure command i enter "make" and  i got this issue 

$ ./configure

Starting hydra auto configuration ...
Detected 32 Bit Linux OS

Checking for zlib (libz/zlib.h) ...
                                ... zlib not found, gzip support disabled
Checking for openssl (libssl/libcrypto/ssl.h/sha.h) ...

    ... NOT found, SSL support disabled
Get it from http://www.openssl.org
Checking for gcrypt (libgcrypt/gpg-error.h) ...
                                            ... gcrypt not found, radmin2 module disabled
Checking for idn (libidn) ...
                          ... NOT found, unicode logins and passwords will not be supported
Checking for curses (libcurses/term.h) ...
                                       ... NOT found, color output disabled
Checking for pcre2 (libpcre/pcre.h) ...
                                    ... NOT found, server response checks will be less reliable
Checking for Postgres (libpq/libpq-fe.h) ...
                                         ... NOT found, module postgres disabled
Checking for SVN (libsvn_client-1/libapr-1/libaprutil-1) ...

         ... NOT found, module svn disabled
Checking for firebird (libfbclient) ...
                                    ... NOT found, module firebird disabled
Checking for MYSQL client (libmysqlclient/math.h) ...
                                       ... math.h not found, module Mysql disabled
Checking for AFP (libafpclient) ...
                                ... NOT found, module Apple Filing Protocol disabled - Apple sucks anyway
Checking for NCP (libncp/nwcalls.h) ...
                                    ... NOT found, module NCP disabled
Checking for SAP/R3 (librfc/saprfc.h) ...
                                      ... NOT found, module sapr3 disabled
Get it from http://www.sap.com/solutions/netweaver/linux/eval/index.asp
Checking for libssh (libssh/libssh.h) ...
                                      ... NOT found, module ssh disabled
Get it from http://www.libssh.org
Checking for Oracle (libocci/libclntsh/oci.h/libaio/liboci) ...

            ... NOT found, module Oracle disabled
Get basic and sdk package from http://www.oracle.com/technetwork/database/features/instant-client/index.html
Checking for Memcached (libmemcached/memcached.h) ...

  ... NOT found, module memcached disabled
Checking for Freerdp3 (libfreerdp3/freerdp.h/libwinpr3/winpr.h) ...

                ... NOT found, checking for freerdp2 module next...
Checking for Freerdp2 (libfreerdp2/freerdp.h/libwinpr2/winpr.h) ...

                ... NOT found, module rdp disabled
Checking for Mongodb (libmongoc-1.0/mongoc.h/libbson-1.0/bson.h) ...

                 ... NOT found, module mongodb disabled
Checking for smbclient (libsmbclient/libsmbclient.h) ...

     ... NOT found, module smb2 disabled
Checking for GUI req's (pkg-config/gtk+-2.0) ...
                                             ... NOT found, optional anyway
Checking for Android specialities ...
                                  ... strrchr() not found
Checking for secure compile option support in gcc ...

  Compiling... no

  Linking... no
Checking for --allow-multiple-definition linker option ... no

Hydra will be installed into .../bin of: /usr/local
  (change this by running ./configure --prefix=path)

Writing Makefile.in ...
now type "make"
$ make
gcc -I. -O3 -g -fcommon  -g -D_GNU_SOURCE  -o pw-inspector  pw-inspector.c
make: gcc: Command not found
make: [Makefile:78: pw-inspector] Error 127 (ignored)
gcc -I. -O3 -g -fcommon  -g -D_GNU_SOURCE -c hydra-vnc.c -DNO_STRRCHR
make: gcc: Command not found
make: *** [Makefile:81: hydra-vnc.o] Error 127

**Comment by vanhauser-thc** [comment]
`make: gcc: Command not found` ... you have not installed a compiler

**Comment by SNA288** [comment]
> `make: gcc: Command not found` ... you have not installed a compiler

thank you for answering sir
what compilers she need can you tell me or guid me?
