### ISSUE TITLE
ssh_set_client_kex: Out of memory                                                                                            

### ISSUE THREAD

**Issue by xgt6op** [vanhauser-thc/thc-hydra#808]
Hydra v9.4 (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-12-04 14:05:03
[DATA] max 4 tasks per 1 server, overall 4 tasks, 130 login tries (l:5/p:26), ~33 tries per task
[DATA] attacking ssh://10.10.207.77:22/
[ERROR] could not connect to ssh://10.10.207.77:22 - **ssh_set_client_kex: Out of memory**

Can anyone help me about this?

**Comment by vanhauser-thc** [comment]
I have never seens this issue. I would recommend compiling hydra yourself from github here and upgrading libssh-dev

**Comment by xgt6op** [comment]
Sir I have done those and also I have tried with hydra-gtk also but same problem sir

**Comment by xgt6op** [comment]
[ERROR] Compiled without LIBSSH v0.4.x support, module is not available!
 now I am getting this

**Comment by vanhauser-thc** [comment]
you have not installed libssh-dev so you have not done it correctly

**Comment by xgt6op** [comment]
I am trying sir is I get any error I will post again...I will open this issue

**Comment by xgt6op** [comment]
./hydra -L ~/Desktop/CTF/TryHackMe/bounty_hacker/user.txt -P ~/Desktop/CTF/TryHackMe/bounty_hacker/locks.txt ssh://10.10.44.90 -t4
Hydra v9.5-dev (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-12-05 14:17:47
[DATA] max 4 tasks per 1 server, overall 4 tasks, 130 login tries (l:5/p:26), ~33 tries per task
[DATA] attacking ssh://10.10.44.90:22/
[ERROR] could not connect to ssh://10.10.44.90:22 - ssh_set_client_kex: Out of memory



Sir same error after doing from the directory.I am not able to understand

**Comment by vanhauser-thc** [comment]
I cannot reproduce this issue, and it has nothing to do with hydra, it is a libssh issue or something in your system setup, sorry. you could try to use the hydra docker container: docker pull vanhauser/hydra etc.

**Comment by xgt6op** [comment]
Ok sir let me try

**Comment by itsAgasthya** [comment]
hello, i am facing this issue, how did you fix it
