### ISSUE TITLE
Optional parameters must have the format X=value

### ISSUE THREAD

**Issue by hoangkm13** [vanhauser-thc/thc-hydra#811]
This is my THC-Hydra command with json body form: 

`hydra -v -V -l abcd -p abcd -s 5000 192.168.162.130 http-post-form "/api/auth/login:{\"username\"\:\"^USER^\",\"password\"\:\"^PASS^\"}:H=Accept: application/json:H=Accept-Language: vi,en;q=0.9,en-GB;q=0.8,en-US;q=0.7:H=Accept-Encoding: gzip, deflate, br:H=Referer: http\://192.168.162.130:4200/:H=Origin: http\://192.168.162.130:4200:H=Connection: keep-alive"`

Note: 5000 is port for back-end and 4200 is port for front-end.

This is the error i get:

```
[INFORMATION] escape sequence \: detected in module option, no parameter verification is performed.
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking http-post-form://192.168.162.130:5000/api/auth/login:{"username"\:"^USER^","password"\:"^PASS^"}:H=Accept: application/json:H=Accept-Language: vi,en;q=0.9,en-GB;q=0.8,en-US;q=0.7:H=Accept-Encoding: gzip, deflate, br:H=Referer: http\://192.168.162.130:4200/:H=Origin: http\://192.168.162.130:4200:H=Connection: keep-alive
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[ERROR] optional parameters must have the format X=value:  application/json:H=Accept-Language: vi,en;q=0.9,en-GB;q=0.8,en-US;q=0.7:H=Accept-Encoding: gzip, deflate, br:H=Referer: http\://192.168.162.130:4200/:H=Origin: http\://192.168.162.130:4200:H=Connection: keep-alive
```

Where do i miss ?

**Comment by vanhauser-thc** [comment]
if you read the description or look at the examples, a colon in the content of a parameter must be quoted with a backslash.
`:H=Accept-Language\: vi:H=...`
