### ISSUE TITLE
Can't detect SMB password when it should detect

### ISSUE THREAD

**Issue by Existential-Kernel** [vanhauser-thc/thc-hydra#812]
**Describe the bug**
So I was doing a Metasploit tutorial on TryHackMe where one section covered SMB bruteforcing. After successfully finding the password using `auxiliary/scanner/smb/smb_login`, I wanted to test the speed comparison between Metasploit and hydra, but hydra somehow doesn't detect the password at all when it should (I am 100% sure I used the same wordlist). My guess is that it probably has to do with the fact that I'm using openvpn to connect to the THM room, but metasploit doesn't have this problem when I'm both running them from my host machine to bruteforce. I tried to compile hydra from source but it still can't detect the SMB password.

1. hydra -l \<user> -P \<wordlist> \<IP> smb -V
(I'm aware this is probably the most useless explanation of how I produced this bug, but I honestly don't know how to explain why it doesn't work).

**Expected behavior**
It should detect the password, but it doesn't.

**Screenshots**
https://imgur.com/a/xGan7m0

**Desktop (please complete the following information):**
 - OS: Linux Fedora 36
 - hydra version: 9.4

**Additional context**

**Comment by vanhauser-thc** [comment]
can you please try to compile from github?
`* smb2: fix for updated libsmb2 which resulted in correct guessing attempts not being detected`
