### ISSUE TITLE
Changing number of threads while resuming Hydra doesn't work

### ISSUE THREAD

**Issue by mukesh-610** [vanhauser-thc/thc-hydra#815]
**The bug**
Resuming hydra with a '-t' option after '-R' does not increase the number of threads used for cracking. All options after '-R' should be honored, according to the tool's warning as well as #184.

**To Reproduce**
- `hydra -t 4 -l bethany -P passes.txt -V rdp://172.16.0.2`
- Press <kbd>Ctrl</kbd> + <kbd>C</kbd>
- `hydra -R -t 8`

**Expected behavior**

The console output should indicate that 8 threads are running, i.e.,

```
...
[ATTEMPT] target 172.16.0.2 - login "bethany" - pass "samantha" - 3092 of 28252 [child 1] (0/0)
[ATTEMPT] target 172.16.0.2 - login "bethany" - pass "barbie" - 3093 of 28252 [child 2] (0/0)
[ATTEMPT] target 172.16.0.2 - login "bethany" - pass "chelsea" - 3094 of 28252 [child 3] (0/0)
[ATTEMPT] target 172.16.0.2 - login "bethany" - pass "lovers" - 3095 of 28252 [child 4] (0/0)
[ATTEMPT] target 172.16.0.2 - login "bethany" - pass "teamo" - 3096 of 28252 [child 5] (0/0)
[ATTEMPT] target 172.16.0.2 - login "bethany" - pass "jasmine" - 3097 of 28252 [child 6] (0/0)
...
```

**Actual behavior**

The console output shows only 4 threads running, i.e.,

```
...
[ATTEMPT] target 172.16.0.2 - login "bethany" - pass "samantha" - 3092 of 28252 [child 3] (0/0)
[ATTEMPT] target 172.16.0.2 - login "bethany" - pass "barbie" - 3093 of 28252 [child 2] (0/0)
[ATTEMPT] target 172.16.0.2 - login "bethany" - pass "chelsea" - 3094 of 28252 [child 1] (0/0)
[ATTEMPT] target 172.16.0.2 - login "bethany" - pass "lovers" - 3095 of 28252 [child 0] (0/0)
[ATTEMPT] target 172.16.0.2 - login "bethany" - pass "teamo" - 3096 of 28252 [child 3] (0/0)
[ATTEMPT] target 172.16.0.2 - login "bethany" - pass "jasmine" - 3097 of 28252 [child 2] (0/0)
...
```

**Desktop (please complete the following information):**
 - OS: Kali Linux on Docker (`kalilinux/kali-rolling:latest`)
 - Hydra v9.4

**Comment by vanhauser-thc** [comment]
yes this cannot be changed. it is not a bug though, technically is is not possible to change this.
