### ISSUE TITLE
[WARNING] child 1 seems to have died, restarting (this only happens if a module is bad) ...

### ISSUE THREAD

**Issue by jjasser** [vanhauser-thc/thc-hydra#816]
**Describe the bug**
When running the Hydra command, I am receiving the following warnings **_child 1 seems to have died, restarting (this only happens if a module is bad) ..._** or **_[WARNING] child 4 seems to have died, restarting (this only happens if a module is bad) ..._** and I'm not sure why.

**To Reproduce**
  * hydra -L /usr/share/ncrack/common.usr -P /usr/share/seclists/Passwords/rockyou-15.txt 192.168.99.22 telnet -v

I'm performing this within an openvpn network through the eJPT certificate labs.

**Expected behavior**
Output of username/password for the telnet service.

**Screenshots**
![image](https://user-images.githubusercontent.com/13125864/212257542-1384a61f-1928-40c7-9bdd-13b4699be48c.png)

**Desktop (please complete the following information):**
 - OS: Linux Linux kali 5.16.0-kali5-amd64 #1 SMP PREEMPT Debian 5.16.14-1kali1 (2022-03-15) x86_64 GNU/Linux
 - hydra version: v9.3

Thank you in advance!

**Comment by vanhauser-thc** [comment]
can you please do 2 things:
 * set `ulimit -c unlimited`, rerun and save the generated core files
 * capture the traffic with tcpdump/wireshark
then upload the capture, hydra binary and core in a zip file here?

note that the `-v` must be set before the target address not afterwards
