### ISSUE TITLE
Dictionary attack not working

### ISSUE THREAD

**Issue by poutsarxidis** [vanhauser-thc/thc-hydra#820]
**IMPORTANT**
I am doing a dictionary attack on my own account. In the text file I wrote my actual password but hydra did not manage to find it. I repeated 100 times but i cant find the problem, the password is written correctly, the command syntax is correct. BUT I DONT KNOW WHATS GOING ON. Heres the command:

hydra -l myacc -P myfile.txt instagram.com http-post-form "/accounts/login/ajax:username=^USER^&password=^PASS^&Log+In=Log+In:Sorry, your password was incorrect. Please double-check your password."

the text file looks like this:

rewtheytrhe
tyhetyhbety
h356h536yh
eytrhetyhe45yt
h54yth4yt5h
dwedwyedgw
my_password

Please help me !!

**Comment by jonathanrey87** [comment]
what os are  you using ?

**Comment by jonathanrey87** [comment]
have  you saved your pass file to you dir

**Comment by MASTREX** [comment]
Use -d parameter with single password to see request and response data and compare it with your proxy requests.

**Comment by poutsarxidis** [comment]
> have you saved your pass file to you dir

Yes it's saved in hydra's files, i am using windows

**Comment by v1ru6** [comment]
Can't you just try hydra -l myacc -P myfile.txt instagram.com http-post-form "/accounts/login/ajax:username=^USER^&password=^PASS^&Log+In=Log+In:Sorry"

**Comment by vanhauser-thc** [comment]
add -d to see what hydra actually sends and receive.
likely you need to add a cookie, use C= ... see `hydra -U http-post-form`
