### ISSUE TITLE
Hydra-Nessus Integration Isn't Working

### ISSUE THREAD

**Issue by slludwig** [vanhauser-thc/thc-hydra#821]
**Describe the bug**
We configured a new Ubuntu 20.04 LTS server with Hydra v9.0.  We can run hydra from the CLI and it works fine.  
We then installed Nessus 10.4.2 on the same system.  When we configure and run a scan, none of the plugins are firing (After  
We have worked with Tenable on this issue, but with the limited amount of documentation available, we're doubtful they will be able to help.

1. Install hydra
2. Install Nessus
3. Execute a scan with the Brute Force options selected, using user provided usernames and passwords

**Expected behavior**
There are approximately 30 plugins that Nessus uses, in conjunction with hydra, to detect default usernames/passwords.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - hydra version [e.g. current github state]: 9.0

**Comment by vanhauser-thc** [comment]
a) hydra 9.0 is old. use a current version.
b) does this sound like a hydra problem to you? it is clearly a nessus issue, maybe hydra is not in the PATH of Nessus. you pay for a commercial product so use their support, you are paying for it.
