### ISSUE TITLE
APPLICATION DID NOT START CORRECTLY

### ISSUE THREAD

**Issue by R3LEASY** [vanhauser-thc/thc-hydra#823]
i am having alot of problems i have linked the application to CMD and yes it reads it as a application but everytime i type in 'Hydra' it says 'application did not start correctly click ok to close the program' i am sure others have this problem but i cannot understand what i have to do to make this application work i am trying for about 4 days now thank you and get back to me as soon as possible.

**Comment by vanhauser-thc** [comment]
it is not a click program. you have to use cmd.exe shell and use a command line

**Comment by R3LEASY** [comment]
> 

Yes i am running it on cmd of course but it dosent let me run it it says ' this application did not start correctly click ok to close the program ' do i have to use a different code line ?

**Comment by vanhauser-thc** [comment]
have you compiled it for windows? with cygwin or something like that? this is source code, so it has to be compiled

**Comment by R3LEASY** [comment]
> have you compiled it for windows? with cygwin or something like that? this is source code, so it has to be compiled

i do have the 3 cygwin application extensions nothing is missing the only thing that isnt working is the application is not starting correctly do you have any idea how to fix this problem?

**Comment by vanhauser-thc** [comment]
I do not know. I stopped using windows many years ago ... sorry. I would search the web. if you havent started hydra.exe via the cygwin console, then try that.

**Comment by R3LEASY** [comment]
well im stuck with windows for now and yes i have tried it but it always shows me this error "cannot execute binary file: Exec format error" if you have an idea man then let me know cause im probaly taking alot of your time for this sorry.
