### ISSUE TITLE
Bug: Hydra not evaluating response headers (http-post-form) responses

### ISSUE THREAD

**Issue by ZackInMA** [vanhauser-thc/thc-hydra#828]
**Describe the bug**
Machine Used: HTB PennyWorth

When attempting to brute force the Jenkins login page, Hydra never returns success, even when providing known good credentials. 

**To Reproduce**
Run this command, subbing in the applicable IP:

hydra -l root -p password 10.129.29.2 -s 8080 http-post-form "/j_spring_security_check:j_username=^USER^&j_password=^PASS^&from=&Submit=Sign+in:F=loginError" -I -vV

The root:password is the CORRECT user login. REceive the below:

 ┌──(kali㉿PwnBox)-[~]
└─$ hydra -l root -p password 10.129.29.2 -s 8080 http-post-form "/j_spring_security_check:j_username=^USER^&j_password=^PASS^&from=&Submit=Sign+in:F=loginError" -I -vV                                           
Hydra v9.4 (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2023-03-01 21:47:49
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking http-post-form://10.129.29.2:8080/j_spring_security_check:j_username=^USER^&j_password=^PASS^&from=&Submit=Sign+in:F=loginError
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[ATTEMPT] target 10.129.29.2 - login "root" - pass "password" - 1 of 1 [child 0] (0/0)
[VERBOSE] Page redirected to http[s]://10.129.29.2:8080/
[STATUS] attack finished for 10.129.29.2 (waiting for children to complete tests)
1 of 1 target completed, 0 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2023-03-01 21:47:50
                                                                                            
The redirect to http[s]://10.129.29.2:8080/ occurs upon SUCCESSFUL login. Upon a  failed login you get this response:

HTTP/1.1 302 Found
Connection: close
Date: Thu, 02 Mar 2023 02:31:10 GMT
X-Content-Type-Options: nosniff
Set-Cookie: remember-me=; Path=/; Expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: JSESSIONID.2ef16928=node014zm6bf00syac12g71ayyoqb7v46.node0; Path=/; HttpOnly
Location: http://10.129.29.2:8080/loginError
Server: Jetty(9.4.39.v20210325)

Notice the location header... The app behaves by serving a 302 redirect to the client upon success or failure. What is different is the value in the Location: header returned in the response. So this is what needs to be evaluated. But, regardless of how I structure my command, it never works. Other examples:

//github.com/vanhauser-thc/thc-hydra) starting at 2023-03-01 21:53:13
[DEBUG] cmdline: hydra -l root -p password -s 8080 -I -vV -d 10.129.29.2 http-post-form /j_spring_security_check:j_username=^USER^&j_password=^PASS^&from=&Submit=Sign+in:F=302:H=Location: http://10.129.29.2:8080/loginError 
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking http-post-form://10.129.29.2:8080/j_spring_security_check:j_username=^USER^&j_password=^PASS^&from=&Submit=Sign+in:F=302:H=Location: http://10.129.29.2:8080/loginError
[VERBOSE] Resolving addresses ... 
[DEBUG] resolving 10.129.29.2
[VERBOSE] resolving done
[ERROR] no valid optional parameter type given: F

└─$ hydra -l root -p password 10.129.29.2 -s 8080 http-post-form "/j_spring_security_check:j_username=^USER^&j_password=^PASS^&from=&Submit=Sign+in:loginError" -I -vV   
Hydra v9.4 (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2023-03-01 21:54:08
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking http-post-form://10.129.29.2:8080/j_spring_security_check:j_username=^USER^&j_password=^PASS^&from=&Submit=Sign+in:loginError
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[ATTEMPT] target 10.129.29.2 - login "root" - pass "password" - 1 of 1 [child 0] (0/0)
[VERBOSE] Page redirected to http[s]://10.129.29.2:8080/
[STATUS] attack finished for 10.129.29.2 (waiting for children to complete tests)
1 of 1 target completed, 0 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2023-03-01 21:54:09
                                                                                     

**Expected behavior**
When Hydra does not see the loginError in the response header, it should return success.... like this:

┌──(kali㉿PwnBox)-[~]
└─$ hydra -l root -p password 10.129.29.2 -s 8080 http-post-form "/j_spring_security_check:j_username=^USER^&j_password=^PASS^&from=&Submit=Sign+in:S=302" -I -vV  
Hydra v9.4 (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2023-03-01 21:54:53
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking http-post-form://10.129.29.2:8080/j_spring_security_check:j_username=^USER^&j_password=^PASS^&from=&Submit=Sign+in:S=302
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[ATTEMPT] target 10.129.29.2 - login "root" - pass "password" - 1 of 1 [child 0] (0/0)
[8080][http-post-form] host: 10.129.29.2   login: root   password: password
[STATUS] attack finished for 10.129.29.2 (waiting for children to complete tests)
1 of 1 target successfully completed, 1 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2023-03-01 21:54:54

So it's obviously evaluating the response codes. But not the Location header value. I need it to eval the Location header value as the server always returns a 302 to the logon request, regardless of success/failure with the difference being the value of the location header. 

**Screenshots**
![image](https://user-images.githubusercontent.com/55891488/222319272-031f3479-a53a-49fc-8f02-a9a457c36d3f.png)

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - 
![image](https://user-images.githubusercontent.com/55891488/222319340-b0c02003-a644-4eb6-a750-3ca13952c79e.png)

 - hydra version 9.4
![image](https://user-images.githubusercontent.com/55891488/222319437-98dc35f1-7fa5-4810-871c-791afcd0e2a1.png)

**Additional context**
Failed Login - in Burp:
![image](https://user-images.githubusercontent.com/55891488/222320404-64045f04-003d-4fc2-a461-7ca5ed74107e.png)

Successful login - burp:

![image](https://user-images.githubusercontent.com/55891488/222320538-43835095-7cc0-4aaa-bf5d-18ad50ecd9d7.png)

**Comment by vanhauser-thc** [comment]
you need to quote the ':' if they are part of your match string (and they are).

**Comment by ZackInMA** [comment]
Let me first say thank you for getting back to me so quickly with a response. That is very much appreciated. Would it be too much to ask that you could post and example of what that quote should look like? If I understand correctly, it would look like this:

hydra -l root -p password -s 8080 -I -vV -d 10.129.29.2 http-post-form /j_spring_security_check:j_username=^USER^&j_password=^PASS^&from=&Submit=Sign+in:F=302:H=Location":" HTTP":"//10.129.29.2":"8080/loginError

I have another question, if I may. I'm wondering why this didn't work as it contains the header value for the failed attempt, but no : character. 

hydra -l root -p password 10.129.29.2 -s 8080 http-post-form "/j_spring_security_check:j_username=^USER^&j_password=^PASS^&from=&Submit=Sign+in:F=loginError" -I -vV

The response header Location contains the text loginError and there are no : in the failure match string. There are no special characters at all that would seem to require any kind of escaping.

**Comment by vanhauser-thc** [comment]
as it is documented you must escape colons with a backslash, e.g.


`hydra -l root -p password -s 8080 -I -vV -d 10.129.29.2 http-post-form '/j_spring_security_check:j_username=^USER^&j_password=^PASS^&from=&Submit=Sign+in:H=Location\\: http\\://10.129.29.2\\:8080/loginError:F=302`

**Comment by ZackInMA** [comment]
Do you think you could point me to that documentation? I've read the man page, but I couldn't locate this applicable documentation. You mention it's documented. I would love to see that so I don't waste anyone's time. I try to RTFM before opening bugs, etc. 

Also, do you know why this didn't work - as it contains no special characters in the failure string? This would suggest that it's not evaluating the Location header. 

`hydra -l root -p password 10.129.29.2 -s 8080 http-post-form "/j_spring_security_check:j_username=^USER^&j_password=^PASS^&from=&Submit=Sign+in:F=loginError" -I -vV`

**Comment by vanhauser-thc** [comment]
> Do you think you could point me to that documentation? I've read the man page, but I couldn't locate this applicable documentation. You mention it's documented. I would love to see that so I don't waste anyone's time. I try to RTFM before opening bugs, etc.

as with all modules, the modules give their usage themselves: `hydra -U http-post-form`

> Also, do you know why this didn't work - as it contains no special characters in the failure string? This would suggest that it's not evaluating the Location header.
> 
> `hydra -l root -p password 10.129.29.2 -s 8080 http-post-form "/j_spring_security_check:j_username=^USER^&j_password=^PASS^&from=&Submit=Sign+in:F=loginError" -I -vV`

you should not give command line parameters after the module options (talking about `-I -vv`) - put them before the target.
likely you are not having a valid cookie? check out the C option.
btw. that `:H=` in the request I fixed for you is something that hydra puts in it's request. that is likely not what you want.
you can add the `-d` parameter to see the exact requests and responses sent.

**Comment by ZackInMA** [comment]
Again, thank you for the quick replies. You've given me a lot of info to consume. After I get off work today I will invest the time to try what you suggest. Thanks for telling me how to get the documentation on the modules. I didn't know I could do that. Very helpful.

**Comment by ZackInMA** [comment]
I believe you helped me figure it out. However, it took a little supplemental research. The cookie from the prior page was the missing key. Thanks for the insight. That said, my command had to be different from your examples. 

If I put the cookie or header parameters in the last field, such as the module example shows, it failed. If I put it in the 3rd field and then the success/fail parameter in the last field, it works. So maybe the documentation isn't correct on this. 

Working example with both valid and invalid credentials. Cookie page in the 3rd field:

![image](https://user-images.githubusercontent.com/55891488/222867262-d033854f-c886-4022-8f36-cb1034eea6a6.png)

Not working example, but aligned with the documentation for the module. Cookie page in the 4th field:

![image](https://user-images.githubusercontent.com/55891488/222867882-3abe8868-0d24-445a-9e5d-ff14f223b82b.png)

The not working example above seems to be aligned with the documentation and last provided example:

`"/exchweb/bin/auth/owaauth.dll:destination=http%3A%2F%2F<target>%2Fexchange&flags=0&username=<domain>%5C^USER^&password=^PASS^&SubmitCreds=x&trusted=0:reason=:**C=/exchweb**"`

Is the documentation incorrect?

**Comment by vanhauser-thc** [comment]
yes that would be an incorrect (or, outdated) example. where did you find that?

**Comment by ZackInMA** [comment]
It was the output from the module, using the command you had prior mentioned. LAst example in the below.


![image](https://user-images.githubusercontent.com/55891488/222913627-8d1a0910-25a2-450e-bbe8-8729de2bd7b8.png)

**Comment by vanhauser-thc** [comment]
fixed
