### ISSUE TITLE
"#" Character confusing hydra?

### ISSUE THREAD

**Issue by 023984344324** [vanhauser-thc/thc-hydra#83]
I'm currently using the Release 8.2 on Linux against DVWA brute/dictionary vulnerability. It appears that "#" character is confusing hydra. When the character is encountered, hydra reports that the password was found. While the real password is "password".  I tested it on all the top password lists from https://wiki.skullsecurity.org/Passwords 
and while testing cain i noticed this error, the other lists worked perfectly as they didn't contain the "#" character or hydra hasn't encountered it.

>$ hydra 127.0.0.1 -V -t 1 -l admin -P pass/test-pass.txt http-form-get "/dvwa/vulnerabilities/brute/:username=^USER^&password=^PASS^&Login=Login:F=incorrect:H=Cookie: security=low; PHPSESSID=dkvknsri2j49ra3trej1umm1u5" -o hydra-result.txt

>Hydra v8.2-dev (c) 2014 by van Hauser/THC - Please do not use in military or secret service or$
>
>Hydra (http://www.thc.org/thc-hydra) starting at 2015-12-25 19:32:51
[DATA] max 1 task per 1 server, overall 64 tasks, 16 login tries (l:1/p:16), ~0 tries per task
[DATA] attacking service http-get-form on port 80
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "hydra" - 1 of 16 [child 0]
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "...." - 2 of 16 [child 0]
[ATTEMPT] target 127.0.0.1 - login "admin" - pass ",,,," - 3 of 16 [child 0]
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "&" - 4 of 16 [child 0]
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "^" - 5 of 16 [child 0]
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "%" - 6 of 16 [child 0]
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "$" - 7 of 16 [child 0]
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "/" - 8 of 16 [child 0]
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "£" - 9 of 16 [child 0]
[ATTEMPT] target 127.0.0.1 - login "admin" - pass """ - 10 of 16 [child 0]
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "!" - 11 of 16 [child 0]
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "\" - 12 of 16 [child 0]
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "|" - 13 of 16 [child 0]
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "@" - 14 of 16 [child 0]
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "@$%^&" - 15 of 16 [child 0]
[ATTEMPT] target 127.0.0.1 - login "admin" - pass "#" - 16 of 16 [child 0]
[80][http-get-form] host: 127.0.0.1   login: admin   password: #
1 of 1 target successfully completed, 1 valid password found
Hydra (http://www.thc.org/thc-hydra) finished at 2015-12-25 19:32:51

Debug:
[hydra-debug.txt](https://github.com/vanhauser-thc/thc-hydra/files/72247/hydra-debug.txt)

**Comment by vanhauser-thc** [comment]
if you take a look at the debug output you see that the result web page does not contain "incorrect" and therefore is reported as successful.
maybe its because it would need to be encoded. I will look into that.

**Comment by vanhauser-thc** [comment]
wanted to sit down to implement it, and saw that the person who wrote the module already had an encoding function in it - with a bug that did not encode the # sign :)
fixed, please test.

**Comment by vanhauser-thc** [comment]
can you please check?

**Comment by vanhauser-thc** [comment]
timeout ... closing the issue
