### ISSUE TITLE
proxy variable causing duplicate port 

### ISSUE THREAD

**Issue by eko-wibowo** [vanhauser-thc/thc-hydra#836]
**IMPORTANT**
This is just for reporting *BUGS* not help on how to hack, how to use hydra, command line options or how to get it compiled. Please search for help via search engines. Issues asking for this here will be closed.

**Describe the bug**
Using HYDRA_PROXY_HTTP (proxy is burpsuite listening on default 127.0.0.1:8080) seems to be causing invalid URL 
https://pastebin.com/gngHi2SL

Command I ran: `HYDRA_PROXY_HTTP="http://127.0.0.1:8080"  hydra -L users.txt -p 'jenkins' 10.0.2.80 -s 8080 http-post-form "/j_sprint_security_check:j_username=^USER^&j_password=^PASS^&Submit=Sign+in:F=invalid" -d`

Search for "8080:8080" it seems the port number is duplicated causing invalid URL, for example 

```
HTTP request sent:[0A]POST http://10.0.2.80:8080:8080/j_sprint_security_check HTTP/1.0[0D][0A]Host: 10.0.2.80:8080[0D][0A]User-Agent: Mozilla/5.0 (Hydra Proxy)[0D][0A]Content-Length: 52[0D][0A]Content-Type: application/x-www-form-urlencoded[0D][0A][0D][0A]j_username=jenkins&j_password=jenkins&Submit=Sign+in[0A]
```

**To Reproduce**
  * Ensure that you have tested the bug to be present in the current github code. You might be using an outdated version that comes with your Linux distribution!
  * You must provide full command line options.

1. Run the command above
2. Observe debug log to see the URL 
3. ...

**Expected behavior**
The target URL should be `<url>:<port>` in this case `10.0.2.80:8080`

**Screenshots**
Note that all messages must be in *English*, not in Chinese, Russian, etc.

**Desktop (please complete the following information):**
 - OS: Kali Linux Purple
```
$ uname -a
Linux kali 6.1.0-kali7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-1kali1 (2023-03-22) x86_64 GNU/Linux
```
 - hydra version 
```
$ hydra       
Hydra v9.4 (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).
```

**Comment by vanhauser-thc** [comment]
this is already fixed in this github repository, just check it out and compile it.
