### ISSUE TITLE
Add support for postgreSQL

### ISSUE THREAD

**Issue by wpf97** [vanhauser-thc/thc-hydra#837]
Add support for brute force guessing in PostgreSQL

**Comment by vanhauser-thc** [comment]
already there

**Comment by wpf97** [comment]
hydra -l admin -p admin 127.0.0.1 postgres
Hydra v9.4 (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2023-04-06 17:52:21
[ERROR] Compiled without LIBPOSTGRES support, module not available!
