### ISSUE TITLE
How to log successful passwords

### ISSUE THREAD

**Issue by 3kh0** [vanhauser-thc/thc-hydra#841]
Say I am attacking a server with a few usernames and a ton of passwords, the password file contains the password for each account, how can I make it so it would log the successful login pairs for later use?

**Comment by Mhagne** [comment]
![image](https://user-images.githubusercontent.com/106419285/235273090-74d49e87-cf1c-4a45-91ed-2efa83c96646.jpeg)

**Comment by Mhagne** [comment]
Even though I put the correct password, it does not give me the reason

**Comment by vanhauser-thc** [comment]
maybe check out the options to hydra? hydra -h ...
