### ISSUE TITLE
The Manual does not explain how to use special characters for -x brute force

### ISSUE THREAD

**Issue by bugith** [vanhauser-thc/thc-hydra#844]
On the way to retrieve my password I was stopped by the limits of -x as I only know the login name and max password length (8).

But I hit another wall : we can't use many special characters among the 95 ascii printable set e.g. -x 1:1: seebelow

I had to escape them with \
Although I'm not sure I didn't specified too much backslashed and if this can have bad impact on operation, that is the unrequired backslashes would be treated as as many new character.
```
hydra -I -l admin -x 1:1:aA1\ \&~#\"\'{\([-\|\`_^@\)]=}$%*?./§,\;:! -v -c1 -t1 http-get://192.1....
```

**Comment by vanhauser-thc** [comment]
obviously this option is tricky for special characters as not everything can be displayed easily on the command line.
But how it is usually done is putting it all in quotes, then you need no escaping except when you need that quote character as well:.
e.g. `-x '1:1:aA1 &~#"\'{([-|`_^@)]=}$%*?./§,;:!' -v

**Comment by bugith** [comment]
Nice. I tried (surely a wrong way then ,maybe with double or back quotes) but failed.
It would also be worth stating in the man if blank-space is part of lower case or upper case set, or none of them what I feel is better. for disambiguation.
Thank you

**Comment by vanhauser-thc** [comment]
some things are obvious. a space has no case, so it is neither uppercase nor lowercase nor a digit.
