### ISSUE TITLE
Need help now 

### ISSUE THREAD

**Issue by amanpatel6778** [vanhauser-thc/thc-hydra#847]
What command i use for instgram brute force give me the command. when i use any command learning by YouTube in termux then your tool show me "yara pkg" 
So please help me because i am beginner 😭😭😭  I don't know anything.
And you closed my issue without giving me any suggestions.
😭😭😭
![Screenshot_2023-05-15-15-02-33-89_84d3000e3f4017145260f7618db1d683](https://github.com/vanhauser-thc/thc-hydra/assets/133213854/cbd0992d-f107-445d-97d0-a251aacefab2)

**Comment by vanhauser-thc** [comment]
this is not a help forum
