### ISSUE TITLE
hydra -l msfadmin -p /usr/share/wordlists/rockyou.txt -t 4 -V ftp://192.168.9.48    not working 

### ISSUE THREAD

**Issue by abhijeet11yadav** [vanhauser-thc/thc-hydra#849]
Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2023-05-31 11:13:44
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking ftp://192.168.9.48:21/
[ATTEMPT] target 192.168.9.48 - login "msfadmin" - pass "/usr/share/wordlists/rockyou.txt" - 1 of 1 [child 0] (0/0)
1 of 1 target completed, 0 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2023-05-31 11:13:48

i found this and i am not able to increase task from 1 to 16 or more please help me anyone

**Comment by MASTREX** [comment]
Capital -P for wordlist

**Comment by abhijeet11yadav** [comment]
> Capital -P for wordlist Check the help section with 'hydra -h'

thanks for help i found it
