### ISSUE TITLE
error

### ISSUE THREAD

**Issue by apkmodz** [vanhauser-thc/thc-hydra#854]
cc -I. -O3 -g -fcommon -Wl,--allow-multiple-definition  -g  -c hydra-nntp.c -DNO_STRRCHR                                                    clang-16: warning: -Wl,--allow-multiple-definition: 'linker' input unused [-Wunused-command-line-argument]                                  hydra-nntp.c:36:20: error: call to undeclared library function 'rindex' with type 'char *(const char *, int)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]          if ((ptr = rindex(buf, '\n')) != NULL) {
                   ^
hydra-nntp.c:36:20: note: include the header <strings.h> or explicitly provide a declaration for 'rindex'                                   1 error generated.
make: *** [Makefile:80: hydra-nntp.o] Error 1
cc -I. -O3 -g -fcommon -Wl,--allow-multiple-definition  -g  -c hydra-nntp.c -DNO_STRRCHR
clang-16: warning: -Wl,--allow-multiple-definition: 'linker' input unused [-Wunused-command-line-argument]
hydra-nntp.c:36:20: error: call to undeclared library function 'rindex' with type 'char *(const char *, int)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        if ((ptr = rindex(buf, '\n')) != NULL) {
                   ^
hydra-nntp.c:36:20: note: include the header <strings.h> or explicitly provide a declaration for 'rindex'
1 error generated.
make: *** [Makefile:80: hydra-nntp.o] Error 1
cp: cannot stat 'hydra': No such file or directory

**Comment by vanhauser-thc** [comment]
no mentioning of on what operating system you on, or what compiler you are using... what should I do with such a bad issue report?

**Comment by francisuk1989** [comment]
> no mentioning of on what operating system you on, or what compiler you are using... what should I do with such a bad issue report?

I would say close any bad reports. The bug report template is stright forward.
