### ISSUE TITLE
Optional parameters in http-post-form not working

### ISSUE THREAD

**Issue by daniruiz** [vanhauser-thc/thc-hydra#855]
The optional parameters in http-post-form module fail with the error message `[ERROR] optional parameters must have the format X=value: false:H=Cookie`. 

I've tested also scaping the colon in `Cookie` as I've seen that somewhere, but no luck. Testing the examples shown by `hydra -U http-post-form` give the same result

`hydra -L xato-net-10-million-usernames-dup.txt -p '' 192.168.188.211 http-post-form '/election/admin/ajax/login.php:step=1&noinduk=^USER^:false:H=Cookie: blocked_num=-997'`

` hydra -L xato-net-10-million-usernames-dup.txt -p '' 192.168.188.211 http-post-form '/election/admin/ajax/login.php:step=1&noinduk=^USER^:false:H=Cookie\: blocked_num=-997'`
![image](https://github.com/vanhauser-thc/thc-hydra/assets/12565871/b2402459-57d8-46a5-8601-0fb6ff985142)

I'm currently using hydra 9.4

**Comment by vanhauser-thc** [comment]
1. update the version
2. read the docs/help output how to specify the options correctly
