### ISSUE TITLE
Testing if password authentication is supported by ssh://*.*.*.*:22

### ISSUE THREAD

**Issue by dfrankes** [vanhauser-thc/thc-hydra#86]
Hi there, 

Hydra keeps getting stuck on Testing if password authentication is supported by ssh://*.*.*.*:22 after a few tests. Running CentOS (Hydra 1.8)

**Comment by vanhauser-thc** [comment]
please send in a debug output ... add "-t 1 -dvV" options

**Comment by b42lat3** [comment]
I am also having the same issue

here is a snippet of my log

[ERROR] could not connect to target port 22
[ERROR] ssh protocol error
[VERBOSE] Retrying connection for child 5
[ERROR] could not connect to target port 22
[ERROR] ssh protocol error
[VERBOSE] Retrying connection for child 3
[ERROR] could not connect to target port 22
[ERROR] ssh protocol error
[VERBOSE] Retrying connection for child 4
[ERROR] could not connect to target port 22
[ERROR] ssh protocol error
[ERROR] could not connect to target port 22
[ERROR] ssh protocol error
[VERBOSE] Retrying connection for child 1
[VERBOSE] Retrying connection for child 2
[ERROR] could not connect to target port 22
[ERROR] ssh protocol error
[VERBOSE] Retrying connection for child 0
[ERROR] could not connect to target port 22

**Comment by b42lat3** [comment]
the command I am running is 

hydra 192.168.33.251 ssh -l root -P password-file.txt -t 6 -v

Thank you for any help

**Comment by vanhauser-thc** [comment]
can you please send the full output with -vVdt 1  ?

**Comment by dfrankes** [comment]
it doesnt say anything diffrent when i add that.

**Comment by dfrankes** [comment]
hydra -l users.txt -p passwd.txat -M hosts.txt -o output.txt -fservice ssh -d -v -w 10 -t 4 -dvV -vVdt 1

**Comment by vanhauser-thc** [comment]
hydra -l users.txt -p passwd.txt -M hosts.txt -o output.txt -dvV -t 1 -w 10 SERVER ssh

please post all output.

**Comment by dfrankes** [comment]
[DEBUG] Ouput color flag is 0
Hydra (http://www.thc.org/thc-hydra) starting at 2016-01-16 11:09:34
[DEBUG] cmdline: hydra -l users.txt -p passwd.txt -M hosts.txt -o output.txt -dvV -t 1 -w 10 SERVER ssh
[WARNING] With the -M FILE option you can not specify a server on the commandline. Lets hope you did everything right!
[ERROR] Unknown service: SERVER
[root@cyka hydra-8.1]#

**Comment by dfrankes** [comment]
The output doesnt change, After like 10/20 hosts it just keeps getting stuck @ Testing if password authentication is supported by ssh://*.*.*.*:22

**Comment by dfrankes** [comment]
Also i added the root / password for 1 of the target machine in the hosts.txt and removed like 90% of the hosts in the file, It still doesnt find correct username / password

**Comment by vanhauser-thc** [comment]
Ah sorry, I quoted the command line wrong:
hydra -l users.txt -p passwd.txt -M hosts.txt -o output.txt -dvV -t 1 -w 10 ssh
but it is OK to do some thinking on your own, pal.

dont give me any more error description. without full debug output I can not do anything.

**Comment by dfrankes** [comment]
Like i said before This is the only debug output im getting:

[INFO] Testing if password authentication is supported by ssh://*.*.*.*
[ERROR] target ssh://*.*.*.*:22/ does not support password authentication
[INFO] Testing if password authentication is supported by ssh://*.*.*.*
^ Stuck right here. There isnt any other output.

**Comment by vanhauser-thc** [comment]
On which operating system does that happen?

I could reproduce the problem, but only on Cygwin and only after I updated my installation (last update 6 months old). Then all OpenSSL based functions break - including SSH which needs openssl for the crypto.

On different Linux installations it runs fine without problems.

**Comment by dfrankes** [comment]
This is a brand new machine with CentOS 

CentOS release 6.7 (Final)

Its updated.

**Comment by vanhauser-thc** [comment]
can you please try? it is fixed hopefully.

**Comment by vanhauser-thc** [comment]
Can you please check?

**Comment by vanhauser-thc** [comment]
timeout ... closing the issue
