### ISSUE TITLE
DYLIB error after running for second time

### ISSUE THREAD

**Issue by tschijvenaars** [vanhauser-thc/thc-hydra#864]
Getting the following after a fresh install:
dyld[52886]: Library not loaded: /usr/lib/libpcre2-8.0.dylib

and the following:

Referenced from: <BD0536E4-645A-3038-92FB-C77AFDBB0C63> /opt/homebrew/Cellar/hydra/9.5_1/bin/hydra Reason: tried: '/usr/lib/libpcre2-8.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/libpcre2-8.0.dylib' (no such file), '/usr/lib/libpcre2-8.0.dylib' (no such file, not in dyld cache), '/usr/local/lib/libpcre2-8.0.dylib' (no such file) zsh: abort 

No idea why it happens, got this after running one command run succesfully (so it worked, then I aborted, next time i ran an hydra command it stopped working)

Running version 9.5_1

**Comment by vanhauser-thc** [comment]
I would update your brew installation and then recompile hydra.
looks like you did a brew update and then the libraries were updated to a newer version

**Comment by tschijvenaars** [comment]
Any particular way how to do this in brew? Tried to brew rm, brew install-from-source but this won't do the trick.

**Comment by vanhauser-thc** [comment]
I think maybe: brew update ; brew upgrade ; cd thc-hydra ; make clean ; make ; sudo make install
but I do not have a mac
