### ISSUE TITLE
Feature request: parseable output file format

### ISSUE THREAD

**Issue by MarioVilas** [vanhauser-thc/thc-hydra#865]
**Is your feature request related to a problem? Please describe.**
I'm trying to integrate Hydra with other tools and I'm finding the output file format a bit lacking for this particular use case. While a human can easily read it, it's not hard for a regex based parser to trip up on it, for example if the password contains the string "password:".

**Describe the solution you'd like**
I'd like any standard output format to be used instead - JSON, YML, whatever you like, as long as there is a parser for it. I'd stay away from custom formats since writing custom parsers is neither fun nor safe.

**Describe alternatives you've considered**
I could keep iterating on my regex but this is generally a bad idea. Like they say, if you have a problem and you try to solve it with regular expressions, now you have two problems.

**Comment by vanhauser-thc** [comment]
Hi,
that is a useful idea. note that I am just maintaining hydra anymore, not adding new features. But i accept pull requests, so you can implement it in a useful way for you and for others and I will merge it.

**Comment by R-Rothrock** [comment]
What about the `-b` option?

From `hydra -h`
`  -b FORMAT specify the format for the -o FILE: text(default), json, jsonv1`

It doesn't have YML or XML, but it has JSON... or do you have something else in mind?

**Comment by MarioVilas** [comment]
I must be blind, because I completely missed the -b option. Sorry for the noise!
