### ISSUE TITLE
-x argument -> [ERROR] No login/password combination given!

### ISSUE THREAD

**Issue by gentilvirus** [vanhauser-thc/thc-hydra#87]
-x argument does not seems to be considered as password in hydra 8.1; running the command:

`hydra -l testuser -x 3:4:A1 -f telnet://192.168.1.1`

gives the following error:

`[ERROR] No login/password combination given!`

isn't -x supposed to replace a generated password file (-P) ?

**Comment by vanhauser-thc** [comment]
when I copy/paste your command line, it works for me.
update to 8.2-dev please from this github

**Comment by vanhauser-thc** [comment]
can you please check?

**Comment by gentilvirus** [comment]
Actually it seems the error occurs when the min lenght is 13 or above.

Try with -x 14:15:A1 for example

**Comment by vanhauser-thc** [comment]
did you update to 8.2-dev?
because also with x 14:... I do not get an error

**Comment by gentilvirus** [comment]
sorry for the late reply.
I just made another test with v8.2-dev but I still have the problem... until 12 characters, it works fine as from 13, if gives the error:

`hydra -l testuser -x 13:13:A1 -f telnet://192.168.1.1
Hydra v8.2-dev (c) 2016 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

Hydra (http://www.thc.org/thc-hydra) starting at 2016-02-05 18:17:31
[WARNING] telnet is by its nature unreliable to analyze, if possible better choose FTP, SSH, etc. if available
[ERROR] No login/password combination given!`

**Comment by vanhauser-thc** [comment]
fixed it, although you will not like it.
hydra will now bail with the correct error message - too many passwords from -x definiton

**Comment by gentilvirus** [comment]
okay, thank you.
since it was working with you, I guess it depends on the CPU of the machine?

**Comment by vanhauser-thc** [comment]
no.
it was a but that it allowed more than 4 billion :)
