### ISSUE TITLE
http-post-form: H=Cookie\: password=^PASS^ only uses the top few entries from a passwordlist 

### ISSUE THREAD

**Issue by CoenTempelaars** [vanhauser-thc/thc-hydra#871]
**Describe the bug**
When using http-post-form optional parameter `H=Cookie\: password=^PASS^` in combination with a passwordlist of 6 entries and -t defaults to 2, then 6 cookies are sent, but only the top 2 entries in the passwordlist are used.

(When -t defaults to 16 only the top 16 entries in the passwordlist are used)

**To Reproduce**
1. Pull the latest 9.5-dev (where [issue 863](https://github.com/vanhauser-thc/thc-hydra/issues/863) is solved)
2. Spin up a php server serving the document below
3. Create a passwordlist of 6 entries: 1, 2, 3, 4, 5 and 6
4. Attack the php server with hydra: `hydra -d -t 2 -l admin -P passwordlist -m "/:fname=^USER^:G=:H=Cookie\: password=^PASS^:failed" http-post-form://127.0.0.1`
5. Observe that hydra does 6 different attempts with only 2 different cookies:

```
[ATTEMPT] target ... - login "admin" - pass "1" - 1 of 6 [child 0] (0/0)
Cookie:  PHPSESSID=2
[ATTEMPT] target ... - login "admin" - pass "2" - 2 of 6 [child 1] (0/0)
Cookie:  PHPSESSID=1
[ATTEMPT] target ... - login "admin" - pass "3" - 3 of 6 [child 0] (0/0)
Cookie:  PHPSESSID=1
[ATTEMPT] target ... - login "admin" - pass "4" - 4 of 6 [child 1] (0/0)
Cookie:  PHPSESSID=2
[ATTEMPT] target ... - login "admin" - pass "5" - 5 of 6 [child 0] (0/0)
Cookie:  PHPSESSID=2
[ATTEMPT] target ... - login "admin" - pass "6" - 6 of 6 [child 1] (0/0)
Cookie:  PHPSESSID=1
```

**Expected behavior**
Six different cookies with values 1 till 6.

**Desktop (please complete the following information):**
 - OS: Kali Linux 2022.4
 - hydra version 9.5-dev

**Additional context**
```
<html>
<body>

<form method="post" action="<?php echo $_SERVER['PHP_SELF'];?>">
  Name: <input type="text" name="fname">
  <input type="submit">
</form>

<?php
print_r($_COOKIE);
?>

</body>
</html>
```

**Comment by vanhauser-thc** [comment]
why should have get a new cookie?  the server gave none and the two childs already have all the cookies they need.
you might want to use the module C option.
