### ISSUE TITLE
Make install

### ISSUE THREAD

**Issue by Eugenexjay** [vanhauser-thc/thc-hydra#872]
cc -I. -O3 -g -fcommon  -g -D_GNU_SOURCE  -o pw-inspector  pw-inspector.c
make: cc: No such file or directory
make: [Makefile:78: pw-inspector] Error 127 (ignored)
cc -I. -O3 -g -fcommon  -g -D_GNU_SOURCE -c hydra-vnc.c -DNO_STRRCHR
make: cc: No such file or directory
make: *** [Makefile:81: hydra-vnc.o] Error 127

=============

Hydra installation error please help me ???

**Comment by vanhauser-thc** [comment]
install a compiler

**Comment by Eugenexjay** [comment]
> install a compiler

How to install compiler ???

Please help me !

**Comment by MASTREX** [comment]
Install gcc by searching online how to install

**Comment by shibashisdey** [comment]
still not working after installing gcc
