### ISSUE TITLE
Make install error ???

### ISSUE THREAD

**Issue by Eugenexjay** [vanhauser-thc/thc-hydra#874]
Now type make install
strip hydra pw-inspector
make: strip: No such file or directory
make: [Makefile:84: strip] Error 127 (ignored)
echo OK > /dev/null && test -x xhydra && strip xhydra || echo OK > /dev/null
mkdir -p /usr/local/bin
mkdir: cannot create directory ‘/usr’: Read-only file system
make: [Makefile:88: install] Error 1 (ignored)
cp -f hydra-wizard.sh hydra pw-inspector /usr/local/bin && cd /usr/local/bin && chmod 755 hydra-wizard.sh hydra pw-inspector
cp: target '/usr/local/bin': No such file or directory
make: *** [Makefile:89: install] Error 1

root@localhost$ ___

Please help me ???
============================

**Comment by vanhauser-thc** [comment]
sudo make install
