### ISSUE TITLE
0 valid passwords found

### ISSUE THREAD

**Issue by Louisj007** [vanhauser-thc/thc-hydra#875]
Hi, I have tried all verions from Hydra but nothing works I hope you can help.

This is my command: hydra -l username -P password list -V instagram.com http-post-form "/accounts/login/ajax:username=^USER^&password=^PASS^&Log+In=Log+In:Sorry, your password was incorrect. Please double-check your password."

Everything works but at the end it says: 1/1 taks completed, 0 valid passwords found. 

Can anyone help?

**Comment by vanhauser-thc** [comment]
add the -d flag and see what of your options are wrong to what the server expects
