### ISSUE TITLE
-t 1 -W 60 not work

### ISSUE THREAD

**Issue by pythonmandev** [vanhauser-thc/thc-hydra#879]
I use "hydra -L ./user.txt -P ./pass.txt -M ./22_iplist.txt -e nsr -o ./log.txt -t 1 -W 60 -v ssh" to crack the ssh service, but it seems the "-t 1 -W 60" not work.
It did not sleep 60 seconds between each try.

Hydra v9.5 (c) 2023 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2023-08-04 22:54:24
[DATA] max 1 task per 494 servers, overall 64 tasks, 44 login tries (l:4/p:11), ~340 tries per task
[DATA] attacking ssh://(494 targets):22/
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[INFO] Testing if password authentication is supported by ssh://root@192.168.100.1:22
[INFO] Successful, password authentication is supported by ssh://192.168.100.1:22
[INFO] Testing if password authentication is supported by ssh://root@192.168.100.10:22
[INFO] Successful, password authentication is supported by ssh://192.168.100.10:22
[INFO] Testing if password authentication is supported by ssh://root@192.168.100.100:22
[INFO] Successful, password authentication is supported by ssh://192.168.100.100:22
[INFO] Testing if password authentication is supported by ssh://root@192.168.100.120:22
[INFO] Successful, password authentication is supported by ssh://192.168.100.120:22
[INFO] Testing if password authentication is supported by ssh://root@192.168.100.121:22
[INFO] Successful, password authentication is supported by ssh://192.168.100.121:22
[INFO] Testing if password authentication is supported by ssh://root@192.168.100.139:22
[INFO] Successful, password authentication is supported by ssh://192.168.100.139:22
[INFO] Testing if password authentication is supported by ssh://root@192.168.100.150:22
^C[ERROR] Received signal 2, going down ...

real    0m1.035s
user    0m0.091s
sys     0m0.009s

**Comment by vanhauser-thc** [comment]
oh true, that option was only supported in module that do not use a library for authentication. fixed. thanks for reporting.
