### ISSUE TITLE
one by one question

### ISSUE THREAD

**Issue by shadowfolder** [vanhauser-thc/thc-hydra#88]
Guys, hydra checking passwords like
test@gmail.com:pass
test@gmail.com:pass1
test@gmail.com:pass2
test@gmail.com:pass3

How i configure request if i have list with
test1@gmail.com:pass1
test@gmail.com:pass2
and want that requests was only sended every line new email and password?

**Comment by vanhauser-thc** [comment]
-C option.
this is not a help forum
