### ISSUE TITLE
Issues With Bruteforcing a json Web login

### ISSUE THREAD

**Issue by JewyOG** [vanhauser-thc/thc-hydra#880]
Hey THC, ive recently started to get into cybersecurity but apart from a bit of THM i havent had any real world use for it. im currently learning how to bruteforce .json webserver logins with hydra but i havent really had success, the command im currently running is the following : 

"
passwords=$(crunch 16 16 ASDFGHVBNM012 -t \!\@@@@@@HMDM2021\#) | hydra -V -l "admin" -P "<(echo "$passwords")" -s 80 192.168.2.69 http-post-form "/#/login:{\"login\"\:\"admin\",\"password\"\:\"^PASS^\"}\:\changeFirstName\:\H=Accept\:\ application/json, text/plain, */*\:\H=Accept-Language\:\ en-US,en;q=0.5\:\H=Accept-Encoding\:\ gzip, deflate:H=Referer\:\ http\://80 192.168.2.69/:\H=Origin\:\ http\://80 192.168.2.69\:\H=Connection\:\ keep-alive"
"

im creating a custom password list in crunch and creating a variable for it so i can pipe it straight to hydra without having to make a huge list , the crunch part is also shortened down a bit just so i can see if the command works quicker as it doesnt have to generate as many passwords, the issues ive been having are the following : 

**if i run the command as i showed above i get the issue** 
" zsh: argument list too long: hydra"

**if i pregenerate the variable in its own command and then run the hydra command with the "<(echo "$passwords")"**
it tells me that it couldnt find the list for passwords, i tried both -p and -P even replacing the first " in the echo command with '

**and if i remove the crunch pipe to hydra and run this command and hardcode the password "admin"**
"
hydra -V -l "admin" -p "admin" -s 80 192.168.2.69 http-post-form "/#/login:{\"login\"\:\"admin\",\"password\"\:\"^PASS^\"}\:\changeFirstName\:\H=Accept\:\ application/json, text/plain, */*\:\H=Accept-Language\:\ en-US,en;q=0.5\:\H=Accept-Encoding\:\ gzip, deflate:H=Referer\:\ http\://80 192.168.2.69/:\H=Origin\:\ http\://80 192.168.2.69\:\H=Connection\:\ keep-alive"
"
the command actually goes thru but i get this message :
"
Hydra v9.4 (c) 2022 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2023-08-09 09:28:31
[INFORMATION] escape sequence \: detected in module option, no parameter verification is performed.
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking http-post-form://192.168.2.69:80/#/login:{"login"\:"admin","password"\:"^PASS^"}\:\changeFirstName\:\H=Accept\:\ application/json, text/plain, */*\:\H=Accept-Language\:\ en-US,en;q=0.5\:\H=Accept-Encoding\:\ gzip, deflate:H=Referer\:\ http\://80 192.168.2.69/:\H=Origin\:\ http\://80 192.168.2.69\:\H=Connection\:\ keep-alive
[ATTEMPT] target 192.168.2.69 - login "admin" - pass "admin" - 1 of 1 [child 0] (0/0)
[ERROR] Child with pid 23311 terminating, cannot connect
[REDO-ATTEMPT] target 192.168.2.69 - login "admin" - pass "admin" - 2 of 2 [child 0] (1/1)
[ERROR] Child with pid 23336 terminating, cannot connect
[REDO-ATTEMPT] target 192.168.2.69 - login "admin" - pass "admin" - 3 of 3 [child 0] (2/2)
[ERROR] Child with pid 23361 terminating, cannot connect
[ERROR] all children were disabled due too many connection errors
0 of 1 target completed, 0 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2023-08-09 09:28:40
"

it just tells me that it couldnt connect to the website and after 3 attempts it disables the children
this also happens when i use the right password instead of admin.

as i said im fairly new to cybersecurity and also hydra, ive been trying to get this to work for prolly like 5 days now and havent gotten anywhere it would be greatly appreciated i you could help me with my command or even tell me what im doing wrong as im at the end :D

Kind Regards
JewyOG

**Comment by R-Rothrock** [comment]
First things first, can you try the first variation (the one with the "too many args" issue) in Bash? It's possible this is just one of Zsh's kinks.

**Comment by JewyOG** [comment]
hey, ty for the reply ill test it out tmr, i just noticed that all the commands i sent were changed by github? theres a lot of "\"s missing for some reason, ill send the proper command in here tmr, not sure why it was changed.
anyways ty for the reply ill get back to you soon

**Comment by JewyOG** [comment]
the original command has a \ infront of every :/ and also a \ infront of the defined crunch pattern infront of the !@@@@

**Comment by vanhauser-thc** [comment]
you do something that cannot work. read the docs and examples. and sorry, this is not a help forum, this is just for bugs.
