### ISSUE TITLE
Hydra password file not found

### ISSUE THREAD

**Issue by bradley1999** [vanhauser-thc/thc-hydra#89]
Hello,
I am a new Hydra user 8.8_1 on Terminal, Mac OSX 10.10.4
I have an error each time I try to run it. I am trying to find the password of an ethernet connected router I have bought with the default password (admin/1234) disabled, and can't be reset with a factory reset.

For example this       hydra -l admin -P /root/Desktop/passwords/passwd.txt 192.168.1.1 http-get /
returns this                File for passwords not found: /root/Desktop/passwords/passwd.txt

I have a list of .txt files in a folder called passwords on desktop. I have tried various options with -p and -P, and different paths to the password list, but same problem.

Am I doing something obviously wrong? 
Thanks

**Comment by vanhauser-thc** [comment]
well what happens if you do an "ls /root/Desktop/passwords/passwdtxt" ?
(seems you are missing a "." in passwd.txt though)

**Comment by bradley1999** [comment]
Hi,
Thanks for the heads up.
I replaced the missing “.” and used p (instead of P) which does find the path to the /txt file. P shows file not found.

Here is my command to the router which I know the login details for -  hydra -l admin -p /root/Desktop/passwords/phpbb.txt 192.168.0.1 http-get /

Here is the reply- Hydra (http://www.thc.org/thc-hydra) starting at 2016-01-24 00:04:24
[DATA] max 1 task per 1 server, overall 64 tasks, 1 login try (l:1/p:1), ~0 tries per task
[DATA] attacking service http-get on port 80
1 of 1 target completed, 0 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2016-01-24 00:04:24

The password file called phpbb.txt is 1.6MB, with several thousand words, but Hydra only lists 64 tries! I don’t think it is reading them all.
“admin" is the router login (not found) and “password" is the password, which is contained in the .txt file. 
is the p/P making a difference here?

**Comment by vanhauser-thc** [comment]
this is not a help forum.
-P and not -p for files. if it can not find the file you specified the wrong path/name.
64 tasks it the maximum number of parallel attacks.

**Comment by EvictionnNoticee** [comment]
Same Problem

**Comment by ImmortlLucifer** [comment]
[ERROR] File for passwords not found: passwords.txt in hydra

**Comment by CesarBeltran** [comment]
[Proven solution]
Do not run the command like this:
hydra -L admin -P pass.lst 192.168.124.131 ssh


instead, create a file containing the user or list of users you want to test.
example:
hydra -L users.txt -P pass.lst 192.168.124.131 ssh 


└─# cat users.txt                     
admin
user
administrator
kali
....
....

**Comment by Logan0112** [comment]
Bom dia...valeu

Em seg., 23 de set. de 2024 14:52, Cesar Ramiro Beltrán Hernandez <
***@***.***> escreveu:

**Comment by YugandharrPatil** [comment]
if you're running hydra via a docker container (you installed it using docker, you'll need to supply a path relative to the location of hydra in that container).

```bash
docker run -it --rm -v /opt:/host_opt vanhauser/hydra
hydra -l kay -P /host_opt/SecLists/Passwords/Leaked-Databases/rockyou.txt $IP ssh
```

the above will work if that's the case.
