### ISSUE TITLE
Termux error with command hydra

### ISSUE THREAD

**Issue by NeverGonaLetYouCry** [vanhauser-thc/thc-hydra#894]
When i type my hydra command it says: No command hydra found, did you mean:
 Command yara in package yara

And btw im on termux

**Comment by MASTREX** [comment]
You need to install it first, most probably by compiling it from the source

**Comment by NeverGonaLetYouCry** [comment]
I already installed hydra too

**Comment by MASTREX** [comment]
There might be error in the installation, check the proces output about the final status. Possibly external libraries are not installed.
Have you checked the steps in [Readme](/README.md)

**Comment by Codershell911** [comment]
Even I checked the READ.md and even watched tutorials to install still same
