### ISSUE TITLE
hydra resolving done 0 of 1 target completed, 0 valid password found

### ISSUE THREAD

**Issue by racsou4coding** [vanhauser-thc/thc-hydra#897]
can some help me here I am trying to login to my account using hydra
 hydra -l ***********@gmail.com -P /home/racsou/pass.txt -s 465 -S -v -V -t 4 smtp.gmail.com smtp
and I got this even that I enteterd my own password : 

[DATA] max 4 tasks per 1 server, overall 4 tasks, 7 login tries (l:1/p:7), ~2 tries per task
[DATA] attacking smtps://smtp.gmail.com:465/
[VERBOSE] Resolving addresses ... [failed for smtp.gmail.com] [VERBOSE] resolving done
0 of 1 target completed, 0 valid password found

**Comment by Goofygiraffe06** [comment]
Hello @racsou4coding,

It's no longer possible as there was a new change made accounts to prevent logins only using username and passwords as the often lead to bruteforcing.
```
To help keep your account secure, from May 30, 2022, ​​Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password.

Important: This deadline does not apply to Google Workspace or Google Cloud Identity customers. The enforcement date for these customers will be announced on the Workspace blog at a later date.

For more information, continue to read.
```
Read more at [Google Support](https://support.google.com/accounts/answer/6010255?hl=en#zippy=%2Cif-less-secure-app-access-is-on-for-your-account)

Thanks,
Goofygiraffe06
