### ISSUE TITLE
can hydra do a failure check while doing a http-get method crack

### ISSUE THREAD

**Issue by gbcbooks** [vanhauser-thc/thc-hydra#90]
i was trying to burte a netcore brand router , it use http-get method to authenticate. but every 3 time your input in the wrong passwod ,it refresh a error page to warning you.
so i was think if hydra can do a failure check when it doing http-get crack just like http-get-form do.

**Comment by vanhauser-thc** [comment]
hmm that sounds like something very special. never heard of any other web site/device doing that.

if you need it, code it in yourself, but I will accept a patch :)

**Comment by gbcbooks** [comment]
yes,it is special, every time hydra received  the warning page will treat the credential as correct pair. 
i have a very little knowlege of coding,waiting for you update.

**Comment by vanhauser-thc** [comment]
I put it on my todo list, but at so low priority I doubt I will ever have the time and leasure for it.
