### ISSUE TITLE
Recover facebook

### ISSUE THREAD

**Issue by gab480** [vanhauser-thc/thc-hydra#904]
They hacked my Facebook from when I was a child and they are using it to post inappropriate content and I really want to get it back

**Comment by Kjamess** [comment]
> They hacked my Facebook from when I was a child and they are using it to post inappropriate content and I really want to get it back


I will advise you to contact the best hacker around he helped me recover my facebook,fast and reliable his telegram is 
https://t.me/Blackhathacker110

**Comment by Rahman2326** [comment]
> They hacked my Facebook from when I was a child and they are using it to post inappropriate content and I really want to get it back

My Experience:
💗. Recovering Hacked WordPress Website
💗. Full Vulnerability Scan and WordPress website malware removal
💗. Vulnerability Assessment
💗. Antispam protection
💗. Analysis of database servers
💗. Restore a hacked website
💗. Ethical Hacking(White Hat Hacker)
💗. Hacked account recovery
💗. Password recovery
💗. Decode encrypted files
💗. Vulnerability Testing
💗....my WhatsApp number +8801314956025
