### ISSUE TITLE
optional parameters must have the format X=value:

### ISSUE THREAD

**Issue by goodpeanuts** [vanhauser-thc/thc-hydra#909]
```bash
hydra -l admin -P rockyou.txt -s 8088 192.168.13.143 http-get-form "/vulnerabilities/brute/:username=^USER^&password=^PASS^&Login=Login:Username and/or password incorrect.:H=Cookie:security=low; PHPSESSID=j1hde1o1hbashq9s74dqdus6v2"
```
![image](https://github.com/vanhauser-thc/thc-hydra/assets/143506992/e3843558-83ee-4cec-9a0d-2487e16f8c45)

why above it cannot work but other can
here is link ： https://medium.com/@dannybeton/dvwa-brute-force-tutorial-low-security-463880d53e50
![image](https://github.com/vanhauser-thc/thc-hydra/assets/143506992/9ec98c4e-54dc-43bc-9b39-dd4e7111cf7b)

already latest
![image](https://github.com/vanhauser-thc/thc-hydra/assets/143506992/fd2d3cd9-574d-425c-acbf-a9e9f97abec5)

**Comment by MASTREX** [comment]
Match string or incorrect string should be in last

**Comment by goodpeanuts** [comment]
Thanks a bunch for your help!

**Comment by goodpeanuts** [comment]
> Match string or incorrect string should be in last

 Thanks a bunch for your help!
