### ISSUE TITLE
Is there hydra on windows 11?

### ISSUE THREAD

**Issue by MehmetAliCan10** [vanhauser-thc/thc-hydra#910]
Is there hydra on windows 11?

**Comment by R-Rothrock** [comment]
The readme says it compiles on Windows/Cygwin.

**Comment by MehmetAliCan10** [comment]
> The readme says it compiles on Windows/Cygwin.

Ok thanks but which os is fastest?

And can also be android and how? On termux?

**Comment by R-Rothrock** [comment]
What do you mean fastest? To install, to compile, to run?

As to your second question, this is from `README.md`:

> It was tested to compile cleanly on Linux, Windows/Cygwin, Solaris,
> FreeBSD/OpenBSD, QNX (Blackberry 10) and MacOS.

so I don't think it supports Android (at least, not conventionally).

also from `README.md`

> Hydra in the most current github state can be directly downloaded via docker:
> ```
> docker pull vanhauser/hydra
> ```

**Comment by MehmetAliCan10** [comment]
> What do you mean fastest? To install, to compile, to run?
> 
> As to your second question, this is from `README.md`:
> 
> > It was tested to compile cleanly on Linux, Windows/Cygwin, Solaris,
> > FreeBSD/OpenBSD, QNX (Blackberry 10) and MacOS.
> 
> so I don't think it supports Android (at least, not conventionally).
> 
> also from `README.md`
> 
> > Hydra in the most current github state can be directly downloaded via docker:
> > ```
> > docker pull vanhauser/hydra
> > ```

So best is Windows or Kali Linux which is brute force fastest ?

**Comment by R-Rothrock** [comment]
Well... There's quite a lot of moving parts to that question.

For the fastest possible system, I'd use Linux without a UI running (solely a VT) and would plug in to eth, since the bottleneck of performance would most likely be network long before you have to worry about hardware.

**Comment by MehmetAliCan10** [comment]
> Well... There's quite a lot of moving parts to that question.
> 
> For the fastest possible system, I'd use Linux without a UI running (solely a VT) and would plug in to eth, since the bottleneck of performance would most likely be network long before you have to worry about hardware.

So I think Kali Linux without VMware fastest installer image...

SUPPORTED PLATFORMS
-------------------
- All UNIX platforms (Linux, *BSD, Solaris, etc.)
- MacOS (basically a BSD clone)
- Windows with Cygwin (both IPv4 and IPv6)
- Mobile systems based on Linux, MacOS or QNX (e.g. Android, iPhone, Blackberry 10, Zaurus, iPaq)
But there is also Android or not?

**Comment by R-Rothrock** [comment]
I wouldn't use VMware/Virtualbox, but I also wouldn't run Kali Linux on hardware...

If it says it uses Android, then it does, I was mistaken.

**Comment by MehmetAliCan10** [comment]
> Well... There's quite a lot of moving parts to that question.
> 
> For the fastest possible system, I'd use Linux without a UI running (solely a VT) and would plug in to eth, since the bottleneck of performance would most likely be network long before you have to worry about hardware.

Can you give a link Linux without ui running ? The fastest Linux ever?

**Comment by MehmetAliCan10** [comment]
Ok Ubuntu server but it's possible Twitter hack without blocking ip?
So with need max 64 ip VDS for proxy hydra hack possible? And Instagram also possible hack?

**Comment by R-Rothrock** [comment]
They'll probably end up blocking your ip eventually, whether it's Twitter or Instagram. There are a couple ways to prevent this, but as far as speed goes, I'm not entirely sure which is best. I recommend you search the internet, maybe take a look at https://security.stackexchange.com, and close this issue, as we've gone off topic.

Keep in mind, Hydra's devs don't appreciate usage of their software without permission from the target (i.e. Twitter). Technically, you _should_ confirm you have permission from Twitter and/or Instagram. Otherwise, don't get caught.
