### ISSUE TITLE
Error make install: redefinition of 'tmp'

### ISSUE THREAD

**Issue by dmclazaro01** [vanhauser-thc/thc-hydra#911]
**Describe the bug**
Hi everyone. I'm using this program since more than 1 year on docker containers and I neved had a problem. But since today, I'm getting an error when I try to install thc-hydra about "redefinition of 'tmp':
  root@simuladorataques:/app/simulador/thc-hydra# make
  cc -I. -O3 -g -fcommon -Wno-deprecated-declarations -pie -fPIE -fstack-protector-all --param ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wl,-z,now -Wl,-z,relro -Wl,--allow-multiple-definition -g -D_GNU_SOURCE -c hydra-http-form.c -DLIBOPENSSL -DLIBSSH -DHAVE_ZLIB -DLIBFREERDP -DLIBWINPR2 -DHAVE_MATH_H  -I/usr/include/freerdp2 -I/usr/include/winpr2
  hydra-http-form.c: In function 'parse_options':
  hydra-http-form.c:451:13: error: redefinition of 'tmp'
    451 |       char *tmp = strchr(miscptr, ':');
        |             ^~~
  hydra-http-form.c:443:13: note: previous definition of 'tmp' with type 'char *'
    443 |       char *tmp = strchr(miscptr, ':');
        |             ^~~
  make: *** [Makefile:81: hydra-http-form.o] Error 1

**To Reproduce**
On Dockerfile:
    RUN git clone https://github.com/vanhauser-thc/thc-hydra.git
    RUN cd thc-hydra && ./configure && make install && make

At the moment of execute "make install" or "make"

**Screenshots**
![image](https://github.com/vanhauser-thc/thc-hydra/assets/93814183/45bcbe37-9fd9-4996-9ba9-adc99631e382)

**Desktop (please complete the following information):**
 - OS: Debian image (latest, but tried too on Debian 11 and Debian 12)
 - hydra version: last uploaded to git.

**Comment by Hatsumi-FR** [comment]
Hey, you can switch on this branch if you want to run it : Hatsumi-FR:fix/redefinition-of-tmp (https://github.com/vanhauser-thc/thc-hydra/pull/912). There is a problem in tmp var declaration

**Comment by Hatsumi-FR** [comment]
update : fix has been merge. I think that this issue can be closed
