### ISSUE TITLE
hydra using incorrect paths on linux (openSUSE)

### ISSUE THREAD

**Issue by alanbortu** [vanhauser-thc/thc-hydra#92]
Hi,

I am attempting to package hydra for openSUSE and I notice that the configure script seems to try and place files inside of _/usr/etc_ and _/usr/man_. Neither of these exist, the first as far as I know has not been used in linux in a long time and _/usr/man_ should be _/usr/share/man_ (at least for openSUSE and Fedora, not sure about other distros). 

Would it be possible to get this changed?

**Comment by vanhauser-thc** [comment]
configure sets the data directory to $PREFIX/etc
By default PREFIX is /usr/local
A data directroy of /usr/local/etc it totally fine IMHO.

I guess you are setting the PREFIX to /usr and that is why hydra does try to write to these directories.
What directories should it be? I could create ./configure options for that.

**Comment by alanbortu** [comment]
Thanks for the quick reply, for the build process it is suggested by the packaging guidelines to use `make %{?_smp_mflags}` which I imagine is what is setting the PREFIX. You can take a look at the spec file [here](https://build.opensuse.org/package/view_file/home:alanbortu:hydra/hydra/hydra.spec?expand=1).

I am not sure about /usr/local/etc, I have not seen any package store files there on my systems. I think the correct path to use would be /usr/share/hydra.

**Comment by vanhauser-thc** [comment]
Would it be possible for you to specify a specific configure flag in your build for hydra?

**Comment by alanbortu** [comment]
Yes I think that would be fine, at least for now. If I ever submit it for inclusion into the distribution itself there may be issues if it doesn’t meet their standard but for now I don’t plan to do that so it should be fine.

**Comment by vanhauser-thc** [comment]
I added the ./configure option "--fhs", check if this installs everything like it should

**Comment by alanbortu** [comment]
Thanks a lot, that seems to have fixed it. Package seems to build fine now.
