### ISSUE TITLE
termux android

### ISSUE THREAD

**Issue by Sigirrr** [vanhauser-thc/thc-hydra#927]
Hi, i have a problem with install hydra on termux android.
termux - Linux localhost 4.14.141 #1 SMP PREEMPT Fri May 21 12:32:19 CST 2021 aarch64 Android.
Android 12 rooted.

i did this steps without errors:
# pkg install -y x11-repo
  # pkg install -y clang make openssl openssl-tool wget openssh coreutils gtk2 gtk3
and when i did next step i have a error.
~ $ ./configure --prefix=$PREFIX
bash: ./configure: No such file or directory
it's error from my side or programm-installer side? 
Sorry, i'm litle noob:)

**Comment by vanhauser-thc** [comment]
wrong directory you are in
