### ISSUE TITLE
Error: network size may only be between /16 and /31

### ISSUE THREAD

**Issue by Spiksee3** [vanhauser-thc/thc-hydra#929]
i know this is for bugs and not for help but i've been searching forums for hours and this is my last resort
my code:

sudo hydra -L /home/spark/Downloads/usernames.txt -P /home/spark/Downloads/rockyou-75.txt -u -f www.this.web.site/login.php https-post-form "/login.php:userid=^USER^&password=^PASS^:F=<form name='logonForm'"

when i run it i get

Error: network size may only be between /16 and /31: www.this.web.site/login.php

**Comment by vanhauser-thc** [comment]
wrong command line usage
