### ISSUE TITLE
Hydra Error:  network size may only be between /16 and /31:

### ISSUE THREAD

**Issue by SiFunk** [vanhauser-thc/thc-hydra#931]
Hey, i got a error from hydra : network size may only be between /16 and /31:
my command is this: hydra lfs-ratingen.ebk-cloud.de/login/index -L /home/kali/Schreibtisch/Wordlist.txt -P /home/kali/Schreibtisch/10millionpassword.txt https-post-form  "/login/index.php:username=^USER^&password=^PASS^:F=Login Failed"

**Comment by vanhauser-thc** [comment]
wrong command line usage
