### ISSUE TITLE
Maybe not New, False Positives

### ISSUE THREAD

**Issue by dyang99** [vanhauser-thc/thc-hydra#95]
I am sure Hydra must have worked in the past, but i only get false positives.
I am using the gui interface and the wierd thing is that hydra often continues after the
false positive is found. i am using a large wordlist snd the result is below.
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "rashad" - 28692470 of 43033194 [child 5]
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "pringles" - 28692471 of 43033194 [child 15]
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "poppop" - 28692472 of 43033194 [child 12]
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "lillie" - 28692473 of 43033194 [child 6]
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "leeann" - 28692474 of 43033194 [child 1]
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "ilove?" - 28692475 of 43033194 [child 14]
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "icecream1" - 28692476 of 43033194 [child 9]
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "doggy" - 28692477 of 43033194 [child 3]
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "cheekymonkey" - 28692478 of 43033194 [child 8]
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "candle" - 28692479 of 43033194 [child 0]
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "because" - 28692480 of 43033194 [child 10]
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "alinutza" - 28692481 of 43033194 [child 2]
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "weezer" - 28692482 of 43033194 [child 13]
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "raven1" - 28692483 of 43033194 [child 11]
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "raerae" - 28692484 of 43033194 [child 4]
[ATTEMPT] target smtp.gmail.com - login "xxxxxxxx@gmail.com" - pass "pereira" - 28692485 of 43033194 [child 7]

[465][smtp] host: smtp.gmail.com   login: xxxxxxxx@gmail.com   password: rashad
[465][smtp] host: smtp.gmail.com   login: xxxxxxxx@gmail.com   password: weezer
1 of 1 target successfully completed, 4 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2016-02-11 08:04:48

**Comment by vanhauser-thc** [comment]
when hydra starts it writes that many mail services have protection against bruteforcing. this is what you are seeing.
