### ISSUE TITLE
Bug Install in Termux

### ISSUE THREAD

**Issue by dionealfarisi** [vanhauser-thc/thc-hydra#966]
**Bug Install in Termux**

`                                                  Now type make install                             strip hydra pw-inspector                          echo OK > /dev/null && test -x xhydra && strip xhydra || echo OK > /dev/null
mkdir -p /usr/local/bin                           mkdir: cannot create directory ‘/usr’: Read-only file system                                        make: [Makefile:88: install] Error 1 (ignored)
cp -f hydra-wizard.sh hydra pw-inspector /usr/local/bin && cd /usr/local/bin && chmod 755 hydra-wizard.sh hydra pw-inspector                          cp: target '/usr/local/bin': No such file or directory                                              make: *** [Makefile:89: install] Error 1`

**When I wanted to do the installation I found this, isn't tch-hydra a folder? Can you please update to fix this bug**

**Comment by Webpage-gh** [comment]
Please reconfigure using `./configure --prefix=$PREFIX`, but it doesn't seem to work because of file descriptor issues.
