### ISSUE TITLE
Symbian version

### ISSUE THREAD

**Issue by Symbian9** [vanhauser-thc/thc-hydra#97]
How make it for using on Series 60 3rd Edition phones(ARM based)?

**Comment by vanhauser-thc** [comment]
I have no clue.
dont have that phone.
If you find that out, submit the required build files so others can compile it as well

**Comment by Symbian9** [comment]
Here are few active projects, that based on SDL and steal make builds for S60v3
1) ScummVM (SDL) - https://github.com/scummvm/scummvm
1.1) http://wiki.scummvm.org/index.php/SymbianOS
2) INSTEAD (SDL+Lua) - http://github.com/instead-hub/instead/
2.1) https://github.com/instead-hub/instead/blob/master/instead.pkg

Also here is full GnuPoc SDK (opensource, can run on Linux and OS X ) used to build binary for Symbian:
3) http://www.martin.st/symbian/
3.1) https://cloud.mail.ru/public/JxE5/CDr4AStEZ
3.2) https://github.com/mstorsjo/gnupoc-package

**Comment by vanhauser-thc** [comment]
as I said - I dont have a phone, and I won't do that.
if you want to have it - you will have to do it youself.
I have enough on my plate to work ...
