### ISSUE TITLE
Broken on Debian

### ISSUE THREAD

**Issue by ChervonaKomanda** [vanhauser-thc/thc-hydra#971]
Tried on both Debian 11 and Debian 12. Installed via `sudo apt-get install hydra` Also tried via `sudo apt-get install hydra-gtk` Also tried building myself from git clone of the repository. Between each install I completely reinstalled OS and wiped to default. No matter what there's always missing or broken dependencies such as: 
`
Package libmysqlclient-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libmariadb-dev-compat libmariadb-dev

E: Unable to locate package  libgtk2.0-dev
E: Couldn't find any package by glob ' libgtk2.0-dev'
E: Couldn't find any package by regex ' libgtk2.0-dev'
E: Package 'libmysqlclient-dev' has no installation candidate
E: Unable to locate package  firebird-dev
E: Unable to locate package libncp-dev
` 

Even after finding a way around and fixing as many dependencies as possible, running hydra in any way it was build just returns 
`freerdp init failed`. Tried every method online, tried my own methods, no matter what it's not repairable from what I've tried on Debian. Other sources suggest trying Cent OS which is worth a shot, but requiring me to install an entirely different OS just for this program is instead of Debian ( And Kali and Ubuntu which also have highly reported build issues ) is mindblowing

**Comment by vanhauser-thc** [comment]
Why do you post here? It’s a Debian problem.
Try apt update before installing
