### ISSUE TITLE
No special characters?

### ISSUE THREAD

**Issue by Zibethicus** [vanhauser-thc/thc-hydra#98]
So why did I not see special characters? Is there a way to use them? Is there a way to use specific letters only?

**Comment by vanhauser-thc** [comment]
I am not a psychic to know what you exactly mean ...

**Comment by Zibethicus** [comment]
For example: @#$%&-+*, these are all special characters.

**Comment by vanhauser-thc** [comment]
but where? where is there a problem with special characters? please describe your problem in detail, best with a command line, or input file example etc.

**Comment by vanhauser-thc** [comment]
no response, closing this now
